### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by spenagon** [davidemms/OrthoFinder#1]
How can I solve this error?

File "orthofinder.py", line 229
    with open(clustersFilename, 'rb') as clusterFile, open(newFilename, "wb") as output:
                                                    ^
SyntaxError: invalid syntax

**Comment by davidemms** [comment]
Are you using an old version of python? If you're having problems with the 'with' statement it might be that that's the problem (https://www.python.org/dev/peps/pep-0343/). If so then it's best to install and use version 2.7.


Date: Thu, 6 Aug 2015 02:24:56 -0700

**Comment by spenagon** [comment]
I am using python version 2.6.5. When I change lines of with I get another error:
  File "orthofinder.py", line 1031
    fastaFileIndices = {filename:iSpecies for iSpecies, filename in enumerate(originalFastaFilenames_justNames)}
                                            ^
SyntaxError: invalid syntax

**Comment by davidemms** [comment]
Hi spenagon

I've just checked and the dictionary comprehension (the syntax you've posted) was introduced in versions 2.7, released 2010. I will put a note in the README file to tell users that they'll need to use version 2.7 but will download some older versions of python and see if I can make the code backwards compatible with these.

David

**Comment by davidemms** [comment]
Closing this issue now that README now makes clear the python version requirements.
