### ISSUE TITLE
scipy.optimize

### ISSUE THREAD

**Issue by RobertoFe** [davidemms/OrthoFinder#10]
Hi there,

I am trying to run OrthoFinder, I have installed Python 2.7, MCL , BLAST but I still get this error:

Traceback (most recent call last):
  File "orthofinder.py", line 34, in <module>
    from scipy.optimize import curve_fit            # install
ImportError: No module named scipy.optimize

I thought was related to NumPy and I re-installed a newer version but still I get the same error.

Any idea of what is the problem?

thanks in advance for the reply

Regards
Roberto

**Comment by davidemms** [comment]
Hi

Scipy needs to be installed to run OrthoFinder, it looks like it eaither isn't installed or there is a problem with the installation. Instructions for installing scipy on for different systems is given here: http://www.scipy.org/install.html/

All the best
David

**Comment by dipsaha** [comment]
The same problem here. Please let me know the solution.
