### ISSUE TITLE
"IndexError: index out of bounds" with latest version

### ISSUE THREAD

**Issue by ekayal** [davidemms/OrthoFinder#101]
Hello,
After the installation of the latest version of OrthoFinder (v1.1.8), I keep getting the IndexError: index out of bounds message at the OthoFinder algorithm stage (see below). I checked for duplicated sequence names and found none.
Also, this error was not happening with my data while running an older version (v1.1.2).
Thank you for your help.
Cheer,
E

Running OrthoFinder algorithm
-----------------------------
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1499, in <module>
  File "orthofinder/orthofinder.py", line 1201, in DoOrthogroups
  File "orthofinder/orthofinder.py", line 340, in GetSequenceLengths
IndexError: index out of bounds
Failed to execute script orthofinder

**Comment by davidemms** [comment]
Hi 

That sounds strange, could you just confirm that if you run orthofinder from the directory containing the "Blast*txt" files using "orthofinder.py -b directory_with_blast_files" using version 1.1.2 that you don't get this problem and using v1.1.8 you do get the problem? It should only take a few seconds to get to this point if you run orthofinder this way.

If the problem is occurring in that way, could you go to that directory with a (bash) terminal and run
`for f in Species*fa ; do echo $f ; grep ">" $f | wc -l ; done > SeqNumbers.txt` 
and send me the file SeqNumbers.txt together with SpeciesIDs.txt and SequenceIDs.txt and I'll take a look. Also, what orthofinder commands did you run to get to this point?

Thanks
David

**Comment by ekayal** [comment]
The issue was a duplicated species in the SpreciesIDs. It works now. Thank you for yoru help and very sorry for spamming the Issues thread.
Do you think it is possible to have a table to complement the Statistics_Overall.csv and Statistics_PerSpecies.csv ones with the list of orthogroups and the list of genes per OG? The general statics have some numbers but a more detailed table would be nice.
Thanks. Cheers,
E

**Comment by davidemms** [comment]
Hi 

No problem, it's useful to have it on the issues page in case someone else has a similar problem.

As for the extra table, could you explain a bit more what sort of thing you're thinking of? The list of orthogroups and the list of genes per OG is contained in the file Orthogroups.csv and then there is the file Orthogroups.GeneCount.csv which tells you how many genes there are from each species in each orthogroup. Could you tell me the extra information you have in mind?

Thanks
David

**Comment by ekayal** [comment]
I was thinking of a table that mixes the tables Orthogroups.GeneCount.csv and Orthogroups.csv/txt. For example, I want to capture the list (and later the sequence) of the genes from all the OGs that have at least one gene from each taxon or from half the taxa; those who have only one gene per taxon. The Statistics_Overall.csv file has a few good stats on that but not the OG nor the gene names.
I know it can easily be done with a short script but since OF already creates these tables, it might be good to have the additional info as well.
Thanks
E

**Comment by davidemms** [comment]
Hi

From what you say it sounds like all the information you need is already in the results files. I think for OrthoFinder to create extra results files with duplicated information in would only be confusing to other users, even if it does solve one particular use case for you. 

There is a good tutorial here on doing the kind of analysis you mention:
http://arken.nmbu.no/~larssn/teach/bin310/week8.html

Also, you could if you want just paste the Orthogroups.GeneCount.csv table into the Orthogroups.csv file and have the tables side-by-side, they are already formatted the same way.

All the best
David
