### ISSUE TITLE
Error in producing Orthologues and gene_trees 

### ISSUE THREAD

**Issue by zillurbmb51** [davidemms/OrthoFinder#106]
Sir,
I was running the latest orthofinder:
`./orthofinder -t 512 -a 512 -M msa -A muscle -T raxml -f /gondor/zillur/orthology_new/july_5/`
It gave me almost everything but the alignments and gene trees. The error is like:
`Error: producing Orthologue, argument given 6 instead of 5`
I can't copy error message now, because to traceback the error I ran few commands; like ls, ls -sh, 
etc. which gave me: `[zillur@genomics Results_Aug05]$ ls -sh
total 17M
5.6M Orthogroups.csv                  4.0K Orthologues_Aug15
1.5M Orthogroups.GeneCount.csv           0 SingleCopyOrthogroups.txt
 12K Orthogroups_SpeciesOverlaps.csv  4.0K Statistics_Overall.csv
6.2M Orthogroups.txt                   20K Statistics_PerSpecies.csv
2.9M Orthogroups_UnassignedGenes.csv  260K WorkingDirectory`
And in the Orthologues_Aug15 directory I have:
`[zillur@genomics Results_Aug05]$ ls Orthologues_Aug15/
Alignments  Gene_Trees  Sequences  WorkingDirectory
[zillur@genomics Results_Aug05]$ ls Orthologues_Aug15/Alignments/
[zillur@genomics Results_Aug05]$ ls Orthologues_Aug15/Gene_Trees/
[zillur@genomics Results_Aug05]$ ls -sh Orthologues_Aug15/Alignments/
total 0
[zillur@genomics Results_Aug05]$ ls -sh Orthologues_Aug15/Gene_Trees/
total 0
[zillur@genomics Results_Aug05]$`
In the Orthologues_Aug15/Sequences I have many fasta alignments and in Orthologues_Aug15/WorkingDirectory I have blast results. After checking all this now I can't scroll up too much to find the error message to copy, my mistake and ignorance. Is there any way to find the log? What should I do now?
Thanks in advance.
Best Regards
Zillur

**Comment by davidemms** [comment]
Hi Zillur

Thanks for reporting this, I've identified the error and I'm working on a fix now.

All the best
David
