### ISSUE TITLE
Dummy question

### ISSUE THREAD

**Issue by mariferrarini** [davidemms/OrthoFinder#110]
I am trying to make Orthofinder work on my Mac. However, I can't even make the computer to show the help line:

```
sh-3.2# tar xzf OrthoFinder-1.1.8.tar.gz 
sh-3.2# OrthoFinder-1.1.8/orthofinder -h
sh: OrthoFinder-1.1.8/orthofinder: cannot execute binary file

```

Would you know why I'm having this trouble?

Thank you very much.

**Comment by paulotokimatu** [comment]
Check this issue: 
https://github.com/davidemms/OrthoFinder/issues/45

The version you downloaded was compiled for linux, so you need to compile the source .tar.gz file for your system

**Comment by mariferrarini** [comment]
Thank you very much.

**Comment by davidemms** [comment]
The source code version can just be downloaded and run, you don't even need to compile it:
`python OrthoFinder-1.1.8_source/orthofinder/orthofinder.py -h`

All the best
David
