### ISSUE TITLE
Unrecognised argument: -T

### ISSUE THREAD

**Issue by sarah872** [davidemms/OrthoFinder#111]
I am trying to run OrthoFinder version 1.1.4 with iqtree instead of Fasttree, so this is my code:
`
orthofinder -f $PFASTAS -T iqtree
`
Unfortunately I get the error stated above.

**Comment by davidemms** [comment]
Hi Sarah

That option wasn't available until later releases, you can see the available options in a particular version with, `orthofinder -h`.
 
If you download the latest version (1.1.10) then you will be able to use that option. Note that to use iqtree you need to select the multiple sequence alignment method for tree inference so your command line will look like this
`orthofinder -f $PFASTAS -M msa -T iqtree`

All the best
David
