### ISSUE TITLE
Missing internal branch length

### ISSUE THREAD

**Issue by CIWa** [davidemms/OrthoFinder#118]
Hi David, 

I used the implemented MSA-approach in Orthofinder and when I checked the gene trees I discovered that the internal branch lengths are missing. Unfortunately, I wanted to use those values for my research. Is there a way to re-generate those values? I found that in the tree-id files similar values seem to exist. Are those the correct values? And if so, is there a simple way to insert them into the gene tree?

Thank you very much,
and best wishes,
Isabel

**Comment by davidemms** [comment]
Hi Isabel

I think that this might be an issue that's been resolved, could you let me know what version you are using and I'll check.

Thanks
David

**Comment by davidemms** [comment]
Hi Isabel

If you download the latest version of the code from the "Clone or download" button on the front page you should be able to run something like this:  
`python orthofinder/orthofinder.py -ft ExampleDataset/Results_Nov09/Orthologues_Nov09/`
to recreate the "Recon_Gene_Trees/" directory which will contain the trees, with branch lengths, that the orthologues are inferred from. If you used the dlcpar method before then the inferred orthologues will be a little bit different as new method is being used that doesn't require dlcpar.

Alternatively, if you just want to create copies of the trees with branch lengths in `Trees_ids/` directory and put gene accessions in them, you can use the new `convert_tree_ids.py` script in `orthofinder/tools`.

All the best
David
