### ISSUE TITLE
fastme dependency -oa and -M msa

### ISSUE THREAD

**Issue by swuyts** [davidemms/OrthoFinder#119]
Hi David,

I've just downloaded OrthoFinder v2.0.0 and wanted to test this out using the following command

`orthofinder -f $pin_sequences -oa -M msa -S diamond -t 20`

However I get a dependency error 

```
OrthoFinder version 2.0.0 Copyright (C) 2014 David Emms

    This program comes with ABSOLUTELY NO WARRANTY.
    This is free software, and you are welcome to redistribute it under certain conditions.
    For details please see the License.md that came with this software.

20 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /small/antwerpen/202/vsc20280/plantarum/SimpleTest.phy -o /small/antwerpen/202/vsc20280/plantarum/SimpleTest.tre" - failed
ERROR: Cannot run fastme
Please check FastME is installed and that the executables are in the system path.

Dependencies have been met for inference of orthogroups but not for the subsequent orthologue inference.
Either install the required dependencies or use the option '-og' to stop the analysis after the inference of orthogroups.

ERROR: An error occurred, please review previous error messages for more information.
```

Looking at the overview picture in the OrthoFinder manual, I don't see the necessity of having fastme installed using the options -oa and -M msa. Am I right that this error should not be thrown?

Thanks again for this awesome tool!
Sander

**Comment by davidemms** [comment]
Hi Sander

Yes you're right, I'll have a look into it.

Thanks
David

**Comment by davidemms** [comment]
Hi Sander

Previously OrthoFinder still needed FastME to infer the species tree when using the "-M msa" option. Now it uses a multiple sequence alignment for that too, I'm submitting a change now so that it doesn't check for FastME in this case.

All the best
David

**Comment by N-poorin** [comment]
Hi David,
I'm working with OrthoFinder v2.1.2 and still have the same problem with fastme as Sander said. Although when working with your example data there are no problems, with my own faa files I face the fast me issue. can you please help?
