### ISSUE TITLE
Error in trees_for_orthogroups.py

### ISSUE THREAD

**Issue by fenciso13** [davidemms/OrthoFinder#12]
Hi.
I'm trying to run trees_for_orthogroups.py but I got this error:
Traceback (most recent call last):
  File "trees_for_orthogroups.py", line 14, in <module>
    import orthofinder    
ImportError: No module named orthofinder

Any suggestions?
Thanks in advance.
Felix Enciso

**Comment by davidemms** [comment]
Hi Felix

You need to have the corresponding version of orthofinder.py in the same directory as the trees_for_orthogroups.py file (or in the python path).

All the best
David
