### ISSUE TITLE
Fastme error while working with user's own faa files

### ISSUE THREAD

**Issue by N-poorin** [davidemms/OrthoFinder#121]
Hi David,
Using  OrthoFinder 2.1.2 with the input of 2 faa files, I faced error from fastme. However, when I work with the ExampleData no error occurs which ensures that fastme is properly installed. 

```
OrthoFinder version 2.1.2 Copyright (C) 2014 David Emms

16 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "makeblastdb -help" - ok
Test can run "blastp -help" - ok
Test can run "mcl -h" - ok
Test can run "fastme -i /home/naghmeh/Downloads/OrthoFinder-2.1.2/Acetobacterium woodii DSM 1030/SimpleTest.phy -o /home/naghmeh/Downloads/OrthoFinder-2.1.2/Acetobacterium woodii DSM 1030/SimpleTest.tre" - failed
ERROR: Cannot run fastme
Please check FastME is installed and that the executables are in the system path.

Dependencies have been met for inference of orthogroups but not for the subsequent orthologue inference.
Either install the required dependencies or use the option '-og' to stop the analysis after the inference of orthogroups.

ERROR: An error occurred, please review previous error messages for more information.

```

When I directly run fastme on the SimpleTest.phy as input the following error occurs: 
`**Warning: The matrix is not symmetric.**`

SimpleTest.phy -the fastme input file tested- is:

4
1_1 0 0 0.2 0.25
0_2 0 0 0.21 0.28
3_1 0.21 0.21 0 0
4_1 0.25 0.28 0 0

It is appreciated if you could help.
Best
Poorin

**Comment by N-poorin** [comment]
I guess I found out the reason. The input folder name should not be so long otherwise the error occurs! Moreover, after fixing the input folder name, fastme cannot generate tree with two species and therefore only we got orthogroups not orthologous data.

**Comment by davidemms** [comment]
Just to add, it's best not to have any spaces in the path to your input files including the file names themselves.

All the best
David
