### ISSUE TITLE
Segmentation fault during diamond search

### ISSUE THREAD

**Issue by sepro** [davidemms/OrthoFinder#122]
When running OrthoFinder version 2.1.2 using diamond, diamond (v 0.9.9) produces a segmentation fault during the similarity search. (An empty output is produced and then every subsequent step throws warnings.)

The same data-set was processed successfully using OrthoFinder v1.1.10.

**Comment by davidemms** [comment]
Hi 

The first thing to do would be to try the latest version of diamond: https://github.com/bbuchfink/diamond/releases. There was an issue that I reported to them that affected versions prior to 0.9.12. Let me know if you still have the same issue with the latest version. If you do, could you post the terminal output you get as well.

Thanks
David

**Comment by davidemms** [comment]
Hi

Were you able to resolve this issue with the latest version of diamond?

Thanks
David

**Comment by sepro** [comment]
Unfortunately I haven't been able to test the solution and no longer have access to the server where the issue occurred (as I'm no longer working at that institute).

**Comment by davidemms** [comment]
No problem, thanks for letting me know!
