### ISSUE TITLE
Troubleshooting an unassigned orthogroup

### ISSUE THREAD

**Issue by photocyte** [davidemms/OrthoFinder#123]
Hi there,

I have a particular protein, which ended up in an "unassigned" orthogroup, when I think this protein should be in another orthogroup (it has 50% identity to multiple members of this orthogroup).  

Would the solution be to decrease the mcl inflation parameter and rerun the orthogroup production from the BLASTP results?

All the best,
-Tim

**Comment by davidemms** [comment]
Hi Tim

In general I wouldn't recommend changing the MCL inflation parameter, it won't affect your orthogroups in a predictable way and doesn't really get at the question you're trying to answer. However, if you do want to change the MCL parameter then use the command line option "-I". Note, you can also see all the OrthoFinder options by just calling it with the option "-h".

As I understand it, you're interested in a particular gene/orthogroup and you want to know if the orthogroup assignment is correct. I'd look at this directly using a gene tree, OrthoFinder will give you everything you need (although I admit it's not clear all the things you can do, I'll try and write up some of these use cases in the near future!).

1. Write out the sequence files for your orthogroups:
`orthofinder -fg <your_orthogroup_results> -M msa -os `
(Figure 2 in the manual gives an overview of these options)

2. Get the sequence file for your orthogroup and add to it the sequence you think should be in it

3. Do a multiple sequence alignment and infer a gene tree for this using whatever programs you're most happy with.

4. Root the tree and check the position of the your gene, is it where it should be if it did belong to the orthogroup? (A complete run of OrthoFinder will produce a rooted species tree, should you need it,  which will help with rooting the gene tree.)


Also, if you did run OrthoFinder with a lower inflation parameter to investigate just this gene family then you could also check out the gene tree automatically produced by OrthoFinder to see if you think your gene of interest belongs in the orthogroup.

All the best
David
