### ISSUE TITLE
Missing tools in 2.1.2 source archive

### ISSUE THREAD

**Issue by abretaud** [davidemms/OrthoFinder#125]
Hi,
I've seen the https://github.com/davidemms/OrthoFinder/blob/master/orthofinder/tools/convert_tree_ids.py script which I find useful, but I couldn't find it in the [2.1.2 archive](https://github.com/davidemms/OrthoFinder/releases/download/2.1.2/OrthoFinder-2.1.2_source.tar.gz)
Would it be possible to add it in future releases?

**Comment by davidemms** [comment]
Hi 

Thanks for pointing that out, I've made changes so that it will appear in the next release.

All the best
David
