### ISSUE TITLE
Orthofinder: unresolved with Numps - RuntimeWarning: invalid value encountered in double_scalars

### ISSUE THREAD

**Issue by rafaeltiveron** [davidemms/OrthoFinder#129]
Hi

I was running analysis just for one FAA file with 600 protein sequences. When mounting orthogroups, I received:

```
Writing orthogroups to file
---------------------------
Orthogroups have been written to tab-delimited files:
   /mnt/hgfs/SharedFolders/VectorBase/ofixodesricinus/Results_Jan23/Orthogroups.csv
   /mnt/hgfs/SharedFolders/VectorBase/ofixodesricinus/Results_Jan23/Orthogroups.txt (OrthoMCL format)
   /mnt/hgfs/SharedFolders/VectorBase/ofixodesricinus/Results_Jan23/Orthogroups_UnassignedGenes.csv
/tmp/_MEIm1QyzP/numpy/core/fromnumeric.py:37: RuntimeWarning: invalid value encountered in double_scalars
/tmp/_MEIm1QyzP/numpy/core/fromnumeric.py:2374: RuntimeWarning: invalid value encountered in double_scalars
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1543, in <module>
  File "orthofinder/orthofinder.py", line 1255, in DoOrthogroups
  File "orthofinder/orthofinder.py", line 694, in Stats
StopIteration
Failed to execute script orthofinder
```

If I run ExampleData from Orthofinder package with the four FAA file examples, everything goes fine. If I run just one FAA file from ExampleData, the same error appears. My version is Orthofinder 2.1.2.

What is happening?

**Comment by GuillaumeRS** [comment]
I have the same error, but haven't managed to find out a solution.

**Comment by davidemms** [comment]
Hi

Orthologues and orthogroups are concepts that apply between the genes in different species, they don't apply to a single species. It never occurred to me to write some code to check that a user had provided more than one species, hence there isn't a specific error message from OrthoFinder. 

To do an analysis you need an absolute minimum of two species, but ideally you should have at least four. 

All the best
David

**Comment by Neato-Nick** [comment]
I encountered this same error but am running OrthoFinder (v2.2.7) with three genomes. They are three genomes from within the same species, but am not providing only one fasta file as the OP of this issue did. 

```
/data/_MEImBtScy/numpy/core/fromnumeric.py:37: RuntimeWarning: invalid value encountered in double_scalars
/data/_MEImBtScy/numpy/core/fromnumeric.py:2374: RuntimeWarning: invalid value encountered in double_scalars
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1588, in <module>
  File "orthofinder/orthofinder.py", line 1277, in DoOrthogroups
  File "orthofinder/orthofinder.py", line 697, in Stats
StopIteration
Failed to execute script orthofinder
```

In my case, some output was written but all the orthogroups/genes are empty and no genes were assigned to any groups. This is reflected in `Statistics_Overall.csv`

```
$ cat Statistics_Overall.csv 
Number of genes	980
Number of genes in orthogroups	0
Number of unassigned genes	980
Percentage of genes in orthogroups	0.0
Percentage of unassigned genes	100.0
Number of orthogroups	0
Number of species-specific orthogroups	0
Number of genes in species-specific orthogroups	0
Percentage of genes in species-specific orthogroups	0.0
Mean orthogroup size	nan
Median orthogroup size	nan
```

**Comment by Neato-Nick** [comment]
Also: running OrthoFinder v1.1.10 on the same dataset finished successfully.

```
$ head -n 3 Statistics_Overall_v1.1.10.csv
Number of genes 980
Number of genes in orthogroups  892
Number of unassigned genes      88
```

**Comment by davidemms** [comment]
Hi Nick

Would you be able to send me the input files you used and I can take a look. Email might be best, you can find it at the top of any of the [python files](https://github.com/davidemms/OrthoFinder/blob/master/orthofinder/orthofinder.py).

All the best
David

**Comment by Neato-Nick** [comment]
@davidemms sorry for the delay, just e-mailed the files I was working with to you

**Comment by davidemms** [comment]
Hi Nick

I've tested the files you send and they work fine for me with version 2.2.7. If you run the ExampleDataset what happens? And then what if you attempt to run it on your files from the same terminal?  

Thanks
David

**Comment by Neato-Nick** [comment]
Hi David,

Thanks for testing that. I did some more testing. I found v1.1.10 and v2.2.7 both worked using the default BLAST for searching on the example dataset and my own dataset. I get errors running diamond on both versions. The error message is different for each version though. Looks like v1.1.10 caught that it couldn't connect to Diamond at the beginning, but v2.2.7 got all the way to the end. I get similar errors using my own dataset as the test dataset for each version.

v2.2.7
```
Writing orthogroups to file
---------------------------
Orthogroups have been written to tab-delimited files:
   ~/Results_Apr17_1/Orthogroups.csv
  ~/Results_Apr17_1/Orthogroups.txt (OrthoMCL format)
  ~/Results_Apr17_1/Orthogroups_UnassignedGenes.csv
/data/_MEIQiW4tY/numpy/core/fromnumeric.py:37: RuntimeWarning: invalid value encountered in double_scalars
/data/_MEIQiW4tY/numpy/core/fromnumeric.py:2374: RuntimeWarning: invalid value encountered in double_scalars
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1588, in <module>
  File "orthofinder/orthofinder.py", line 1277, in DoOrthogroups
  File "orthofinder/orthofinder.py", line 697, in Stats
StopIteration
Failed to execute script orthofinder
```

v1.1.10
```
Checking required programs are installed
----------------------------------------

ERROR: Cannot run diamond
Format of make database command:
  diamond-sse2 makedb --in INPUT -d OUTPUT
ERROR: Cannot run diamond
Format of search database command:
  diamond-sse2 blastp -d DATABASE -q INPUT -o OUTPUT --sensitive -p 1 --quiet -e 0.001
```

**Comment by davidemms** [comment]
Hi Nick

Yes, there were some problems with a couple of the diamond releases, glad you've got it working with the latest release.

(I think your problem with OrthoFinder v1 is that it's looking for an executable called, "diamond-sse2", which is what it was called at the time. If you renamed your diamond executable to this then it should work too. Of course, you're best using the latest version.)

Thanks for getting back to me with the update.

All the best
David
