### ISSUE TITLE
Does OrthoFinder run on Sierra?

### ISSUE THREAD

**Issue by l-yampolsky** [davidemms/OrthoFinder#135]
Looks like it should install on a Mac, but I am getting this:

$ OrthoFinder-2.2.0/orthofinder -h
-bash: OrthoFinder-2.2.0/orthofinder: cannot execute binary file

(Sierra 10.12.1)

Will appreciate your kind advise!
Thanks,
Lev Yampolsky

PS same thing on El Capitan

**Comment by davidemms** [comment]
Hi

OrthoFinder doesn't support Macs, but if you can install the python dependencies (Python 2.7 + numpy and scipy) can may be able to run it.

All the best
David
