### ISSUE TITLE
how does OrthoFinder parse fasta defline?

### ISSUE THREAD

**Issue by l-yampolsky** [davidemms/OrthoFinder#136]
Given the example dataset, OrthoFinder expects fasta defline GenBank-style,

>gi|144227417|gb|AAZ44095.2| chromosomal replication initiator protein [Mycoplasma hyopneumoniae J]

with gene ID either after the 1st or the 3rd pipe and species name in [ ]. 
does it have to be that way for correct identification of species and gene ID?
For example does the species name have to be in the end of the defline or anywhere in it as long as it is in [ ]?

PS. Experimentally established that OrthoFinder correctly parses species IDs from defline of the format 
>species_id@transcript_id.

Cool!

**Comment by davidemms** [comment]
Hi

OrthoFinder uses the filename of the input fasta file as the identifier for the species and attempts to use the first word of the accession (the text up to the first space) as the gene identifier. If the first word doesn't give a unique identifier then OrthoFinder uses the full accession as the identifier for the genes. Basically, the accession lines of fasta files are far too variable for OrthoFinder to parse them in any way that would be applicable for all files.

All the best
David
