### ISSUE TITLE
KeyError: 115

### ISSUE THREAD

**Issue by ESjokvist** [davidemms/OrthoFinder#138]
Hi,
I am running orthofinder using a conda install with precomputed blast and get Key error 115. Have commented out some of the species in the SpeciesIDs.txt file, otherwise nothing special. Running orthofinder like so:

orthofinder -b orthofinder/ -a 64 &> orthofinder_spongospora.log

Log file:

OrthoFinder version 2.1.2 Copyright (C) 2014 David Emms

16 thread(s) for highly parallel tasks (BLAST searches etc.)
64 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /scratch/esjokvist/spongospora/orthofinder/SimpleTest.phy -o /scratch/esjokvist/spongospora/orthofinder/SimpleTest.tre" - ok
Using previously calculated BLAST results in /scratch/esjokvist/spongospora/orthofinder/

Running OrthoFinder algorithm
-----------------------------
Traceback (most recent call last):
  File "/ceph/users/esjokvist/.conda/envs/orthofinder/bin/orthofinder", line 1562, in <module>
    clustersFilename_pairs, statsFile, summaryText, orthogroupsResultsFilesString = DoOrthogroups(options, dirs, seqsInfo, options.qDoubleBlast, options.separatePickleDir)
  File "/ceph/users/esjokvist/.conda/envs/orthofinder/bin/orthofinder", line 1217, in DoOrthogroups
    Lengths = GetSequenceLengths(seqsInfo, fileInfo)
  File "/ceph/users/esjokvist/.conda/envs/orthofinder/bin/orthofinder", line 330, in GetSequenceLengths
    sequenceLengths.append(np.zeros(seqsInfo.nSeqsPerSpecies[iFasta]))
KeyError: 115

Thanks,
Elisabet

**Comment by davidemms** [comment]
Hi Elisabet

It looks like the files probably haven't quite been prepared correctly. If you could attach the contents list of your 'orthofinder/' directory (e.g. `ls orthofinder/ > files.txt`) and also attach the SpeciesIDs.txt files then I'll take a look. You should be able to attach them here (or let me know if you'd prefer to email them).

All the best
David

**Comment by ESjokvist** [comment]
Hi David,

Thanks for the response. The files are attached. 

Best,
Elisabet

[SpeciesIDs.txt](https://github.com/davidemms/OrthoFinder/files/1785131/SpeciesIDs.txt)
[files.txt](https://github.com/davidemms/OrthoFinder/files/1785133/files.txt)

**Comment by davidemms** [comment]
Got it! You're missing the line for species 112 from your SpeciesIDs.txt file. If you put that line back in it should run without any problems.

All the best
David

**Comment by ESjokvist** [comment]
Oh lovely! Thanks :)

Elisabet
