### ISSUE TITLE
Having problems with the Blast run

### ISSUE THREAD

**Issue by drorhilman** [davidemms/OrthoFinder#14]
Hi, I have 63 proteomes I am trying to run OrthoFinder on.
The script worked fine with the example datasest,
 However, when I tried on my data-sets, it looks like the initial files were created fine, so does the SpeciesIDs.txt and SequenceIDs.txt, but the **blast files** came out empty!
So for each species I am getting the error: "**WARNING: Too few hits between species %d and species %d to normalise the scores, these hits will be ignored**".
So eventually I do not get any ortholog group!,
What could be the problem?

**Comment by davidemms** [comment]
Hi, the first thing to check is your input fasta files. Do they contain sequences? Are the amino acid sequences rather than nucleotides? Are there any other obvious problems with them?

**Comment by drorhilman** [comment]
Yes, there are 63 fasta files, containing protein sequences. The "Species%s.fa" files also seems OK. it also seems as the blast databases were created as well, but the blast%s_%s.txt files are empty. So for some reason, either blastp didn't work or that something went wrong with the program. How can I tell?

**Comment by drorhilman** [comment]
I tried again,
Now I see that the "BlastDBSpecies" files were not created.

**Comment by davidemms** [comment]
Could you paste/attach the output you get when you run OrthoFinder?

**Comment by drorhilman** [comment]
It seems as something went wrong in my linux machine mounting. I am running it on a different network drive, and now it seems fine. Thanks.
