### ISSUE TITLE
Orthofinder process state turned into sleep (Sl) when doing mcl

### ISSUE THREAD

**Issue by ZiyingKe** [davidemms/OrthoFinder#146]
Hi,
I am running orthofinder with nohup and the command is  'orthofinder -I 1.1 -f protein -t 32' (protein is a directory that I have put all my fasta files in) but every time the process state turns into sleep at the same place and the last line in my nohup.out file is always 'Written final scores for species 112 to graph file'.
When I do 'ps aux' , it shows:  
s1789887 170032 99.9  0.9 5050740 5026916 ?     Sl   Mar26 191:03 mcl /localdisk/home/s1789887/refseq/protein/Results_Mar25/WorkingDirectory/OrthoFinder_v2.1.2_graph.txt -I 1.1 -o /localdisk/home/s1789887/refseq/protein/Results_Mar25/WorkingDirectory/clusters_OrthoFinder_v2.1.2_I1.1.txt -te 1 -V all

I guess Sl means the process is 'sleeping' but why it turns into sleep at the same place everytime and it is possible to restart it?

Thank you,
Ziying

**Comment by davidemms** [comment]
Hi Ziying

I've not used nohup myself. A better way for launching any long running program such as OrthoFinder is in a [screen](https://uisapp2.iu.edu/confluence-prd/pages/viewpage.action?pageId=115540034) session.

All the best
David

**Comment by ZiyingKe** [comment]
Hi David,
Thank you for your suggestion. I will have a try.

Best wishes,
Ziying
