### ISSUE TITLE
Include shebang line with the interpreter directive

### ISSUE THREAD

**Issue by anpefi** [davidemms/OrthoFinder#16]
Hi David,

I'm using OrthoFInder through [a pipeline module I made](https://github.com/anpefi/agalma-modules) for [agalma](https://bitbucket.org/caseywdunn/agalma). The aim is to integrate orthofinder into the general agalma pipelines as an alternative to the default methods used in agalma for building a concatenated matrix of orthologous loci. 

These modules require that third-party software installed in the PATH as executables, so in the case of python scripts, like OrthoFinder, they would require a shebang pointing to python. I know that everyone can do it or that there is some workarounds (like using aliases), but I think that would be helpful to simplify the process of setting up the module if you can add the shebang `#!/usr/bin/env python` to your scripts rather than explain how to deal with that to some users.

Please, consider that cost-less addition.

Cheers,
Andrés

**Comment by davidemms** [comment]
Hi Andres

Thanks for the suggestion, I'll add the shebang line to the orthofinder.py and trees_for_orthogroups.py scripts. 

All the best
David
