### ISSUE TITLE
Error in OrthoFinder Algorithm 

### ISSUE THREAD

**Issue by aguirsx14** [davidemms/OrthoFinder#160]
Hey guys,

I'm doing some research and I cannot get orthofinder to work in comparing two fasta sequences between fish species. When I installed it, it worked fine on the ExampleData, but now it won't work for comparing other fasta sequences. I keep trying to run it and get this error. Can anyone explain why it won't work?

OrthoFinder version 2.2.3 Copyright (C) 2014 David Emms

32 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "makeblastdb -help" - ok
Test can run "blastp -help" - ok
Test can run "mcl -h" - ok
Test can run "fastme -i /home/BIO380_18_12/OrthoFinder/OrthoFinder-2.2.3/IA_Proteomes/SimpleTest.phy -o /home/BIO380_18_12/OrthoFinder/OrthoFinder-2.2.3/IA_Proteomes/SimpleTest.tre" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2018-04-23 04:18:15 : Creating Blast database 1 of 1

Running BLAST all-versus-all
----------------------------
Using 32 thread(s)
2018-04-23 04:18:17 : This may take some time....

Running OrthoFinder algorithm
-----------------------------
2018-04-23 07:43:05 : Initial processing of each species
2018-04-23 07:43:55 : Initial processing of species 0 complete
2018-04-23 07:44:01 : Connected putatitive homologs
/tmp/_MEIzqeejB/numpy/core/fromnumeric.py:37: RuntimeWarning: invalid value encountered in double_scalars
/tmp/_MEIzqeejB/numpy/core/fromnumeric.py:2374: RuntimeWarning: invalid value encountered in double_scalars
2018-04-23 07:44:04 : Ran MCL

Writing orthogroups to file
---------------------------
Orthogroups have been written to tab-delimited files:
   /home/BIO380_18_12/OrthoFinder/OrthoFinder-2.2.3/IA_Proteomes/Results_Apr23/Orthogroups.csv
   /home/BIO380_18_12/OrthoFinder/OrthoFinder-2.2.3/IA_Proteomes/Results_Apr23/Orthogroups.txt (OrthoMCL format)
   /home/BIO380_18_12/OrthoFinder/OrthoFinder-2.2.3/IA_Proteomes/Results_Apr23/Orthogroups_UnassignedGenes.csv
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1567, in <module>
  File "orthofinder/orthofinder.py", line 1270, in DoOrthogroups
  File "orthofinder/orthofinder.py", line 695, in Stats
StopIteration
Failed to execute script orthofinder
2018-04-23 07:44:03 : Written final scores for species 0 to graph file

**Comment by davidemms** [comment]
Hi

It looks like you have provided a directory one fasta file, is that right? It's recommended that you run OrthoFinder with a minimum of at least 4 species, although it is possible to run it with as few as two species although this isn't recommended.

All the best
David

**Comment by davidemms** [comment]
Thanks for reporting this issue, I've now submitted a fix to check that at least two fasta files are provided as input. I think this is probably the issue you were having, but please reopen the issue if not.

All the best
David
