### ISSUE TITLE
Reconciling gene trees with custom tree

### ISSUE THREAD

**Issue by bmmoore43** [davidemms/OrthoFinder#163]
Hello!
I have used orthofinder successfully using 25 species. The problem is the rooted species tree was slightly off. I then used the single copy orthogroups to generate a new species tree using MAFFT amd RAxML. However, when I input the new species tree and restart orthofinder at -ft, I get this error:
**Error:**
Using orthogroups in file:
    /mnt/home/john3784/3-Solanaceae_project/orthofinder_results/WorkingDirectory/Orthologues_Apr06/../Orthogroups_4.txt
and corresponding clusters file:
    /mnt/home/john3784/3-Solanaceae_project/orthofinder_results/WorkingDirectory/Orthologues_Apr06/../clusters_OrthoFinder_v2.1.2_I1.5_4.txt_id_pairs.txt
ERROR: Species names are not unique
Species 'Mpolymorpha_320_v3.1' appears 3 times
Species 'Nicotiana_tomen' appears 2 times
Species 'Osativa_323_v7.0' appears 2 times
Species 'Nicotiana_tabacum-TN90_AYMY-SS' appears 2 times
Species 'Mtruncatula_285_Mt4.0v1' appears 2 times
ERROR: An error occurred, please review previous error messages for more information.

**My input looks like this:** 
orthofinder -ft /mnt/home/john3784/3-Solanaceae_project/orthofinder_results/WorkingDirectory/Orthologues_Apr06/ -s /mnt/home/john3784/3-Solanaceae_project/orthofinder_results/WorkingDirectory/RAxML_bestTree.allspecies.mafft_align_mod.txt -t 8
**My species tree looks like this:**
((((((((Coffea_canephora:0.20336099425404582930,(Ipomoea_trifida_ITR_r1.0:0.20150465858344487891,(Petunia_axillaris:0.08624666676915652974,((Nicotiana_tabacum-TN90_AYMY-SS:0.00123702993334804008,Nicotiana_tomen:0.00550532085956650843):0.05875121052454949228,((Solanum_melongena:0.05874751223136523426,((Slycopersicum:0.00975060053146069652,Solanum_pennellii:0.00919869477003317296):0.02419143936319694335,Solanum_tuberosum:0.01900222514498418891):0.01706752083773248330):0.01787270626656232986,(Capsicum_annuum_Pepper.v.1.55:0.00079486398113940240,Capsicum_annuum_var.glabr_Chil:0.00167119048651178997):0.05605834806037292978):0.04012336306897368310):0.01352441570324714425):0.13345789026861323845):0.07919885408126497994):0.08072615807174732261,(Vvinifera_145:0.18528165287646622406,(Mtruncatula_285_Mt4.0v1:0.29422366442442376977,(Ptrichocarpa_210_v3.0:0.21829679889532807580,(Tcacao_233_v1.1:0.20948985202192144106,(BrapaFPsc_277_v1.3:0.07816591430823663367,((Alyrata_384_v2.1:0.01785484134537846865,Athaliana_167_TAIR10:0.02948792557353713609):0.00980084969888481844,Crubella_183_v1.0:0.05553556391728667330):0.03168332222389702579):0.29303778194818119740):0.03006889393480829259):0.03911625874126338498):0.04811092912698015922):0.03023873258592367844):0.10019466995543548082,Acoerulea_322_v3.1:0.34154838294870282223):0.12916401370701416362,Osativa_323_v7.0:0.72540253196126125435):0.11345708614353544608,Atrichopoda_291_v1.0:0.53841205723475593636):0.48996936638516558338,Pabies_HCMC:0.37231869224209013236):0.24690333530525485073,Smoellendorffii_91_v1.0:0.47980087261071857618):0.09162164891295104807,(Ppatens_318_v3.3:0.57136964651495114609,Mpolymorpha_320_v3.1:0.57658248292873726104):0.09162164891295104807);

What am I doing wrong?
Thank you for your help!

**Comment by davidemms** [comment]
Hi Bethany

Could you post the contents of your SpeciesIDs.txt file please and I'll take a look at what's happened. I think think the file will be in something like /mnt/home/john3784/3-Solanaceae_project/orthofinder_results/WorkingDirectory/.

Thanks
David

**Comment by bmmoore43** [comment]
Yes! the original speciesIDs.txt file is this:
0: Acoerulea_322_v3.1.faa
1: Alyrata_384_v2.1.faa
2: Athaliana_167_TAIR10.faa
3: Atrichopoda_291_v1.0.faa
4: BrapaFPsc_277_v1.3.faa
5: Capsicum_annuum_Pepper.v.1.55.faa
6: Capsicum_annuum_var.glabr_Chil.faa
7: Coffea_canephora.faa
8: Crubella_183_v1.0.faa
9: Ipomoea_trifida_ITR_r1.0.faa
#10: Mpolymorpha_320_v3.1.faa
#11: Mtruncatula_285_Mt4.0v1.faa
#12: Nicotiana_tabacum-TN90_AYMY-SS.faa
#13: Nicotiana_tomen.faa
#14: Osativa_323_v7.0.faa
#15: Mpolymorpha_320_v3.1.faa
16: Mtruncatula_285_Mt4.0v1.faa
17: Nicotiana_tabacum-TN90_AYMY-SS.faa
18: Nicotiana_tomen.faa
19: Osativa_323_v7.0.faa
20: Ppatens_318_v3.3.faa
21: Ptrichocarpa_210_v3.0.faa
22: Slycopersicum.faa
23: Mpolymorpha_320_v3.1.faa
24: Pabies_HCMC.faa
25: Petunia_axillaris.faa
26: Solanum_melongena.faa
27: Solanum_pennellii.faa
28: Solanum_tuberosum.faa
29: Smoellendorffii_91_v1.0.faa
30: Tcacao_233_v1.1.faa
31: Vvinifera_145.faa

And so I thought that maybe it was because I had the 'removed' species still in there, so I also tried removing the species with a # from both the speciesID.txt file and the sequenceID.txt file so it looks like this:
0: Acoerulea_322_v3.1.faa
1: Alyrata_384_v2.1.faa
2: Athaliana_167_TAIR10.faa
3: Atrichopoda_291_v1.0.faa
4: BrapaFPsc_277_v1.3.faa
5: Capsicum_annuum_Pepper.v.1.55.faa
6: Capsicum_annuum_var.glabr_Chil.faa
7: Coffea_canephora.faa
8: Crubella_183_v1.0.faa
9: Ipomoea_trifida_ITR_r1.0.faa
16: Mtruncatula_285_Mt4.0v1.faa
17: Nicotiana_tabacum-TN90_AYMY-SS.faa
18: Nicotiana_tomen.faa
19: Osativa_323_v7.0.faa
20: Ppatens_318_v3.3.faa
21: Ptrichocarpa_210_v3.0.faa
22: Slycopersicum.faa
23: Mpolymorpha_320_v3.1.faa
24: Pabies_HCMC.faa
25: Petunia_axillaris.faa
26: Solanum_melongena.faa
27: Solanum_pennellii.faa
28: Solanum_tuberosum.faa
29: Smoellendorffii_91_v1.0.faa
30: Tcacao_233_v1.1.faa

But then I get a different error which is this one:
WARNING:  When using FastTree multi-threading, please adjust your job submission script to request the appropriate resource reservation (e.g. ppn=2).

For single threaded runs, use: 'export OMP_NUM_THREADS=1'.

Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1581, in <module>
  File "orthofinder/orthofinder.py", line 1404, in GetOrthologues_FromTrees
  File "orthofinder/scripts/orthologues.py", line 847, in OrthologuesFromTrees
  File "orthofinder/scripts/orthologues.py", line 792, in ReconciliationAndOrthologues
  File "orthofinder/scripts/trees2ologs_of.py", line 387, in DoOrthologuesForOrthoFinder
  File "orthofinder/scripts/trees2ologs_of.py", line 249, in GetOrthologues_for_tree
KeyError: '29_18937'
Failed to execute script orthofinder

So it seems like it maybe fixed the original error, but now this is another error.

Again, thank you for your help!
Bethany

**Comment by davidemms** [comment]
Hi

A fix that should work is to edit your original SpeciesIDs.txt file so that none of the species have the same name, whether or not they are commented out. I.e. change the file so that the offending lines look like this:

<span>#</span>10: Not_used_Mpolymorpha_320_v3.1.faa
<span>#</span>11: Not_used_Mtruncatula_285_Mt4.0v1.faa
<span>#</span>12: Not_used_Nicotiana_tabacum-TN90_AYMY-SS.faa
<span>#</span>13: Not_used_Nicotiana_tomen.faa
<span>#</span>14: Not_used_Osativa_323_v7.0.faa
<span>#</span>15: Also_not_used_Mpolymorpha_320_v3.1.faa

I think it's probably not necessary to make any changes to the OrthoFinder code for this as the latest version doesn't allow species to be added with the same name (https://github.com/davidemms/OrthoFinder/commit/0035297340ce00fc728111033508a878a5f18e97) so this problem shouldn't occur from now on.

Let me know if this works. Thanks, 
David

**Comment by bmmoore43** [comment]
Hi David!
I will let you know if this works.. right now my job is waiting on the queue. Thank you for your help!

~Beth

**Comment by bmmoore43** [comment]
Hi David,

OK it looks like it throws an error because I didn't include these species in the species tree:

OrthoFinder version 2.1.2 Copyright (C) 2014 David Emms

8 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Using orthogroups in file:
    /mnt/home/john3784/3-Solanaceae_project/orthofinder_results/WorkingDirectory/Orthologues_Apr06/../Orthogroups_4.txt
and corresponding clusters file:
    /mnt/home/john3784/3-Solanaceae_project/orthofinder_results/WorkingDirectory/Orthologues_Apr06/../clusters_OrthoFinder_v2.1.2_I1.5_4.txt_id_pairs.txt

Checking required programs are installed
----------------------------------------
Test can run "fastme -i /mnt/home/john3784/3-Solanaceae_project/orthofinder_results/WorkingDirectory/Orthologues_Apr06/../SimpleTest.phy -o /mnt/home/john3784/3-Solanaceae_project/orthofinder_results/WorkingDirectory/Orthologues_Apr06/../SimpleTest.tre" - ok

Using orthogroups in file:
    /mnt/home/john3784/3-Solanaceae_project/orthofinder_results/WorkingDirectory/Orthologues_Apr06/../Orthogroups_4.txt
and corresponding clusters file:
    /mnt/home/john3784/3-Solanaceae_project/orthofinder_results/WorkingDirectory/Orthologues_Apr06/../clusters_OrthoFinder_v2.1.2_I1.5_4.txt_id_pairs.txt
ERROR: 'Not_used_Mtruncatula_285_Mt4.0v1' is missing from species tree
ERROR: 'Not_used_Mpolymorpha_320_v3.1' is missing from species tree
ERROR: 'Not_used_Nicotiana_tomen' is missing from species tree
ERROR: 'Not_used_Nicotiana_tabacum-TN90_AYMY-SS' is missing from species tree
ERROR: 'Also_not_used_Mpolymorpha_320_v3.1' is missing from species tree
ERROR: 'Not_used_Osativa_323_v7.0' is missing from species tree
ERROR: An error occurred, please review previous error messages for more information.

**Comment by davidemms** [comment]
Hi Beth

Thanks for pointing this out! I'm just submitted a fix now to resolve this, i.e. it will now only check the species tree for the required species, not ones that have been excluded. 

All the best
David

**Comment by davidemms** [comment]
The new release that includes this fix is available on the releases page (v2.2.6): https://github.com/davidemms/OrthoFinder/releases
