### ISSUE TITLE
Orthofinder is not recognizing makeblastdb

### ISSUE THREAD

**Issue by rafaeltiveron** [davidemms/OrthoFinder#164]
I installed ncbi-blast+ 2.7.1 manually in my Linux Ubuntu Mint 18.4, exported the PATH, but Orthofinder still doesn't recognize makeblastdb.

```
$ orthofinder -f ExampleData

OrthoFinder version 2.2.3 Copyright (C) 2014 David Emms

16 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "makeblastdb -help" - failed
ERROR: Cannot run BLAST+
Please check BLAST+ is installed and that the executables are in the system path

ERROR: An error occurred, please review error messages for more information.
```

```
$ makeblastdb
USAGE
  makeblastdb [-h] [-help] [-in input_file] [-input_type type]
    -dbtype molecule_type [-title database_title] [-parse_seqids]
    [-hash_index] [-mask_data mask_data_files] [-mask_id mask_algo_ids]
    [-mask_desc mask_algo_descriptions] [-gi_mask]
    [-gi_mask_name gi_based_mask_names] [-out database_name]
    [-max_file_sz number_of_bytes] [-logfile File_Name] [-taxid TaxID]
    [-taxid_map TaxIDMapFile] [-version]

DESCRIPTION
   Application to create BLAST databases, version 2.7.1+

Use '-help' to print detailed descriptions of command line arguments
========================================================================

Error: Argument "dbtype". Mandatory value is missing:  `String, `nucl', `prot''
Error:  (CArgException::eNoArg) Argument "dbtype". Mandatory value is missing:  `String, `nucl', `prot''
```
As you can see, the system is getting the path normally. There is no way for me to install as root. I've exported and tested in both, .bash_profile and/or .bashrc.

**Comment by davidemms** [comment]
Hi 

I've just downloaded and tested BLAST+ version 2.7.1 and haven't had any problems with using it with OrthoFinder. There's no need to install it as root, you just need the executables to work and to be in the (exported) PATH variable, which it sounds like you've done. 

Are you still having problems with it? If so, could you just double check everything? For example, by running the following commands in order and from the same terminal.

```
$ export PATH=your_list_of_path_directories_here
$ which makeblastdb 
```
(confirm it gives the correct path to the makeblastdb executable)
```
$ makeblastdb -help
```
(confirm it runs correctly)
```
$ orthofinder -f ExampleData
```

It looks like this is probably what you've done, but I'd recommend double-checking all of this first. If there are still problems we can look for other potential causes.

All the best
David

**Comment by rafaeltiveron** [comment]
Hi David, thanks. The problem was on .bash_profile that wasn't invoking "which makeblastdb". There was:
`export PATH="your_list_of_path_directories_here"` and the correct form needs to be `export PATH=your_list_of_path_directories_here`.
