### ISSUE TITLE
Using diamond instead of BLAST

### ISSUE THREAD

**Issue by reubwn** [davidemms/OrthoFinder#167]
Hello,

First, thanks for the great tool!

I'm having trouble using the `-S diamond` option. The program fails with:
```
ERROR: Cannot run diamond
Format of make database command:
  diamond makedb --in INPUT -d OUTPUT
ERROR: Cannot run diamond
Format of search database command:
  diamond blastp -d DATABASE -q INPUT -o OUTPUT --more-sensitive -p 1 --quiet -e 0.001 --compress 1
Please check diamond is installed and that the executables are in the system path
```

The diamond executable is in my $PATH and should be discoverable (e.g., no problem with `which diamond`).

I can bodge it by commenting out the testing parts in `CheckDependencies` of the main orthofinder.py script:
```
elif not program_caller.TestSearchMethod(dirForTempFiles, options.search_program):
            print("\nERROR: Cannot run %s" % options.search_program)
            print("Format of make database command:")
            print("  " + program_caller.GetSearchMethodCommand_DB(options.search_program, "INPUT", "OUTPUT"))
            print("ERROR: Cannot run %s" % options.search_program)
            print("Format of search database command:")
            print("  " + program_caller.GetSearchMethodCommand_Search(options.search_program, "INPUT", "DATABASE", "OUTPUT"))
            print("Please check %s is installed and that the executables are in the system path\n" % options.search_program)
            util.Fail()
```

This stops the program from quitting at testing, but (unsurprisingly perhaps) runs into problems later. The per-species diamond databases (*.dmnd files) are created and are correctly formatted (I checked by running diamond blastp on them outwith the orthofinder program) but the program fails with:
```
Running OrthoFinder algorithm
-----------------------------
2018-05-23 16:02:54 : Initial processing of each species
Malformatted line in /med-bio/rnowell/analysis/orthofinder/pop_bdelloid/proteins/Results_test_May23_2/WorkingDirectory/Blast0_0.txt
Offending line was:

Process Process-10:
Traceback (most recent call last):
  File "/home/rnowell/.localpython/Python-2.7.9/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/rnowell/.localpython/Python-2.7.9/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rnowell/software/OrthoFinder/orthofinder/orthofinder.py", line 484, in Worker_ProcessBlastHits
    WaterfallMethod.ProcessBlastHits(*args, qDoubleBlast=qDoubleBlast)
  File "/home/rnowell/software/OrthoFinder/orthofinder/orthofinder.py", line 471, in ProcessBlastHits
    Bij = BlastFileProcessor.GetBLAST6Scores(seqsInfo, fileInfo, seqsInfo.speciesToUse[iSpecies], seqsInfo.speciesToUse[jSpecies], qDoubleBlast=qDoubleBlast)
  File "/export131/home/rnowell/software/OrthoFinder/orthofinder/scripts/blast_file_processor.py", line 61, in GetBLAST6Scores
    with (gzip.open(fn + ".gz", 'rb') if os.path.exists(fn + ".gz") else open(fn, 'rb')) as blastfile:
IOError: [Errno 2] No such file or directory: '/med-bio/rnowell/analysis/orthofinder/pop_bdelloid/proteins/Results_test_May23_2/WorkingDirectory/Blast0_0.txt'
ERROR: An error occurred, please review error messages for more information.
```

It would appear the results files (BLAST0_0.txt etc) were not generated:
```
/path/to/WorkingDirectory/ $ ll
total 1.3G
-rw-rw-r-- 1 foo hpc-users 13M May 23 16:02 SequenceIDs.txt
-rw-rw-r-- 1 foo hpc-users 16M May 23 16:02 Species0.fa
-rw-rw-r-- 1 foo hpc-users 15M May 23 16:02 Species1.fa
-rw-rw-r-- 1 foo hpc-users 15M May 23 16:02 Species2.fa
-rw-rw-r-- 1 foo hpc-users 296 May 23 16:02 SpeciesIDs.txt
-rw-rw-r-- 1 foo hpc-users 36M May 23 16:02 diamondDBSpecies0.dmnd
-rw-rw-r-- 1 foo hpc-users 36M May 23 16:02 diamondDBSpecies1.dmnd
-rw-rw-r-- 1 foo hpc-users 36M May 23 16:02 diamondDBSpecies2.dmnd
```

At this point I stopped fiddling :-)
Any insights? I wondered if diamond is fully implemented currently? It's a great idea to use it, substantially faster than BLASTP.

Many thanks,
reubwn

**Comment by davidemms** [comment]
Hi

That's strange, diamond is definitely what I'd recommend from now and is fully implemented. A couple of ideas to try:

Have you exported the PATH variable: "export PATH"? Although perhaps that's unlikely if it's created the databases correctly.

Test `diamond blastp -d diamondDBSpecies0 -q Species0.fa -o TestOut.txt -more-sensitive -p 1 --quiet -e 0.001 --compress 1`. There were some problems with some of the versions of diamond prior to v0.9.21, see https://github.com/davidemms/OrthoFinder/issues/43.

Let me know if neither of those suggestions identify the problem and we can try something else. What version of diamond are you using?

All the best
David

**Comment by reubwn** [comment]
Aha, yes updating to diamond 0.9.22 did the trick! (had been using 0.7.10)

Because it was failing at the testing dependencies stage I had thought it was something more along the lines with how OrthoFinder was trying to find the diamond executable, rather than diamond itself.

Thanks for the quick response!

Cheers,
reubwn

**Comment by davidemms** [comment]
No problem, glad it's working now!

David
