### ISSUE TITLE
problem with species-specific hypothetical protein family

### ISSUE THREAD

**Issue by dw2018** [davidemms/OrthoFinder#169]
Hi

I ran orthofinder (versin 2.2.6) with five (not closely related) species, of which one species (A) has several species-specific (hypothetical) protein families (see below for orthofinder stats). See e.g. this blastp output for 13x00830 of A vs proteome of A:

query subject ... evalue bit score
13x00830	13x00830	100.00	365	0	0	1	365	1	365	0.0	 735
13x00830	13x00690	74.23	357	89	2	1	357	1	354	2e-146	 514
13x00830	13x00700	75.66	341	80	2	7	347	138	475	2e-142	 501
13x00830	13x01860	69.47	357	94	6	1	356	1	343	8e-128	 452
13x00830	13x00810	61.96	368	44	6	1	366	1	274	2e-110	 395
13x00830	13x01040	59.84	254	74	7	1	213	1	249	4e-71	 264
13x00830	13x01040	37.11	194	85	6	10	179	102	282	2e-22	 102
13x00830	13x01040	32.54	252	111	6	120	346	53	270	9e-19	90.5
13x00830	13x00630	50.47	139	119	12	1	292	1	307	3e-66	 248
13x00830	13x01060	57.48	254	76	8	1	213	1	245	8e-57	 216
13x00830	13x01060	37.70	191	82	6	10	176	98	275	3e-22	 101
13x00830	13x01060	32.14	252	112	6	120	346	49	266	1e-14	76.6
13x00830	13x00770	53.93	191	66	7	14	192	3	183	3e-37	 151
13x00830	13x00890	66.04	106	27	1	1	106	1	97	8e-34	 140
13x00830	13x00850	66.04	106	27	1	1	106	1	97	8e-34	 140
13x00830	14x02720	40.34	238	115	8	1	216	20	252	6e-32	 134
13x00830	14x02720	38.94	113	64	3	115	224	67	177	4e-11	64.7
13x00830	03x07610	41.86	129	70	1	181	309	22	145	2e-21	99.4
13x00830	03x07590	41.86	129	70	1	181	309	22	145	2e-21	99.4

However, these proteins are each assigned to an individual cluster (e.g. 13x00830 in clusterX,13x00690 in clusterY..) instead of all being assigned to one cluster. I played with the inflation parameter of MCL (set to 1.1 instead of default 1.5) but this does not solve the problem.

Is there any other way, to change the settings of Orthofinder to cluster these proteins into one cluster?

Thank you in advance!

###################
orthofinder stats:
Species	B	C A	D	E
"Number of genes	16376	17310	19086	20219	13931"
"Number of genes in orthogroups	7103	10871	9778	7650	8559"
"Number of unassigned genes	9273	6439	9308	12569	5372"
"Percentage of genes in orthogroups	43.4	62.8	51.2	37.8	61.4"
"Percentage of unassigned genes	56.6	37.2	48.8	62.2	38.6"
"Number of orthogroups containing species	5522	5933	5773	5094	5945"
"Percentage of orthogroups containing species	78.5	84.4	82.1	72.4	84.5"
"Number of species-specific orthogroups	13	22	31	33	21"
"Number of genes in species-specific orthogroups	56	319	635	372	187"
"Percentage of genes in species-specific orthogroups	0.3	1.8	3.3	1.8	1.3"

**Comment by davidemms** [comment]
Hi

I have a solution for this that I'm testing at the moment, it should be available in the next few months. 

All the best
David

**Comment by lassancejm** [comment]
Hi, 
Any chance that your solution would be mature enough to be released? I am interested in clustering species-specific genes in 'paragroups'. Such genes currently end up as singleton in the unassigned gene category.

Thanks!
JM

**Comment by davidemms** [comment]
HI JM

Thanks for asking, this is part of a larger part of work on unclustered genes which isn't quite finished yet. However, the species-specific orthogroups are ready to go so I've just up uploaded code for that (220e3ba4adf68e8f030f1afb04a4082c1249749b) so you can try it out. 

All the best
David

**Comment by lassancejm** [comment]
Hi David, 

Awesome. I pulled the updated code and run a quick test. At first glance,  it seems to be doing exactly what I want. 

Thanks for implementing this!

JM

**Comment by dw2018** [comment]
Hi David

I tried to run your  update, but somehow it is not working in my hands. I ran "python orthofinder.py" after downloading the github master but then I got the following error:

Traceback (most recent call last):
  File "orthofinder.py", line 39, in <module>
    from scipy.optimize import curve_fit            # install
ImportError: No module named scipy.optimize

Probably I am doing something wrong. Would you have any suggestion to solve my issue?

Thank you.

**Comment by davidemms** [comment]
Hi

For the source code version of OrthoFinder you need to install the scipy library (https://github.com/davidemms/OrthoFinder#python-source-code-version).

All the best
David
