### ISSUE TITLE
add species fails after blast searches complete: duplicate sequence ID

### ISSUE THREAD

**Issue by l-yampolsky** [davidemms/OrthoFinder#174]
Updated version of the issue:

I am still having trouble running OF by dropping / adding species to previously completed analysis.

Blast searches completed successfully. So now I am starting it with -b option. And get the following:

ERROR: /WorkingDirectory/SequenceIDs.txt contains a duplicate ID. The IDs for the orthogroups in /WorkingDirectory/clusters_OrthoFinder_v2.2.0_I1.5_2.txt_id_pairs.txt will not be replaced with the sequence accessions. If /WorkingDirectory/SequenceIDs.txt was prepared manually then please check the IDs are correct. 
ERROR: An error occurred, please review error messages for more information.
2018-06-19 19:42:46 : Written final scores for species 6 to graph file
2018-06-19 19:42:47 : Written final scores for species 0 to graph file
2018-06-19 19:42:48 : Written final scores for species 7 to graph file
2018-06-19 19:42:49 : Written final scores for species 2 to graph file
2018-06-19 19:42:49 : Written final scores for species 1 to graph file

On a couple of runs it proceeds to various steps of writing to graph file, but then invariably dies.

Again, would be very grateful for suggestions of what may be going wrong.

Lev Yampolsky

**Comment by l-yampolsky** [comment]
Actually the behavior changes depending on I am not sure what... sometimes it fails with the message as above, sometimes with this:
ore of-f-adddrop.sh.o867646

OrthoFinder version 2.2.0 Copyright (C) 2014 David Emms

24 thread(s) for highly parallel tasks (BLAST searches etc.)
8 thread(s) for OrthoFinder algorithm

Checking required programs are installed
[all ok]

Adding new species in /lustre/haven/proj/ETSU0001/KnightRiderBackup2/yampolsk/project_gammarus/4root17sp/bragr/ to existing analysis in /lustre/haven/proj/ETSU0001/KnightRiderBackup2/yampolsk/project
_gammarus/4root17sp/Results_Mar17/WorkingDirectory/


more of-f-adddrop.sh.e867646
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1510, in <module>
  File "orthofinder/orthofinder.py", line 1436, in ProcessesNewFasta
ValueError: invalid literal for int() with base 10: ''
Failed to execute script orthofinder


I'm lost. Thanks in advance for any help!

**Comment by l-yampolsky** [comment]
now it's running.
I think what was happening is this: there was an empty line in SpeciesIDs.txt. Not sure how it got there, perhaps when I was commenting species to drop. That empty line was causing the problem.

**Comment by l-yampolsky** [comment]
further update: manual removal of duplicate sequence IDs solves the problem. All duplicates were for the newly added species. I wonder what I did wrong to add the new species sequences to the SequenceIDs.txt twice.

**Comment by davidemms** [comment]
Hi Lev

It sounds like you may have attempted to add some species but had a problem and then tried a second time to run it adding those new species. I can see that a problem would occur if the IDs of species were added by OrthoFinder to the IDs file and then it crashed. Do you think this is what happened? I think I should add some functionality to OrthoFinder so that it reverts the IDs files back to a clean state if a failure occurs so as to prevent this happening.

As to the second error, that has been fixed in the latest version of OrthoFinder (with this commit: 7d6fbff52fd1b305d04ef7a56e1bdd41ee8ba2ec)

All the best
David

**Comment by l-yampolsky** [comment]
that's exactly what happened. yes, it would be great for the future to add the revert to clean state feature. And thanks for fixing the second issue, I'll update my installation!
LY

**Comment by davidemms** [comment]
Thanks for confirming, I leave this issue open as a reminder to do that.

**Comment by kstankie** [comment]
Hello, I experienced a similar issue that was resolved by manually removing the duplicate IDs. However, now, I am receiving this error message when trying to run orthofinder with the addition of two new species:

Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1510, in <module>
  File "orthofinder/orthofinder.py", line 1436, in ProcessesNewFasta
ValueError: invalid literal for int() with base 10: ''
Failed to execute script orthofinder

Has anyone else had this problem? 

Thanks!

**Comment by davidemms** [comment]
Hi

It sounds like you probably didn't revert the files to their previous state. Judging from the error message, perhaps there was a newline at the end of the file?

**Comment by kstankie** [comment]
Hi David,

Thanks for your reply. You were correct and this fixed the issue. It ran successfully, and I see the blast reports for the additional new species, however, other files such as the "Statistics_Overall.csv" and the "Orthogroups.GeneCounts.csv" have not been updated to include the new species. Is there a way I can ensure that these files are updated?

Thanks again.

**Comment by davidemms** [comment]
Hi kstankie

Could you post the output that OrthoFinder printed to screen please?

Thanks
David

**Comment by kstankie** [comment]
Hi David,

Sorry for the delayed reply. I ended up finding that there were still some additional lines of duplicated gene IDs that I had not deleted. I'm not sure why it was able to get so far into the analysis this time before snagging and error. So, I was able to re-run successfully after this. 

Thanks for your help!
