### ISSUE TITLE
OrthoFinder or Diamond is sensitive to '.' at the end of sequences

### ISSUE THREAD

**Issue by josiahseaman** [davidemms/OrthoFinder#175]
This issue cost me 3 hours before I was able to track it down because Diamond error messages don't propagate back up to OrthoFinder.  I'm posting it here so that it can help others or hopefully be handled more gracefully in the future.

OrthoFinder will fail out saying that it can't find BLAST results.
```
IOError: [Errno 2] No such file or directory: '.../Proteome/Results_Jun18/WorkingDirectory/Blast0_0.txt'
```
This is because Diamond died in the database creation step.  No *.dmnd files were created.

The **solution** was to remove the offending character at the end of each sequence (newline) but not . in other contexts:
```
head filtered_protein.fasta
>FRAEX38873_V2_000007600.2_R0 gene=gene_2
MEDTDERKLFVGAKDRNTGTPRGFAFICFSESSAVELALQDSHEILGRMVDVKKAIPRSEQQQSQQQHNR
GLSRDTRTNGRSNDKFRTKKIFVGGLSANLTEEEFRSYFEKFGMITDVVIMQDSMTHRPRGFGFITFDLE
DSVEDVMKKNFYELNGKLVEVKRAVPKDGISSSNNGSNGRPGGGSGSNFNSYQLGSYPTYNPYYPSGYGN
VSGYPYGTGTYGGGYPSGGYGGLGYNFTPIGPRSPWNASAMVGVGGSLLHYGSATPIYPSYLNGGAGVMG
FSVSGYNGIFGTGFNGKSSQLGNTDTQGAAESVPSQTSRGNVDDNFYSSGRTDGAAADKQNEERNDEQFK
SDPVGNSS.
>FRAEX38873_V2_000091130.1_R0 gene=gene_3

sed -i -e ':a;N;$!ba;s/\.\n/\n/g' filtered_protein.fasta
```
That last line replaces `.\n` with `\n`.  Here's an [explanation of the syntax](https://stackoverflow.com/a/1252191/3067894).

**Comment by davidemms** [comment]
Yes, it appears as though diamond accepts '*'.

**Comment by davidemms** [comment]
Hi Josiah

I'm submitting a fix so that OrthoFinder prints the error messages from diamond if the makedb step fails. Thanks for posting this.

All the best
David

**Comment by josiahseaman** [comment]
Thank you for the fix!

Kind regards
Josiah
