### ISSUE TITLE
conda OrthoFinder

### ISSUE THREAD

**Issue by micromania2** [davidemms/OrthoFinder#178]
Hi I am installing OrthoFinder via conda cloud using

**conda install -c bioconda orthofinder**

I am installing this into a new (no apps have been installed) conda folder. There are no other apps installed but I still get a conflict error...

**UnsatisfiableError: The following specifications were found to be in conflict:
  - orthofinder
  - ruamel_yaml
Use "conda info <package>" to see the dependencies for each package.**

How can I resolve this issue?

Thanks,
Chris

**Comment by davidemms** [comment]
Hi Chris

I'm not familiar with conda cloud. Possibly the person who maintains or created the package looks at this forum, but I suspect you may need to track down the a more specific conda/bioconda forum where such bugs problems should be reported.

All the best
David

**Comment by micromania2** [comment]
Oh ok, I thought you all had submitted your software there. Will check with them.

**Comment by emilhaegglund** [comment]
Create a new conda environment with Python 2.7 and then install Orthofinder in the clean environment.
```
conda create --name orthofinder_env --channel bioconda python=2.7 orthofinder
```
