### ISSUE TITLE
Species Tree Orthogroups

### ISSUE THREAD

**Issue by HRitchie89** [davidemms/OrthoFinder#179]
Hi,

Sorry if this is a silly question but I can't seem to figure something out. 

I have successfully ran Orthofinder across 21 species where the computed species tree was built "using 1006 orthogroups with a minimum of 71.4% of species having single copy genes in the orthogroups". I have located the file that lists all the single copy orthogroups (78 in total) but I can't seem to figure out which orthogroups the remaining 928 belong to. 

I'm using the MSA method as ideally I want to use downstream analysis to identify which orthogroups are responsible for driving the topology of the species tree. (I have actually done this using the SpeciesTreeAllignment.fa and can identify the regions that are responsible but now can't work out how to partition the SpeciesTreeAllignment.fa back into individual Orthogroups as I can't find a definitive list of which 1006 orthogroups were concatenated into the SpeciesTreeAllignment.fa).

Any pointer would be greatly appreciated.

Thanks in advance,
Heather

**Comment by davidemms** [comment]
Hi Heather

71.4% of your species correspond to 15 species so the 1006 orthogroups will be those which have exactly one gene in at least 15 of the species and either no genes or more than one gene in the remaining species. You'd be able to identify them from the Orthogroups.GeneCount.csv file. I've attached an example spreadsheet where I've used a few excel formulae to identify 249 orthogroups with minimum of 75% of species having single copy genes, could can adapt this to your dataset.
[Orthogroups.GeneCount_IdentifyMostlySingleCopy.xlsx](https://github.com/davidemms/OrthoFinder/files/2171359/Orthogroups.GeneCount_IdentifyMostlySingleCopy.xlsx)

I think with the orthogroups identified you should be able to re-partion the SpeciesTreeAllignment.fa, note that columns that are more than 50% gaps are removed.

All the best
David

**Comment by HRitchie89** [comment]
Hi David,

Thanks for this. I've had a play around with my Orthogroups.GeneCount.csv file but I still can't pin down the exact orthogroups used.

I have a total of 67,855 orthogroups and using your formula I can identify that 78 of these are single copies in all 21 of my species. This matches the output SingleCopyOrthogroups.txt so i'm happy the formula works.

My issue is that using the formula I identify 3031 orthogroups with a minimum of 71.4%/15 species species with exactly one gene in at least 15 of the species and either no genes or more than one gene in the remaining species. 

If I order the orthogroups by gene count the 1006th orthogroup contains 17 species with a single copy.

Number of individuals with single copy orthogroup     number of orthogroups
21                                                                                        78
20                                                                                        158
19                                                                                        262
18                                                                                        404
17                                                                                        548
16                                                                                        680
15                                                                                        901
                                                                                 sum= 3031

Do you have any idea why it would only use 1006 orthogroups from the 3031 identified? And would it likely just use the first chronological 1006 groups that satisfied its criteria, or would it stop at the 1006th orthogroup (which above suggests would be somewhere in range of 17 species with single copies)? 

Sorry to be a pain - I feel like I'm missing something obvious but can't seem to understand it.

Many thanks,
Heather
