### ISSUE TITLE
Can't find output after removing species

### ISSUE THREAD

**Issue by mthon** [davidemms/OrthoFinder#182]
I followed the documentation to remove several species from my original output.  I commented out the species in the SpeciesIDs.txt file and then re-ran orthofinder like this:
orthofinder.py -t 12 -a 12 -b fasta/Results_Jul13/WorkingDirectory/
the file Orthogroups.csv and the other files have the time stamp of the original orthofinder run and their contents haven't changed.  I looked in some other directories but I don't see any new results.  Where should they be?  I didn't see any errors from the second run but I didn't review all of the STDOUT so I can't be sure there wasn't an error in there.

**Comment by davidemms** [comment]
Hi

The location of the results files is printed to the terminal at the end of the OrthoFinder run. I think the files will be in the 'WorkingDirectory' that contained the SpeciesIDs.txt file that you edited.

All the best
David
