### ISSUE TITLE
TOO FEW SPECIES

### ISSUE THREAD

**Issue by xinliu005** [davidemms/OrthoFinder#185]
@davidemms 
Dear David,
6 species, but still got the error message as "TOO FEW SPECIES". Could you please have a look whether there is any problem in clustalO_output.txt (attached)?

/nfs/production/seqdb/embl/developer/xin/bin/standard-RAxML-master/raxmlHPC -m PROTGAMMALG -s clustalO_output.txt -n xin_prefix
TOO FEW SPECIES
[clustalO_output.txt](https://github.com/davidemms/OrthoFinder/files/2209803/clustalO_output.txt)

Kind regards,
Xin

**Comment by davidemms** [comment]
Dear Xin

It sounds like you're having a problem with RAxML, is that correct? It doesn't look like this is an OrthoFinder issue?

All the best
David
