### ISSUE TITLE
stacks error? 

### ISSUE THREAD

**Issue by setarehi** [davidemms/OrthoFinder#186]
Dear David,

Thank you for your kind replies. I think that I have almost finished my analyses. But now I get the following error, do you have any idea how I can fix this? 

My best,
Setareh

Best outgroup(s) for species tree
---------------------------------
Observed 1899 well-supported, non-terminal duplications. 1884 support the best root and 15 contradict it.
Best outgroup for species tree:
  vvi, csi, tca

Reconciling gene trees and species tree
---------------------------------------
Outgroup: vvi, csi, tca
2018-07-07 19:48:26 : Done 0 of 22348
2018-07-09 03:23:11 : Done 1000 of 22348
2018-07-10 06:10:36 : Done 2000 of 22348
2018-07-11 07:44:05 : Done 3000 of 22348
2018-07-12 09:08:36 : Done 4000 of 22348
2018-07-13 11:52:17 : Done 5000 of 22348
Traceback (most recent call last):
  File "orthofinder.py", line 1578, in <module>
    GetOrthologues(dirs, options, program_caller, clustersFilename_pairs)
  File "orthofinder.py", line 1398, in GetOrthologues
    options.name)
  File "/media/biosys3/UNTITLED/OrthoFinder-2.2.1/orthofinder/scripts/orthologues.py", line 1085, in OrthologuesWorkflow
    ReconciliationAndOrthologues(recon_method, db.TreeFilename_IDs, db.ogSet, speciesTree_fn, db.workingDir, resultsDir_new, reconTreesRenamedDir, nHighParallel, i if qMultiple else None, pickleDir=pickleDir, all_stride_dup_genes=all_stride_dup_genes) 
  File "/media/biosys3/UNTITLED/OrthoFinder-2.2.1/orthofinder/scripts/orthologues.py", line 859, in ReconciliationAndOrthologues
    nOrthologues_SpPair = trees2ologs_of.DoOrthologuesForOrthoFinder(ogSet, treesIDsPatFn, speciesTree_fn, trees2ologs_of.GeneToSpecies_dash, workingDir, resultsDir, reconTreesRenamedDir, all_stride_dup_genes)
  File "/media/biosys3/UNTITLED/OrthoFinder-2.2.1/orthofinder/scripts/trees2ologs_of.py", line 562, in DoOrthologuesForOrthoFinder
    orthologues, recon_tree, suspect_genes = GetOrthologues_for_tree(iog, treesIDsPatFn(iog), species_tree_rooted, GeneToSpecies, neighbours, dupsWriter=dupWriter, seqIDs=ogSet.Spec_SeqDict(), spIDs=ogSet.SpeciesDict(), all_stride_dup_genes=all_stride_dup_genes)
ValueError: need more than 2 values to unpack

**Comment by davidemms** [comment]
Hi Setareh

I think that one of the gene trees couldn't be inferred and OrthoFinder dealt with the missing file incorrectly. I have fixed what I think is the problem. You'll need to download the latest version of the orthofinder code (front page: https://github.com/davidemms/OrthoFinder, click "Clone or download" button). You should be able to restart from the gene trees that have already been inferred using the options, "-ft DIRECTORY_NAME" where DIRECTORY_NAME is something like the directory containing the directories "Gene_Trees", "Orthologues" etc. (e.g. "ExampleDataset/Results_Jul30/Orthologues_Jul30/").

All the best
David

**Comment by setarehi** [comment]
Hi David,

Thank you for your response and I am sorry that I bothered you while you
were off. I hope that you have had a good off the grid time :). Thank you
for quickly fixing this.
Sorry but I am a bit confused about what is happening as I get now the
following error:

####
python orthofinder_better.py -ft
/media/biosys3/UNTITLED/OrthoFinder-2.2.1/orthofinder/Sequences/Results_May02_1/WorkingDirectory/Orthologues_Jul02
-t 20

OrthoFinder version 2.2.1 Copyright (C) 2014 David Emms

2018-07-31 07:57:07 : Starting OrthoFinder
20 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm
ERROR: Results from multiple OrthoFinder runs found

Tab-delimiter Orthogroups*.txt/OrthologousGroups*.txt files:

/media/biosys3/UNTITLED/OrthoFinder-2.2.1/orthofinder/Sequences/Results_May02_1/WorkingDirectory/Orthologues_Jul02/../../Orthogroups.txt

/media/biosys3/UNTITLED/OrthoFinder-2.2.1/orthofinder/Sequences/Results_May02_1/WorkingDirectory/Orthologues_Jul02/../Orthogroups_1.txt

/media/biosys3/UNTITLED/OrthoFinder-2.2.1/orthofinder/Sequences/Results_May02_1/WorkingDirectory/Orthologues_Jul02/../Orthogroups_2.txt

/media/biosys3/UNTITLED/OrthoFinder-2.2.1/orthofinder/Sequences/Results_May02_1/WorkingDirectory/Orthologues_Jul02/../Orthogroups_3.txt
With corresponding cluster files:

/media/biosys3/UNTITLED/OrthoFinder-2.2.1/orthofinder/Sequences/Results_May02_1/WorkingDirectory/Orthologues_Jul02/../clusters_OrthoFinder_v2.2.1_I1.5.txt_id_pairs.txt

/media/biosys3/UNTITLED/OrthoFinder-2.2.1/orthofinder/Sequences/Results_May02_1/WorkingDirectory/Orthologues_Jul02/../clusters_OrthoFinder_v2.2.1_I1.5_1.txt_id_pairs.txt

/media/biosys3/UNTITLED/OrthoFinder-2.2.1/orthofinder/Sequences/Results_May02_1/WorkingDirectory/Orthologues_Jul02/../clusters_OrthoFinder_v2.2.1_I1.5_2.txt_id_pairs.txt

/media/biosys3/UNTITLED/OrthoFinder-2.2.1/orthofinder/Sequences/Results_May02_1/WorkingDirectory/Orthologues_Jul02/../clusters_OrthoFinder_v2.2.1_I1.5_3.txt_id_pairs.txt

Please run with only one set of results in directories or specifiy the
specific clusters_OrthoFinder_*.txt_id_pairs.txt file on the command line
ERROR: An error occurred, please review error messages for more information.
###

So what I understand is that the program quit while it was reconciling the
gene trees with the species trees. So what happens that it now gets
confused?

And the final speciestree is the one that is now in the working directory
right?

Sorry again for all these questions, but I just want to make sure that I
understand all well.

My best,
Setareh

**Comment by davidemms** [comment]
Hi Setareh

It looks like you've run OrthoFinder at least 4 times for which it has successfully inferred orthogroups and now it doesn't know which of these results files it should use. In fact, I don't know if I'd know either! I wonder if the easiest thing would be to do a clean start?

Alternatively, did you use the same set of species each time? If so, then the results in the files Orthogroups.txt, Orthogroups_1.txt, Orthogroups_2.txt, Orthogroups_3.txt are probably all the same. Is that right? If so, try removing the extra results files from the subsequent runs:  Orthogroups_1.txt, .._2.txt, .._3.txt, clusters_OrthoFinder_v2.2.1_I1.5_1.txt_id_pairs.txt, ..._2.txt_id_pairs.txt, .._3.txt_id_pairs.txt and clusters_OrthoFinder_v2.2.1_I1.5_1.txt, ..._2.txt, .._3.txt and put them somewhere else. That way you should have only set of orthogroup results files and it shouldn't get confused as long as they correspond to the trees that were generated. Then run the command:

python orthofinder_better.py -ft /media/biosys3/UNTITLED/OrthoFinder-2.2.1/orthofinder/Sequences/Results_May02_1/WorkingDirectory/Orthologues_Jul02 -t 20

This might work.

All the best
David

**Comment by setarehi** [comment]
Hi David,

Thank you very much. I will do a clean start from the Blast results....lets
see how it works this time.

Cheerio,
Setareh
