### ISSUE TITLE
OrthoFinder

### ISSUE THREAD

**Issue by juulluu21** [davidemms/OrthoFinder#188]
Hello,

I am running OrthoFinder in HPC. I have received these error messages. Not sure what went wrong. 

_Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1549, in <module>
  File "orthofinder/orthofinder.py", line 1398, in GetOrthologues
  File "orthofinder/scripts/orthologues.py", line 948, in OrthologuesWorkflow
  File "orthofinder/scripts/orthologues.py", line 408, in RunAnalysis
  File "orthofinder/scripts/stag.py", line 252, in Run_ForOrthoFinder
  File "orthofinder/scripts/stag.py", line 237, in InferSpeciesTree
  File "orthofinder/scripts/consensus_tree.py", line 249, in ConsensusTree
  File "orthofinder/scripts/consensus_tree.py", line 153, in GetAllSplits
  File "orthofinder/scripts/tree.py", line 180, in __init__
  File "orthofinder/scripts/newick.py", line 231, in read_newick
scripts.newick.NewickError: Unexisting tree file or Malformed newick tree structure.
Failed to execute script orthofinder_

Would you please give me some explanation?

Thank you very much!

**Comment by davidemms** [comment]
Hi 

It looks like something went wrong with the tree inference. In your results directory there should be a directory called something like: Results_May23/Orthologues_May23/WorkingDirectory/SpeciesTrees_ids/. This should contain the set of newick tree files. Are there files present and non-empty? Could you post me the contents of the first one?

All the best
David

**Comment by davidemms** [comment]
Hi

Did you make any progress with this?

Thanks
David

**Comment by menghappy324** [comment]
Hi, when I use the orthofinder, I find the  sequence search program included  blast, mmseqs, blast_gz, diamond. Now, I want to consult that when I use -S diamond like this:  orthofinder -f /data/plantlab/miniconda3/pkgs/orthofinder-2.2.7-0/ExampleData -S diamond, how much the alignment similarity is. Besides,  the "-S diamond" made my programm stop and showed as below "ERROR: Cannot run diamond
Format of make database command:
  diamond makedb --in INPUT -d OUTPUT
ERROR: Cannot run diamond
Format of search database command:
  diamond blastp -d DATABASE -q INPUT -o OUTPUT --more-sensitive -p 1 --quiet -e 0.001 --compress 1
Please check diamond is installed and that the executables are in the system path", but in fact, I have installed the diamond 2.2.7 successfully. Is it the problem of the version? Thank you very much.

**Comment by davidemms** [comment]
Hi menghappy324, this isn't related to the question above, could you open a new issue for it please. 

Thanks
David

**Comment by davidemms** [comment]
Hi

I've moved this to a new issue for you and put a reply there: https://github.com/davidemms/OrthoFinder/issues/255

All the best
David
