### ISSUE TITLE
support python 3.4 and later?

### ISSUE THREAD

**Issue by ekopylova** [davidemms/OrthoFinder#19]
Are there plans to support python 3.4 and later?
I'm using [scikit-bio](https://github.com/biocore/scikit-bio) for many of my algorithms and it requires python 3.4 and later making it incompatible with OrthoFinder :(
Thanks!

**Comment by ekopylova** [comment]
Hi,
I've ran 2to3 & manually edited code on all OrthoFinder scripts and [this branch](https://github.com/ekopylova/OrthoFinder/tree/python3) should now work with Python 3.4 and later (at least testing on my own data).

**Comment by davidemms** [comment]
From the changes given by 2to3 it looks like maintaining two versions would be an unnecessary overhead.

You should be able to just call OrthoFinder as an external program i.e something like subprocess.call("python orthofinder.py ....", shell=True) from your python3 scripts. Does this satisfy your use case?

**Comment by davidemms** [comment]
As it's an external program rather than a module for users to import there are no compatibility issues with using either 2 or 3. And at the moment I can be more sure of users having python 2 although if this were to change in the future then I'd move to python 3.

**Comment by davidemms** [comment]
Just an additional comment to say that the OrthoFinder release now also comes with standalone binaries so you can run it without having any version of python installed at all! Hope this helps, David.

**Comment by macmanes** [comment]
Given the deprecation date of Python 2 is 1 Jan 2020, I think the time to make the switch is soon. I too, work mostly in a Py3 env.  

(sorry to be commenting on an old and closed issue)

**Comment by davidemms** [comment]
Yes, I'll do that in the next couple of months as changes for the new functionality are coming to an end.

Thanks
David
