### ISSUE TITLE
IOError: No such file or directory clusters_OrthoFinder_v2.2.0_I1.5.txt

### ISSUE THREAD

**Issue by evolbeginner** [davidemms/OrthoFinder#192]
Hi David,

I was running orthofinder for ~900 bacteria genomes. The command was 
python orthofinder.py -f pep -t 32 -a 16 -1 -og -S diamond

I think the diamond blast part was perfectly done. However, during mcl clustering, there was a problem that caused it to fail. The error message is shown as follows. Basically, it said that the file WorkingDirectory/clusters_OrthoFinder_v2.2.0_I1.5.txt did not exist (and it really was not there). Could you please help me have a look at it? Thank you.

2018-08-02 00:55:55 : Ran MCL
Traceback (most recent call last): 
  File "/home-user/sswang/software/sequence_analysis/OrthoFinder/orthofinder/orthofinder.py", line 1565, in <module>
    clustersFilename_pairs, statsFile, summaryText, orthogroupsResultsFilesString = DoOrthogroups(options, dirs, seqsInfo, options.qDoubleBlast, options.separatePickleDir)    
  File "/home-user/sswang/software/sequence_analysis/OrthoFinder/orthofinder/orthofinder.py", line 1246, in DoOrthogroups
    MCLread.ConvertSingleIDsToIDPair(seqsInfo, clustersFilename, clustersFilename_pairs)   
  File "/home-user/sswang/software/sequence_analysis/OrthoFinder/orthofinder/scripts/mcl.py", line 76, in ConvertSingleIDsToIDPair
    with open(clustersFilename, 'rb') as clusterFile, open(newFilename, "wb") as output:
IOError: [Errno 2] No such file or directory: '/home-user/sswang/project/Rhizobiales/results/orthofinder/pep/Results_Jul25/WorkingDirectory/clusters_OrthoFinder_v2.2.0_I1.5.txt'

Thanks,
Sishuo

**Comment by davidemms** [comment]
Hi Sishuo 

I think that the MCL run failed in that case. The file clusters_OrthoFinder_v2.2.0_I1.5.txt is the output from MCL. I've not had that happen before, but you could investigate it by trying to run it yourself:
`mcl OrthoFinder_v2.2.0_graph.txt -I 1.5 -o clusters_OrthoFinder_v2.2.0_I1.5.txt -te 16`

Does it produce an error?

All the best
David

**Comment by evolbeginner** [comment]
Hi David,

Thanks very much for your prompt reply.

I tried it but failed. It seemed that it was due to the RAM limit. So, could I ask whether there might be a way to reduce the memory required? I am running orthofinder for 900 bacterial genomes. The command is python orthofinder/orthofinder.py -b pep/Results_Jul25/WorkingDirectory/ -t 32 -a 12 -1 -og -S diamond

I guess maybe I can try a lower blast evalue cutoff, e.g., 1e-10?

Thanks,
Sishuo

**Comment by davidemms** [comment]
Hi Sishuo

You could try the mcl command without the "-te 16". That option gets it to run in parallel and probably increases the memory requirements. 

If that works then try running OrthoFinder without the "-a 16". This will still do most of the important parts in parallel but the the high RAM, less time-critical parts won't be in parallel and this should save memory:
`python orthofinder/orthofinder.py -b pep/Results_Jul25/WorkingDirectory/ -t 32 -1 -og`

All the best
David

**Comment by davidemms** [comment]
Hi Sishuo

Were you able to complete your analysis?

All the best
David

**Comment by evolbeginner** [comment]
Hi David,

Thanks for your kindly attention. It cost a long time and much RAM. Fortunately, the analysis was finished on the weekend without any problem, and the result looks nice.

Thank you for your great help!

Best,
Sishuo

**Comment by davidemms** [comment]
Hi Sishuo

That's great, thanks!

David
