### ISSUE TITLE
Reconstructing the gene trees is not multithreaded?

### ISSUE THREAD

**Issue by geo80** [davidemms/OrthoFinder#193]
Might be minor, but I see that although I have used both -t 20 and -a 20, the process, which I have started after using -ft, is using only one core out of the 20 I have available.
I can see the recon_gene_trees folder to increase in files, but it's going slow (13000 trees after 1.5 days). Is this normal? I'm afraid the walltime won't be enough to end the process.
Thanks,
George

**Comment by davidemms** [comment]
Hi George

Yes, I'm afraid that is at the moment. There are a few problems with trying to parallelise that step. With n species there are n^2 orthologues results files. On a number of systems the disk access to these file is rate limiting. Each tree will generally have orthologues for each of these n^2 files so it all needs to be carefully managed. Neither of these are insurmountable so I would like to parallelise it soon, but I can't promise how soon! 

On a more positive note, it does start at the largest trees which take the most time so you'll probably see the rate speed up as it gets to the smaller trees.

All the best
David
