### ISSUE TITLE
How are orthofinder binaries made?

### ISSUE THREAD

**Issue by OkoSanto** [davidemms/OrthoFinder#194]
Hi,

I ran the same computation twice, once by running the "_source" scripts using a natively compiled Python, and once using OrthoFinder's pre-compiled binaries.  Against my expectations, the binaries were slightly faster.  I ran the experiment twice, and found the same speedup: about 24 minutes on a total processing time of about 7 hours (using 20 cores, though not all cores were fully used all the time: total cpu time is about 57 hours).

I'm trying to understand what can cause the difference.  Can you tell us how these binaries are created?

thank you!

Thomas

**Comment by davidemms** [comment]
Hi Thomas

They're created using [pyinstaller](https://www.pyinstaller.org/). I wouldn't have really expected them to be quicker either! Pyinstaller just packages the code and the libraries that get called into a single package, so it's not a lot different really. Perhaps some of the libraries that are packaged up (e.g. numpy) are faster than the ones on your system, but that's just a guess.

All the best
David
