### ISSUE TITLE
Please help me finding the error message

### ISSUE THREAD

**Issue by tengchong** [davidemms/OrthoFinder#198]
Hi all,
There was an error happened when running OrthoFinder algorithm, but I couldn't find the error message. Here's what I got:

Running OrthoFinder algorithm
-----------------------------
2018-08-25 14:05:12 : Initial processing of each species
2018-08-25 14:35:36 : Initial processing of species 0 complete
2018-08-25 15:18:51 : Initial processing of species 1 complete
2018-08-25 15:42:02 : Initial processing of species 2 complete
ERROR: An error occurred, please review error messages for more information.

How can I find the error message in the first place? Please help! Many thanks!

TC

**Comment by sunnycqcn** [comment]
I think you should check the format of your sequence file.
Fuyou

发自我的 iPhone

**Comment by davidemms** [comment]
Hi

Is this just the output from stdout? Is there any output to stderr? If there's no stderr output, would you be able to print the full output you got from OrthoFinder from the start up to when the error occurs. I've looked through the OrthoFinder code and I can't see anywhere where you'd get this error message without having a more detailed message first. With some more information we should be able to find what the error was. 

All the best
David

**Comment by davidemms** [comment]
Did you make any progress on this? Is it possible your computer ran out of RAM?

Thanks
David

**Comment by tengchong** [comment]
Yes! Not sure why that happened, but I updated orthofinder to 2.2.7 and use diamond, then it finished everything without problem! So I guess this is sort of resolved? Thanks, David!

**Comment by davidemms** [comment]
Thanks, that's good to hear!
