### ISSUE TITLE
Gene tree MSA trimming

### ISSUE THREAD

**Issue by AlexdeMendoza** [davidemms/OrthoFinder#199]
Hi David, 

I have read in the Closed Issues that for the species tree, there is a trimming step for the MSA which is fed into the Maxium Likelihood Tree inference software. But what about the gene trees? Looking at the Working_directory, many of the MSA are filled with gaps (most sequences have gaps in the same positions, thus not very informative), which slows down the ML inference quite significantly. 

As an example, I ran an alignment with 25 sequences and 984 positions as I found it in the `WorkingDirectory/Alignments_ids/` using this command:
`time raxmlHPC-AVX2 -m PROTGAMMALG -p 12345 -s OG0004671.fa -n OG0004671 > /dev/null`

`real	1m20.716s`
`user	1m20.697s`
`sys	0m0.023s`

But if I do filter the alignment for positions with too many gaps using trimal:
`trimal -in OG0004671.fa -out OG0004671.trim.fa -gappyout`
I get the same 25 sequences, but now only 215 positions. Then running 
`time raxmlHPC-AVX2 -m PROTGAMMALG -p 12345 -s OG0004671.trim.fa -n OG0004671.trim > /dev/null`

`real	0m49.485s`
`user	0m49.441s`
`sys	0m0.034s`

Thus in a Orthofinder run with thousands of computed trees, a trimming step would likely be very beneficial for gene tree building speed (trimal or the built in function used in the Species Tree section). 

Sorry if this has already been solved before, or maybe trimming is already implemented in gene tree searches or you consider it detrimental, but I thought it could be helpful. 

Thanks!

Best,

Alex

**Comment by davidemms** [comment]
Hi Alex

I think that's a very good suggestion. I had avoided trimming as it's a little bit controversial, but on reflection I think you're right that it's the best thing to do. I'll try and add it sometime soon.

All the best
David

**Comment by AlexdeMendoza** [comment]
Hi David, 

Thanks a lot for your prompt answers. In my experience building trees, trimming usually gives better results. If 70% of the alignment are mostly gaps (missing data), it will likely decrease accuracy, as well as dubiously aligned regions are not likely to be homologous. 

The only case where I can see trimming being problematic are big orthogroups which might be together because they share a single domain (e.g. Kinases), trimming something like all positions having 80% gaps in all sequences, it would reduce the information from all other domains present in some of those proteins (a subset of sequences with Kinase and another domain), but anyway, big orthogroups (>800seq) are not really likely to retrieve good gene trees anyway. 

Thanks again for taking your time to maintain this fantastic pipeline. 
Best,

Alex

**Comment by AlexdeMendoza** [comment]
Sorry to bother you again, but I am wondering if I could run the tree finding part myself including trimming steps and maybe using several cores for the biggest orthogroups as most ML softwares really get stuck with the bigger orthogroups (once they are done, then the smaller orthogroups run very fast, but meanwhile, most of the server RAM has been used by the bigger orthogroups during days). 

Among the -help options, there is a `-ft <dir>` which should take a Gene_Trees folder as input and proceed from there. But I cannot seem to be able to run it, and the documentation in  the main github page seems to be lacking explanations for that option. Could you please explain how could could a modular run go? 
1st step - From fasta_folder to Orthogroups and a folder with a fasta file for each orthogroup should be OK using the `-oa` option like in this command: 
`orthofinder -M msa -T raxml -oa -t 10 -a 10 -n MyOrthofinder_Run -I 1.1 -S diamond -f my_fasta_folder/` 
2nd step - Then how should I call the 2nd step assuming I run the trees myself, rename them as `OGXXXXXX_tree_id.txt` and store them in the folder:
`my_fasta_folder/Results_MyOrthofinder_Run_Aug29/Orthologues_MyOrthofinder_Run_Aug29/WorkingDirectory/Trees_ids/` 
`orhofinder -ft my_fasta_folder/Results_MyOrthofinder_Run_Aug29/Orthologues_MyOrthofinder_Run_Aug29/WorkingDirectory/Trees_ids/` ?

Thanks for your help.

Alex

**Comment by davidemms** [comment]
Hi Alex

On the documentation in general, I will hopefully get some time to update it in the coming weeks. 

The '-ft' option is for an already calculated set of trees created by OrthoFinder. It's not intended for user-created trees. In principle you could create the files that OrthoFinder would have created and use this option, but it's not an intended workflow. What you describe is more or less what you'd need to do though. You'd have to check the files created on the small ExampleDataset and then recreate them for yours, e.g. you'd also need a species tree. 

Another approach is possible especially if you want a reusable solution, it's slightly technical though. OrthoFinder has an extensibility mechanism to allow you to use whatever tree inference method you like. This is all done with the config.json file in the orthofinder directory. There's no reason you couldn't create an 'alignment program' which is just a wrapper. It's first step would be to do the alignment and it's second step would be to trim it. Similarly with the tree inference, your wrapper program could look at the filename or the the number of taxa and then call your preferred tree inference program using more cores for the biggest orthogroups and one core for the rest. It might initially sound technical, but I think it's a very neat solution. The 'wrapper program' just needs to be a very short bash or python script or whatever to call the programs you want. 

In fact, for the alignment you wouldn't even need a wrapper. You could just do something like this in the config file to run two commands one after the other:

```
    "muscle_and_trim":{ 
    "program_type": "msa",
    "cmd_line": "muscle -in INPUT -out OUTPUT_pre_trim ; trimal -in  OUTPUT_pre_trim -out OUTPUT -gt 0.5 "
    },
```

Let me know if you have any questions, I'd be very interested to hear how you get on. 

All the best
David

**Comment by davidemms** [comment]
The wrapper round the tree could be like this:

tree_wrapper.py:
```
import sys
import subprocess

def ChoseNumberOfCores(infilename):
    """could use any method: 
        - open alignment and count number of taxa
        - largest 10 orthogroups use more cores
    """   
    if "OG000000" in infilename:
        # ten largest
        return 4
    else:
        return 1
    
infilename = sys.argv[1]
#outfilename = sys.argv[2]
nCores = ChoseNumberOfCores(infilename)
subprocess.call("raxml-ng --msa %s --model LG+G4 --seed 12345 --threads %d" % (infilename, nCores), shell=True)
```
```

    "my_raxml-ng_wrapper":{ 
    "program_type": "tree",
    "cmd_line": "python tree_wrapper.py INPUT",
    "ouput_filename": "INPUT.raxml.bestTree"
    },

```

I've not tested this, but this is the general idea.

All the best
David

**Comment by AlexdeMendoza** [comment]
Hi David, 

Thanks a lot for your help. I had time to try this, and this option seems to be working well:
   "mafft_and_trim":{
       "program_type": "msa",
       "cmd_line": "mafft --auto --anysymbol INPUT > OUTPUT_pre_trim 2> /dev/null; trimal -in OUTPUT_pre_trim -out OUTPUT -gappyout "
    },

Regardingt he wrapper that you kindly provided, I realised that running raxml-ng with several cores it is not a good idea, as the software tells you that it won't speed up the process (it would help if computing bootstrap supports)...

However, I think the mafft step is quite crucial, and in your `program_caller.py` you seem to implement a "if" loop that does "mafft linsi" for alignments with less than 500 seqs, and the fast mode for alignments >500seqs. In my experience "mafft-linsi" mode is really curcial for any size of alignment, and I am unsure if `mafft --auto` would be chosing linsi only for very small datasets, so I was wondering if I could set the same condition of 500 seqs in my "mafft_and_trim" option as you have in the `program_caller.py` in the "config.json". Else, if a similar wrapper could be added to run mafft linsi with many cores for alignments >500 seqs, and then one per node for those with less than 500 seqs.  

Cheers,

Alex

**Comment by davidemms** [comment]
Hi Alex

I'd suggest following the tree_wrapper.py example. Just get it to open the alignment file, count how many sequences there are (number of lines starting with ">") and make your decision on how to call mafft based on that.

All the best
David
