### ISSUE TITLE
Removing species and aligning the new output

### ISSUE THREAD

**Issue by tarunaaggarwal** [davidemms/OrthoFinder#20]
Hi David,
I reran OF by removing some species and the new `OrthologousGroups.txt` is now in the WorkingDirectory but the old ones are still in the main Results_date dir. I would like to run the tree script next but I just want to make sure that I give the correct dir path to `-f` option when running that script. It would be path to where the new `OrthologousGroups.txt` right? Please let me know. Thanks!
Taruna

**Comment by davidemms** [comment]
Hi Taruna

In the WorkingDirectory there will also be a file of the form `clusters_OrthoFinder_\*.txt_id_pairs.txt` corresponding to the new `OrthologousGroups.txt` (you can check the creation dates). When you call `trees_for_orthogroups.py` just specify the `clusters_OrthoFinder_\*.txt_id_pairs.txt` file corresponding to results you want to create trees for. The script should ask you to do this if you call it with a directory with multiple results in.

All the best
David
