### ISSUE TITLE
Closely related species - Orthofinder

### ISSUE THREAD

**Issue by KristinaGagalova** [davidemms/OrthoFinder#200]
Hi,
First of all thank you for this amazing tool. I am looking forward to have more info about the new implementations and options that you describe in the GitHub.

I have 3 species which are very closely related and I would need some feedback from you about my analysis. Do you have any suggestions on how to run Orthofinder for those? One species is a natural hybrid of the other two so not really divergent.

Thank you in advance
Kristina

**Comment by davidemms** [comment]
Hi Kristina

With 3 species it would be very fast to run, especially if you use DIAMOND. I would suggest trying it and then looking at the results, particularly the "Statistics_PerSpecies.csv" file and the "Percentage of genes in orthogroups" entry in that file to check if everything's ok. Also look at the "OrthologuesStats_Totals.csv" file. I'm not sure in advance exactly how things will work out with your hybrid but I'd be happy to take a look at these results to check.

All the best
David

**Comment by KristinaGagalova** [comment]
Hi David, 
I have some preliminary results for the comparison, only including 2 species and with Default Orthofinder run.
 Just to give you a bit more context: I am comparing genome annotations from very large and fragmented genome assemblies. The other thing is that my species do not have a close orthologue with "good" reference genome.

Those are the results for Statistics_PerSpecies
```
	PG29v5_validatedProt	WS77111v2_validatedProt
Number of genes	50686	26254
Number of genes in orthogroups	16395	14255
Number of unassigned genes	34291	11999
Percentage of genes in orthogroups	32.3	54.3
Percentage of unassigned genes	67.7	45.7
Number of orthogroups containing species	10675	10678
Percentage of orthogroups containing species	99.9	100.0
Number of species-specific orthogroups	4	7
Number of genes in species-specific orthogroups	43	30
Percentage of genes in species-specific orthogroups	0.1	0.1

Number of genes per-species in orthogroup	Number of orthogroups	Number of orthogroups
'0	7	4
'1	7800	8248
'2	1873	1748
'3	481	474
'4	236	132
'5	94	43
'6	66	18
'7	35	6
'8	17	1
'9	16	3
'10	11	1
11-15	21	2
16-20	10	0
21-50	13	0
51-100	2	2
101-150	0	0
151-200	0	0
201-500	0	0
501-1000	0	0
'1001+	0	0

Number of genes per-species in orthogroup	Percentage of orthogroups	Percentage of orthogroups
'0	0.1	0.0
'1	73.0	77.2
'2	17.5	16.4
'3	4.5	4.4
'4	2.2	1.2
'5	0.9	0.4
'6	0.6	0.2
'7	0.3	0.1
'8	0.2	0.0
'9	0.1	0.0
'10	0.1	0.0
11-15	0.2	0.0
16-20	0.1	0.0
21-50	0.1	0.0
51-100	0.0	0.0
101-150	0.0	0.0
151-200	0.0	0.0
201-500	0.0	0.0
501-1000	0.0	0.0
'1001+	0.0	0.0

Number of genes per-species in orthogroup	Number of genes	Number of genes
'0	0	0
'1	7800	8248
'2	3746	3496
'3	1443	1422
'4	944	528
'5	470	215
'6	396	108
'7	245	42
'8	136	8
'9	144	27
'10	110	10
11-15	259	26
16-20	179	0
21-50	408	0
51-100	115	125
101-150	0	0
151-200	0	0
201-500	0	0
501-1000	0	0
'1001+	0	0

Number of genes per-species in orthogroup	Percentage of genes	Percentage of genes
'0	0.0	0.0
'1	15.4	31.4
'2	7.4	13.3
'3	2.8	5.4
'4	1.9	2.0
'5	0.9	0.8
'6	0.8	0.4
'7	0.5	0.2
'8	0.3	0.0
'9	0.3	0.1
'10	0.2	0.0
11-15	0.5	0.1
16-20	0.4	0.0
21-50	0.8	0.0
51-100	0.2	0.5
101-150	0.0	0.0
151-200	0.0	0.0
201-500	0.0	0.0
501-1000	0.0	0.0
'1001+	0.0	0.0
```  
OrthologuesStats_Totals.csv
```
	PG29v5_validatedProt	WS77111v2_validatedProt
PG29v5_validatedProt	0.0	16336.0
WS77111v2_validatedProt	14193.0	0.0
```

It looks like the there is only a partial overlap between them. The number of unassigned genes is also quite high. Do you maybe suggest to include another type of comparison here (another species with draft genome annotation) so to lower down this number?
Do you have any suggestion? Could I use some other tree building method for the comparison?
