### ISSUE TITLE
Unexpected root generated by STRIDE

### ISSUE THREAD

**Issue by komalck88** [davidemms/OrthoFinder#201]
This issue is related to issue #195. I had to post this as new issue because that one is already closed, and I am not sure whether you will see it.

The most-most probable root (the one with maximum probability) that STRIDE has generated for my species tree is in fact not the root that was expected. I had included two species from a different taxonomical order (as outgroups) to a set of 37 species (belonging to another taxonomical order) of my interest. Maximum probability should have come for this node where the speciation has occured between two different taxonomical orders, but in fact although this node was one of the most probable node of 7 nodes, it had the least probability percentage. This made me suspicious.

I have attached the Duplication_counts file generated by STRIDE here. According to predictions, Node 10 should have been the one with maximum probability.

Could you kindly clear this doubt for me, is there something that I understood wrongly?

Cheers,
Komal
[Duplication_counts.txt](https://github.com/davidemms/OrthoFinder/files/2345268/Duplication_counts.txt)

**Comment by davidemms** [comment]
Hi Komal

I think the first thing to stress, for any program like this, the results are not going to be 100% every time. The same would apply to tree inference programs, or multiple sequence alignments or whatever. That's what's happening with the root. I don't think there's anything you've misunderstood. Including the outgroup was a good idea and so now you know exactly where the root should be, so you don't have to use the one picked by OrthoFinder. To complete the analysis, you should re-infer the orthologues using your correctly rooted tree (none of the earlier steps rely on the rooted species tree, so you just need to do this last bit). You do this with:

`orthofinder -ft path/to/Orthologues_Data_Dir -s rooted_species_tree.txt`

It will probably make only a small difference to the orthologues--generally, if the root does make more of a difference then that makes it easier for OrthoFinder to find the correct root. But inferring the orthologues with the correct root is the right thing to do.

All the best
David
