### ISSUE TITLE
Do not rename sequences

### ISSUE THREAD

**Issue by holmrenser** [davidemms/OrthoFinder#202]
Orthofinder renames fasta sequences to include the filename from which the sequence originates. This hampers downstream processing and prevents integration with tools that rely on sequence IDs.

Example:

Fasta entry ```>Eucgr.D01468.1.v2.0``` from file ```Eucalyptus.primary_transcripts.pep.fasta``` gets renamed to ```>Eucalyptus_primary_transcripts_pep_Eucgr.D01468.1.v2.0```

**Comment by andrewalverson** [comment]
Finally figured out that this is what was messing up several downstream analyses. This is an unfortunate feature.

**Comment by holmrenser** [comment]
This is what is currently making integration of OrhoFinder output in [GeneNoteBook](https://github.com/genenotebook/genenotebook/) quite cumbersome.

@davidemms I'd be happy to take some pointers for submitting a PR to change this!

**Comment by andrewalverson** [comment]
I ended up writing a regular expression to remove the filename, but this was only possible to do on a large scale because of my file naming convention.

**Comment by davidemms** [comment]
Hi, I've added an option "-X" to deactivate this. Sorry it's taken a while, I've been working heavily on the paper, which is now online.

Note, if you have a look at the latest version of the code, there has been a long overdue change to the results directory structure. This is to coincide with the second OrthoFinder paper (on the orthologues, gene trees etc) and is to make the complete set of results files clearer. The plan is for this to remain constant now, although it is in beta at the moment. It should be easy to see where everything is. I hope this helps.

All the best
David

**Comment by andrewalverson** [comment]
Thanks, David.

We’re reading the paper at one of our next lab meetings. And thanks for making all the output so easily parse-able!

Andy
