### ISSUE TITLE
Option to specify the config.json

### ISSUE THREAD

**Issue by jlanga** [davidemms/OrthoFinder#207]
Hi David.

When running Orthofinder in a cluster, you can't know in which machine it is going to execute. Therefore, if you want to modify the config.json file, you have to modify and install it in every machine.

Is there an option to specify a path for a custom config.json?

Thanks,

Jorge

**Comment by davidemms** [comment]
Hi Jorge

No, I'm afraid there's no option to specify this.

All the best
David
