### ISSUE TITLE
Error orthofinder.py : problems with BLAST 

### ISSUE THREAD

**Issue by MTS1989** [davidemms/OrthoFinder#21]
Hi, 
I met this error while running BLAST all-versus-all:

Command line argument error: Argument "query". File is not accessible: ` ~/WorkingDirectory/Species32.fa'
Command line argument error: Argument "query". File is not accessible: ` ~/WorkingDirectory/Species4.fa'
Traceback (most recent call last):
  File " ~/OrthoFinder/orthofinder.py", line 1129, in <module>
  File " ~/OrthoFinder/orthofinder.py", line 504, in GetNumberOfSequencesInFileFromDir                                                                  
ValueError: invalid literal for int() with base 10: ''

I was trying to achieve the orthologous groups for 56 fasta files (with amino acid sequences) and the program stopped with over a 70 BLAST files remaining. The program has created over 3000 BLAST files without any problem (no empty files). Everything seems to be fine in the Working Directory and I have no idea how I can fix it.

Any clues?
I really appreciate any help you can provide.

María

**Comment by MTS1989** [comment]
Sorry, I messed up the message error in the previous message. The truly error: 

Command line argument error: Argument "query". File is not accessible:  `~/WorkingDirectory/Species54.fa'
Command line argument error: Argument "query". File is not accessible:  `~/WorkingDirectory/Species32.fa'
Command line argument error: Argument "query". File is not accessible:  `~/WorkingDirectory/Species4.fa'
Traceback (most recent call last):
  File "~/OrthoFinder/orthofinder.py", line 1129, in <module>
  File "~/OrthoFinder/orthofinder.py", line 504, in GetNumberOfSequencesInFileFromDir
ValueError: invalid literal for int() with base 10: ''

**Comment by MTS1989** [comment]
Message error messed up. There is a diamond signal with **module** between after:
File " ~/OrthoFinder/orthofinder.py", line 1129, in

**Comment by davidemms** [comment]
Hi, it sounds like for some reason the fasta files for your species aren't accessible or aren't there. Inside your directory there should be a Results_... directory and inside that a WorkingDirectory. If you started with 56 fasta files then inside the WorkingDirectory there should be files called Species0.fa, Species1.fa right up to Species55.fa. The error message sounds like at the very least 'Species4.fa' and 'Species32.fa' had been deleted or you didn't have read permission for them. Can you check if these files are missing?

**Comment by davidemms** [comment]
It sounds like this was an issue on the file system. If that isn't the case then feel free to reopen this issue and provide more details.

Thanks
David
