### ISSUE TITLE
Few blast txt file cann't be created

### ISSUE THREAD

**Issue by ykjyhmj** [davidemms/OrthoFinder#210]
Hi David,

I run into a strange problem. The command line I am using is `OrthoFinder-2.2.7/orthofinder -S mmseqs -t 22 -M msa -M msa -f fastafile`
It shows that `No such file or directory: 'fastafile/Results_Oct15/WorkingDirectory/Blast0_4.txt'`
While I have majority of the blast files except several.
This is all the blast file I have.
![image](https://user-images.githubusercontent.com/39601931/46962152-6ab59600-d070-11e8-9070-34e01dced760.png)

The program run well when I analysis close related species. But when I test on some other far away species, the problem comes.

Thanks for the help

Minjie

**Comment by davidemms** [comment]
Hi Minjie

I will try and look into this soon, but I believe there may be some reliability problems with running multiple versions of mmseqs in parallel that I need to get to the bottom of. It may be that the best thing to do is to run with diamond instead (which has similar performance) or to run the mmseqs commands yourself and then use the OrthoFinder "-b" option to start from these results files. The commands run for mmseqs look like this:
`mmseqs search ExampleDataset/Results_Oct17/WorkingDirectory/mmseqsDBSpecies2.fa ExampleDataset/Results_Oct17/WorkingDirectory/mmseqsDBSpecies1.fa ExampleDataset/Results_Oct17/WorkingDirectory/Blast2_1.txt.db /tmp/tmpBlast2_1.txt  --threads 1` 

`mmseqs convertalis ExampleDataset/Results_Oct17/WorkingDirectory/mmseqsDBSpecies2.fa ExampleDataset/Results_Oct17/WorkingDirectory/mmseqsDBSpecies1.fa ExampleDataset/Results_Oct17/WorkingDirectory/Blast2_1.txt.db ExampleDataset/Results_Oct17/WorkingDirectory/Blast2_1.txt`

The first option involves more computing time but little manual work, the first option is the opposite.

Hope this helps
David

**Comment by ykjyhmj** [comment]
I changed to use diamond. And it works. Thanks very much!
