### ISSUE TITLE
Problem with running the OrthoFinder algorithm 

### ISSUE THREAD

**Issue by EmilyAmor** [davidemms/OrthoFinder#212]
Hi there,
 
I run into a problem with the Orthofinder algorithm and get the following error message:

Running OrthoFinder algorithm
-----------------------------
2018-10-27 13:13:44 : Initial processing of each species
ERROR: An error occurred, please review error messages for more information.

Any advice about what may be causing this?

Kind regards,
Emily

**Comment by davidemms** [comment]
Hi Emily

Were there earlier error messages? Could you copy the full output that OrthoFinder printed to screen please. 

All the best
David
