### ISSUE TITLE
-s User-specificed rooted species tree

### ISSUE THREAD

**Issue by Edison2021** [davidemms/OrthoFinder#214]
Hi David
Could you explain more about how to use this parameter? I wonder if i need to provide some extra files telling OrthoFinder to recognize species names on usr tree.

Thanks
Edison

**Comment by davidemms** [comment]
Hi Edison

The tree should be in newick formal and the species names just have to match the names of the input (per-species) fasta files minus the filename extension. Have a look at the results species tree from running OrthoFinder on the example dataset for an example. In fact, you can try this out by running the analysis on the example dataset again using the "-s" option and providing this species tree for the previous run.

All the best
David

**Comment by Edison2021** [comment]
Thanks!
