### ISSUE TITLE
numpy error?

### ISSUE THREAD

**Issue by fayweili** [davidemms/OrthoFinder#217]
I got the following error message when running the example dataset on my linux server. Not sure what happened (my numpy isn't right?). Thanks!! 

Writing orthogroups to file
---------------------------
Orthogroups have been written to tab-delimited files:
   /home/fay-wei/bin/OrthoFinder-2.3.1/ExampleData/OrthoFinder/Results_Nov09_1/Orthogroups/Orthogroups.tsv
   /home/fay-wei/bin/OrthoFinder-2.3.1/ExampleData/OrthoFinder/Results_Nov09_1/Orthogroups/Orthogroups.txt (OrthoMCL format)
   /home/fay-wei/bin/OrthoFinder-2.3.1/ExampleData/OrthoFinder/Results_Nov09_1/Orthogroups/Orthogroups_UnassignedGenes.tsv
Sequences for orthogroups:
   /home/fay-wei/bin/OrthoFinder-2.3.1/ExampleData/OrthoFinder/Results_Nov09_1/Orthogroup_Sequences/

/tmp/_MEIcfL38b/numpy/core/fromnumeric.py:37: RuntimeWarning: invalid value encountered in double_scalars
/tmp/_MEIcfL38b/numpy/core/fromnumeric.py:2374: RuntimeWarning: invalid value encountered in double_scalars
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1626, in <module>
  File "orthofinder/orthofinder.py", line 1321, in DoOrthogroups
  File "orthofinder/orthofinder.py", line 709, in Stats
StopIteration
Failed to execute script orthofinder

**Comment by davidemms** [comment]
I'm not sure if it's numpy, it could be. Would you be able to compress the results directory created by OrthoFinder and email it to me? Also, could you include all of the text OrthoFinder printed to if you still have it? My email address is at the top of the [orthofinder.py](https://github.com/davidemms/OrthoFinder/blob/master/orthofinder/orthofinder.py) fie.

Thanks
David

**Comment by davidemms** [comment]
Hi

I'll just post the earlier warnings that were produced at the start as they may help other people:

```
Running OrthoFinder algorithm
-----------------------------
2018-11-13 08:39:53 : Initial processing of each species
WARNING: Too few hits between species 0 and species 0 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 0 and species 1 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 0 and species 2 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 0 and species 3 to normalise the scores, these hits will be ignored
2018-11-13 08:39:53 : Initial processing of species 0 complete
WARNING: Too few hits between species 1 and species 0 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 1 and species 1 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 1 and species 2 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 1 and species 3 to normalise the scores, these hits will be ignored
2018-11-13 08:39:53 : Initial processing of species 1 complete
WARNING: Too few hits between species 2 and species 0 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 2 and species 1 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 2 and species 2 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 2 and species 3 to normalise the scores, these hits will be ignored
2018-11-13 08:39:53 : Initial processing of species 2 complete
WARNING: Too few hits between species 3 and species 0 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 3 and species 1 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 3 and species 2 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 3 and species 3 to normalise the scores, these hits will be ignored
2018-11-13 08:39:53 : Initial processing of species 3 complete
```

In general, this could occur if the fasta files don't contain the complete set of protein coding genes in your species and you get too few hits. Obviously that's not the case here as you used the Example Dataset.

In your case, I can see the results files from the DIAMOND search were empty and so something went wrong with that:
```
$ ls -l Results_Nov13/WorkingDirectory
total 2508
-rw-r--r-- 1 david david      0 Nov 13 13:42 Blast0_0.txt.gz
-rw-r--r-- 1 david david      0 Nov 13 13:42 Blast0_1.txt.gz
-rw-r--r-- 1 david david      0 Nov 13 13:42 Blast0_2.txt.gz
-rw-r--r-- 1 david david      0 Nov 13 13:42 Blast0_3.txt.gz
-rw-r--r-- 1 david david      0 Nov 13 13:42 Blast1_0.txt.gz
-rw-r--r-- 1 david david      0 Nov 13 13:42 Blast1_1.txt.gz
-rw-r--r-- 1 david david      0 Nov 13 13:42 Blast1_2.txt.gz
```

Could you go into Results_Nov13/WorkingDirectory and run:
`diamond blastp -d diamondDBSpecies3 -q Species2.fa -o Blast2_3.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1` and see what happens. It should produce an error message to say what went wrong. Let me know what it says.

I will make a change to OrthoFinder so that if there is an error message from diamond then it gets printed to the screen so that it's easier for the user to correct the problem.

All the best
David
