### ISSUE TITLE
run orthofinder from mcl cluster file

### ISSUE THREAD

**Issue by ESDeutekom** [davidemms/OrthoFinder#219]
Dear David Emms, 
I had the same issue as: https://github.com/davidemms/OrthoFinder/issues/192 (MCL stopped). 
I was able to rerun mcl and now have a cluster file (clusters_OrthoFinder_v2.2.6_I1.5.txt) produced from the graph file. How do I restart orthofinder with this file now? From the manual it says it can be restarted from the orthogroups, should they be made by mcl? 
Kind regards, 
Eva

**Comment by davidemms** [comment]
Hi Eva

There's no functionality to restart it from an MCL output file unfortunately. Do you have any ideas what went wrong with MCL before? I'd not heard of this before #192 so I'd like to find out the cause.

Many thanks
David

**Comment by ESDeutekom** [comment]
Dear David, 
I didn't find out what the problem was. It was likely a memory problem (someone started a process without my knowledge at the time). It probably consumed all the memory. I just had to rerun it all. 
Kind regards, 
Eva
