### ISSUE TITLE
search for paralogs on genes w/o orthologs

### ISSUE THREAD

**Issue by varnion** [davidemms/OrthoFinder#22]
i think this suggestion is out of the scope of the program, but i'd be a nice addition an option to also cluster paralogs without orthologs.

in most of the cases users are really interested on orthogroups, but sometimes we also want to check families of proteins "exclusive" for a single organism (or, better saying, not yet found on other species)

**Comment by sepro** [comment]
+1 , could be a bug-vs-feature discussion. But I would like to see the option to group in-paralogs in the absence of an outgroup as well.

**Comment by davidemms** [comment]
Hi

OrthoFinder now reports the number of orthogroups specific to a single organism in the **Statistics_PerSpecies.csv** results file. Is this what you were looking for? You can then identify which orthogroups they are by looking in the file **Orthogroups.GeneCount.csv**.

All the best
David

**Comment by varnion** [comment]
Thank you!
