### ISSUE TITLE
How the  SpeciesTreeAlignment.fa is generated in Orthofinder ?

### ISSUE THREAD

**Issue by dieunelderilus** [davidemms/OrthoFinder#223]
Dear all

Please , how the SpeciesTreeAlignment.fa is generated in orthofinder? this file is located inside the Alignement directory it contains the alignment for different orthogroups. I want to know if this was generated with the concatenation of the core orthgroups or with all the Orthogroups. Or any additional explanations. are welcome.

Thanks in advance for your help

DD

**Comment by davidemms** [comment]
Hi

The details are in the new paper on biorxiv: https://www.biorxiv.org/content/early/2018/11/08/466201 in the section "Species tree inference".

Briefly, orthogroups are identified for which for most species there is only one gene from that species. For these orthogroups, these single-copy genes are used in the alignment. For the species for which there were no genes or multiple genes in the orthogroup, gap characters are inserted instead. This ensures that all the genes included are one-to-one orthologues. It also ensures that sufficient sequence data is used even in cases where there has been a lot of gene duplication and loss.

All the best
David
