### ISSUE TITLE
no error messages

### ISSUE THREAD

**Issue by lurebgi** [davidemms/OrthoFinder#225]
Hi,

I didn't see any error messages when running 

orthofinder -t 8  -f protein_dir -b bjbbbf -n bjbbbf

OrthoFinder version 2.2.7 Copyright (C) 2014 David Emms

2018-11-26 23:59:37 : Starting OrthoFinder
8 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "makeblastdb -help" - ok
Test can run "blastp -help" - ok
Test can run "mcl -h" - ok
Test can run "fastme -i /scratch/luohao/amphioxus/ortholog/protein_dir/SimpleTest.phy -o /scratch/luohao/amphioxus/ortholog/protein_dir/SimpleTest.tre" - ok
/scratch/luohao/amphioxus/ortholog/bjbbbf/SpeciesIDs.txt file must be provided if using previously calculated BLAST results
ERROR: An error occurred, please review error messages for more information.

**Comment by davidemms** [comment]
Hi

It's the line that says "/scratch/luohao/amphioxus/ortholog/bjbbbf/SpeciesIDs.txt file must be provided if using previously calculated BLAST results"

All the best
David

**Comment by davidemms** [comment]
I've updated the code to preface this message with "ERROR".

**Comment by lurebgi** [comment]
Hi,

Thanks for the reply.

I am still confused since I had never run orthofinder before. I have now
manually created a 'SpeciesIDs.txt' file following the example of
https://raw.githubusercontent.com/davidemms/OrthoFinder/master/Tests/Input/ExampleDataset_addOneRemoveOne/Results_Jan28/WorkingDirectory/SpeciesIDs.txt

And now the error message is:
Checking required programs are installed
----------------------------------------
Test can run "makeblastdb -help" - ok
Test can run "blastp -help" - ok
Test can run "mcl -h" - ok
Test can run "mafft
/tmp/slurm-4580959/protein_dir//_dependencies_check/SimpleTest.fa" - ok
Test can run "FastTree
/tmp/slurm-4580959/protein_dir//_dependencies_check/SimpleTest.fa" - ok
No processed fasta files in the supplied previous working directory:
/scratch/luohao/amphioxus/ortholog/bjbbbf/

ERROR: An error occurred, please review error messages for more information.

**Comment by davidemms** [comment]
Hi 

The bit on the command line where you've put, "-b bjbbbf" tells orthofinder to continue from a previous orthofinder analysis in a directory called "bjbbbf". If you haven't run it before then I presume that that's a mistake and you didn't want that option? If you take it out then it should run fine. (Currently orthofinder will be looking for a SpeciesIDs.txt file there)

All the best
David
