### ISSUE TITLE
Rooted gene trees?

### ISSUE THREAD

**Issue by photocyte** [davidemms/OrthoFinder#226]
Hi there,

Are the gene trees produced by Orthofinder (e.g. parameters "-M msa -A mafft -T fasttree") rooted on an outgroup?  Perhaps it could be done using information from the rooted species tree?

All the best,
-Tim

**Comment by davidemms** [comment]
Hi Tim

The trees in Gene_Trees/ are exactly as produced by the tree inference tool (i.e. unrooted). The trees in the Resolved_Gene_Trees/ directory have been rooted using the rooted species tree. but also 'resolved' as described in the [new paper](https://www.biorxiv.org/content/early/2018/11/08/466201). Basically, minor rearrangements are made of the branches to find the most parsimonious interpretation of duplication/loss/tree conflict so as to improve the accuracy of orthologue inference from the trees.

All the best
David

**Comment by photocyte** [comment]
Thank you David, indeed the new paper is quite explicit about this!  Closing the issue

**Comment by sknaack** [comment]
Thanks! I've a quick but deceptively simple question: What is the best way to check/verify the resolved gene trees in the Resolved_Gene_Trees directory are indeed distinct from those in the Gene_Trees directory, i.e., that they aren't trivially the same? If I understand what I'm seeing, n# labels appear for internal nodes in the trees in Resolved_Gene_Trees, meaning it's not trivial to compare with diff (to give one example of a simple way one might compare the contents of the directories). Is there a good way to check the number of trees that are non-trivially altered? For the results I'm looking at I provided a rooted species tree and some trees aren't changed but at least some are so I infer the analysis is valid. This particular gene tree analysis completed so fast  I wondered how to best troubleshoot the results.
