### ISSUE TITLE
OrthoFinder cannot find location of mmseqs

### ISSUE THREAD

**Issue by chainorato** [davidemms/OrthoFinder#228]
Dear Developer,

I'm sorry for disturb you with this kind of the question. But it seems to have some problems in my computer that OrthoFinder could not locate mmseqs although the mmseqs program was installed and be executable. Do you have any ideas for solving this issues? The error was shown below. Thank you in advance.

OrthoFinder version 2.3.1 Copyright (C) 2014 David Emms

2018-12-04 14:18:53 : Starting OrthoFinder
40 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed

----------------------------------------

ERROR: Cannot run mmseqs
Format of make database command:
  mmseqs createdb INPUT OUTPUT.fa ; mmseqs createindex OUTPUT.fa /tmp
ERROR: Cannot run mmseqs
Format of search database command:
  mmseqs search /mmseqsDBINPUT DATABASE.fa OUTPUT.db /tmp/tmpOUTPUT  --threads 1 ; mmseqs convertalis /mmseqsDBINPUT DATABASE.fa OUTPUT.db OUTPUT
Please check mmseqs is installed and that the executables are in the system path

ERROR: An error occurred, please review error messages for more information.

**Comment by chainorato** [comment]
Here is a result when I ran "which mmseqs"
~/bin/mmseqs

**Comment by chainorato** [comment]
I'm now able to locate mmseqs.
But there is another error instead which is:

Running mmseqs all-versus-all
-----------------------------
Using 40 thread(s)
2018-12-27 15:53:01 : This may take some time....
2018-12-27 15:53:19 : Done all-versus-all sequence search
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1624, in <module>
  File "orthofinder/orthofinder.py", line 1441, in RunSearch
NameError: global name 'dirs' is not defined
Failed to execute script orthofinder

If you have any ideas for fixing this problem, please help me. Thank you in advance.

**Comment by Perugolate** [comment]
same error here with version 2.3.1.
2.2.7 works fine

**Comment by davidemms** [comment]
Hi, thanks for reporting this. It has been resolved in d938a0cb105e0130a9ca4b868ba7211796a828d0. There's not a release with it in currently, but you can download the latest version of the code from the main github page.

All the best
David
