### ISSUE TITLE
orthofinder killed inferring gene and species

### ISSUE THREAD

**Issue by ESDeutekom** [davidemms/OrthoFinder#230]
Dear David,
Sorry for being so active...running orthofinder isn't going as smooth as I hoped. 

Everything runs fine now till inferring the gene trees and species trees. The process is killed, without any additional info as to why. Also with the rerunning from the orthogroup files a couple of times. Since it takes ages every time I have to rerun, I gave up and ask for your guidance.

It might be similar to issue #229, but not sure. Thank you kindly for your help. Below an output of the rerun. I also used the default tread amount. This one is with 20.

>[eva] ~: orthofinder -t 20 -fg /linuxhome/tmp/eva/Results_Aug23_1/

>OrthoFinder version 2.2.6 Copyright (C) 2014 David Emms

>20 thread(s) for highly parallel tasks (BLAST searches etc.)
>1 thread(s) for OrthoFinder algorithm

>Using orthogroups in file:
>    /linuxhome/tmp/eva/Results_Aug23_1/Orthogroups_1.txt
>and corresponding clusters file:
 >   /linuxhome/tmp/eva/Results_Aug23_1/clusters_OrthoFinder_v2.2.6_I1.5_1.txt_id_pairs.txt

>Checking required programs are installed
>"----------------------------------------"
>Test can run "fastme -i /linuxhome/tmp/eva/Results_Aug23_1/SimpleTest.phy -o /linuxhome/tmp/eva/Results_Aug23_1/SimpleTest.tre" - ok

>Analysing Orthogroups
>"====================="

>Calculating gene distances
>"--------------------------"
>2018-12-08 04:11:12 : Done

>Inferring gene and species trees
>"--------------------------------"
>2018-12-08 04:11:15 : Done 0 of 23921
>Killed

**Comment by ESDeutekom** [comment]
PS: It seems there are Distance files made (.phy). The process is killed when .phy_fastme_stat.txt and tree_id files are made.

**Comment by davidemms** [comment]
Hi

I think 'Killed' probably means that the computer ran out of RAM and killed the process. Do you have access to a machine with more RAM? Another alternative is to use the "-M msa" option. This will get it to use multiple sequence alignments for tree inference. In general this would be slower, but it should require less RAM and so may be more successful. Sorry for the delay in the response.

All the best
David

**Comment by ESDeutekom** [comment]
Dear David, 

Thank you for your response.
I had around a 93 RAM machine. I tried more and it didn't work still. I just left the trees from the analyses out and go further from the OGs. I guess the data was too much (165 eukaryotic proteomes). 
Thanks anyways. 

Cheers, 
Eva
