### ISSUE TITLE
Species tree

### ISSUE THREAD

**Issue by sarah872** [davidemms/OrthoFinder#233]
Are the branch support values coming from bootstraps or are they posterior probability values?

**Comment by davidemms** [comment]
A number of different methods are available for species tree inference in OrthoFinder. The default is to use STAG, which gets an estimate of the species tree from each gene tree that includes all species. The consensus tree of all these is taken. The branch support values are the proportion of these gene trees that contained that bipartition. As such, they will be lower than bootstraps/posterior probability values inferred with the same data. You should keep this in mind when assessing whether or not you trust a particular bipartition.

Full details on species tree inference in OrthoFinder are here: https://www.biorxiv.org/content/early/2018/11/08/466201

All the best
David
