### ISSUE TITLE
Question about alignment

### ISSUE THREAD

**Issue by lillianleung** [davidemms/OrthoFinder#235]
Hi Emily

Were there earlier error messages? Could you copy the full output that OrthoFinder printed to screen please. 

All the best
David

_Originally posted by @davidemms in https://github.com/davidemms/OrthoFinder/issues/212#issuecomment-434276086_

**Comment by davidemms** [comment]
Hi

It looks like your error message was: 

> Malformatted line in /hwfssz1/ST_AGRIC/USER/lianghongping/SUPER/SE/00.data/Seleprotein/Phylogenetic_Tree/34_Species/result/Results_Dec17/WorkingDirectory/Blast6_0.txt Offending line was: 6_9945 0_4951 29.93 147 80 7 203 346 503 629 5e-06 50.8


This looks like the problem was with the sequence search/local alignment. Were you using BLAST, DIAMOND or MMSeqs?

Thanks
David

**Comment by davidemms** [comment]
I'm closing this issue as there's nothing I can investigate without further information.
