### ISSUE TITLE
Changing BLASTp parameters

### ISSUE THREAD

**Issue by Piergiorge** [davidemms/OrthoFinder#238]
Hello!

I am trying to use Orthofinder with a specific filter (-seg yes; -soft_masking true; theoretical BD size = 10000; -evalues < 10-3; coverage relative to query >= 70%; coverage relative to subject >= 70%; raw score > 120).  I can run BLASTp and select the sequences that I need with awk, but I have not found how to re-use the blastp results in the orthofinder (from previous analysis) or how to add those steps in the Orthofinder script.

Thanks.

**Comment by davidemms** [comment]
Hi

Are you trying to run OrthoFinder using your own set of options for BLAST? If so, then you can add your version to the config file, following the description and examples in the file:
https://github.com/davidemms/OrthoFinder/blob/master/orthofinder/config.json

You could, for example, include a call to your awk filter once the individual BLAST search has completed. I show how to do similar things here: https://github.com/davidemms/OrthoFinder/issues/199. Essentially, you just include the multiple commands you want to run. E.g.

```"search_cmd": "blastp -outfmt 6 -evalue 0.001 -query INPUT -db DATABASE -out OUTPUT.tmp ; awk -f your_script.awk OUTPUT.tmp > OUTPUT ; rm OUTPUT.tmp"```
(or better still, get awk to edit the blast results file in place if that's possible?)

All the best 
David

**Comment by davidemms** [comment]
A second way to do this would be to use the '-b' option to start from your blast results.

1. Get OrthoFinder to only prepare the files then stop using the, '-op' option.
2. It prints out the BLAST commands you'll need to run. Edit these as appropriate to use the options you want to use and then run your BLAST searches, awk etc
3. Resume OrthoFinder using these files using the, '-b' option.

All the best
David
