### ISSUE TITLE
Cannot allocate memory error

### ISSUE THREAD

**Issue by ddomman** [davidemms/OrthoFinder#24]
Hi David,

I keep getting the following error while running OrthoFinder on a cluster:

````
Traceback (most recent call last):
  File "/nfs/users/nfs_d/dd6/apps/OrthoFinder-0.4/orthofinder.py", line 1240, in <module>
    pool.map(RunCommandReport, commands)   
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 227, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 528, in get
    raise self._value
OSError: [Errno 12] Cannot allocate memory
```

When I check the job log file, it seems I've allocated enough memory (8Gb with the job only using ~300 Mb)... so I'm not sure what is going on here. 

Best,
Daryl

**Comment by davidemms** [comment]
That seems strange, it's the point in the script where the BLAST searches are launched in parallel and they don't use that much memory. How many threads do you request for it to run on (the -t argument)? Or do you use the default?

**Comment by ddomman** [comment]
The weird thing is that many (not sure if its all) BLAST searches were finished when this error pops up. I requested 16 threads. I'm running this using ~300 bacterial genomes each with ~400 genes.

**Comment by davidemms** [comment]
I think I've made some progress on working out what the problem might be after having read the posts here: http://stackoverflow.com/questions/1367373/python-subprocess-popen-oserror-errno-12-cannot-allocate-memory

Apparently opening a subprocess uses fork under the hood and when this happens you're requesting as much memory as is already being used by the python script that requested the new process. I.e. it doesn't matter if the actual process only ends up using a little memory.

Using this, I've been able to create an "OSError: [Errno 12] Cannot allocate memory" error using a simple script in python that initially consumes a load of memory and then launches a load of light way processes. Similarly to what you see, the error occurs even though the system reports low memory usage. I'll see if I can work out a way of getting around this problem.

**Comment by davidemms** [comment]
The latest release of OrthoFinder (https://github.com/davidemms/OrthoFinder/releases) uses a different process to launch the BLAST searches. Do you still see the same problem with that? What if you allocate more memory?

**Comment by ddomman** [comment]
Perfect, I will try it out now and let you know.

Thanks so much!

**Comment by davidemms** [comment]
Did you have any success with this or are you still seeing the same problem?

Thanks
David

**Comment by ddomman** [comment]
Hi David,
So sorry for not getting back about this, but yes the patch worked and the BLAST works fine now.

Thanks so much for the help!
