### ISSUE TITLE
Problem with running the OrthFinder example.

### ISSUE THREAD

**Issue by chphprun** [davidemms/OrthoFinder#242]
Hi every teachers:

below for the wrong screenshot. i am a beginner , sorry!

Environment : On Windows 10, use VMware 14 workstation.  install Ubuntu18.0 Desktop .

Installed : 
OrthoFinder-2.2.7 , 
diamond-linux64
fastme-2.1.5
MCL
ncbi-blast+

Coud you help me see the problem?

I use the OrthoFinder-2.3.1 version, also issue like this error.

![b4b7049161ff7e17e7d0b6dc3272721](https://user-images.githubusercontent.com/13096257/52836176-a0ed4a00-3124-11e9-87df-59f92b5caab6.jpg)

**Comment by davidemms** [comment]
Hi

I've not seen anything like this before. It is possible that the problem is caused by the non-Latin characters in the directory containing OrthoFinder. Could you try it in a different directory with only the letters a-z in the full directory path.

All the best
David
