### ISSUE TITLE
Odd low support Species tree node value

### ISSUE THREAD

**Issue by girouxem** [davidemms/OrthoFinder#245]
I'm confused about the node values I'm seeing in my species tree. I generated it using OrthoFinder v. 2.2.6 with the msa option. The node values are incredibly low that I wonder why a tree would even be possible.

I have 8 fungal species, 7 in a genus called Lachnellula, and the outgroup is _Botrytis cinerea_. The tree follows the topology I would expect.

I don't know what the branch lengths and node values represent. I'm used to seeing bootstrap support values, and these seem so far off that I'm just left puzzled. Blow is a copy of the tree I generated with FigTree, you can ignore the colours.

![image](https://user-images.githubusercontent.com/14061098/53445060-b3496c80-39dd-11e9-939a-fef65dda5e5c.png)

Below is the content of the SpeciesTree_rooted.txt and SpeciesTree_rooted_node_labels.txt files:
`$ cat SpeciesTree_rooted.txt
(Botcin.pep.singleline:0.175825,(((Lcer:0.02256,(Lari:0.00647,Lawi:0.00906)1:0.01522)1:0.012,(Locc:0.04251,(Lsub:0.01869,Lhya:0.01795)1:0.02102)1:0.00646)1:0.08598,Lsue:0.11113)1:0.175825);

$ cat SpeciesTree_rooted_node_labels.txt
(Botcin.pep.singleline:0.175825,(((Lcer:0.02256,(Lari:0.00647,Lawi:0.00906)N5:0.01522)N3:0.012,(Locc:0.04251,(Lsub:0.01869,Lhya:0.01795)N6:0.02102)N4:0.00646)N2:0.08598,Lsue:0.11113)N1:0.175825)N0;
`

I also tried to re-run just STAG on using the SpeciesIDs.txt and the Gene_Trees folder. The tree generated looks almost identical to the one I pasted above that was generated with the msa option, with slightly higher node values.
`$ cat SpeciesTree.tre (Locc:0.0444682,(Lsub:0.0223584,Lhya:0.0215445)0.851615:0.0241354,((Lsue:0.129402,Botcin_pep_singleline:0.391331)0.931791:0.0974091,(Lcer:0.0243521,(Lawi:0.0131359,Lari:0.00725539)0.87136:0.0201729)0.703032:0.0193593)0.389908:0.0155536);`

**Comment by girouxem** [comment]
I also tried to re-run just STAG on using the SpeciesIDs.txt and the Gene_Trees folder. The tree generated looks almost identical to the one I pasted above that was generated with the msa option, with slightly higher node values.
`$ cat SpeciesTree.tre
(Locc:0.0444682,(Lsub:0.0223584,Lhya:0.0215445)0.851615:0.0241354,((Lsue:0.129402,Botcin_pep_singleline:0.391331)0.931791:0.0974091,(Lcer:0.0243521,(Lawi:0.0131359,Lari:0.00725539)0.87136:0.0201729)0.703032:0.0193593)0.389908:0.0155536);`

**Comment by davidemms** [comment]
Hi

I think you may have misread the newick format. The low values are the branch lengths in substitutions per site. The values immediately after the closing brackets (and before the colon) are the support values. The SpeciesTree_rooted.txt newick file above says that all the bipartitions have 100% support.

All the best
David

**Comment by girouxem** [comment]
Thank-you!!

**Comment by Callithrix-omics** [comment]
I had a similar question regarding STAG support values. I produced a species tree using the standard Orthofinder configuration. The species relationships match what you expect but the support values seem low. Are such values normal/acceptable for STAG??? 

thank you 
Joanna 

![SpeciesTree_rooted txt](https://user-images.githubusercontent.com/37043957/86061010-33666300-ba66-11ea-8cf7-a9fda75a2bcd.jpg)

(Mus_musculus.GRCm38.pep.all:0.0561655,(((Otolemur_garnettii.OtoGar3.pep.all:0.0689166,(Microcebusmurinusproteins:0.037822,(Prolemur_simus.Prosim_1.0.pep.all:0.0365074,Propithecus_coquereli.Pcoq_1.0.pep.all:0.0511123)0.344308:0.0141764)0.417746:0.0220122)0.299554:0.0163292,(Carlito_syrichta.Tarsius_syrichta-2.0.1.pep.all:0.0773054,(((Aotus_nancymaae.Anan_2.0.pep.all:0.028493,(Saimiri_boliviensis_boliviensis.SaiBol1.0.pep.all:0.0294418,Cebus_capucinus.Cebus_imitator-1.0.pep.all:0.0223788)0.250781:0.00779887)0.189732:0.00841162,(Cpenicillata_v1.2_annotation.proteins.clean:0.142612,Callithrix_jacchus.ASM275486v1.pep.all:0.0256229)0.344196:0.0255989)0.267969:0.0239742,((Nomascus_leucogenys.Nleu_3.0.pep.all:0.0371627,(Pongo_abelii.PPYG2.pep.all:0.0347416,((Homo_sapiens.GRCh38.pep.all:0.00429917,(Pan_troglodytes.Pan_tro_3.0.pep.all:0.00518479,Pan_paniscus.panpan1.1.pep.all:0.0110136)0.426786:0.00730327)0.246763:0.00418965,Gorilla_gorilla.gorGor4.pep.all:0.0153884)0.360938:0.00742121)0.178348:0.0053218)0.242857:0.0086653,(((Piliocolobus_tephrosceles.ASM277652v2.pep.all:0.0226375,Colobus_angolensis_palliatus.Cang.pa_1.0.pep.all:0.0178333)0.230022:0.00412884,(Rhinopithecus_roxellana.Rrox_v1.pep.all:0.00903545,Rhinopithecus_bieti.ASM169854v1.pep.all:0.021324)0.485045:0.0100645)0.214397:0.00528904,(Chlorocebus_sabaeus.ChlSab1.1.pep.all:0.0181593,((Macaca_nemestrina.Mnem_1.0.pep.all:0.00992401,(Macaca_fascicularis.Macaca_fascicularis_5.0.pep.all:0.00540247,Macaca_mulatta.Mmul_10.pep.all:0.0240023)0.235491:0.00384626)0.236496:0.00400778,((Papio_anubis.Panu_3.0.pep.all:0.00868324,Theropithecus_gelada.Tgel_1.0.pep.all:0.00581935)0.218638:0.00330237,(Cercocebus_atys.Caty_1.0.pep.all:0.011814,Mandrillus_leucophaeus.Mleu.le_1.0.pep.all:0.0163709)0.160826:0.00377972)0.0915179:0.00282349)0.132478:0.00410192)0.153237:0.00571974)0.23817:0.0127437)0.246317:0.016607)0.316629:0.0324991)0.159598:0.0131972)0.259933:0.0130177,(Canis_lupus_familiaris.CanFam3.1.pep.all:0.100246,(Sus_scrofa.Sscrofa11.1.pep.all:0.0842542,Bos_taurus.ARS-UCD1.2.pep.all:0.0758344)0.528571:0.0225116)0.398661:0.0197162)1:0.0561655);

**Comment by davidemms** [comment]
Hi Joanna

The low support values with STAG are to be expected since they are calculating the support in a different way to the standard bootstrap support. The STAG support values are the proportion of gene trees that support a given species tree bipartition whereas for the standard bootstrap it is the number of bootstrap replications of a resampling of the full concatenated MSA that give that bipartition. This means that for the same data and for the same level of certainty, the support values of STAG will be lower. Whereas a concatenated MSA species can often give support values of 100%. It's best to just think of STAG as giving a far more stringent assessment of support than bootstrap. 

In terms of 'acceptable' if you mean for a publication then I think it might be better to avoid using STAG support values since they are not widely known and are likely to be misinterpreted. You can use the OrthoFinder option "-fg PREVIOUS_RESULTS_DIR -M msa" to redo the trees using multiple sequence alignments and to infer the species tree from a concatenated MSA if you need that.

All the best
David

**Comment by Callithrix-omics** [comment]
Thank you for the feedback as  I have already thought along the same lines re MSA

Enviado do meu iPhone
