### ISSUE TITLE
Version 2.3.1 won't work with provided species tree

### ISSUE THREAD

**Issue by rfernandezgarcia** [davidemms/OrthoFinder#248]
Hi David,

Just wanted to let you know that I've tried to provide a species tree with the -s flag and it won't work in the latest version. It calculates the species tree with STRIDE anyway and use that tree instead.

Hope this helps!

Rosa

**Comment by davidemms** [comment]
Hi Rosa

Thanks very much for pointing that out, just submitting a fix now.

All the best
David
