### ISSUE TITLE
Problem with Orthogroups

### ISSUE THREAD

**Issue by bioinformaticspcj** [davidemms/OrthoFinder#249]
Hello,
 Thanks for writing this software, it is very effective and useful. Now I used this Orthofinder (version 2.2.7) to  search for single copy genes among 8 species, but I met a problem that the order of genes in "Orthogroups.txt" file did not correspond to the order of species. The reason may be that the names of one species genes are not the same but they are directly ordered by alphabetical order.
Could you please fix this.
I am looking forward to your valuable reply.
Very thanks !

**Comment by davidemms** [comment]
Hi

There is a file, Orthogroups.tsv (in older versions of OrthoFinder it's Orthogroups.csv), which separates the genes from each species into separate columns using the tab character. I think this should satisfy your requirements? The Orthgroups.txt file is a legacy file, matching the format used by OrthoMCL.

All the best
David

**Comment by bioinformaticspcj** [comment]
Thanks a lot. The genes order is right in ".csv" file. I could extract them easily.This software is a time-saved one compared with the OrthoMCL. Very nice.
Thanks again for your timely response. Hopefully, the software could be better and better.
