### ISSUE TITLE
Doubts regarding the minimum number of sequences

### ISSUE THREAD

**Issue by MartaLopesGomes** [davidemms/OrthoFinder#250]
Hello, 
I do not have an issue by now, but I couldn't find this information anywhere.

I saw that you said before, in one of your answers, that you don't recommend the use of OrthoFinder with less than 4 species. I would like to know if you have some recommendations regarding the number of sequences per species too. For instance, if I want to focus my research in a more restricted set of proteins and not in the whole genome, will this influence the quality of the results?

**Comment by davidemms** [comment]
Hi Marta

I think it could affect your results although I haven't tried it myself. In general I would recommend using all the genes in each species and then looking at the results for the sequences of interest. With DIAMOND (now the default option) used for sequence searching it is usually pretty quick. 

The potential problems I can think of from just putting some of the sequences in could be: i) there being insufficient BLAST/DIAMOND hits for orthofinder to model how sequence length affects bit scores for your sequences ii) Failing to include in the input all sequences homologous to restricted set of proteins you're interested in.

If you do try it though, I would be interested to hear what the results are like. I think you'd probably need over 100 sequences per species as a bare minimum. 

All the best
David
