### ISSUE TITLE
Is there any way to build species tree based on a subset of Orthogoups

### ISSUE THREAD

**Issue by ykjyhmj** [davidemms/OrthoFinder#251]
Hi David,

Thanks for the great software. I already used it compute the orthogroups and build the species tree. As we are more interested in a subset of orthogroups with specific gene function, I wonder if it is possible to build the species tree based on a subset of orthogroups.

Thanks very much in advance.

Best,
Minjie

**Comment by davidemms** [comment]
Hi Minjie

That would require some manual work. I'd suggest:
- running OrthoFinder with the "-M msa" option to get multiple sequence alignments for each orthogroup
- creating a concatenated MSA using just the orthogroups you want
- inferring the species tree from this concatenated alignment

All the best
David
