### ISSUE TITLE
how to achieve Construction of a clock-calibrated phylogenetic tree using orthofinder

### ISSUE THREAD

**Issue by amit4mchiba** [davidemms/OrthoFinder#254]
Hi David,

I am writing here to seek your advice on how to achieve a clock calibrated phylogenetic tree using orthofinder.

In my case, I have 42 plant genomes that I am working with. I was able to run Orthofinder using default mode and it was much faster using the diamond search option. Finally, I was able to get all expected files, species tree, trees for each gene families and so on. In this analysis, I got no single copy orthogene across all species. This is what you have explained in your paper as a challenge that Orthofinder tries to solve when we have a set of diverse species set to compare. 

The species tree that I have now can be converted into ultrametric, thanks to the script that you latter provided. But I am interested to understand divergence time between species. I have seen many interesting articles who have described this but the method is rather not so clear. Several studies try to get sequence alignment and then run PAML and other packages to get age estimation. I was curious if there is something I can do to do the same using Orthofinder analysis. 

I am not a computational guy, and therefore, Orthofinder is really a lifesaver for me. If there is some way around then that's really cool as I seriously need to know divergence time and to get gain and loss (or expansion and contraction of gene families) for my species, very similar to this article- https://www.sciencedirect.com/science/article/pii/S1674205217300709?via%3Dihub (Fig1B). In this case, method is not described detail enough to be able to replicate. I know that many people use sequence alignment and identify the number of matched amino acids, and then use that for age estimation using tools such as r8s, which then is used in CAFE to estimate gain and loss of gene families.

Your comments will be of great help.

thank you so much in advance,

with best regards
Amit

**Comment by aditi-2017** [comment]
I would like to know answer for this as well. Thank you.

**Comment by Barsha-P** [comment]
I am also trying to work out divergence time for my species. If you guys have already figure out the way, could you please share.  Many thanks.

**Comment by davidemms** [comment]
Hi, there's a script for making an ultra-metric tree: "tools/make_ultrametric.py". There's some extra discussion here: https://github.com/davidemms/OrthoFinder/issues/153
