### ISSUE TITLE
Can't run diamond

### ISSUE THREAD

**Issue by davidemms** [davidemms/OrthoFinder#255]
Opened on behalf of menghappy324 (moved from https://github.com/davidemms/OrthoFinder/issues/188):

Hi, when I use the orthofinder, I find the sequence search program included blast, mmseqs, blast_gz, diamond. Now, I want to consult that when I use -S diamond like this: orthofinder -f /data/plantlab/miniconda3/pkgs/orthofinder-2.2.7-0/ExampleData -S diamond, how much the alignment similarity is. Besides, the "-S diamond" made my programm stop and showed as below "ERROR: Cannot run diamond
Format of make database command:
diamond makedb --in INPUT -d OUTPUT
ERROR: Cannot run diamond
Format of search database command:
diamond blastp -d DATABASE -q INPUT -o OUTPUT --more-sensitive -p 1 --quiet -e 0.001 --compress 1
Please check diamond is installed and that the executables are in the system path", but in fact, I have installed the diamond 2.2.7 successfully. Is it the problem of the version? Thank you very much.

**Comment by davidemms** [comment]
Hi

What happens when you execute the command "diamond" from the same terminal you use when you unsuccessfully try "orthofinder -f /data/plantlab/miniconda3/pkgs/orthofinder-2.2.7-0/ExampleData -S diamond"

All the best 
David

**Comment by timregan** [comment]
Hi David, was this ever fully resolved?
I had been using Orthofinder with no issues, until I attempted rerunning some analysis and I got this Error message:
OrthoFinder version 2.3.12 Copyright (C) 2014 David Emms

2020-06-05 10:55:43 : Starting OrthoFinder
16 thread(s) for highly parallel tasks (BLAST searches etc.)
16 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------

ERROR: Cannot run diamond
Format of make database command:
  diamond makedb --in INPUT -d OUTPUT
ERROR: Cannot run diamond
Format of search database command:
  diamond blastp -d DATABASE -q INPUT -o OUTPUT --more-sensitive -p 1 --quiet -e 0.001 --compress 1
Please check diamond is installed and that the executables are in the system path

By the way, when I run diamond from the terminal, I get this message:
Error: Syntax: diamond COMMAND [OPTIONS]. To print help message: diamond help

I have installed diamond v0.9.24 using bioconda. 

Many thanks,
Tim

**Comment by sjfleck** [comment]
I downloaded OrthoFinder v2.5.4 through a conda environment and I've come across this same issue. For some reason, I can run orthofinder and it finds Diamond perfectly fine when it's run in the front end of our cluster (there are cpu, memory, and time limits on the front end, so I can't actually complete the job when I run it here). This is what I see on when I run it in terminal (before I cancel the command):

###########################################################
OrthoFinder version 2.5.4 Copyright (C) 2014 David Emms

2021-10-21 09:55:49 : Starting OrthoFinder 2.5.4
4 thread(s) for highly parallel tasks (BLAST searches etc.)
4 thread(s) for OrthoFinder algorithm

Checking required programs are installed
Test can run "mcl -h" - ok

Dividing up work for BLAST for parallel processing
2021-10-21 09:55:58 : Creating diamond database 1 of 7
2021-10-21 09:55:58 : Creating diamond database 2 of 7
2021-10-21 09:55:59 : Creating diamond database 3 of 7
2021-10-21 09:55:59 : Creating diamond database 4 of 7
2021-10-21 09:55:59 : Creating diamond database 5 of 7
2021-10-21 09:56:00 : Creating diamond database 6 of 7
2021-10-21 09:56:00 : Creating diamond database 7 of 7

Running diamond all-versus-all
Using 4 thread(s)
2021-10-21 09:56:00 : This may take some time....
2021-10-21 09:56:00 : Done 0 of 49
###########################################################

When I submit this same job to my cluster, I end up with this error:

###########################################################
ERROR: Cannot run diamond
Format of make database command:
  diamond makedb --in INPUT -d OUTPUT
ERROR: Cannot run diamond
Format of search database command:
  diamond blastp -d DATABASE -q INPUT -o OUTPUT --more-sensitive -p 1 --quiet -e 0.001 --compress 1
Please check diamond is installed and that the executables are in the system path
###########################################################

I'm wondering if this is related to the problem in this issue. I use conda environments very frequently and never have this kind of issue ...except yesterday when I installed "Proteinortho" through a conda environment . It also couldn't find Diamond even though it also is definitely available in the system path when I test it in the front end.
