### ISSUE TITLE
Stall at: Inferring remaining multiple sequence alignments and gene trees

### ISSUE THREAD

**Issue by ykjyhmj** [davidemms/OrthoFinder#257]
Dear OrthoFinder developers,

Thanks for the awesome software. It worked pretty good previously. But when I tried to add more species, it stalled at: 
Inferring remaining multiple sequence alignments and gene trees
---------------------------------------------------------------
2019-04-26 12:11:29 : Done 0 of 16999

It has already beed 3 days. Is it normal? Right now, I totally have 11 species. And I am using version 2.2.7 .

Thanks very much!

**Comment by davidemms** [comment]
Hi

The easiest thing is to use top or htop to see what the computer is doing--you will be able to see if it is running MSA & tree inference programs, this is probably the most likely. OrthoFinder always does the largest trees first, this makes the parallelisation better but means the first 1000 can take a while but then the later trees get done very quickly. If you want, you can also look in the WorkingDirectory in the OrthoFinder results directory to see how many trees have already been done to get a more fine-grained measure of progress.

How long the tree inference takes when using multiple sequence alignments will depend on things like how many cores you're using, the speed of the computer and what programs you are using for MSA & tree inference (default, or some other programs). Different programs can have very different run times.

All the best
David

**Comment by ykjyhmj** [comment]
Hi David,

By looking into the top, I do find a thread from iqtree running.  Does the tree building is a single thread process? Here's my code to run the orthofinder: 
orthofinder -S diamond -t 22  -M msa -A muscle -T iqtree -a 24 -fg new_species/Results_Apr24/WorkingDirectory/. 
Is there any way to speed up the running, like changing the tree building program?

Thanks!
Minjie

**Comment by davidemms** [comment]
Hi Minjie

With the arguments you've given then 22 orthogroups should be running in parallel, each one either running muscle or iqtree. When you look at top, are 22 cores being used? 

Using the default FastTree is a lot quicker than iqtree. If you have the time though, it is good to use iqtree as it is more accurate. In general I also think the default mafft is better than muscle.

All the best
David

**Comment by ykjyhmj** [comment]
Hi David,

It's weired that there is only one core running iqtree. 
![image](https://user-images.githubusercontent.com/39601931/56978473-96e4c000-6b45-11e9-9c94-c5046ff6c7b3.png)

**Comment by davidemms** [comment]
Hi Minjie

It's hard to say what's happening without being able to try lots of different thing on the computer itself. Questions to look at would be:
1. Does it run in parallel if you run the same thing with the ExampleDataset? 
2. What trees are already completed, and when where they completed? To see this run the command `ls -lct new_species/Results_Apr24/WorkingDirectory/Orthologues_Apr26/WorkingDirectory/Trees_ids/` (using whatever is the correct directory path for your results directory)
3. If you run the pstree command what do you see for the part of the tree corresponding to OrthoFinder? For example, I see something like this when it's running the trees in parallel:
```
─bash(29961)───python(26943)─┬─python(26953)
                             ├─python(27109)───sh(5661)───raxmlHPC-AVX(5672)
                             ├─python(27110)───sh(5512)───mafft(5521)
                             ├─python(27111)───sh(5764)───mafft(5766)
                             ├─python(27113)───sh(5644)───mafft(5652)
                             ├─python(27116)───sh(5569)───raxmlHPC-AVX(5578)
                             ├─python(27119)───sh(5591)───raxmlHPC-AVX(5596)
                             ├─python(27125)───sh(5206)───raxmlHPC-AVX(5230)
                             ├─python(27136)───sh(5334)───mafft(5341)
                             └─{python}(27108)
```

All the best
David

**Comment by ykjyhmj** [comment]
David,
Thanks for all the suggestions.

I changed to use default tree build method. It finished analysis less than half day while iqtree based method is still running.
