### ISSUE TITLE
Getting Original Protein Sequence

### ISSUE THREAD

**Issue by micromania2** [davidemms/OrthoFinder#258]
Once I have found the OG of interest, what is the best way to go back and get a representative protein sequence of that OG?

**Comment by davidemms** [comment]
Hi

If you are using the latest version of Orthofinder it writes out a fasta file for each orthogroup containing all the protein sequences for the genes in that orthogroup. You'll need to decide yourself what you take to be a 'representative' sequence. You could do something as simple as taking the longest sequence, but you'll probably know better based on what you want to achieve.

If it is useful to have multiple sequence alignments to help with this they can be generated using the "-M msa" option, which can be combined with the "-fg" option which will start the analysis from the already computed orthogroups (assuming you've already inferred them).

All the best
David

**Comment by micromania2** [comment]
Hi David,

Thanks for the quick reply. It there an option to get a representative (i.e. longest sequence) for each OG or plans to offer this feature in the near future?

**Comment by davidemms** [comment]
Hi

There aren't any current plans to.

All the best
David
