### ISSUE TITLE
faster sequence comparison

### ISSUE THREAD

**Issue by inti** [davidemms/OrthoFinder#26]
Hi,
For large projects it could be beneficial to use https://github.com/soedinglab/MMseqs or another fast sequence comparison tool (faster than blast) and perhaps nice to have it wrapped over within the same orthofinder tool.

thanks

**Comment by davidemms** [comment]
Hi

I'm testing out LAST+ at the moment (https://github.com/hallamlab/LAST-Plus) and hope to have it included in OrthoFinder soon. From what I've seen so far its performance is very good in comparison to BLAST.

All the best
David

**Comment by davidemms** [comment]
Hi

Diamond is a significantly faster alternative to BLAST and is now integrated into the latest version of OrthoFinder, it's selected using "-S diamond".

In fact, there is now an extensibility mechanism in OrthoFinder that allows you to use any other sequence search program in place of BLAST if it can output in the BLAST tabular format. You just need to enter the correct command line format in the config.json file as described in the manual (5.7 User-speciefied MSA, Tree Inference or Sequence Search Program).

All the best
David
