### ISSUE TITLE
what's the meaning of the node labers

### ISSUE THREAD

**Issue by LHXqwq** [davidemms/OrthoFinder#260]
i have finished my task,but i can't understand the node labers of the Species tree,
![node labers](https://user-images.githubusercontent.com/50397597/57357234-0ccfd380-71a5-11e9-87f8-5b5c9f26c096.png)
what does this numbers mean ,does it related to the Divergence time ？

**Comment by davidemms** [comment]
These are the proportion of estimates of the species tree that  support each bipartition. 

All the best
David

**Comment by bbalog87** [comment]
Hi @davidemms,

Are these number (node labels) related with the rate gen duplication in that node ? I don't really understand biological meaning of these node labels. Could you give more hints to facilitate its biological interpretation? 


Best,
Julien

**Comment by davidemms** [comment]
Hi Julien

A number of files are provided which given information about the species tree. I'm assuming that the one you've pasted above is the `Species_Tree/SpeciesTree_rooted_node_labels.txt`, but let me know if it was a different one you're asking about. The numbers in this tree are branch lengths. 

Node labels are used throughout the OrthoFinder results for the gene and species trees. These can refer to nodes or branches according to context. This is the cleanest way to refer to nodes and branches unambiguously within the newick format. When branches need to be referred to, it is done by using the node that the branch terminates at.

In terms of gene duplication events, the node labels in the `Species_Tree/SpeciesTree_rooted_node_labels.txt` are referred to in the `Gene_Duplication_Events/Duplications.tsv` file. Each putative gene duplication event detected in one of the gene trees is cross-referenced to the **branch** of the species tree along which it occurred. The node in the gene tree for this putative duplication event is also given as well as the support (proportion of expected species for which a gene is present below both putative duplicate branches in the gene tree). 


A summary of the number of duplication events with 50+% support which were detected along each branch of the species tree is given in the file  `Gene_Duplication_Events/SpeciesTree_Gene_Duplications_0.5_Support.txt`. 

E.g. for the Example Dataset:
`(Mycoplasma_hyopneumoniae_24:0.260965,((Mycoplasma_genitalium_9:0.52544,Mycoplasma_gallisepticum_25:0.44698)N2_7:0.49834,Mycoplasma_agalactiae_21:0.50473)N1_2:0.260965)N0_12;`
This says, for example, that there were 7 gene duplication events with 50% support on the branch corresponding to the common ancestor of _M. genitalium_ and _M. gallisepticum_.

All the best
David
