### ISSUE TITLE
Diamond not working anymore

### ISSUE THREAD

**Issue by andhartm** [davidemms/OrthoFinder#267]
Hello,

First of all thanks for the great tool! I'm an absolute beginner and I managed to get it running fairly easy.

To my problem: 
I was using OrthoFinder (2.2.7) a few month back (RedHatVM) and everything worked very well.
After upgrading to OrthoFinder-2.3.3_glibc-2.19, using diamond as an optional function stopped working. It is the same for the old version. Diamond is not listed as an option (-S) anymore. 

I get following error message:
Invalid argument for option -S: diamond
Valid options are: {blast}

Installed the normal blast search and it's working just fine. It just takes way too long on my machine which is slow anyways.

Any suggestions are appreciated!

Cheers!

**Comment by davidemms** [comment]
Hi

You need to make sure that the config.json that comes with OrthoFinder remains in the same directory as the orthofinder executable. It contains details for how OrthoFinder should call DIAMOND.

All the best
David

**Comment by andhartm** [comment]
Too easy...
Thanks David

**Comment by davidemms** [comment]
No problem, I've updated the README file to tell people this, beforehand there was no way for anyone to know.

Thanks
David
