### ISSUE TITLE
Cannot run diamond

### ISSUE THREAD

**Issue by carlosparq** [davidemms/OrthoFinder#268]
Hi,

When i try to run Orthofinder v 2.2.7 using Diamond I get the following error message:

> OrthoFinder version 2.2.7 Copyright (C) 2014 David Emms
> 
> 2019-06-06 11:44:33 : Starting OrthoFinder
> 16 thread(s) for highly parallel tasks (BLAST searches etc.)
> 1 thread(s) for OrthoFinder algorithm
> 
> Checking required programs are installed
> ----------------------------------------
> 
> ERROR: Cannot run diamond
> Format of make database command:
>   diamond makedb --in INPUT -d OUTPUT
> ERROR: Cannot run diamond
> Format of search database command:
>   diamond blastp -d DATABASE -q INPUT -o OUTPUT --more-sensitive -p 1 --quiet -e 0.001 --compress 1
> Please check diamond is installed and that the executables are in the system path
> 
> ERROR: An error occurred, please review error messages for more information.

If I try to make the databases directly from the same terminal it works perfectly. Right now I'm running diamond v 0.9.10.111 because I've tried downgrading it to see if it works (at first I couldn't run diamond either).

I've also tried downgrading Orthofinder but couldn't find a version that works for me.

Any help will be much appreciated, thanks in advance.

**Comment by davidemms** [comment]
Hi

Could you download the latest versions of OrthoFinder and diamond and try that please. I think you may have been unlucky in your choice of an old version of diamond; v0.9.10 had a rare bug in it that I remember reporting: https://github.com/davidemms/OrthoFinder/issues/89 &  https://github.com/bbuchfink/diamond/issues/175.

If you have a problem with the latest versions, would you be able to post a complete terminal session (screenshot or the full text) of you calling the command "which diamond", then calling diamond makedb and blastp commands successfully and then calling OrthoFinder and it failing. 

Thanks
David

**Comment by carlosparq** [comment]
I've upgraded all the packages but as I said I couldn't even run diamond separately with the latest version, that's why I tried downgrading it. Here's what I got with the latest versions:

> lubuntu@lubuntu:/media/sf_VMshared/mclBusco/orthofinder$ which orthofinder
> /home/lubuntu/anaconda3/bin/orthofinder
> lubuntu@lubuntu:/media/sf_VMshared/mclBusco/orthofinder$ which diamond
> /home/lubuntu/anaconda3/bin/diamond
> lubuntu@lubuntu:/media/sf_VMshared/mclBusco/orthofinder$ which makeblastdb
> /home/lubuntu/anaconda3/bin/makeblastdb
> lubuntu@lubuntu:/media/sf_VMshared/mclBusco/orthofinder$ diamond makedb --in test/Absrep1.fa --db test/Absrep
> diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>
> Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
> Check http://github.com/bbuchfink/diamond for updates.
> 
> #CPU threads: 4
> Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
> Database file: test/Absrep1.fa
> Opening the database file... Text file busy
>  [0.003268s]
> Error: Error calling unlink.
> 
> lubuntu@lubuntu:/media/sf_VMshared/mclBusco/orthofinder$ makeblastdb -in test/Absrep1.fa -dbtype prot -out test/Absrep1
> 
> 
> Building a new DB, current time: 06/07/2019 12:22:13
> New DB name:   /media/sf_VMshared/mclBusco/orthofinder/test/Absrep1
> New DB title:  test/Absrep1.fa
> Sequence type: Protein
> Deleted existing Protein BLAST database named /media/sf_VMshared/mclBusco/orthofinder/test/Absrep1
> Keep MBits: T
> Maximum file size: 1000000000B
> Adding sequences from FASTA; added 14919 sequences in 1.24716 seconds.
> lubuntu@lubuntu:/media/sf_VMshared/mclBusco/orthofinder$ orthofinder -f test/ -S diamond
> 
> OrthoFinder version 2.3.3 Copyright (C) 2014 David Emms
> 
> 2019-06-07 12:22:44 : Starting OrthoFinder
> 4 thread(s) for highly parallel tasks (BLAST searches etc.)
> 1 thread(s) for OrthoFinder algorithm
> 
> Checking required programs are installed
> ----------------------------------------
> 
> ERROR: Cannot run diamond
> Format of make database command:
>   diamond makedb --in INPUT -d OUTPUT
> ERROR: Cannot run diamond
> Format of search database command:
>   diamond blastp -d DATABASE -q INPUT -o OUTPUT --more-sensitive -p 1 --quiet -e 0.001 --compress 1
> Please check diamond is installed and that the executables are in the system path
> 
> ERROR: An error occurred, please review error messages for more information.

Hope it helps to solve the problem!

**Comment by carlosparq** [comment]
It seems to work with BLAST and with MMseqs2, I can paste the initial steps of the blast  searches:

lubuntu@lubuntu:/media/sf_VMshared/mclBusco/orthofinder$ orthofinder -f test/ -S blast

OrthoFinder version 2.3.3 Copyright (C) 2014 David Emms

2019-06-07 12:29:11 : Starting OrthoFinder
4 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

> Checking required programs are installed
> ----------------------------------------
> Test can run "makeblastdb -help" - ok
> Test can run "blastp -help" - ok
> Test can run "mcl -h" - ok
> Test can run "fastme -i /media/sf_VMshared/mclBusco/orthofinder/test/OrthoFinder/Results_Jun07_2/WorkingDirectory/SimpleTest.phy -o /media/sf_VMshared/mclBusco/orthofinder/test/OrthoFinder/Results_Jun07_2/WorkingDirectory/SimpleTest.tre" - ok
> 
> Dividing up work for BLAST for parallel processing
> --------------------------------------------------
> 2019-06-07 12:29:15 : Creating Blast database 1 of 7
> 2019-06-07 12:29:16 : Creating Blast database 2 of 7
> 2019-06-07 12:29:18 : Creating Blast database 3 of 7
> 2019-06-07 12:29:19 : Creating Blast database 4 of 7
> 2019-06-07 12:29:20 : Creating Blast database 5 of 7
> 2019-06-07 12:29:21 : Creating Blast database 6 of 7
> 2019-06-07 12:29:22 : Creating Blast database 7 of 7
> 
> Running BLAST all-versus-all
> ----------------------------
> Using 4 thread(s)
> 2019-06-07 12:29:23 : This may take some time....
> 2019-06-07 12:29:23 : Done 0 of 49

So, in case I cannot get it to work, how reliable is MMseqs2 compared to BLAST?

**Comment by davidemms** [comment]
Hi 

In terms of the problems with the latest version of diamond, it would be great if you could report it on their github page https://github.com/bbuchfink/diamond/issues, they should be able to help out. I've tried running that version on my computer and it doesn't have any problems so I can't tell you what's going wrong there. Nobody has contacted me with any problems with prior versions, except for the v0.9.10 issue I linked to, so I think that may have been an unfortunate choice, perhaps have one last try with [v0.9.11](https://github.com/bbuchfink/diamond/releases/download/v0.9.11/diamond-linux64.tar.gz). If OrthoFinder is reporting that it can't get diamond to run then that sounds like the correct behaviour in this case. I'd be surprised if they can't resolve the issue with diamond though, I've always found it to be very reliable.

Unfortunately I have had occasional problems with running multiple copies of MMseqs2, which may or may not have been resolved. I'll try it now and let you know if I see any problems.

All the best
David

**Comment by davidemms** [comment]
Hi 

Just to let you know, I was having some problems with MMseqs, see https://github.com/davidemms/OrthoFinder/issues/269. This only occurs if there is a sequence longer than 65535 amino acids in one of your input files. I've submitted a fix for this. If you need this fix you can download the python code from the main github page. There are no other issues I'm aware of for MMseqs so it should run fine. 

All the best
David
