### ISSUE TITLE
Highly similar paralogues in different orthogroups

### ISSUE THREAD

**Issue by twohrdrive** [davidemms/OrthoFinder#271]
Perhaps the answer to this question is biological in nature, but I'm having difficulty wrapping my head around it: two paralogous sequences (>98% identity) are ending up in different orthogroups.  

These two sequences arose recently via gene duplication, following the split of most of the species analyzed

Within each of the two orthogroups, containing one of the two paralogues, most of the species analyzed are represented.

Taken together, this makes little sense to me.  I analyzed around 20 proteomes, using the diamond option and rooted species tree. Has anyone encountered something like this?

Thanks, and best,

-Andy

**Comment by davidemms** [comment]
Hi Andy

You may be right, it could be that they do belong in the same orthogroup. To work out if they do for certain I would recommend taking the fasta files for the two orthogroups, combining them into a single file and generating an multiple sequence alignment and tree for them. Once you've worked out on which branch the tree should be rooted, look to see if the sequences diverged before or after the first of your species diverged. 

If you're using the latest version of OrthoFinder then these starting orthogroup sequence files will have been generated by default. If you were using an older version then you can generate them using the options "-M msa -os -fg _PREVIOUS_RESULTS_DIRECTORY_"

All the best
David

**Comment by twohrdrive** [comment]
Hi David,

Thanks, I will try exactly this.  I suppose my question would be what would cause two closely related, recently-duplicated paralogues end up in differnet orthogroups? Might there be a biological (evolutionary) explanation or would there be a known issue in the pipeline?

Thanks again and take care,

-Andy

**Comment by davidemms** [comment]
Hi Andy

It's hard to say without seeing the tree and the MSA for this family, although there's no obvious biological reason for them to be in two different orthogroups. The only thing I can think of is a gene having a domain from another family inserted into it--this would be unlikely, and the MSA would clearly show if this were the case or not. The most likely reason is simply that the results will never be 100% accurate. Even though OrthoFinder is more accurate for orthogroup inference than any other method, it is still only about 90% accurate on randomly chosen gene families. This means that you will always be able to find some cases where human examination of a particular gene family will reveal incorrect assignments. 

All the best
David
