### ISSUE TITLE
Error reading input stream at line 1: FASTA format error: Missing '>' at record start

### ISSUE THREAD

**Issue by jeagull** [davidemms/OrthoFinder#279]
Hello,
I am trying to run Orthofinder and whenever I run the command I always get an error saying:
`Erorr: Error reading input stream at line 1: FASTA format error: Missing '>' at record start`
and I looked at the corresponding file and it is indeed missing > at the start for some reason. All the Species*** files I checked are formed correctly. Do you have any idea what is happening and I would appreciate if you have any suggestions on what to do next. Thanks.

![スクリーンショット 2019-08-02 10 09 56](https://user-images.githubusercontent.com/13218402/62337097-29627a00-b50e-11e9-8be4-ac3081375a06.png)
![スクリーンショット 2019-08-02 10 09 32](https://user-images.githubusercontent.com/13218402/62337098-29fb1080-b50e-11e9-9575-4943bc3c88e8.png)

**Comment by davidemms** [comment]
Hi 

I'm not entirely sure I understand the description you've given, but this is what I'd check.
- Does the file, "WorkingDirectory/Species724.fa" have a sequence which is missing a ">" at the start? It sounds like you say this is the case.
- Look in "WorkingDirectory/SpeciesIDs.txt" to see which of your input files corresponds to Species724
- Check this file to see if it has any problems.

All the best
David

**Comment by jeagull** [comment]
I am terribly sorry for very late reply. Thanks for your comment. I checked the corresponding file and it was problematic and I fixed it. Thank you so much.

**Comment by Jiangjiangzhang6** [comment]
I had run successfully, but run pfam database its show the error ,
