### ISSUE TITLE
WARNING: program called by OrthoFinder produced output to stderr

### ISSUE THREAD

**Issue by ZhongchiLiu** [davidemms/OrthoFinder#282]
Hi,
My job can be completed, but I got the warning at the step shown below. I'm wondering whehter the result will be influenced by the warning.

Thank you!

Running OrthoFinder algorithm
-----------------------------

2019-08-29 14:16:24 : Initial processing of each species
2019-08-29 14:17:33 : Initial processing of species 0 complete
2019-08-29 14:18:15 : Initial processing of species 1 complete
2019-08-29 14:18:57 : Initial processing of species 2 complete
2019-08-29 14:19:10 : Connected putatitive homologs

WARNING: program called by OrthoFinder produced output to stderr

Command: [......]

stdout
------

stderr
------
[mcl] cut <2> instances of overlap

2019-08-29 14:20:07 : Ran MCL

Writing orthogroups to file
---------------------------

**Comment by Fede-Rome** [comment]
Hi,

I am also getting this ! How does it influence the results ? Many thanks for any help !

**Comment by davidemms** [comment]
Hi

Sorry for the delay in replying to this. This isn't a problem, OrthoFinder only reports it because it is output directed to stderr by one of the programs it calls but in this case it can be ignored.

All the best
David

**Comment by Fede-Rome** [comment]
great, thanks a lot!

Federico
