### ISSUE TITLE
WriteGraphParallel ignores specified number of cpu's

### ISSUE THREAD

**Issue by rrodgers12** [davidemms/OrthoFinder#29]
I ran OrthoFinder v0.6.1 on a 32Gb machine using pre-computed BLAST results totaling 256 files at 163.2Gb.  I specified only one process, but would run out of RAM when final scores are written to graph files.  This seemed to be occurring because multiple processes were spawning at this step even though only one process was specified.

We worked around this by modifying the WriteGraphParallel function, line 834, by changing pool=mp.pool() to pool=mp.pool(1) to restrict it to one process.  This hard-coded change allowed the program to complete successfully in around 16 hours on this large amount of data.  I thought you may be interested to know about this issue and work-around.  

Thanks so much,

Rachel

**Comment by davidemms** [comment]
Thanks for pointing this out!
