### ISSUE TITLE
Orthogroup Sequences files not generated

### ISSUE THREAD

**Issue by joao1980** [davidemms/OrthoFinder#291]
I have run the Orthofinder tool with -og option. However, I am not getting the folder Orthogroup Sequences with the respective OG.fa files. In theory, the -og option should not have any influence on this outcome. Any help would be appreciated.

**Comment by davidemms** [comment]
Hi

I've just run the current release on the Example dataset with the '-og' option and it does produce the Orthogroup Sequences files. Can you confirm that you see the same? Is there anything you are doing differently with your dataset?

All the best
David
