### ISSUE TITLE
Diamond evalue cutoff

### ISSUE THREAD

**Issue by ankita86** [davidemms/OrthoFinder#295]
Hi,

I have read original paper of orthofinder that uses blast as first step for all-versus-all sequence comparisons it uses evalue threshold of 0.01. But for newer version, where Diamond is default . Does evalue cutoff for Diamond is same ?

**Comment by davidemms** [comment]
Hi

OrthoFinder uses 0.001 for DIAMOND and BLAST. If you want to change anything in the command line for DIAMOND, you can do that in the config.json file in the OrthoFinder package.

All the best
David
