### ISSUE TITLE
ValueError: cannot remove a zero-sized axis from an iterator

### ISSUE THREAD

**Issue by ashforda** [davidemms/OrthoFinder#299]
Hi, 

Running the most recent version of OrthoFinder I come across this error directly after the "initial processing" of my species.

<img width="595" alt="Screen Shot 2019-10-29 at 8 37 36 PM" src="https://user-images.githubusercontent.com/57164709/67827081-f76c9f80-fa8b-11e9-8b86-59ca11ce3e9a.png">

I ran the script with the following parameters:
/home/orthofinder_loc/orthofinder -S blast -f my_fasta_directory

**Comment by davidemms** [comment]
Hi

I'm guessing this came from only providing a very few sequences per species as input? I'll have a look at the code and make sure it produces a clearer message if this occurs or has a way of dealing with it gracefully.

Thanks
David

**Comment by davidemms** [comment]
Hi 

I've been looking into this and I think the warnings up to this point provide enough information. It would be better not to force OrthoFinder to return an error if there are very few hits because there is no clear rule for how few is too few. 

All the best
David
