### ISSUE TITLE
Possible to start from MSA's?

### ISSUE THREAD

**Issue by ngroberts** [davidemms/OrthoFinder#302]
Is it possible to have Orthofinder begin from a set of multiple sequence alignments? I would like to stop at MSAs using -oa and then clean up those alignments using my script and begin the gene tree building, and species tree step using a command similar to -ft.

**Comment by davidemms** [comment]
Hi

There's no option to start from MSAs but you can easily include your script in OrthoFinder using the config file, that way it will do it automatically for you. 

The way to do this would be to create a new "msa" "program_type" in the config file. The command line would then have two commands separated by a semi-colon. The first would do the alignment and save it to a file X (a different filename for each orthogroup) and the second would call your script with X as input and the OUTPUT tag as the output filename. You would then be able to select this option for your OrthoFinder runs. The mmseqs command in the config file gives an example of this approach. Let me know how you get on. I can help out with any queries tomorrow our Monday.

All the best
David

**Comment by davidemms** [comment]
Just following up on this now I'm back at the computer. Here's an example of how I'd do this using muscle to infer the alignments and trimal to trim the alignments:

In the file orthofinder/config.json add the following entry:

```
    "muscle_and_trim":{ 
    "program_type": "msa",
    "cmd_line": "muscle -in INPUT -out OUTPUT_untrimmed ; trimal -in OUTPUT_untrimmed -out OUTPUT -automated1"
    },
```
This runs two commands for each orthogroup at the alignment stage. First it infers the alignment using muscle saving the MSA file to, for example, `ExampleData/OrthoFinder/Results_Nov04/WorkingDirectory/Alignments_ids/OG0000001.fa_untrimmed` for orthogroup OG0000001. The second command then takes this intermediate file and trims it, saving the final trimmed MSA file to be used in the following steps by OrthoFinder to the correct `OUTPUT` variable, which will be `Alignments_ids/OG0000001.fa` for OG0000001.

Run "orthofinder -h" to check you now see this option in the help output:
```
 -A <txt>          MSA program, requires '-M msa' [Default = mafft]
                   Options: muscle_and_trim, muscle, mafft
```
And then run it on the test dataset:
```./orthofinder_test_config/orthofinder -f orthofinder_test_config/ExampleData/ -M msa -A muscle_and_trim```

(Note, this is just an example of how to do it. I wouldn't recommend using trimal to do this as it has a tendency to over-trim the alignment and so you lose information, and potentially (?) whole MSAs.

All the best
David
