### ISSUE TITLE
Dating STAG species tree

### ISSUE THREAD

**Issue by KnudNorNielsen** [davidemms/OrthoFinder#303]
Hi David
I would like to date a recent divergence observed in a stag species tree. Is it possible from the orthofinder output to identify the specific genes (gene-trees) that are in topological concordance with the STAG species tree?
Or, would you recommend that I simply build a new phylogeny based on single-copy-orthologs, and dated that based on the genes that were made building it? In this case, I would still love to know have to find the genes that agree with the species tree.
Cheers Knud

**Comment by davidemms** [comment]
Hi Knud

The orthogroups used for the STAG species trees are the ones in the directory `WorkingDirectory/SpeciesTrees_ids/`. Not all of these will be in topological concordance with the final species tree, many will be different. The species tree is the greedy consensus tree of these trees. You would need to write a script to see which ones are in concordance, this isn't information OrthoFinder needs to generate.

If there are enough single copy orthogroups to give you a good species tree then yes, that could be a good approach also. If there are a lot of species in your analysis then I think 100 or so would probably be enough.

All the best
David
