### ISSUE TITLE
[OrthoFinder -b] does not normalize blast scores

### ISSUE THREAD

**Issue by remyd1** [davidemms/OrthoFinder#304]
Hi,

I don't see any option to just normalize blast scores from blast outputs. 

However, there is an option in OrthoFinder to take as inputs the blast outputs (`-b`). In that case, scores are not normalized, and OrthoFinder continues from there.

Is it possible to add just an option (eg: `-N`) for normalization ? Or if OrthoFinder starts from blast output (`-b`), it normalizes scores before continuing ?

Thanks,
Best regards,

**Comment by davidemms** [comment]
Hi

You don't need to provide any options, in all cases OrthoFinder performs the normalisation of the BLAST scores that it reads in.

All the best
David
