### ISSUE TITLE
Problems with GLIBC_2.25

### ISSUE THREAD

**Issue by JC-therea** [davidemms/OrthoFinder#305]
Hi,
Recently I have been searching a good tool to find orthologs and paralogs in several species. I think that OrthoFinder can do this job very well. However, I am using a CentOS 7 server to work and this is a problem for some libraries. Running OrthoFinder it outputs the following error:

Traceback (most recent call last):
  File "PyInstaller/loader/rthooks/pyi_rth_certifi.py", line 11, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "ssl.py", line 98, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 684, in load_module
ImportError: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEISppDv9/libcrypto.so.1.1)

I suppose that the problem is with the library GLIBC_2.25. As I am using a CentOS 7 machine and I can not change it I would like to ask if there is some version of OrthoFinder that uses a previous version of GLIBC (Im using 2.17).

Thank you for all the help.

Jose Carlos Montañes

**Comment by davidemms** [comment]
Hi

Yes, there is a version using 2.17 on the releases page: https://github.com/davidemms/OrthoFinder/releases. 

It's also possible to use the source code version if you have the numpy and scipy libraries installed, this has no requirements on GLIBC version. 

All the best
David

**Comment by JC-therea** [comment]
Thank you David. With the source code works.
Kind regards
JC
