### ISSUE TITLE
error while running on mac 

### ISSUE THREAD

**Issue by cparsania** [davidemms/OrthoFinder#306]
I tried below command on mac but it didn't work 

`./orthofinder.py -f ExampleData/Mycoplasma_agalactiae.faa`
 
I installed latest version of diamond and mcl 

```
diamond --version
diamond v0.9.28.129 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

diamond version 0.9.28
```

```
mcl --version
mcl 14-137
Copyright (c) 1999-2014, Stijn van Dongen. mcl comes with NO WARRANTY
to the extent permitted by law. You may redistribute copies of mcl under
the terms of the GNU General Public License.
```

blastp version  

```
DESCRIPTION
   Protein-Protein BLAST 2.6.0+

```
![image](https://user-images.githubusercontent.com/10338600/69023260-232ed580-09f9-11ea-8af0-2f88f94ba12c.png)

**Comment by davidemms** [comment]
Hi

The things to check would be:
- There is a copy of diamond in `orthofinder/bin`, try deleting that.
- confirm that you can call diamond from the same terminal, same directory as you are calling orthofinder from.
- check you can call the commands that orthofinder is trying to run. e.g. for "diamond makedb --in INPUT -d OUTPUT" you could replace INPUT with one of the example files and OUTPUT with any name: `diamond makedb --in ExampleDataset/Mycoplasma_agalactiae.faa -d test_output`.

All the best
David

**Comment by cparsania** [comment]
Deleting files from `orthofinder/bin` does the trick. 

Cheers
Chirag.

**Comment by davidemms** [comment]
Thanks, that's useful to know!

All the best
David
