### ISSUE TITLE
KeyError: '82'

### ISSUE THREAD

**Issue by HendAbuElmakarem** [davidemms/OrthoFinder#307]
Hi,
I ran orthofinder and it was working, but when I updated my species list and added and removed species based on the manual instructions, I hit an error when I re-ran orthofinder using the following code: 
`orthofinder -S diamond -T iqtree -b /mnt/storage/scratch/nl18621/Hend_Orthofinder/p_keilini_clustering_OF_sep19/Results_Sep16/WorkingDirectory -f /mnt/storage/scratch/nl18621/Hend_Orthofinder/Nov15_Orthofinder_run/new_fasta`

Working on a cluster, the job status update on the job submission script was "FAILED", and I could see in the job output a KeyError: '82'. 

I have attached the job output file below.

Thanks in advance!

[orthofinder-job-output.txt](https://github.com/davidemms/OrthoFinder/files/3859634/orthofinder-job-output.txt)

**Comment by davidemms** [comment]
Hi

Could you update to a newer version of OrthoFinder, I think this issue has already been resolved. Let me know if you have any further problems

All the best
David
