### ISSUE TITLE
Please create a new tag for v2.3.7

### ISSUE THREAD

**Issue by liaochenlanruo** [davidemms/OrthoFinder#308]
Dear sir,
        I saw that you modified the codes 12 days ago, allowing orthofinder to support python 3, but the tag of v2.3.7 was created about a month ago and did not contain the latest changes. Therefore, would you like to recreate the tag of v2.3.7, so that someone can update the bioconda recipe of orthofinder (https://bioconda.github.io/recipes/orthofinder/README.html?highlight=orthofinder#recipe-Recipe%20&#x27;orthofinder&#x27;) .
        Thanks and best wishes for you!

**Comment by davidemms** [comment]
Hi

I'd just like to do a bit more testing first and then will create a new release tag next week.

All the best
David

**Comment by davidemms** [comment]
Hi

I've created a new release (v2.3.8) which includes support for python3 and have updated the bioconda recipe.

All the best
David

**Comment by liaochenlanruo** [comment]
Dear David,
        There is another request. It is about the python version of another recipe (https://bioconda.github.io/recipes/dlcpar/README.html#package-dlcpar). Does the software “dlcpar” support python 3? If so, would you like to modify meta.yaml?
        Thanks a lot.

**Comment by davidemms** [comment]
Hi

DLCpar is no longer required by OrthoFinder, please see https://github.com/davidemms/OrthoFinder/issues/314

All the best
David
