### ISSUE TITLE
unable to run orthofinder because of libc.so.6

### ISSUE THREAD

**Issue by YibiChen** [davidemms/OrthoFinder#312]
Hi,
I got this error message `./orthofinder: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/_MEIhDLZ1K/libz.so.1)` when trying to run orthofinder. I know I have to update this library but I don't have root permission. I also tried to use OrthoFinder-2.3.3_glibc-2.19.tar.gz, which was supposed to work on any system but it didn't.

So any suggestions now?

**Comment by davidemms** [comment]
Hi

You'll need to use the source code version. The OrthoFinder-2.3.3_glibc-2.19.tar.gz will only work if your glibc version isn't too old.

All the best
David
