### ISSUE TITLE
Does OrthoFinder still depend on dlcpar?

### ISSUE THREAD

**Issue by liaochenlanruo** [davidemms/OrthoFinder#314]
Dear David,

        Thank you very much for adding Python 3 support to OrthoFinder and modifying the bioconda recipe. When I tried to add gubbins and OrthoFinder to the same bioconda recipe, I found that the two were still incompatible. After inspection, I found that the software "dlcpar" that OrthoFinder relies on only supports Python 2.

        I browsed the codes and the readme documentation of the latest version of the OrthoFinder and found that it no longer seemed to rely on "dlcpar" software. If so, can you modify the recipe of OrthoFinder and delete "dlcpar"?

        Thanks and best wishes!

**Comment by davidemms** [comment]
Hi Hualin Liu 

You are correct, OrthoFinder doesn't require DLCpar any more, I have submitted a pull request on the bioconda recipe with the dlcpar dependency removed.

All the best
David

**Comment by liaochenlanruo** [comment]
Thanks a lot！
