### ISSUE TITLE
New duplication events with more genes?

### ISSUE THREAD

**Issue by JC-therea** [davidemms/OrthoFinder#315]
Dear Dr. Emms,

I am using this days OrthoFinder to find out duplication events in a set of 11 yeasts. 

First, I ran OrthoFinder with default genes that are available online and the output give me like 250 duplication events in one yeast specie. 
After that I run again OrthoFinder but adding new genes that were not previously annotated. As expected I get more duplication events (like ~20 more). However the problem is that OrthoFinder now identify some duplication events in genes that were in the first run. If I search for this genes in the "Duplication.tsv" file from the first run they are not.

My question is, why OrthoFinder is able to detect new gene duplication events only in the scond run in genes that were in both runs?

Kind regards,
JC

**Comment by JC-therea** [comment]
I will paste a figure for tying to be more ilustrative:

![text4164-0](https://user-images.githubusercontent.com/43994737/70226450-28a65280-1751-11ea-822e-182bae6538a9.png)

Here we can see that the protein called COS9 highlighthed in pink with the original annotation is classified outside the s_cer COS branch but with the addition of new genes COS9 is relocated in the s_cer COS branch. I thought that this can happen because some new genes was added in the branch but my newly added genes start with "TCONS-*******" so I think that is not the problem.

Thank you for your help.
JC

**Comment by davidemms** [comment]
Hi JC

This is just a feature of tree inference, adding new data will sometimes affect the results. Generally, having the extra data in is going to be better. I think the best thing to do in cases like this when you are interested in a particular orthogroup is to use the corresponding Orthogroup_Sequences file that OrthoFinder has created and do a more careful analysis on this one orthogroup. You can create a MSA and infer your own tree from this. Because you are looking at one orthogroup (or a few orthogroups) you can afford to use slower but more accurate methods like iqtree, and perform a bootstrap analysis as well. 

All the best
David

**Comment by JC-therea** [comment]
Hi David,

First of all thank you for your kind and quick reply. 

Actually, I am trying to be accurate finding duplication events from close related yeasts. My problem is that I would like to be sure that nearly all gene duplicates are found with the first analysis (online annotation). Then do the second analysis and see the improvement when new genes can match (or not) with previous genes. If I have now more gene duplication events but most of them are because tree inference is slightly different and not because the new genes can be matched with the old ones that would be a problem for me.

For all this reasons, could you please recommend me what is the most accurate way to run OrthoFinder? Or it's better to run iqtree in all the orthogroups?

Thank you for all David, you are helping me a lot with this.
JC

**Comment by davidemms** [comment]
Hi

The highest accuracy would be to run it with trees inferred from multiple sequence alignments using "-M msa". This will use FastTree by default, I would see how that goes. IQTREE will take a lot longer, so may only be possible if you're looking at a subset of the orthogroup.

All the best
David

**Comment by JC-therea** [comment]
Thank you for your help.

JC
