### ISSUE TITLE
finding Single Copy Orthogroups in subset data 

### ISSUE THREAD

**Issue by LiuKe98** [davidemms/OrthoFinder#317]
Hello everyone,
    I'm using Orthofinder to find the single copy orthogroups to construct the species tree and do positive selection analysis. I had got the results from 15 species proteome. Now I want to find the orthogroups of 5 species among the 15 species. Can I extrcat the groups from the results of 15 species? should I re-run Orthofinder with the protein sequences of the 5 species?

**Comment by davidemms** [comment]
Hi

If the last common ancestor (LCA) of your 5 species is the same as the LCA of your 15 species then the orthogroups are still valid for these 5 species: https://github.com/davidemms/OrthoFinder#orthogroups-orthologs--paralogs. If the LCA has changed then you can run OrthoFinder again on just these 5 species by commenting out the ones you don't want and using the '-b' option: https://github.com/davidemms/OrthoFinder#removing-species. This will be realtively quick as it will reuse your BLAST/DIAMOND searches from before.

All the best
David
