### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'Blast0_10.txt'

### ISSUE THREAD

**Issue by priyanka8590** [davidemms/OrthoFinder#324]
I have 11 organisms, 8 of which belong to different ecotypes of Arabidopsis thaliana, one of Arabidopsis halleri, one of Arabidopsis lyrata and one outgroup, Brassica rapa. I have the fasta sequences in the folder 'datasets'. I have loaded 'orthofinder/2.2.0-py2-tf3rsoz' because that's available on the cluster I'm using. This is the command I'm running:
orthofinder -f OrthoFinder/smaller_datasets/ -S diamond
This is the error I'm running into:
IOError: [Errno 2] No such file or directory: '/work/LAS/mash-lab/bhandary/phylogenetic_analysis/OrthoFinder/smaller_datasets/Results_Dec18/WorkingDirectory/Blast0_10.txt'
Is there something I'm missing?
Thank you for the help!

**Comment by davidemms** [comment]
Hi

That means that (at least) one of your all-v-all Blast or diamond species searches failed. That's not a normal occurrence, it would most likely happen if the user or computer had killed one of the processes or if there were disk problems. Another possibility is that there is something wrong with Species 0 or 10--you can see the speices IDs in the WorkingDirectory/SpeciesIDs.txt file. There might also be more clues in the earlier output that OrthoFinder printed to screen.

All the best
David

**Comment by priyanka8590** [comment]
Thank you for your reply, David. I'm not able to get BLAST to run and I'm just using diamond. Is there a log file generated that would help pin down the problem?
In the SpeciesID.txt file, I have all the species IDs, I'm pasting the contents of the file below:

0: An-1.fasta
1: Ara_halleri.fasta
2: Ara_lyrata.fasta
3: Ara_thaliana.fasta
4: Brassica.fasta
5: C24.fasta
6: Cvi.fasta
7: Eri.fasta
8: Kyo.fasta
9: Ler.fasta
10: Sha.fasta

The earlier output that OrthoFinder printed to the screen seems fine. At the 'Running OrthoFinder algorithm' stage, it stopped at 'Initial processing of each species' with the error message 'An error occurred, please review error messages for more information'. The error is the same that I had in the earlier comment 'IOError: [Errno 2] No such file or directory: '/work/LAS/mash-lab/bhandary/phylogenetic_analysis/OrthoFinder/smaller_datasets/Results_Dec18/WorkingDirectory/Blast0_10.txt''. 
What else can I check to pin down the problem?

**Comment by davidemms** [comment]
Hi

Did you check if there is anything wrong with An-1.fasta or Sha.fasta (species 0 & 10)? And have you confirmed if there could have been any disk problems that stopped this file from being written or from being read? If you don't find anything wrong then it might be best to try running it again.

All the best
David

**Comment by priyanka8590** [comment]
Hello David,

Thank you for your reply! Figured out what the problem was!! There was a problem in my An-1.fasta file. Now, I ran it but ended up with another problem. After I started running it again, this was the error file that was generated:

[mcl] added <2> garbage entries
/tmp/_MEIZhUOup/numpy/core/fromnumeric.py:2374: RuntimeWarning: invalid value encountered in double_scalars
Traceback (most recent call last):
  File "orthofinder/orthofinder.py", line 1549, in <module>
  File "orthofinder/orthofinder.py", line 1398, in GetOrthologues
  File "orthofinder/scripts/orthologues.py", line 976, in OrthologuesWorkflow
  File "orthofinder/scripts/stride.py", line 501, in GetRoot
  File "orthofinder/scripts/tree.py", line 180, in __init__
  File "orthofinder/scripts/newick.py", line 231, in read_newick
scripts.newick.NewickError: Unexisting tree file or Malformed newick tree structure.
Failed to execute script orthofinder

I don't understand this error. Where could the problem be originating from? Thank you for your prompt replies, I really appreciate it! Have a great weekend!

Thank you,
Priyanka

**Comment by davidemms** [comment]
Hi Priyanka

This suggests there might still be a problem with something in one of your input files since the tree inference is failing for one of your orthogroups (OrthoFinder is looking for one of the tree files and finding it is empty it bit there). Nevertheless, there is an update in the latest version which I think should allow OrthoFinder to run even if this occurs. You can just download the latest version to your cluster and run it, it doesn't actually need to be installed, so I would recommend that. You can restart from your previous diamond results using the "-b" option, with the results directory from your previous run as the argument.

All the best
David
