### ISSUE TITLE
orthofinder results: visualisation

### ISSUE THREAD

**Issue by mjfi2sb3** [davidemms/OrthoFinder#33]
Hi folks,

Now that I have the results from Orthofinder. I cannot find the number of genes overlapping and the one to one orthogroups.

Regards,
/SB

**Comment by davidemms** [comment]
Hi

I plan to add a table that lists the orthogroups containing exactly one gene per species in the next week. 

For the number of genes overlapping, there is a results file, "Orthogroups_SpeciesOverlaps.csv" that gives the number of orthogroups which have a given pair of species present. Is it this that you are interested in? Or the number of genes in these orthogroups? 

Thanks
David

**Comment by ces940208** [comment]
Hi,
I did not see the lists of orthogroups with exactly one gene per species in my results after using orthofinder1.1.4. Are they available ? 
I also would like to know if it is possible to have the number of genes overlapping and not just the number of orthogroups ?
Thanks,
Best regards,
CM

**Comment by davidemms** [comment]
Hi

The orthogroups with exactly one gene per species are listed by the latest version of OrthoFinder (v1.1.8) in the file 'SingleCopyOrthogroups.txt'. 

When you say the number of genes overlapping, do you mean the number of genes in one species that are orthologues of genes in the second species? There currently aren't any statistics files produced for the orthologues but you could count these up from the orthologues results tables. Statistics for the orthologues may be added in a future release.

All the best
David

**Comment by ces940208** [comment]
Hi,
Thank you for your answer, 
Yes. Okay, I will do that !
I have also a question about the SingleCopyOrthogroups list. Do they correspond only to genes that had no paralogues or are they included also genes with paralogues but with a duplication that occured before the speciation ?
Thank you,

Best regards,
CM

**Comment by davidemms** [comment]
Hi CM

It's possible that there could have been a duplication prior to the last common ancestor of all the species present i.e. the genes may have ancient paralogues which are outside of the orthogroup. The genes in the single copy orthogroup should all be (unique) orthologues of one another and with no duplications since the most distant speciation event for the whole set of species.

All the best
David
