### ISSUE TITLE
Too many files

### ISSUE THREAD

**Issue by scubapenn** [davidemms/OrthoFinder#331]
When analyzing large number of species I get this error:
raceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
  File "scripts_of/__main__.py", line 1681, in main
  File "scripts_of/__main__.py", line 1507, in GetOrthologues
  File "scripts_of/orthologues.py", line 1012, in OrthologuesWorkflow
  File "scripts_of/orthologues.py", line 810, in ReconciliationAndOrthologues
  File "scripts_of/trees2ologs_of.py", line 648, in DoOrthologuesForOrthoFinder
  File "scripts_of/trees2ologs_of.py", line 600, in __enter__
IOError: [Errno 24] Too many open files:

**Comment by davidemms** [comment]
Hi

You can increase the limits on the number of files you can have open on your computer:
https://www.tecmint.com/increase-set-open-file-limits-in-linux/amp/

All the best
David

**Comment by lyy005** [comment]
Hi David,
I ran into the same error. I tried to increase the limits to 2048 and still got the error. And it's not easy to change the limit to be more than 2048. Thank you for any suggestions on this. 

YY

**Comment by davidemms** [comment]
Hi YY

I'm afraid OrthoFinder will need to open larger numbers of files as the number of species is increased. The performance implications of changing this would be substantial and would affect a very large number of people. Is it a question of permissions on your machine? Can your system administrators help you?

All the best
David

**Comment by scubapenn** [comment]
Hi David
I wonder do you think orthofinder could work on 1000 species. When I try 30 I get a too many files error. Any suggestions for doing 1000 species? I want copy number distribution among a phyla 
Thanks
Kevin

**Comment by davidemms** [comment]
Hi Kevin

The too many files error can be resolved by increasing the maximum number for your system as described above. 

I have run a complete analysis on 1300 bacteria but it required over 512GB of RAM. If you just want copy number then you only need to run the first part of the OrthoFinder analysis up to the orthogroups stage, you can request this with the '-og' option. This will make things easier. The main thing to keep in mind is that time and RAM requirements will scale quadratically with the number of genes (i.e. genes per species X number of species) so a bit of experimentation will start to give you an idea as to whether you have sufficient computation resources for 1000 species.

All the best
David
