### ISSUE TITLE
RuntimeWarnings when writing orthologous groups to files

### ISSUE THREAD

**Issue by shelbyLanda** [davidemms/OrthoFinder#335]
Hi David--

After following your suggestions for issues [#318](https://github.com/davidemms/OrthoFinder/issues/318) and [#329](https://github.com/davidemms/OrthoFinder/issues/329) I am encountering these runtime warnings when OrthoFinder writes orthogroups to file.

`Users/shelby/miniconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.`
and
`Users/shelbylanda/miniconda3/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars`

The Orthogroups.txt file looks complete, but nothing aside from the first column of headers has been written to the .tsv files.

Are these issues related to the recent fix in the parallel_task_manager.py file?

**Comment by shelbyLanda** [comment]
Here is the full message plus the traceback: 

```
Writing orthogroups to file
---------------------------
/Users/shelbylanda/miniconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/Users/shelbylanda/miniconda3/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
    main(args)
  File "/Users/shelbylanda/OrthoFinder-master/scripts_of/__main__.py", line 1678, in main
    DoOrthogroups(options, speciesInfoObj, seqsInfo)    
  File "/Users/shelbylanda/OrthoFinder-master/scripts_of/__main__.py", line 1353, in DoOrthogroups
    Stats(ogs, speciesNamesDict, speciesInfoObj.speciesToUse, files.FileHandler.iResultsVersion)
  File "/Users/shelbylanda/OrthoFinder-master/scripts_of/__main__.py", line 731, in Stats
    j, _ = next((i, x) for i, x in enumerate(L) if x > nAssigned/2)
```

**Comment by davidemms** [comment]
Hi

My first guess is that this could be caused by having a limited number of genes. Have you provided the full set of protein coding genes for each species? 

All the best
David

**Comment by shelbyLanda** [comment]
I see. I am just attempting to test whether I have installed everything correctly, so I have been using the ExampleData provided in the source material which I assumed would have no issues.

**Comment by davidemms** [comment]
In that case you shouldn't be seeing this warning I don't think. Did you also get an error? Would you be able to post the full output, it looks like something has gone wrong with installing something.

All the best
David

**Comment by shelbyLanda** [comment]
Oh, I completely missed the initial errors. 

Running with diamond (installed with conda), I receive the standard error code: -4 error mentioned in one of the issues in my first question. 

```
ERROR: external program called by OrthoFinder returned an error code: -4

Command: diamond blastp -d /Users/shelbylanda/OrthoFinder-master/ExampleDataset/OrthoFinder/Results_Jan28_3/WorkingDirectory/diamondDBSpecies3 -q /Users/shelbylanda/OrthoFinder-master/ExampleDataset/OrthoFinder/Results_Jan28_3/WorkingDirectory/Species0.fa -o /Users/shelbylanda/OrthoFinder-master/ExampleDataset/OrthoFinder/Results_Jan28_3/WorkingDirectory/Blast0_3.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
```
etc.

I have deleted the bin from scripts_of and still receive this output when running with blast.

```(base) ~/OrthoFinder-master shelby says: python orthofinder.py -S blast -f ExampleDataset/

OrthoFinder version 2.3.9 Copyright (C) 2014 David Emms

2020-01-28 13:23:13 : Starting OrthoFinder
8 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "makeblastdb -help" - ok
Test can run "blastp -help" - ok
Test can run "mcl -h" - ok
Test can run "fastme -i /Users/shelbylanda/OrthoFinder-master/ExampleDataset/OrthoFinder/Results_Jan28_2/WorkingDirectory/SimpleTest.phy -o /Users/shelbylanda/OrthoFinder-master/ExampleDataset/OrthoFinder/Results_Jan28_2/WorkingDirectory/SimpleTest.tre" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2020-01-28 13:23:13 : Creating Blast database 1 of 4
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
    main(args)
  File "/Users/shelbylanda/OrthoFinder-master/scripts_of/__main__.py", line 1674, in main
    CreateSearchDatabases(speciesInfoObj, options, prog_caller)
  File "/Users/shelbylanda/OrthoFinder-master/scripts_of/__main__.py", line 1440, in CreateSearchDatabases
    RunBlastDBCommand(command) 
  File "/Users/shelbylanda/OrthoFinder-master/scripts_of/__main__.py", line 100, in RunBlastDBCommand
    n_stdout_lines = stdout.count("\n")
TypeError: argument should be integer or bytes-like object, not 'str'
```

**Comment by davidemms** [comment]
Hi

I've just submitted a fix that should resolve the blast issue, thanks for letting me know about this.

All the best
David

**Comment by shelbyLanda** [comment]
I appreciate the communication--thank you so much.

Cheers,
Shelby

**Comment by davidemms** [comment]
I think the diamond issue is the one being discussed here: https://github.com/bbuchfink/diamond/issues/303

I'm just trying to work out if there's anything I can do with respect to this while it is being resolved, but don't have a computer that exhibits this problem to be able to test out solutions. It sounds like version 9.24 of diamond may be free of the issue. Would you be able to try:

`conda install -c bioconda diamond=0.9.24-0`

and see if that works. It would be a great help as I think a number of people are suffering from this problem and so if this is a solution it would help out a number of people.

Many thanks
David

**Comment by shelbyLanda** [comment]
Happy to help -- I was able to complete the ExampleDataset analysis with the blast fix (after deleting scripts_of/bin).

Installing Diamond version 9.24 also worked. OrthoFinder ran using ExampleDataset with no errors.

Thank you again!
