### ISSUE TITLE
Not an issue, but it might be.

### ISSUE THREAD

**Issue by ddiazescandon** [davidemms/OrthoFinder#337]
The problem is this. I run Orthofinder, it ran properly and after 10 hours I got my results without a single problem. But, when I review each folder's results I just found 8 single-copy orthologs, but previously a similar set of proteomes in OrthoMCL found 321. 

I tried another data more dissimilar than the first one,  and the program found 71 single-copy orthologs, I was expecting less than the initial one in OrthoMCL, but the surprise was getting more than the single Class run, the last one include two different Phyla.

I will attach the logs if you need to later (I'm using a VM to run it without problems in Ubuntu 19.10 )

**Comment by davidemms** [comment]
Hi

One of the biggest differences between orthogroups from OrthoMCL versus those from OrthoFinder is that OrthoMCL can miss many genes from orthogroups that they should be in. See, for example, Figure 6 here: <https://genomebiology.biomedcentral.com/articles/10.1186/s13059-015-0721-2>. This can happy especially if gene duplication events have occurred. This might mean that OrthoMCL is mis-reporting the number of true single copy orthogroups. 

It does sound strange that you get more when you include more distantly related species, I would not expect this. Is it the same set of species with additional species added, or do the sets of input species differ in another way?

All the best
David

**Comment by ddiazescandon** [comment]
Hi David,

Well, there are two different sets, but related somehow. One is within Ascomycete and the other set which also includes Ascomycete  (same Clases but different species) are Ascomycetes and  Basidiomycetes, so they are more distantly related, and this one is recoverin 71 single-copy orthologs, and the single phylum is recovering only 8. I will try the same run including exactly the same species and I'll let you know what happens with the logs.

**Comment by davidemms** [comment]
Hi

Yes, I'd expect that it will vary between different species sets. I think that sets of one-to-one orthologs are actually a lot rarer than people previously realised due to the prior use of heuristic methods based on reciprocal best hits. OrthoFinder is showing that there are more duplications happening in these orthogroups that people had thought, and you can check the gene trees produced by OrthoFinder to confirm that these duplications are really within the orthogroups and are therefore true orthology relationships that are not one-to-one.

All the best
David

**Comment by timregan** [comment]
Hi,
I have a related possible issue. After running Orthofinder on 22 Mollusc species, everything seemed fine and as expected. Except that the Single-Copy Orthologs file is empty. 
I find this quite surprising. Is it possible that this is correct or is it more likely that an error has occurred somewhere? Can attach logs etc. if useful.
Many thanks,
Tim

**Comment by davidemms** [comment]
Hi Tim

I think it's quite possible. The first file I generally check is: **Comparative_Genomics_Statistics/Statistics_PerSpecies.tsv**
I would check that most of the genes from each of your species have been assigned to orthgroups (say >75-80%). If something had gone wrong, you'd see it here.

You can also look at the file:
**Orthogroups/Orthogroups.GeneCount.tsv** to see how genes are distrubted across the orthogroups in terms of copy number. If you are familiar with something like Excel or Python you can analyse, for example, what proportion of your orthogroups are single copy in 50% of your species, or all but one of your species etc. 

There a guided tour of the results files here:
https://davidemms.github.io/orthofinder_tutorials/exploring-orthofinders-results.html

All the best
David

**Comment by ddiazescandon** [comment]
I change the groups and I was able to retrieve 288 single-copy orthologs, but I was wondering how Orthofinder deal with protein ambiguities such as  B, J and Z, I think this was the initial problem and some weird proteomes containing * (stops). Also, this is an off-topic question but how STAG works ( I already read the paper), which file uses, It doesn't seem to be using the single-copy orthologs alone, it seems to be using a 1000+ orthogroups, but which ones? I made a tree from and msa from the 288 orthologs, and the tree was completely different from the species tree, and now I'm running single trees to compile a species tree with astral.

**Comment by davidemms** [comment]
Hi

OrthoFinder doesn't make any decisions itself about protein ambiguities, it will be decided by the local alignment tool you select e.g. DIAMOND/BLAST. Also the MSA and tree inference tools used if you use the "-M msa" option. 

For STAG, there is a separate paper which explains how that works: https://www.biorxiv.org/content/10.1101/267914v1. Briefly, it uses the orthogroups with all species present, regardless of copy number.

All the best
David

**Comment by ddiazescandon** [comment]
Yes, I read the paper (I still don't fully understand support values), so it uses more than just the single-copy orthologs. This question is because I did an MSA file with all the single copy Orthologs and the tree was different. Will the MSA option will retrieve an MSA file with the 1000+ orthogroups used or just the single-copy orthologs?  

Also, I got these two different results one from the STAG run with +1000 gene trees, and the one using an MSA only using single-copy orthologs +288 (mafft, trimal, raxml). Which one would you trust, both trees contain 52 taxa and only three taxa are moving around, and none of them seems to be taxonomically coherent, and MSA support values are clearly biased (>95) by the alignment size (200k), and STAG support values are bellow 0.3  (even bellow 0.1).

**Comment by davidemms** [comment]
The MSA option will select sets of genes that are single-copy in their species, there are more details here: https://github.com/davidemms/OrthoFinder/issues/338#issuecomment-582943545. This will be fewer than the number used by STAG. 

You'll have to make your own judgements on how much you trust either of the trees. The support value used for STAG is different from the boostrap method, it is more stringent and will consistently produce lower values. It is the number of input gene trees supporting each bipartition in the consensus tree. I think STAG support values can be compared within and across datasets, but I have no method for comparing between bootstrap and STAG support values.

All the best
David
