### ISSUE TITLE
Unknown error 

### ISSUE THREAD

**Issue by erin-baggs** [davidemms/OrthoFinder#339]
Hi, 

If possible please could you help me, I have attempted to run orthofinder (using docker) twice on the same dataset. It has repeatedly failed and I am not sure why. The last error message was 'ERROR: An error occurred, please review previous error messages for more information.' but there was no clear error prior. Do you know what may have caused this? 
I am attaching the standard output from the run. 

Thank you
[Orthofinder_std_out.txt](https://github.com/davidemms/OrthoFinder/files/4149317/Orthofinder_std_out.txt)

Erin

**Comment by davidemms** [comment]
Hi Erin

Were stdout and stderr being directed to different files? OrthoFinder will write (at least some) errors to stderr. 

My best recommendation though would be to use a more up-to-date version of OrthoFinder. Version 1.1.8 is over 2.5 years old. There have been a number of bug fixes and crucially, a far more accurate method for ortholog inference is now being used. What operating system are you using? There's an up-to-date docker file here that I think you should be able to use:
https://github.com/MrTomRod/Orthofinder-Dockerfile

I wasn't aware that there was also an old, non-updated one out there. I will see what I can do about that.

Thanks
David

**Comment by erin-baggs** [comment]
Hi David, 

Thank you this is very helpful I will download the new docker file. I had been using this version in case that helps (https://hub.docker.com/r/cmonjeau/orthofinder/). 

Thanks, 
Erin

**Comment by davidemms** [comment]
Hi Erin

This prompted me to create an official docker file that I will try and keep up to date, you can find it here:

**davidemms/orthofinder:** https://hub.docker.com/repository/docker/davidemms/orthofinder/>

All the best
David
