### ISSUE TITLE
particular peptides not being assigned to orthogroups despite presence in all species

### ISSUE THREAD

**Issue by desmondramirez** [davidemms/OrthoFinder#340]
Hi David,

I'm having an unexpected issue with orthofinder. I'm working with brain transcriptomes from 8 species and want be sure that neuropeptides are included. However, despite the fact that I can recover particular neuropeptides by blasting each transcriptome, these peptides end up in the unassigned genes category and not assigned to a shared orthogroup.

I have had a similar problem using diamond in the past for one of the neuropeptides, which was resolved with turning off masking. I'm currently running diamond blasts with the '--masking 0' flag included, and then I'll ask orthofinder to pick up the analysis from there. I'll let you know what happens.

Thanks,
Des

**Comment by davidemms** [comment]
Hi Des

You can edit the command that OrthoFinder uses to run diamond in the `config.json` file. 

That's interesting to know about the neuropeptides, what is it about the sequence that is affected by the masking. Can you point me in the direction of an example gene, I'm curious to know.

Thanks
David

**Comment by desmondramirez** [comment]
Hi David,

I've attached a file with the sequences that keep falling out. I wonder if it's something because of repeats within the sequence-- for example, FMRFamide has many repeats of 'FMRF'. They also tend to be short.
[unassigned_neuropeptides.txt](https://github.com/davidemms/OrthoFinder/files/4149759/unassigned_neuropeptides.txt)



Thanks for the tip about editing the config.json file-- I couldn't figure out where to make the change within orthofinder.

**Comment by desmondramirez** [comment]
Hi again,

Despite changing the diamond call to get rid of any masking, the same list of neuropeptides is still stuck in the unassigned genes file. I can blast and manually assign/create orthogroups for these genes as a workaround for now, but it makes me wonder what else might be left out that I'm not looking for specifically. Plus, I won't have all the other perks of orthofinder, which is too bad!

Des

**Comment by davidemms** [comment]
Hi Des

One thing to check is the diamond/blast results files produced by OrthoFinder. You'll have to look in the SequencesIDs.txt file to see the IDs assigned to your genes of interest. If diamond is not reporting good hits for these sequences then there is nothing OrthoFinder can really do, if there are good hits then there might be some improvements I can make, but it's hard to think of what exactly, OrthoFinder has to trust the local alignment results it gets.

All the best
David

**Comment by desmondramirez** [comment]
Hi David,

It turned out that I changed the wrong config.json file (I'm still having trouble using the conda install on ubuntu and mac but am able to run the github version, but I changed the conda version).

Adding the '--masking 0' flag matched many more of the sequences than previously (45 vs 13), and the unmatched ones are for the most part ones that are lineage specific and would not be expected in my transcriptomes.

So all is well and Orthofinder continues to be great.

Thanks for you help,
Des

**Comment by davidemms** [comment]
Thanks great to hear, thanks for letting me know.

By the way, I've been working on the conda recipe for OrthoFinder today and am waiting for the changes to be accepted. I'll let you know when it's up, if you still have problems with it then please let me know.

Thanks
David
