### ISSUE TITLE
orthoFinder -M msa -fg PREVIOUS_RESULTS_DIRECTORY;construct species tree

### ISSUE THREAD

**Issue by LiuKe98** [davidemms/OrthoFinder#342]
Dear David,
I run the command "-M msa -fg PREVIOUS_RESULTS_DIRECTORY" using orthofinder version 2.2.7. And I got the message:
Using 456 orthogroups with minimum of 56.2% of species having single-copy genes in any
orthogroup.
In addition, there are many files such as SpeciesTree_rooted.txt and SpeciesTreeAlignment.fa generated by orthoFinder,but no Orthogroups_for_concatenated_alignment.txt. Is SpeciesTreeAlignment.fa a concatenated alignment file for single-copy genes from 456 orthogroups selected by orthofinder? Can I run RAxML using the file SpeciesTreeAlignment.fa to construct an accurate species tree?
Thanks in advance

**Comment by davidemms** [comment]
Hi

It should be here: Species_Tree/Orthogroups_for_concatenated_alignment.txt

If it's not there they you probably need to update to the latest version, this file was introduced sometime after the "-M msa" workflow was first implemented.

All the best
David
