### ISSUE TITLE
OrthoFinder with transcriptomes

### ISSUE THREAD

**Issue by Luca-Marisaldi** [davidemms/OrthoFinder#343]
Hello!
I am wondering how to interpret the output of OrthoFinder applied on transcriptomes rather than genomes. Specifically, the concept of species-specific orthogroups in this case. If a transcript is expressed and present in several transcriptomes, then the relative orthologues should be identified right? But, what if this doesn't happen? The meaning would be that the similarity among transcripts is not high enough to justify the inclusion in the relative orthogroup?

**Comment by davidemms** [comment]
Hi 

Yes, if the transcript is expressed and it's orthologues are also expressed and in the transcriptome of the input species then the orthogroup & orthologues should be identified. If they are orthologues then OrthoFinder doesn't need them to meet any pre-defined similarity threshold. 

If orthologues haven't been identified but you think they should then the best thing to do is to try a tree. Identify one of the transcripts and do a diamond (or blast) search against the other species to identify the homologous sequences, infer a multiple sequence alignment for all these sequences (including your query sequence) and do a tree and once you've rooted it correctly see if they are orthologues.

This is more or less what OrthoFinder tries to do, but it can occasionally miss something. A manual check like this is the best way to confirm if you agree with the results or not.

All the best
David
