### ISSUE TITLE
OrthoFinder2 with diamond more sensitive

### ISSUE THREAD

**Issue by jolienvanhooff** [davidemms/OrthoFinder#344]
In order to increase sensitivity, I would like use OrthoFinder with diamond in the **--more-sensitive** mode. Is that possible in the current version? It does not seem to be an option, but the orthology benchmarking service seems to suggest that it was, [here](https://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=ShowProject&p1=MzenEWTFzBEJoPQ). 

Is it correct that the **fast** mode of diamond is the default used by OrthoFinder?

If so, I could solve it by first running diamond myself and starting OrthoFinder using its result as input with the '-b' option.

Thanks in advance!

**Comment by davidemms** [comment]
Hi

OrthoFinder uses the "--more-sensitive" mode already, I found this gave the best results and with a reasonable runtime. You can see the options OrthoFinder passes to diamond, and change them if you like, in the config.json file.

All the best
David

**Comment by jolienvanhooff** [comment]
Hi David, 

Great, I just saw it indeed! Thanks for your quick reply. 

Jolien
