### ISSUE TITLE
scipy.optimize

### ISSUE THREAD

**Issue by akita4567** [davidemms/OrthoFinder#347]
I am trying to install OrthoFinder using miniconda2 on Mac OSX 10.15.3. When I run "orthofinder -h" to confirm installation, an error message comes out.
> orthofinder -h
  File "/Users/akita4567/miniconda2/bin/orthofinder", line 3, in <module>
    from scripts_of.__main__ import main
  File "/Users/akita4567/miniconda2/bin/scripts_of/__main__.py", line 42, in <module>
    from scipy.optimize import curve_fit            # install
ModuleNotFoundError: No module named 'scipy'

However, python 2.7 can open "scipy.optimize" and there was no error message.
How could you teach me a solution.

**Comment by davidemms** [comment]
Hi

I'm not entirely sure what would have caused this, it would need so interactive trial and error. to investigate The message is indicating that the version of python used was not able to find the scipy library. Perhaps it's a python 2 versus 3 problem? You could investigate this by:
```
which orthofinder
```
This will give you the full path to the orthofinder script. You can then try calling it with both python 2 and python 3 and see what happens. It may be that one of these works but the other doesn't:
```
python `which orthofinder`
python3 `which orthofinder`
```

All the best
David

**Comment by akita4567** [comment]
Hi

Thank you for giving me clue to solve this problem.

When I run 
>python `which orthofinder`
OrthoFinder version 2.3.11 Copyright (C) 2014 David Emms

SIMPLE USAGE:
Run full OrthoFinder analysis on FASTA format proteomes in <dir>
  orthofinder [options] -f <dir>

Add new species in <dir1> to previous run in <dir2> and run new analysis
  orthofinder [options] -f <dir1> -b <dir2>

OPTIONS:
 -t <int>          Number of parallel sequence search threads [Default = 4]
 -a <int>          Number of parallel analysis threads [Default = 1]
 -M <txt>          Method for gene tree inference. Options 'dendroblast' & 'msa'
                   [Default = dendroblast]
 -S <txt>          Sequence search program [Default = diamond]
                   Options: blast, mmseqs, blast_gz, diamond
 -A <txt>          MSA program, requires '-M msa' [Default = mafft]
                   Options: muscle, mafft
 -T <txt>          Tree inference method, requires '-M msa' [Default = fasttree]
                   Options: iqtree, raxml-ng, fasttree, raxml
 -s <file>         User-specified rooted species tree
 -I <int>          MCL inflation parameter [Default = 1.5]
 -x <file>         Info for outputting results in OrthoXML format
 -p <dir>          Write the temporary pickle files to <dir>
 -1                Only perform one-way sequence search 
 -X                Don't add species names to sequence IDs
 -n <txt>          Name to append to the results directory
 -o <txt>          Non-default results directory
 -h                Print this help text

WORKFLOW STOPPING OPTIONS:
 -op               Stop after preparing input files for BLAST
 -og               Stop after inferring orthogroups
 -os               Stop after writing sequence files for orthogroups
                   (requires '-M msa')
 -oa               Stop after inferring alignments for orthogroups
                   (requires '-M msa')
 -ot               Stop after inferring gene trees for orthogroups 

WORKFLOW RESTART COMMANDS:
 -b  <dir>         Start OrthoFinder from pre-computed BLAST results in <dir>
 -fg <dir>         Start OrthoFinder from pre-computed orthogroups in <dir>
 -ft <dir>         Start OrthoFinder from pre-computed gene trees in <dir>

LICENSE:
 Distributed under the GNU General Public License (GPLv3). See License.md

CITATION:
 When publishing work that uses OrthoFinder please cite:
 Emms D.M. & Kelly S. (2019), Genome Biology 20:238

 If you use the species tree in your work then please also cite:
 Emms D.M. & Kelly S. (2017), MBE 34(12): 3267-3278
 Emms D.M. & Kelly S. (2018), bioRxiv https://doi.org/10.1101/267914

While, as for, 
>python3 `which orthofinder`
Traceback (most recent call last):
  File "/Users/akita4567/miniconda2/bin/orthofinder", line 3, in <module>
    from scripts_of.__main__ import main
  File "/Users/akita4567/miniconda2/bin/scripts_of/__main__.py", line 42, in <module>
    from scipy.optimize import curve_fit            # install
ModuleNotFoundError: No module named 'scipy'

In the python3 folder, there was no scipy program. Thus, I re-install python3.7 using miniconda. Finally, OrthoFinder worked. 

Many Thanks
akita
