### ISSUE TITLE
dlcpar installation problems

### ISSUE THREAD

**Issue by sujaikumar** [davidemms/OrthoFinder#35]
Hi David (great to see you at UK GS2016!)

When installing dlcpar for the new functionalities, I encountered two problems:

1. python setup.py install in the dlcpar folder gave an error that it could not find dlcpar/deps/rasmus/ply. I got around that by running pip install ply and changing setup.py to import ply rather than requiring the package dlcpar.deps.rasmus.ply. The install ran fine after that, but we may not have done this the right way. 

    Can you tell us how you installed dlcpar?

2. After doing the above, on running the program (the script/libs are all in the path etc, I checked), I get this error:

```
dlcpar_search 
Traceback (most recent call last):
  File "/exports/virt_env/python/orthofinder/bin/dlcpar_search", line 204, in <module>
    sys.exit(main())
  File "/exports/virt_env/python/orthofinder/bin/dlcpar_search", line 127, in main
    options, treefiles = parse_args()
  File "/exports/virt_env/python/orthofinder/bin/dlcpar_search", line 46, in parse_args
    common.add_common_options(grp_io,
AttributeError: 'module' object has no attribute 'add_common_options'
```

And on checking the code, add_common_options is not a function in the module (It was removed a few versions ago it seems).

Could you confirm which version of dlcpar you are using?

Thanks!

**Comment by davidemms** [comment]
Hi Sujai

Great to meet you at the Genome Science conference too! 

The version of dlcpar I'm using is 0.9.1.

I downloaded it from here: http://compbio.mit.edu/dlcpar/ and the link there claimed that it was the latest version. I then ran "python setup install". What version of dlcpar were you using when you tried this approach? Does the 0.9.1 version work for you?

Thanks
David

**Comment by sujaikumar** [comment]
Ah, that might be the problem. I used the most recent version from github
https://github.com/wutron/dlcpar 0.9.7

But will try this - might solve the problem.

Yep, runs fine now. Maybe you could edit the README to specify that people
should download 0.9.1 from
http://compbio.mit.edu/dlcpar/pub/sw/dlcpar-0.9.1.tar.gz ?

Thanks very much!

Cheers,

Sujai

**Comment by davidemms** [comment]
Thanks, I'll see if I can work out what caused the problem when using 0.9.7 and see if I can resolve that and if that's not possible I'll specify in the README the version requirement. 

All the best
David
