### ISSUE TITLE
Exception RuntimeError: RuntimeError('cannot join current thread',) in <Finalize object, dead> ignored

### ISSUE THREAD

**Issue by Marenno** [davidemms/OrthoFinder#350]
Hi,
i'm currently trying to predict orthogroups of a transcriptome dataset. 
This is the command i entered: `OrthoFinder/orthofinder -f test`
And this is where the error message occurred. However, the program did not quit but stagnated after the runtime error. After aborting the command the "traceback of the most recent call last" appears.

Running OrthoFinder algorithm
-----------------------------
2020-02-24 14:18:49 : Initial processing of each species
2020-02-24 14:19:17 : Initial processing of species 0 complete
2020-02-24 14:19:45 : Initial processing of species 1 complete
2020-02-24 14:19:57 : Connected putative homologues
2020-02-24 14:20:08 : Written final scores for species 0 to graph file
2020-02-24 14:20:21 : Written final scores for species 1 to graph file
Exception RuntimeError: RuntimeError('cannot join current thread',) in <Finalize object, dead> ignored
^CProcess Process-1:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
  File "multiprocessing/process.py", line 114, in run

[230319] Failed to execute script orthofinder
  File "scripts_of/parallel_task_manager.py", line 290, in _I_Spawn_Processes
KeyboardInterrupt

I read that this is an issue of python but since all dependencies are installed and loaded automatically i can not simply try it out with another version of python. 

Thank you in advance for your help.

**Comment by davidemms** [comment]
Hi 

Do you have the full output to the terminal, that may give some clues as to what happened. Also, how long was it after the RuntimeError that you hit ctrl+c? I've seen that message appear before and it is a false alarm, it doesn't indicate a problem. What happens if you leave it to run?

All the best
David

**Comment by Marenno** [comment]
Hi David,
thank you for the fast reply. I haven't been leaving it to run for too long (approx. 10 min.). I'm going to try letting it run now. In case it was a false alarm, i'm sorry for the inconvenience. I just thought it is a fatal error. Thanks for your help!

Kind regards
Maren

**Comment by davidemms** [comment]
Hi Maren

No problem, 10 minutes is probably enough given that I can see the previous set of steps only took about 1.5 mins. If you could paste the full output from this run then that might suggest where to start looking for problems.

All the best
David

**Comment by Marenno** [comment]
Hey David,
it's working now. It was really just me being impatient, thinking the error prevented any further processes. But that wasn't the case. Thank you so much!

Kind regards
Maren

**Comment by davidemms** [comment]
That's great, thanks for letting me know. I agree that the message is confusing, I discovered recently that it occurs on some systems and I've hopefully now eliminated it in the latest release (2.3.11) so it hopefully won't cause others problems in the future.

**Comment by haruosuz** [comment]
When I did "Run OrthoFinder on the Example Dataset” (https://davidemms.github.io/orthofinder_tutorials/downloading-and-checking-orthofinder.html) using `./orthofinder -f ExampleData/`, I got the following messages, as shown in attachment <log.orthofinder.2020-02-08.txt>.

```
2020-02-08 12:52:27 : Written final scores for species 3 to graph file
RuntimeError: RuntimeError('cannot join current thread',) in <Finalize object, dead> ignored
2020-02-08 12:52:28 : Ran MCL

--

Reconciling gene trees and species tree
---------------------------------------
Exception RuntimeError: RuntimeError('cannot join current thread',) in <Finalize object, dead> ignored
2020-02-08 12:52:37 : Done 0 of 325
```
[log.orthofinder.2020-02-08.txt](https://github.com/davidemms/OrthoFinder/files/4306339/log.orthofinder.2020-02-08.txt)

**Comment by davidemms** [comment]
Hi 

This should be fine. It's a false alarm which should now be eliminated in the latest release.

All the best
David
