### ISSUE TITLE
the generation and processing for SpeciesTreeAlignment.fa and Orthogroups_for_concatenated_alignment.txt

### ISSUE THREAD

**Issue by LiuKe98** [davidemms/OrthoFinder#352]
Dear David，
If I want to obtain a super alignment matrix by myself like the file SpeciesTreeAlignment.fa for these orthogroups from Orthogroups_for_concatenated_alignment.txt generated by OrthoFinder, should I extract all sequences and align them for each orthogroups and then trim these alignmnets and remove the multiple copy genes from these alignmnet files and then concatenate all processed alignment files into one super matrix? Or do I just need to extract only the genes from those species that are single-copy for alignment, trimming and concatenation thesa super matrix for phylogeny?
LiuKe

**Comment by davidemms** [comment]
Hi LiuKe

I think both are reasonable approaches. As I understand it, the only difference between the two approaches you're suggesting are whether you extract just the single-copy sequences before or after the alignment stage, is that right? The first one might be easier as you can just use the existing alignments from OrthoFinder, if you're doing it from the start then the second approach may be easier. I don't know if either would be more accurate than the other. OrthoFinder does the first approach: align sequences then extract just the single-copy ones.

All the best
David

**Comment by davidemms** [comment]
Note, do the trimming after you've removed the multi-copy sequences not before.
