### ISSUE TITLE
No support value in SpeciesTree_rooted.txt

### ISSUE THREAD

**Issue by haruosuz** [davidemms/OrthoFinder#355]
[faa.tar.gz](https://github.com/davidemms/OrthoFinder/files/4306378/faa.tar.gz)
Attached is a result of analyzing 8 IncP-1 plasmids using OrthoFinder version 2.3.10 by typing `orthofinder -f faa/`.

In this tutorial (https://davidemms.github.io/orthofinder_tutorials/exploring-orthofinders-results.html), it is stated that “Using one of these, open the file Species_Tree/SpeciesTree_rooted.txt. As this file has bootstrap values” and “With the default options, species tree inference is performed with STAG, which uses the proportion of species trees derived from single-locus gene trees supporting each bipartition as its measure of support. This is a more stringent measure than standard bootstrap support from a multiple sequence alignment.”
However, there is not any support value in the file **faa/OrthoFinder/Results_Mar08/Species_Tree/SpeciesTree_rooted.txt**, while there are node labels such as ‘N1’ in the file **faa/OrthoFinder/Results_Mar08/Species_Tree/SpeciesTree_rooted_node_labels.txt**.

**Comment by davidemms** [comment]
Hi 

OrthoFinder requires as input the complete set of protein coding genes from each species, without the proper input then it will be limited in what it can do. 

In this case it looks like OrthoFinder has used its fallback method to infer the species tree anyway, but this doesn't provide support values as there is not enough information. Providing the full information should resolve this. Alternatively, you could use the "-M msa" option which might be successful on your data. If so then you will get a MSA for your species tree, "MultipleSequenceAlignments/SpeciesTreeAlignment.fa" and you can run a bootstrap analysis on this to get support values.

All the best
David

**Comment by haruosuz** [comment]
Dear David:

Thank you for your advice. I used `orthofinder -f data/faa/ -M msa -A mafft -T fasttree`.

I wonder if the file **MultipleSequenceAlignments/SpeciesTreeAlignment.fa** is a concatenated sequence alignment of Single_Copy_Orthologue_Sequences, and if FastTree used this alignment_file as input?

Is there any way to log all commands executed (parameters used) in OrthoFinder? (e.g. `FastTree -gtr -nt alignment_file > tree_file`)

In the file **Species_Tree/SpeciesTree_rooted.txt**, all the internodes exhibited highest support values of 1. Are these local support values computed by FastTree with the Shimodaira-Hasegawa test? (http://www.microbesonline.org/fasttree/#Support)

Is there any documentation for the "fallback method to infer the species tree"?

**Comment by davidemms** [comment]
Hi

The MultipleSequenceAlignments/SpeciesTreeAlignment.fa is generated from the single-copy genes in the orthogroups that are single copy in at least p% of species. OrthoFinder prints the what percentage cut-off it has used to the terminal. E.g. for the Example Dataset it prints:

> Species tree: Using 246 orthogroups with minimum of 100.0% of species having single-copy genes in any orthogroup

The [STAG](https://www.biorxiv.org/content/10.1101/267914v1) paper describes the method for determining the percentage, p, for a given dataset for CMSA (concatenated MSA).

There isn't any functionality to print out the commands executed, but yes, the fasttree support values are from the Shimodaira-Hasegawa test. The command used is:
```FastTree INPUT > OUTPUT 2> /dev/null``` 
although you can define your own command in the config.json file. You can also use the SpeciesTreeAlignment.fa prepared by OrhtoFinder to run whatever tree inference method(s) you want on the file.

No, I haven't documented the fallback method, it allows OrthoFinder to complete the run when minimal data is supplied but I can't see any uses beyond that.

All the best
David

**Comment by davidemms** [comment]
Hi

I've written a description of the species tree inference methods on the README page: https://github.com/davidemms/OrthoFinder#species-tree-inference

All the best
David

**Comment by haruosuz** [comment]
Dear David: Thanks for updating the information.

I wonder if the unrooted species tree inferred by the fallback method was not correctly rooted using the STRIDE algoirithm (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5850722/) because "the number of well-supported gene duplication events mapped to each node in the species tree" (https://davidemms.github.io/orthofinder_tutorials/exploring-orthofinders-results.html) was 0 for all the nodes in the file **Gene_Duplication_Events/SpeciesTree_Gene_Duplications_0.5_Support.txt** (i.e. OrthoFinder did not detect any gene duplication event).

How did you know that "In this case it looks like OrthoFinder has used its fallback method to infer the species tree"?
"OrthoFinder prints the what percentage cut-off it has used to the terminal."
Is it possible for OrthoFinder to print it in the file **Log.txt**?

Is it possible to infer a tree for a nucleotide alignment instead of a protein alignment in OrthoFinder by editing the config.json file?

**Comment by davidemms** [comment]
Yes, if there are no duplication events because you've only provided incomplete data then the STRIDE algorithm will have no information to use to determine the correct root.

OrthoFinder will print a message in it's output if it uses the fallback method:, "Using fallback species tree inference method". 

There's no option to print the percentage cut-off to the Log.txt file at the moment. I would suggest saving the output that OrthoFinder produces. I can look at adding a feature to print this info to the Log.txt file but that would be a low priority at the moment. The intention of the Log.txt file is to track what analysis has been done so parts of it can be automatically re-run or extended by the user ("-b", "-fg", "-ft" options), it's not really there to save results.

All the best
David
