### ISSUE TITLE
Genome Limit

### ISSUE THREAD

**Issue by scubapenn** [davidemms/OrthoFinder#357]
Besides the number of files that open
I wonder do you think orthofinder could work on 1000 species. When I try 30 I get a too many files error. I am trying to estimate how many files would need to be open 1000 species? I want copy number distribution within a phyla
Thanks
Kevin

**Comment by davidemms** [comment]
Hi Kevin

The too many files error can be resolved by increasing the maximum number for your system as described in other issues. 

The number of open files is unlikely to be the constraining factor. A linux system can easily have millions of files open, instead RAM (and runtime) will be the biggest constraints. I have run a complete analysis on 1300 bacteria but it required over 512GB of RAM. If you just want copy number then you only need to run the first part of the OrthoFinder analysis up to the orthogroups stage, you can request this with the '-og' option. This will make things easier. The main thing to keep in mind is that time and RAM requirements will scale quadratically with the number of genes (i.e. genes per species X number of species). This means that an analysis of 10 vertebrates with 20,000 genes could require at least 4x4=16 times more resources than an analysis of 10 bacteria with 5,000 genes each. A bit of experimentation will start to give you an idea as to whether you have sufficient computation resources for 1000 species.

All the best
David

**Comment by scubapenn** [comment]
Orthofinder seems to run and make results but I get this error: any ide what it is and if my results are effected 

Exception RuntimeError: RuntimeError('cannot join current thread',) in <Finalize object, dead> ignored

**Comment by davidemms** [comment]
See https://github.com/davidemms/OrthoFinder/issues/350

All the best
David

**Comment by scubapenn** [comment]
Hi David
I finally fixed my max file size issue but now I am getting this error

"Inferring gene and species trees
--------------------------------


ERROR: external program called by OrthoFinder returned an error code: 1

Command: fastme -i /home/kpenn/Orthofinder.faa.dir/OrthoFinder/Results_Apr28/WorkingDirectory/OrthoFinder/Results_May02_3/WorkingDirectory/Distances_SpeciesTree
/OG0000000_tree_id.txt.dist.phylip -o /home/kpenn/Orthofinder.faa.dir/OrthoFinder/Results_Apr28/WorkingDirectory/OrthoFinder/Results_May02_3/WorkingDirectory/Sp
eciesTrees_ids/OG0000000_tree_id.txt.tre -w O -s -n

stdout
------


stderr
------

 . Error: Cannot open file 'OG0000000_tree_id.txt.d'"

**Comment by davidemms** [comment]
Hi Kevin

FastME is trying to write its output tree file to "/home/kpenn/Orthofinder.faa.dir/OrthoFinder/Results_Apr28/WorkingDirectory/OrthoFinder/Results_May02_3/WorkingDirectory/Sp
eciesTrees_ids/OG0000000_tree_id.txt.tre" and this is failing with the error message you posted. So for some reason the file system is not allowing you to open such a file to write to it. 

The first possible cause that comes to mind is that there is no space left on the disc, but there could be other causes.

All the best
David

**Comment by scubapenn** [comment]
It must have to do with the number of species (200) because I just tried the same run with 10 species and it completed. 

     On Wednesday, May 6, 2020, 04:46:22 AM EDT, David Emms <notifications@github.com> wrote:  
 
 


Hi Kevin

FastME is trying to write its output tree file to "/home/kpenn/Orthofinder.faa.dir/OrthoFinder/Results_Apr28/WorkingDirectory/OrthoFinder/Results_May02_3/WorkingDirectory/Sp
eciesTrees_ids/OG0000000_tree_id.txt.tre" and this is failing with the error message you posted. So for some reason the file system is not allowing you to open such a file to write to it.

The first possible cause that comes to mind is that there is no space left on the disc, but there could be other causes.

All the best
David
