### ISSUE TITLE
orthofinder output does not match

### ISSUE THREAD

**Issue by shree-thapa** [davidemms/OrthoFinder#358]
Hi All,

I am not able to understand the results of the orhofinder. Hope to get some assistance in this. Is it correct?

I run orthofinder v2.3.11. This is one output example.
My Orthogroups.txt 

![image](https://user-images.githubusercontent.com/24925652/76446856-e8282780-6384-11ea-8246-d847d365753a.png)
BLH-13_QIA72869.1 in the circled box under orthogroup OG0000109:, has no similarity with LB319 proteins.
However, when i blast BLH-13_QIA72869.1 with all the proteins of LB319 i get number of proteins with 100% hits.
![image](https://user-images.githubusercontent.com/24925652/76447057-405f2980-6385-11ea-9809-7a8df52a19e5.png)

What is the problem in here??

Thanks

**Comment by davidemms** [comment]
Hi

It may that you've misunderstood what an orthogroup is, this is explained here: <https://github.com/davidemms/OrthoFinder#orthogroups-orthologs--paralogs>

Alternatively, it may be that these genes do belong to the same orthogroup. To check this concatenate the OG 108 & 109 fasta files from "Orthogroup_Sequences/" and use them to infer a MSA and gene tree. Once these are rooted you can analyse the tree to determine if the genes should have been in the same orthogroup or not--OrthoFinder won't always get it right, but the presence of each of the genes in each of the species (I can't tell for certain from the screenshot) would suggest it could be correct here.

All the best 
David
