### ISSUE TITLE
OpenBLAS Warning

### ISSUE THREAD

**Issue by kirstengott** [davidemms/OrthoFinder#360]
Hello,

When I pulled the archive and unpacked it and tried to run the exampledata I get this error:
./orthofinder -f ExampleData/

OpenBLAS Warining : The number of CPU/Cores(96) is beyond the limit(64). Terminated.

Thanks,

Kirsten

**Comment by davidemms** [comment]
Hi Kirsten

There's a number of threads about this, for example see:
<https://github.com/davidemms/OrthoFinder/issues/356>

I'm looking into if there is anything I can do in OrthoFinder to prevent this but in the meantime the fix posted in the above thread solves the issue. If it's ok, I'll shut this issue and can respond to any further questions you have in that thread.

All the best
David

**Comment by kirstengott** [comment]
Hi David,

Go ahead and close it, sorry I didn't see that earlier thread and thanks
for forwarding it!

Kirsten
