### ISSUE TITLE
orthologous transcripts

### ISSUE THREAD

**Issue by EasyPiPi** [davidemms/OrthoFinder#364]
Hi,

I have read the manual and understand why OrthoFinder picks the longest transcripts for each gene and use them to find orthologous genes between species, mainly because of computational efficiency. 

But in my analysis, in addition to find the orthologous genes, I also wish to find the "best matched" transcripts between species. The reason is that, for example, there are 5 transcripts in species A (A1.1, A1.2,...A1.5), and 3 transcripts in species B (B1.1,B1.2,B1.3) for the orthologous gene 1. I would like to know the most abundant transcript A1.1 in species A and B1.1 in species B, are they "orthologous transcripts" (in other words, they are "the best" equivalent transcripts in both species)? Or maybe A1.1 matches B1.3 best so the most abundant isoform usage is changed between species? 

Any suggestions for using all protein coding transcripts for comparison in this way?

Many thanks,
Yixin

**Comment by davidemms** [comment]
Hi Yixin

That's an interesting question. OrthoFinder does not consider the problem of recovering a mapping between different transcript variants between species, although I find it intriguing! 

I would suggest that if you want to pursue this problem then using a multiple sequence alignment of the coding DNA sequences of the transcripts would be the best place to start. Then you would have to develop an algorithm for identifying which exons each transcript does or doesn't have, and work out from this information which transcripts you consider "best matched".

All the best
David

**Comment by EasyPiPi** [comment]
Thanks David!

Best,
Yixin
