### ISSUE TITLE
ERROR:external program called by OrthoFinder returned an error code: 1

### ISSUE THREAD

**Issue by depengl** [davidemms/OrthoFinder#365]
Hi,

I didn't find any information about this error. Can you please help me about it?
I am running orthofinder on a new computing system. It was working well before.

It's installed with conda, since when I tyied OrthoFinder.tar.gz and run "./OrthoFinder/orthofinder -h" it shows   "[7516] Error loading Python lib '/tmp/_MEIFah9jt/libpython2.7.so.1.0': dlopen: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/_MEIFah9jt/libpython2.7.so.1.0)"

Thank you !
Sincerely,
Depeng

OrthoFinder version 2.3.11 Copyright (C) 2014 David Emms

Running diamond all-versus-all
------------------------------
Using 24 thread(s)
2020-03-28 21:53:52 : This may take some time....

ERROR: external program called by OrthoFinder returned an error code: 1

Command: diamond blastp -d /home-b/depengli/orthofinder_workdir/Ostracods_aa/OrthoFinder/Results_Mar28/WorkingDirectory/diamondDBSpecies37 -q /home-b/depengli/orthofinder_workdir/Ostracods_aa/OrthoFinder/Results_Mar28/WorkingDirectory/Species19.fa -o /home-b/depengli/orthofinder_workdir/Ostracods_aa/OrthoFinder/Results_Mar28/WorkingDirectory/Blast19_37.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Remote I/O error\nError: Error opening temporary file /home-b/depengli/orthofinder_workdir/Ostracods_aa/OrthoFinder/Results_Mar28/WorkingDirectory/diamond-tmp-Velwfl\n'

ERROR: external program called by OrthoFinder returned an error code: 1

**Comment by davidemms** [comment]
Hi

Do you know what version of diamond you are using? It appears to be that this causing an issue.

Can you try calling the diamond command that it has printed and if you get an error then report it on the github page for diamond.

Many thanks
David

**Comment by depengl** [comment]
Hi  David,
I updated diamond to 9.24 version. It's OK now!
When updating I  found that If I install diamond latest version( 0.9.30) through conda, orthofinder will be degraded to 2.3.8. Just let you know that.

Thank you so much!
Depeng

**Comment by davidemms** [comment]
Hi Depeng

Thanks for letting me know. Do you know what version of DIAMOND you were using originally that caused the problem? It's helpful for me to keep track of these things.

All the best
David

**Comment by depengl** [comment]
Hi David,
I am sorry that I removed the log file. I didn't remember which version it was. But it's installed by conda when I install orthofinder through "conda install -c bioconda orthofinder"

Thanks,
Depeng

**Comment by XK4959** [comment]
Hello I also got the same error using this version：diamond version 2.0.8

The error is as follows：OrthoFinder version 2.5.2 Copyright (C) 2014 David Emms

2021-04-21 15:45:51 : Starting OrthoFinder 2.5.2
10 thread(s) for highly parallel tasks (BLAST searches etc.)
10 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /users/gaoxl/biye/pancore/data/pro-signalp/OrthoFinder/Results_Apr21/WorkingDirectory/SimpleTest.phy -o /users/gaoxl/biye/pancore/data/pro-signalp/OrthoFinder/Results_Apr21/WorkingDirectory/SimpleTest.tre" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2021-04-21 15:45:57 : Creating diamond database 1 of 176
2021-04-21 15:45:57 : Creating diamond database 2 of 176
2021-04-21 15:45:57 : Creating diamond database 3 of 176
2021-04-21 15:45:58 : Creating diamond database 4 of 176
2021-04-21 15:45:58 : Creating diamond database 5 of 176
2021-04-21 15:45:58 : Creating diamond database 6 of 176
2021-04-21 15:45:58 : Creating diamond database 7 of 176
2021-04-21 15:45:58 : Creating diamond database 8 of 176
2021-04-21 15:45:58 : Creating diamond database 9 of 176

ERROR: external program called by OrthoFinder returned an error code: 1

Command: diamond makedb --in /users/gaoxl/biye/pancore/data/pro-signalp/OrthoFinder/Results_Apr21/WorkingDirectory/Species8.fa -d /users/gaoxl/biye/pancore/data/pro-signalp/OrthoFinder/Results_Apr21/WorkingDirectory/diamondDBSpecies8

stdout
------
b''
stderr
------
b'diamond v2.0.8.146 (C) Max Planck Society for the Advancement of Science\nDocumentation, support and updates available at http://www.diamondsearch.org\n\n#CPU threads: 24\nScoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)\nDatabase input file: /users/gaoxl/biye/pancore/data/pro-signalp/OrthoFinder/Results_Apr21/WorkingDirectory/Species8.fa\nOpening the database file...  [0s]\nLoading sequences...  [0.002s]\nError: Error reading input stream at line 13325: Invalid character (.) in sequence\n'
ERROR: diamond makedb failed
ERROR: An error occurred, ***please review the error messages*** they may contain useful information about the problem.

**Comment by MR-D-CJ** [comment]
> Hi Depeng
> 
> Thanks for letting me know. Do you know what version of DIAMOND you were using originally that caused the problem? It's helpful for me to keep track of these things.
> 
> All the best David

Hi,I also have same ERROR(ERROR: external program called by OrthoFinder returned an error code: 1)
I install orthofinder through conda. My operating system version is CentOS Linux release 7.3.1611.
The version of orthofinder is 2.5.4.
The version of diamond is 2.0.15(latest).
I reinstall Diamond(0.9.24) according to the above mentioned. It's worked now.
Hoping the above information can help you
