### ISSUE TITLE
Splitting orthogroups: Separating ancient paralogs from actual orthologs

### ISSUE THREAD

**Issue by ViriatoII** [davidemms/OrthoFinder#367]
I am reading this interesting yet cryptic [paper](https://www.nature.com/articles/s41477-019-0486-9) based on Orthofinder. They end up using Phylogeny for inter-species association Mapping. But before that they did something I cannot get my head around. 

Can you help me understand the need for this and potentially how to do it?  I am not sure how much this issue overlaps with [this one](https://github.com/davidemms/OrthoFinder/issues/327), I'm a bit of a newbie on the topic.

Here's a quote:

> Based on the OGs calculated in a set of eight core species, we defined 18,695 OGs that remained stable after adding all remaining species. To split OGs with gene duplications which predated the divergence of the Brassicaceae or happened at the onset of the evolution of this family, we calculated gene trees for each OG and separated those subtrees that broadly recapitulated the species phylogeny into distinct OGs. This increased the number of OGs to 22,260 (now referred to as gene families).

Kind regards,
Ricardo 

(P.S: Love Orthofinder!)

**Comment by davidemms** [comment]
Hi Ricardo

Thanks, it's good to hear from people who who are finding OrthoFinder useful.

I've actually been working on an some new functionality recently that I think addresses this. It takes the algorithm OrthoFinder uses to infer orthologs from rooted gene trees (described in the latest paper) and applies in back to the original orthogroup problem. This means that any orthogroups that have been mistakenly merged together in the clustering phase should now be correctly split apart once OrthoFinder analyses the gene trees and identifies ancient duplications. A new directory within the results directory is generated:
```
Phylogenetic_Hierarchical_Orthogroups
├── N0.tsv
├── N10.tsv
├── N1.tsv
├── N2.tsv
├── N3.tsv
├── N4.tsv
├── N5.tsv
├── N6.tsv
├── N7.tsv
├── N8.tsv
└── N9.tsv
```
The N0.tsv file contains the newly defined orthogroups at the root of the species tree, determined by examining the gene trees. This is the file you'll need. The other files are the orthogroup at each other hierarchical level within the species tree, given by the node name. You can see the node names in the file, "Species_Tree/SpeciesTree_rooted_node_labels.txt".

I think this functionality is ready to release now so I've pushed it to github. To use it you'll need to download the source code (green button on the main page: https://github.com/davidemms/OrthoFinder/) and run that version.

You can then reanalyse you're previous results using:
```python orthofinder.py -ft PREVIOUS_RESULTS_DIRECTORY```

Any new analysis will do the phylogenetic orthogroup analysis automatically and generate the Phylogenetic_Hierarchical_Orthogroups directory.

Let me know how you get on.

All the best
David

**Comment by ViriatoII** [comment]
That's just perfect, thanks! I'll install it and use it as soon as my cluster is up again (something crashed and the IT guys are half quarentined).

**Comment by davidemms** [comment]
The basic idea is that if a node in the gene tree is identified as a gene duplication event and that node is mapped to the root node of the species tree then the two descendent clades are separate orthogroups. It becomes a bit more involved working out all the other orthogroups at the different hierarchical levels in the species tree (N1, N2 etc) because the gene tree branching order won't always exactly match the species tree branching order, but the core idea remains the same.

All the best
David
