### ISSUE TITLE
Comparatively higher number of orthogroups shared between distant species 

### ISSUE THREAD

**Issue by Barsha-P** [davidemms/OrthoFinder#368]
Hi there, 

I am running orthofinder to study host associated species. For species A, B, C and D; B and C is closer to A as compared to D in phylogenetic analysis. But the number of orthogroups shared between A and D is higher (125) than A  and B (42) or A and C (48). Could you please let me know if this is possible or am I doing something wrong with my analysis. I used Orthogroups.GeneCount.csv to count shared orthogroups. I have attached a picture of the phylogenetic tree and Venn diagram. 
![Orthofinder](https://user-images.githubusercontent.com/56545035/78453116-10304f80-76d3-11ea-8051-1b072c921069.png)

`orthofinder -f <filename> -M msa -A mafft -T fasttree -S diamond -t 16`

Thanks, 
Barsha

**Comment by davidemms** [comment]
Hi Barsha

Yes this is possible since you can have different patterns of gene loss in species, independent of how closely related they are. 

However, in this case it looks like you are misinterpreting your Venn diagram. A and B share many more orthogroups than 42.

All the best
David

**Comment by Barsha-P** [comment]
Thanks David. When I said shared, it is the number of orthogroups only shared between the two species.

**Comment by davidemms** [comment]
HI Barsha

In that case I don't think it's that unexpected. As a thought experiment imagine going to the limit of B & C being closer and closer together until they're basically the same species. Then A & B would have no uniquely shared orthogroups (every orthogroup B had C would also have). Whereas A & D could still have some uniquely shared orthogroups.

All the best
David

**Comment by Barsha-P** [comment]
Hi David, 
This is interesting. In this study, B and C are actually two forms of the same species but are thought to be genetically isolated. Species A is also the same species but collected from alternative host although based on the phylogeny study, I am thinking that A is a different species. I was thinking of merging B and C together to reanalyse A, B+C and D to see if A share more orthogroups with B+C or with D. Do you think this is a good approach? 

Thanks, 
Barsha

**Comment by davidemms** [comment]
Hi Barsha

I'm not sure either way. You're numbers already appear to show that--more shared with (B or C) to the exclusion of D versus the opposite. But it'd up to you to decide if using two strains for B/C versus one for D biases it for your research or gives you the information you require.

All the best
David

**Comment by Barsha-P** [comment]
Thanks David.

**Comment by arslan9732** [comment]
@Barsha-P Sorry it is not relevant to your question. Could you please let me know how did you create this venn diagram from Orthofinder results?

**Comment by arslan9732** [comment]
I know orthovenn2 creates Venn diagram. I thought you used Orthofinder output to create the Venn diagram
