### ISSUE TITLE
Extracting core gene trees for each taxa

### ISSUE THREAD

**Issue by noahaus** [davidemms/OrthoFinder#370]
Greetings,

My question is in regards to creating gene trees of core genes, those genes when comparing taxa are included in all taxa. with the default behavior, the gene trees that are created in orthofinder vary in size even though I gave 20 taxa as input. I was wondering if the developers have any advice on getting only the gene trees that have 20 tips for 20 taxa (a one to one mapping). 

Any assistance would be greatly appreciated.

Best,
Noah Legall

**Comment by davidemms** [comment]
Hi Noah

There is a file called Orthogroups/Orthogroups_SingleCopyOrthologues.txt that lists these orthogroups. 

All the best
David
