### ISSUE TITLE
The results of 2.2.7 and 2.3.11 are different.

### ISSUE THREAD

**Issue by bioinformaticspcj** [davidemms/OrthoFinder#371]
Hi ,
I used 2.2.7 version and 2.3.11 version OrthoFinders to analysis the same protein sets but btained different results:
For 2.2.7 version, I got 1980 singlecopy genes but for 2.3.11 version, the number is 2045.

I do not know why.

I am looking forward to your timely reply.

**Comment by davidemms** [comment]
Hi

In 2.2.7 the default was to use BLAST, after that DIAMOND became the default for searching for homologs. I thought that change was listed on the Releases page but it isn't, I'll update it. The results from these will have a knock-on effect on the OrthoFinder results. You can get the previous results by selecting BLAST with the latest version. 

All the best
David

**Comment by bioinformaticspcj** [comment]
Thanks a lot
