### ISSUE TITLE
annotating orthogroups

### ISSUE THREAD

**Issue by ersgupta** [davidemms/OrthoFinder#373]
Hi,

I am wondering what is the best way to annotate the orthogroups (description, GO, etc..) to perform enrichment analysis of orthogroups? One would expect that genes in an orthogroup have similar annotation, but thats not always the case. One way I could think of is to have a prioritisation order of species, i.e. Species1 > Species2... etc. So if a orthogroup contains genes from multiple species then use this order to assign annotation. Any suggestions would be great.

Thanks
Saurabh

**Comment by davidemms** [comment]
Hi Saurabh

In the cases when I've done this I've generally only had one model species that is well annotated and so I have had to use the annotations of that one species as the best estimate for the orthogroup. Having a prioritisation if you have annotations from multiple species seems reasonable.

All the best
David

**Comment by ersgupta** [comment]
Thanks David. I agree. I was also thinking another easier and straightforward way would be have a representative of the orthogroup, for eg, the longest protein sequence from the orthogroup. Do you think this could have any issues? If this makes sense, then maybe in later versions of orthofinder it could be worth to add another file in orthofinder output which mentions the "representative" sequence of the orthogroup which would be easier then to annotate the group.

**Comment by davidemms** [comment]
Hi Saurabh

I think that sounds a good potential way of analysing the OrthoFinder results. In terms of if this could have any issues, it may be that you find that the longest sequence isn't the most 'representative', in the way you chose to define it. 

In terms of OrthoFinder itself, the guiding idea is to do everything in terms of well-defined phylogenetic concepts. This ensures it has a wide range of applicability to many people. I think at the moment the most representative sequence is too loosely defined for inclusion, but it is a potential idea I've considered. I think there are lots of concepts like this being developed by users in analysing their research question though, and I think they are totally legitimate approaches.  

All the best
David

**Comment by ersgupta** [comment]
Thanks David. This helps. I know it gets difficult to define "representative". Would be great if there will be a way to somehow implement this in orthofinder itself in some future releases. Closing the ticket.
