### ISSUE TITLE
The alignment used to estimate the species tree

### ISSUE THREAD

**Issue by wangxuann1995** [davidemms/OrthoFinder#381]
Hi David,
    Is there any output file contain the alignment used to estimate the species tree, what is needed in the CAFE. And another question is, when I run make_ultrametric.py, I found the relationship between different species in the tree is different from the tree which use the command orthofinder -f pep/. Is there any problem in it?
    Thanks in advance.
    wangxuan

**Comment by wangxuann1995** [comment]
Just the number of sites in the alignment used to estimate the species tree is needed.

**Comment by davidemms** [comment]
Do you mean the number of columns in the alignment? Or the number of genes?

All the best
David

**Comment by wangxuann1995** [comment]
Hi,
    Thanks for your reply, in fact, I don't know what 'sites in the alignment' really mean, it appears in CAFE's tutorial. I have tried to use OrthoFinder's output as CAFE's input. After I have used your python script to converted the tree to ultrametric tree as the tutorial(https://github.com/hahnlab/CAFExp/blob/master/docs/tutorial/tutorial.md) asked. But I think the 'sites in the alignment' means the number of columns in the alignment. I just find the answer in https://groups.google.com/forum/#!topic/hahnlabcafe/kEfPXEx1CN8. Is it right?

    Thanks
    wangxuan

**Comment by davidemms** [comment]
Hi wangxuan

I think the owner of CAFE would be the one to ask about its required inputs. The information in the google groups post looks reliable but if you're able to confirm it officially and post here that would be really useful! I ask since a number of people have used the OrthoFinder issue pages to ask about CAFE and they might also find the information useful.

All the best
David

**Comment by wangxuann1995** [comment]
Hi David
I will make sure what I wondered in CAFE's github, and how can I know the number of columns in the alignment in OrthoFinder? I'll try it during the time I wait for CAFE owner's.

wangxuan

**Comment by davidemms** [comment]
Hi wangxuan

Count them! You could do this in a text editor (most will tell you the column number of the cursor) or if you open it in an alignment viewer such as [AliView](https://ormbunkar.se/aliview/) then it will number the columns for you.

All the best
David
