### ISSUE TITLE
Chech progress

### ISSUE THREAD

**Issue by Tdanis** [davidemms/OrthoFinder#386]
Hello, firstly thank you for this great tool. I would like to ask  ashort question.

How can I check the progress of blast comparisons of orthofinder , I mean in which comparison is in the total of my proteomes.  

Thank you

**Comment by davidemms** [comment]
OrthoFinder will print it's progress as it completes the searches. If will print an update for each multiple of 10, 100 or 1000 it completes according the whether the total number of searches that need to be done is <200, < 2000 or >2000 receptively.

All the best
David

**Comment by Tdanis** [comment]
Thank you very much ,

Thodoris
