### ISSUE TITLE
About fasttree bootstrap value

### ISSUE THREAD

**Issue by awesomedeer** [davidemms/OrthoFinder#388]
Hi David
What's the defalut bootstrap value of fasttree for inferring  species tree? Is it 1000?

Thanks a lot!
Song

**Comment by davidemms** [comment]
Hi Song

FastTree doesn't do a bootstrap analysis, it calculates Shimodaira-Hasegawa support values instead. See the FastTree website for details: http://www.microbesonline.org/fasttree/

All the best
David
