### ISSUE TITLE
Run gets stuck after MSA?

### ISSUE THREAD

**Issue by gettl008** [davidemms/OrthoFinder#390]
I'm trying to do a run of OrthoFinder using Muscle and raxml-ng. The run appears to finish  all alignment and gene tree generation steps but has not produced a status update in over 48 hours. Looking at the Working directory also seems to confirm  these steps are  done. Any ideas what might be going on?

Command:
`orthofinder \
	-b $indir/OrthoFinder/Results_May10  \
	-t  16 \
	-S blast \
	-M msa \
	-A muscle \
	-T raxml-ng`

Log.txt:

> WorkingDirectory_Base: /scratch.global/gettl008/seq_processing/scerevisiae/assem
> blies/nuclear/orthos/faa/OrthoFinder/Results_May10/WorkingDirectory/
> FN_Orthogroups: /scratch.global/gettl008/seq_processing/scerevisiae/assemblies/n
> uclear/orthos/faa/OrthoFinder/Results_May10/../Results_May12_3/WorkingDirectory/
> clusters_OrthoFinder_I1.5.txt_id_pairs.txt
> 
> Species used:
> 0: BJ4.faa
> 1: CBS12357.faa
> 2: CBS432.faa
> 3: COFT1.faa
> 4: CR85.faa
> 5: DBVPG6044.faa
> 6: DBVPG6765.faa
> 7: EN14S01.faa
> 8: GG799.faa
> 9: HLJ1.faa
> 10: HN1.faa
> 11: JXXY16.faa
> 12: N44.faa
> 13: S288C.faa
> 14: SJUR.faa
> 15: SK1.faa
> 16: SX2.faa
> 17: UFRJ50816.faa
> 18: UWOPS03-461.4.faa
> 19: UWOPS91-917.1.faa
> 20: XXYS1.faa
> 21: Y12.faa
> 22: Y55.faa
> 23: YPS128.faa
> 24: YPS138.faa

Stdout:

> OrthoFinder version 2.3.12 Copyright (C) 2014 David Emms
> 
> 2020-05-14 07:06:12 : Starting OrthoFinder
> 16 thread(s) for highly parallel tasks (BLAST searches etc.)
> 1 thread(s) for OrthoFinder algorithm
> 
> Checking required programs are installed
> ----------------------------------------
> Test can run "muscle" - ok
> Test can run "raxml-ng" - ok
> 
> Analysing Orthogroups
> =====================
> 2020-05-14 07:06:23 : Starting MSA/Trees
> Species tree: Using 1985 orthogroups with minimum of 100.0% of species having single-copy genes in any orthogroup
> 
> Inferring multiple sequence alignments for species tree
> -------------------------------------------------------
> 2020-05-14 10:33:31 : Done 1100 of 1985
> 2020-05-14 07:59:52 : Done 300 of 1985
> 2020-05-14 07:25:33 : Done 100 of 1985
> 2020-05-14 08:57:12 : Done 600 of 1985
> 2020-05-14 11:29:51 : Done 1400 of 1985
> 2020-05-14 09:56:14 : Done 900 of 1985
> 2020-05-14 11:10:12 : Done 1300 of 1985
> 2020-05-14 12:07:16 : Done 1600 of 1985
> 2020-05-14 08:19:46 : Done 400 of 1985
> 2020-05-14 12:42:05 : Done 1800 of 1985
> 2020-05-14 08:38:49 : Done 500 of 1985
> 2020-05-14 13:02:23 : Done 1900 of 1985
> 2020-05-14 10:14:00 : Done 1000 of 1985
> 2020-05-14 11:47:26 : Done 1500 of 1985
> 2020-05-14 09:35:36 : Done 800 of 1985
> 2020-05-14 10:52:22 : Done 1200 of 1985
> 2020-05-14 09:15:13 : Done 700 of 1985
> 2020-05-14 12:24:27 : Done 1700 of 1985
> 2020-05-14 07:07:34 : Done 0 of 1985
> 2020-05-14 07:42:14 : Done 200 of 1985
> 
> Inferring remaining multiple sequence alignments and gene trees
> ---------------------------------------------------------------
> 2020-05-15 08:44:32 : Done 3000 of 3821
> 2020-05-15 05:59:33 : Done 2000 of 3821
> 2020-05-14 13:22:15 : Done 0 of 3821
> 2020-05-15 02:37:57 : Done 1000 of 3821

**Comment by davidemms** [comment]
Try running `htop` and see what processes are running. It's likely muscle or raxml are still working on a tree, probably the largest one.

All the best
David

**Comment by gettl008** [comment]
Ah. You're right. Raxml seems to have tried to spend 50+ hours on one orthogroup. Unfortunately, my job timed  out. Is there anyway to resume without having to redo the other trees?

**Comment by davidemms** [comment]
Not really, although you may be able to manually finish the tree off so you can run the '-ft' command to start from the completed trees. You'd need to complete yourself the trees that hadn't finished (use multiple threads or it will take 50+ hours again) and then make sure you have the correct files present for that orthogroup in the WorkingDirectory. You can look at the other orthogroups to see the files you need. It's not supported functionality but you might be able to get it to work.

All the best
David
