### ISSUE TITLE
latest version on conda

### ISSUE THREAD

**Issue by xiaoyezao** [davidemms/OrthoFinder#391]
Hi,

I use miniconda2 to install orthofinder `conda install -c bioconda orthofinder`, but the installed orthofinder is v2.2.6 although it seems that the orthofinder label is v2.3.12 on anaconda website https://anaconda.org/bioconda/orthofinder. Can you please help to figure out what's happening?

Best,

Tao

**Comment by davidemms** [comment]
Hi Tao

That sounds like a question for conda. My guess though is that it is trying to satisfy multiple dependencies for multiple things you've already installed an can only do that with v2.2.6. You could try creating a clean conda environment and installing it there. Or see what information conda give about this situation.

All the best
David
