### ISSUE TITLE
obtaining species-specific orthogroups/genes

### ISSUE THREAD

**Issue by ganiatgithub** [davidemms/OrthoFinder#393]
Hey,

Thanks for the cool program. I was wondering if species specific orthogroups and proteins are included in the standard output. I looked around but cannot find it.
I'm very interested in the species-specific proteins of an organisms within a genus:

```
Number of species-specific orthogroups	2	8	5	0	2	4	16	5	4	169	5	0	0	0
Number of genes in species-specific orthogroups	4	19	12	0	11	8	38	10	15	837	11	0	0	0
```
Cheers!

**Comment by davidemms** [comment]
Hi Gani

Yes, they are provided. Best to use a version from 2.3.7 onwards as that included a significant improvement for their identification. They are best identified using the Orthogroups/Orthogroups.GeneCount.tsv file.

All the best
David

**Comment by ganiatgithub** [comment]
Great, thanks! I'll update and try it.

**Comment by pjyoti29** [comment]
Hii..
I am interested in finding species-specific genes. How is it possible with Orthogroups/Orthogroups.GeneCount.tsv file.
Please suggest
Thanks !

**Comment by plnspineda** [comment]
> Hii.. I am interested in finding species-specific genes. How is it possible with Orthogroups/Orthogroups.GeneCount.tsv file. Please suggest Thanks !

Hi, I think if you look at the file and see a 0 in either of the species, then the gene is specific within the species that doesn't have the 0.
