### ISSUE TITLE
download path of diamond outdated

### ISSUE THREAD

**Issue by MrTomRod** [davidemms/OrthoFinder#395]
Hey David

I noticed that you point to an outdated version of DIAMOND in your README.md. (`https://github.com/bbuchfink/diamond/releases/download/v0.9.22/diamond-linux64.tar.gz`)

Consider this link, which always leads to the latest file: `https://github.com/bbuchfink/diamond/releases/latest/download/diamond-linux64.tar.gz`

Best, Thomas

**Comment by davidemms** [comment]
Updated, thanks!
