### ISSUE TITLE
The rooted speciese tree without support value

### ISSUE THREAD

**Issue by shengzheBian** [davidemms/OrthoFinder#396]
Hello!
      I use orthofinder on your example dataset and its species tree is normal (has support value), however when I use it on my dataset, the rooted species tree don't have support value in nwk file and the branch length is abnormal.
      I have uploaded the tree file and input data, please help me.
                                                                               Thanks,
                                                                               Your shengzhe Bian

[SpeciesTree_rooted.txt](https://github.com/davidemms/OrthoFinder/files/4710746/SpeciesTree_rooted.txt)
[1.40K_seqence.zip](https://github.com/davidemms/OrthoFinder/files/4710750/1.40K_seqence.zip)

**Comment by davidemms** [comment]
Hi

You need to provide OrthoFinder with the complete set of protein coding genes in each species, without that it doesn't have enough data.

All the best
David
