### ISSUE TITLE
ML gene trees && coalescent species tree ?

### ISSUE THREAD

**Issue by xiaoyezao** [davidemms/OrthoFinder#398]
Hi,

From the manual, I understand that by default both gene trees and species tree are inferred by distance-based algorithm FastMe. Alternatively, when setting `-M msa` both gene trees and species tree are inferred by maximum likelihood method. I am wondering is it possible to infer gene trees by ML method and use these gene trees as input to do a coalescent species tree inference.  

bests,

Tao

**Comment by davidemms** [comment]
Hi Tao

Yes, you can do that using the following steps:

1. Infer the gene trees using the "-M msa" option for gene trees from MSA and also "-ot" to stop after the trees are finished (the '-ot' is optional, you could alternatively just let it run to the end).
2. Use the generated genes trees as input to your coalescent species tree inference and then root this tree on the correct branch.
3. Finish the OrthoFinder analysis using this species tree with the option "-s SPECIES_TREE_FILENAME" together with the option "-ft INITIAL_RESULTS_DIRECTORY" to perform the final, species tree dependent steps (ortholog & gene duplication inference) using the species tree you inferred.

All the best
David

**Comment by xiaoyezao** [comment]
Hi David,

Thanks for the explicit explanation. I will try this.

I have another question. In the STAGE tree method, an individual species tree is inferred from each gene tree, and then a consensus species tree is inferred from these species trees. Is it possible to write down these individual species trees in the OrthoFinder results? I am asking this because for some low-level taxa, especially the plants, gene flow and/or hybridization is common, so it would be interesting to generate phylogenetic networks to see how the gene flow and hybridization contribute to the evolution. Currently, most if not all methods to infer phylogenetic networks can only handle single-copy orthologs which are very limited in some plant datasets. If the large number of species trees inferred from multiple-copy gene trees can be used in phylogenetic network analyses, that would be a good improvement I think.  I am not sure whether it's a proper way to do so, or do you have any suggestions?

bests,

Tao
