### ISSUE TITLE
ERROR: external program called by OrthoFinder returned an error code: -4

### ISSUE THREAD

**Issue by gpreising** [davidemms/OrthoFinder#399]
Hi there, 

I'm setting up OrthoFinder and I'm trying to first run it on the example data (`./orthofinder -f ExampleData/`). It seems like I have all the dependencies based on the output (and the fact that they're now included with the OrthoFinder download), but I'm getting this error that repeats many more times before finally showing the message `[22609] Failed to execute script orthofinder`. I can't seem to find any info on the error code I'm getting. Any ideas on fixing this would be greatly appreciated (truncating some of the output with [...]):

`OrthoFinder version 2.3.12 Copyright (C) 2014 David Emms

2020-06-05 11:44:18 : Starting OrthoFinder
64 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /[...]/OrthoFinder/ExampleData/OrthoFinder/Results_Jun05_3/WorkingDirectory/SimpleTest.phy -o /[...]/OrthoFinder/ExampleData/OrthoFinder/Results_Jun05_3/WorkingDirectory/SimpleTest.tre" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2020-06-05 11:44:19 : Creating diamond database 1 of 4
2020-06-05 11:44:19 : Creating diamond database 2 of 4
2020-06-05 11:44:19 : Creating diamond database 3 of 4
2020-06-05 11:44:19 : Creating diamond database 4 of 4

Running diamond all-versus-all
------------------------------
Using 64 thread(s)
2020-06-05 11:44:19 : This may take some time....

ERROR: external program called by OrthoFinder returned an error code: -4

Command: diamond blastp -d /[...]/OrthoFinder/ExampleData/OrthoFinder/Results_Jun05_3/WorkingDirectory/diamondDBSpecies2 -q /[...]/OrthoFinder/ExampleData/OrthoFinder/Results_Jun05_3/WorkingDirectory/Species1.fa -o /[...]/OrthoFinder/ExampleData/OrthoFinder/Results_Jun05_3/WorkingDirectory/Blast1_2.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------

stderr
------`

Thanks, 

Gabe

**Comment by davidemms** [comment]
Hi Gabe

The crucial lines are these:
```
ERROR: external program called by OrthoFinder returned an error code: -4

Command: diamond blastp -d /[...]/OrthoFinder/ExampleData/OrthoFinder/Results_Jun05_3/WorkingDirectory/diamondDBSpecies2 -q /[...]/OrthoFinder/ExampleData/OrthoFinder/Results_Jun05_3/WorkingDirectory/Species1.fa -o /[...]/OrthoFinder/ExampleData/OrthoFinder/Results_Jun05_3/WorkingDirectory/Blast1_2.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------

stderr
------
```

So when OrthoFinder is calling diamond it is getting an error, and the error code from diamond is '-4'. Try calling that diamond command yourself and let me know what happens. The most likely things I can think of are an error in the input files or an error in diamond. 

All the best
David

**Comment by davidemms** [comment]
Hi Gabe

You're welcome, glad you got it running.

All the best
David
