### ISSUE TITLE
Precomputed BLAST results and -x without adding new species fails

### ISSUE THREAD

**Issue by dandaman** [davidemms/OrthoFinder#40]
Hi,

I precomputed BLAST results by running the BLAST jobs produced by the -p option on a cluster...

Now I'd like to start Orthofinder like this:
orthofinder.py -b phytozome/Results_Jul21/WorkingDirectory/ -a 8 -t 2 -x combined3.txt

where combined3.txt looks like this:
head -n2 combined3.txt                                                                                                        
Species63.fa    Zea mays        4577    Phytozome 11    Zmays_284_5b+.protein_primaryTranscriptOnly.fa
Species14.fa    Carica papaya   3649    Phytozome 11    Cpapaya_113_ASGPBv0.4.protein_primaryTranscriptOnly.fa

The run fails at the 
2b. Reading species information file stage 
Traceback (most recent call last):
  File "/home/pgsb/daniel.lang/software/OrthoFinder/orthofinder/orthofinder.py", line 1046, in <module>
    userFastaFilenames = previousFastaFiles + userFastaFilenames
NameError: name 'userFastaFilenames' is not defined

I tried to initialize  userFastaFilenames as an empty list like previousFastaFiles but that also does not solve it because then
Traceback (most recent call last):
  File "/home/pgsb/daniel.lang/software/OrthoFinder/orthofinder/orthofinder.py", line 1075, in <module>
    speciesInfo[iSpecies] = line   
IndexError: list assignment index out of range

Somehow I suspect that the -x switch only works if you start from scratch.

The original Fasta files are named like in the last column of combined3 but in two locations this run does not really know about phytozome/ and another directory...

Do I need to put the original Fasta files someplace together or at least symlink them there?

Best,
Daniel

**Comment by davidemms** [comment]
Hi, I'm able to reproduce the issue. I'll submit a fix in the next couple of days.

All the best
David

**Comment by dandaman** [comment]
Ups, I missed your fix. Thank you. I'm abroad. I'll give it a try when I'm back and report back. All the best,
Daniel
