### ISSUE TITLE
[3168] Cannot open self error (Problem in equesting OrthoFinder to print its help file)

### ISSUE THREAD

**Issue by Anki426** [davidemms/OrthoFinder#402]
After downloading Orthofinder, I am facing a problem in installing it.
I am getting an error in requesting OrthoFinder to print its help file.
Error: 
ankita@ankita-VirtualBox:~/orthofinder_tutorial$ cd OrthoFinder
ankita@ankita-VirtualBox:~/orthofinder_tutorial/OrthoFinder$ ./orthofinder -h
**[3168] Cannot open self /home/ankita/orthofinder_tutorial/OrthoFinder/orthofinder or archive /home/ankita/orthofinder_tutorial/OrthoFinder/orthofinder.pkg**

I have also attached the screenshot of the terminal.
Please help me resolve this issue asap.

![Screenshot from 2020-06-11 13-21-27](https://user-images.githubusercontent.com/66776124/84369785-fccec280-abf4-11ea-98d9-207ee30bcb89.png)

**Comment by davidemms** [comment]
Hi

The screenshot says that an error occurred when you tried to extract the .tar.gz file. It suggest that your download was incomplete. Downloading the file again will resolve that issue.

All the best
David
