### ISSUE TITLE
Name output directory

### ISSUE THREAD

**Issue by CristianRiccio** [davidemms/OrthoFinder#403]
I am using OrthoFinder to find ortholog groups between species. I am using version 2.3.12 downloaded from bioconda using conda on GNU/Linux.

When I run orthofinder -f primary_transcripts it creates an output folder according to the current date. However, I would like to integrate this analysis in a snakemake pipeline, so having a constant output structure would be useful. I tried the -o option and give it a new directory name but then it complains the directory does not exist. When I then create the folder and rerun with the -o option, it complains that the directory exists already.

Is there a way to force a given name to the output folder?

**Comment by davidemms** [comment]
Hi

I've submitted a fix which should resolve the issue. You can use it right away by downloading the latest version of OrthoFinder from the GitHub page and then, from inside your conda environment, running `python path/to/new/orthofinder.py` on the new orthofinder.py file you've downloaded.

(To download the latest version go to the main OrthoFinder github page, click the green 'Clone or download button', download the zip file and unzip it.)

All the best
David
