### ISSUE TITLE
Can't call Diamond

### ISSUE THREAD

**Issue by timregan** [davidemms/OrthoFinder#406]
Hi David, was this (https://github.com/davidemms/OrthoFinder/issues/255) ever fully resolved?
I had been using Orthofinder with no issues, until I attempted rerunning some analysis and I got this Error message:
OrthoFinder version 2.3.12 Copyright (C) 2014 David Emms

2020-06-05 10:55:43 : Starting OrthoFinder
16 thread(s) for highly parallel tasks (BLAST searches etc.)
16 thread(s) for OrthoFinder algorithm

Checking required programs are installed
ERROR: Cannot run diamond
Format of make database command:
diamond makedb --in INPUT -d OUTPUT
ERROR: Cannot run diamond
Format of search database command:
diamond blastp -d DATABASE -q INPUT -o OUTPUT --more-sensitive -p 1 --quiet -e 0.001 --compress 1
Please check diamond is installed and that the executables are in the system path

I have tried using diamond which comes with the OrthoFinder github, I've tried installing diamond from GitHub and bioconda, all work fine, all executable from the path (v 0.9.24), but I keep getting this same message using OrthoFinder. 
I've tried running Blast instead as a workaround but it takes much longer and I'm concerned that something else may be wrong here.

Many thanks,
Tim

**Comment by davidemms** [comment]
Hi Tim

It's usually just a matter of figuring out what's going on on the system. Are you on Linux or Mac? When you ran it before was that using Diamond or Blast (before 2.3.1 Blast was the default)? And are you using the the source code version of OrthoFinder or the packaged version?

One thing to watch out for is that OrthoFinder will try the version of diamond in "OrthoFinder/bin/" or "OrthoFinder/scripts_of/bin/" before looking in the system path. So if you're trying other versions then rename the version which comes with OrthoFinder first (e.g. to "diamond.bak") to ensure OrthoFinder uses the version you intend. 

Next step is to try the two commands it prints on one of the ExampleData files:
```
diamond makedb --in ExampleData/Mycoplasma_agalactiae.faa -d test_db
diamond blastp -d test_db -q ExampleData/Mycoplasma_hyopneumoniae.faa -o test_results.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1
```
and then try running OrthoFinder:
```
python orthofinder.py -f ExampleData/
```

Let me know how you get on. If it doesn't work, could you post the text from your terminal for the above steps.

All the best
David

**Comment by timregan** [comment]
David, firstly thanks so much for such a speedy reply.
I'm on Linux and it was using Diamond when I had run it before. Possibly, I was running into issues with 2 versions of Diamond and OrthoFinder selectively running the one in /bin/ as you say.
I deleted Orthofinder and began again using conda install orthofinder-2.3.12-0.tar.bz2 (which I had downloaded). I also downloaded and installed the source code for OrthoFinder, moving relevant files into the env/bin (e.g. diamond) and moving the ExampleData into the working directory.

After doing this, when I initially tried running "orthofinder -f ExampleData", I got the exact same error message as before (diamond not callable). 
However, I ran the two diamond commands you suggested above and they worked just fine. 
After this, I ran "orthofinder -f ExampleData" again and it worked with no problems!!

This seems very unusual to me and I can't think of any reason why it must be the case, but at any rate, it seems to be working just fine now. I'll let you know if I see anything else unusual.

Thanks again and best wishes,
Tim

**Comment by yashiewashie** [comment]
Hi, David!

I am able to run both commands you mentioned in my current directory from which I am also running orthofinder, however, when I proceed to run orthofinder.py, I continue to get this error:

ERROR: Cannot run diamond
Format of make database command:
diamond makedb --in INPUT -d OUTPUT
ERROR: Cannot run diamond
Format of search database command:
diamond blastp -d DATABASE -q INPUT -o OUTPUT --more-sensitive -p 1 --quiet -e 0.001 --compress 1
Please check diamond is installed and that the executables are in the system path

Please advise.

Thank you,
Yash
