### ISSUE TITLE
Orthofinder hangs during putative homolog step on HPC cluster

### ISSUE THREAD

**Issue by batzza** [davidemms/OrthoFinder#408]
Hi David,

Hope all is well with you.

I am attempting to run OrthoFinder on predicted proteomes from 103 species. For the sake of simplicity, these species can be divided into birds and non-birds. I previously used the -op flag to prepare and then run all 103x103 Diamond searches. Now I am using the -b and -og flags to generate orthogroups from these pre-computed results.

I can run the birds (35 species) alone in ~15 hours, here's the submission command:

`orthofinder -b diamond_hits -s birds.tre -a 8 -og`

And the partial output:

> 2020-06-07 19:58:20 : Starting OrthoFinder
56 thread(s) for highly parallel tasks (BLAST searches etc.)
8 thread(s) for OrthoFinder algorithm
>
>Checking required programs are installed
Test can run "mcl -h" - ok
Test can run "fastme -i /gpfs/gsfs9/users/batzza/GroupOrthoFinder/birds/diamond_hits/SimpleTest.phy -o /gpfs/gsfs9/users/batzza/GroupOrthoFinder/birds/diamond_hits/SimpleTest.tre" - ok
Using previously calculated BLAST results in /gpfs/gsfs9/users/batzza/GroupOrthoFinder/birds/diamond_hits/
>
>Running OrthoFinder algorithm
2020-06-07 19:59:16 : Initial processing of each species
2020-06-07 20:11:29 : Initial processing of species 0 complete
...
2020-06-07 22:14:17 : Initial processing of species 34 complete
2020-06-07 22:50:05 : Connected putative homologues
2020-06-07 22:53:49 : Written final scores for species 0 to graph file
...
2020-06-07 23:25:53 : Written final scores for species 34 to graph file
>
>2020-06-08 11:28:51 : Ran MCL
>
>Writing orthogroups to file
OrthoFinder assigned 5408478 genes (74.6% of total) to 775583 orthogroups. Fifty percent of all genes were in orthogroups with 6 or more genes (G50 was 6) and were contained in the largest 118100 orthogroups (O50 was 118100). There were 7765 orthogroups with all species present and 1 of these consisted entirely of single-copy genes.
>
>2020-06-08 13:41:13 : Done orthogroups

I can also run the non-birds group (68 species) in ~42 hours, here's the submission command:

'orthofinder -b diamond_hits -s all_but_birds.tre -a 16 -og'

And the partial output:

>OrthoFinder version 2.3.11 Copyright (C) 2014 David Emms

>2020-06-17 08:32:11 : Starting OrthoFinder
72 thread(s) for highly parallel tasks (BLAST searches etc.)
16 thread(s) for OrthoFinder algorithm

>Checking required programs are installed
Test can run "mcl -h" - ok

>Running OrthoFinder algorithm
2020-06-17 08:33:19 : Initial processing of each species
2020-06-17 08:41:06 : Initial processing of species 0 complete
...
2020-06-17 13:57:53 : Initial processing of species 67 complete
2020-06-17 14:19:56 : Connected putative homologues
2020-06-17 14:23:34 : Written final scores for species 0 to graph file
...
2020-06-17 15:10:48 : Written final scores for species 67 to graph file

>2020-06-19 01:09:42 : Ran MCL

>Writing orthogroups to file
OrthoFinder assigned 8447237 genes (73.1% of total) to 912745 orthogroups. Fifty percent of all genes were in orthogroups with 13 or more genes (G50 was 13) and were contained in the largest 43817 orthogroups (O50 was 43817). There were 1039 orthogroups with all species present and 0 of these consisted entirely of single-copy genes.

>2020-06-19 03:36:56 : Done orthogroups

But if I try to run all the species together, the program stalls out after initial processing, apparently while trying to connect putative homologs:

>OrthoFinder version 2.3.11 Copyright (C) 2014 David Emms
>
>2020-06-18 07:59:47 : Starting OrthoFinder
72 thread(s) for highly parallel tasks (BLAST searches etc.)
16 thread(s) for OrthoFinder algorithm
>
>Checking required programs are installed
>
>Test can run "mcl -h" - ok
>Using previously calculated BLAST results in /gpfs/gsfs9/users/batzza/GroupOrthoFinder/all_sp/diamond_hits/
>
>Running OrthoFinder algorithm
>2020-06-18 08:01:23 : Initial processing of each species
>2020-06-18 08:11:22 : Initial processing of species 0 complete
...
>2020-06-19 00:21:45 : Initial processing of species 102 complete

I have let this run for up to 10 days without any additional progress. I am running on our computing cluster which also outputs a memory/cpu usage chart specific to the job. You can see in one of the jobs that completes (the non-birds) below along with some annotation based on the log file output. 

![non-birds-cpu-mem](https://user-images.githubusercontent.com/53917879/85463955-1d900400-b575-11ea-9783-287cac9f832b.png)

There is a consistent memory usage as the initial processing occurs, a spike as the putative homolog runs, then consistent 1-2 CPU + ~75GB memory usage as MCL runs and the orthogroups are determined.

In contrast, the all species run cp/mem usage looks like this:

![all_sp_cpu-mem](https://user-images.githubusercontent.com/53917879/85464420-9b540f80-b575-11ea-8289-4bc8389d3cc7.png)

The initial processing runs as expected but then the putative homolog step seems to end prematurely and CPU usage is sits at 0 CPUs with occasional blips of 1 CPU and only ~8GB of memory usage. There are no additional errors output until I eventually kill the process.

I know the files themselves are ok because when divided, they run just fine. Any ideas what might be happening here?

**Comment by davidemms** [comment]
Hi

Thanks for the detailed information, that's very helpful. My initial suspicion is that it could have been the linux Out of Memory (OOM) killer. Do you know how much RAM you have access to on the system, and is it possible that there was a big request for memory and that the processes were immediately killed without that being for long enough to be visible in the plot? My suggestion would be to run OrthoFinder with "-a 1" and see how you get on. If it was a RAM issue then I think this is a lot more likely to be successful. And I'll try to put some time to one side next week to have an in depth look at this.

All the best
David

**Comment by batzza** [comment]
That's a possibility. 

The horizontal line in the usage plots represents my max assigned memory. In the non-birds run (68 species on -a 16) the memory usage spike during the homolog connection tops out around 260 GB (of 320 GB allocated). In the all species run I allocated 360 GB. 

I hadn't considered memory issues because normally my HPC will kill a job that is OOM and reports that both in the terminal log output and the GUI dashboard. Maybe the error isn't being handled correctly so the program has crashed but the HPC doesn't realize it. 

I'll give it a shot with some different -a/mem configurations and report back in a few days. Thanks for the quick response!

**Comment by davidemms** [comment]
The problem is that it could be that one of the parallel worker threads was killed but the main orthofinder thread is still running. If this is what's happening then I think I might be able to implement something so that the main orthofinder thread can detect this.

**Comment by batzza** [comment]
Ahh that makes sense. Thanks!

**Comment by batzza** [comment]
Update:

Running with "-a 1" and 120Gb worked. I was able to run OF from -b to -og for 103 species (~1.4 million genes) in about 13 days with these settings. I'm sorry I can't provide more detailed information about why increasing the algorithm threading killed the job but an unreported OOM seems like a reasonable guess.

Thanks again for your help and let me know if I can do anything to help you further troubleshoot this.
