### ISSUE TITLE
Suggestion on downstream analysis of Orthofinder output

### ISSUE THREAD

**Issue by krishnendu09** [davidemms/OrthoFinder#411]
Hello David,

I am using Orthofinder for the identification of orthologs in ~200 fungal genomes. My objective is to find out the duplication, loss, coalescence events for the orthologs of ~1000 genes (as annotated in one species). I am trying to build a matrix for these genes (rows) against the species (columns) from the Orthogroups.GeneCount.txt and Orthogroups.tsv files. If I have the list of genes (identifiers), is there any script available that can help generate such a matrix? Further, I would like to cluster the genes based on the domains present on them, or the pathway they are involved. Do you have any suggestions on how this can be done?

Best,
Krishnendu

**Comment by davidemms** [comment]
Hi Krishnendu

I don't have a script for doing that unfortunately. If you're willing to classify genes at the orthogroup level then it sounds like you just need to take the subset of the rows of interest from the Orthogroups.GeneCount.txt file. I don't have any advice on the clustering but people discuss, and might be able to offer suggestions on OrthoFinder on forums such as seqanswers/biostars/reddit/twitter.

All the best
David

**Comment by shivank98** [comment]
Hello David,
I have been working on Orthofinder for past few days. I am currently working on to visualize the orthofinder results in a sort of venn diagram, where I can get the count of total genes present and how they all are interacting with other species in orthology.
Please help if this is possible and how to achieve this result.
Thanks and Regards,
Shivank
