### ISSUE TITLE
Venn diagram creation

### ISSUE THREAD

**Issue by mictadlo** [davidemms/OrthoFinder#412]
Hi,
How is it possible to create a venn diagram from OrthoFinder results?

Thank you in advance,

Mic

**Comment by davidemms** [comment]
Hi Mic

I think you'll need to be a lot more specific, there is a vast amount of data in the OrthoFinder results. What is it that you'd like to show in your plot?

All the best
David

**Comment by mictadlo** [comment]
Hi David,
I would like to something similar [to](https://github.com/philippbayer/orthomclToVenn/blob/master/README.md).
Thank you in advance,

Mic

**Comment by davidemms** [comment]
Hi Mic

The OrthoFinder "Orthogroups/Orthogroups.txt" results file is a replacement to the OrthoMCL "groups.txt" file. It contains the orthogroups in the OrthoMCL format. That should allow you to use the tool you link to.

All the best
David

**Comment by mictadlo** [comment]
Hi David,
Thank you. [OrthomclToVenn](https://github.com/philippbayer/orthomclToVenn/blob/master/README.md#input-files) requires two special files: 

1.  `families.txt` (this file details which species are in which groups, first the name of the group, then the short handles that appear in groups.txt). Example:

```
etoids: Gma,Caj,Vir,Adz,G19,BAT
goids: Lja,Clo,Red,Mtr,Des,Kab
ergoids: Ari,Ard
```
2. `singletons.txt` - this file is produced by running orthoMCL's orthomclSingletons and contains all genes that are contained in no groups. With `OrthoMCL` I think it is possible to produce the file with `orthomclSingletons goodProteins.fasta groups.txt > singletons.txt`

How is it possible to create the above two files for OrthoFinder?

Thank you in advance,

Michal

**Comment by davidemms** [comment]
Hi Michal

OrthoFinder doesn't create either of those files. From what you say I think OrthomclToVenn wants you to create the families.txt file to say how you want the species grouped together. The genes that are contained in no groups are listed at the bottom of the Orthogroups/Orthogroups.txt file.

All the best
David

**Comment by mictadlo** [comment]
Hi David,
Could please me provide me with advice or a script on how to create the `families.txt` file?

Thank you in advance,

Best wishes,

Michal

**Comment by davidemms** [comment]
Hi Michal

This doesn't seem to be an OrthoFinder issue?

All the same, I've looked at the description you've pasted above:
```
etoids: Gma,Caj,Vir,Adz,G19,BAT
goids: Lja,Clo,Red,Mtr,Des,Kab
ergoids: Ari,Ard
```
and it looks to me like the idea is that you chose how you want to group the species together (using a text editor to write the file I guess). As I'm sure you'll understand, this isn't something I've done and I don't have a script for it.

All the best
David
