### ISSUE TITLE
Modifying species tree

### ISSUE THREAD

**Issue by JC-therea** [davidemms/OrthoFinder#414]
Dear David,

I am checking duplicates and orthologues in several vertebrates. I ran OrthoFinder both with the default and MSA options and they produced the following species tree:

![Species Tree MSA species tree provided](https://user-images.githubusercontent.com/43994737/86133990-5c7c0780-bae9-11ea-8371-f85a27f73eb1.png)

Most species are correctly located according to several papers like: 

https://academic.oup.com/gbe/article/9/7/1886/3983271
https://science.sciencemag.org/content/334/6055/521

However, some of them (the node of Canis lupus, etc and Oryctolagus) are misplaced probably because the species are closely related. My question is, there is some way to make the species tree of OrthoFinder more similar to the one in the paper? I know that I can provide the species tree but all the newick files that I found have more organisms than those that I used.

Best regards and thanks,
Carlos

**Comment by davidemms** [comment]
Hi Carlos

I've not found a program that will let you edit the species tree and so the way I've done this is to edit the newick file in a text editor by hand. It's sometimes a bit tricky to get all the brackets right but you get the hang of it. If you wanted branch lengths as well then I think with programs like RAxML & IQTREE you can provide as input the MSA and a fixed tree topology and it will calculate them. If you wanted to provide the species tree as input to OrthoFinder to rerun the gene tree rooting & ortholog inference step (using the '-ft' and '-s' options) then you don't need to worry about branch lengths.

All the best
David

**Comment by JC-therea** [comment]
Hi David,

Thank you for your quick response. Indeed using -ft and -s options with the right tree (but without branch lengths) is the faster option and works well. However, I also need branch lengths so I will run IQTREE to get that. 

Thank you very much for your help.
Carlos
