### ISSUE TITLE
Permission to use a figure derivative

### ISSUE THREAD

**Issue by josiahseaman** [davidemms/OrthoFinder#418]
Hello Dr. Kelly or Dr. Emms,
May I have permission to include a derivative of a user manual figure in the methods section of my PhD thesis when describing OrthoFinder?

This is what I'd like to include:
![image](https://user-images.githubusercontent.com/2256148/86659039-c3e0fe00-bfa6-11ea-9c51-9862ec884d7c.png)

As far as I can see this isn't published for example in genome biology so I think that makes the Kelly lab the sole copyright holder. 

Thank you for your consideration.

**Comment by davidemms** [comment]
Hi Josiah

Yes, that would be fine.

Just to let you know, some of the information may need updating. The MSA & tree methods are whichever you selected but unless you specifically requested it or used a very old version then it won't have used "dlcpar_search". There's a completely new algorithm as of version 2.0.0 which is described in the latest OrthoFinder paper. If you did use the dlcpar version I'd highly recommend using this newer version to get the orthologues as it is far more accurate. You should just be able to use the "-ft" option to rerun just this final step which should be pretty quick.

All the best
David

**Comment by josiahseaman** [comment]
Thank you David!
I used OrthoFinder version 2.2.6.  I do think it used dlcpar_search, at least that's what I have written down in my Methods notes. 
> This set of genes is taken from Homeologs_Analysis.ipynb based on reconciled gene trees from dlc_par orthofinder.    

If this is inferior that might be sufficient justification to rerun the reconciliation.  My user manual version is from June 14, 2017.

**Comment by davidemms** [comment]
I think you'll have used the newer method in that case, it was the default from version 2.0.0 and although there was an option to use dlcpar that option was hidden. You can tell if dlcpar was used because it will have a directory called 'dlcpar' in one of the Working Directories, e.g. `Orthologues_Jul08/WorkingDirectory/dlcpar`.

All the best
David

**Comment by josiahseaman** [comment]
Thanks for the clarification then. There's no `dlcpar` subdirectory that I can see.  The WorkingDirectory only has:
`Distances  Distances_SpeciesTree  SpeciesTrees_ids  Trees_ids`  

I think you can close this issue now.  Should I use the 2019 paper when referring to the reconciliation algorithm?  Does that algorithm have a particular name?

**Comment by davidemms** [comment]
Yes, the orthologs algorithm is described in the 2019 paper so that's the one to cite for the method. I'd refer to it as the "hybrid overlap + DLC algorithm".
