### ISSUE TITLE
No orthologues identified although multiple homologous genes were identified based on blast results

### ISSUE THREAD

**Issue by xie186** [davidemms/OrthoFinder#421]
Hi @davidemms,

Thank you for developing OrthoFinder. I want to study the evolution of  one gene in plant. I know the gene ID in Arabidopsis. I ran OrthoFinder using 50 plant species. I found that this gene didn't have any orthologous genes in species B.  But I blasted the protein sequence against proteins from species B. I got several good hits (identity > 80% and eval < 0.00001). 

If this is the case and I want to study the evolution of this gene, is there any way I can loose the criteria to include these homologous genes? Or should I just include the these genes based on blast results?

**Comment by davidemms** [comment]
Hi

I would recommend investigating it using a gene tree to determine if the species B genes are orthologs:
* Look in `Orthogroups/Orthogroups.tsv` for the orthogroup containing the Arabidopsis gene
* Get the sequence file for that orthogroup from the `Orthogroup_Sequences/` results directory
* Add the protein sequences for the genes you identified in species B to this file
* Infer a multiple sequence alignment and tree (e.g. using mafft & iqtree)
* Root the gene tree and analyse it to determine if any of the genes are orthlogs of your Arabidopsis gene (i.e. did the diverge at a speciation event, or at a gene duplication event further back in time)

All the best
David

**Comment by xie186** [comment]
Thank you for your suggestion. I really appreciate it.
