### ISSUE TITLE
A warning during MCL

### ISSUE THREAD

**Issue by Edison2021** [davidemms/OrthoFinder#423]
Hi David

Everything looks good but a warning jumped out at stage of MCL:
.......
WARNING: program called by OrthoFinder produced output to stderr

Command: mcl /OrthoFinder/Results_Jun24/WorkingDirectory/OrthoFinder/Results_Jul02/WorkingDirectory/OrthoFinder_graph.txt -I 1.5 -o /OrthoFinder/Results_Jun24/WorkingDirectory/OrthoFinder/Results_Jul02/WorkingDirectory/clusters_OrthoFinder_I1.5.txt -te 1 -V all

stdout
------

stderr
------
[mcl] cut <2> instances of overlap

2020-07-02 07:47:50 : Ran MCL
.....

Should i worry about this warning?
Thanks

Edison

**Comment by davidemms** [comment]
HI Edison

No, that warning is not tto rare and is not something to worry about.

All the best
David

**Comment by Edison2021** [comment]
Thanks!

Edison
