### ISSUE TITLE
Species tree for each ortholog

### ISSUE THREAD

**Issue by xbarvazx** [davidemms/OrthoFinder#425]
Hi,

Is it possible to build a species tree for each ortholog gene? 
I would like to build an overly plot of all the trees 

Best,
Raz

**Comment by davidemms** [comment]
Hi Raz

I'm not sure I understand specifically what you would like to do. Could you explain a bit more?

All the best
David

**Comment by xbarvazx** [comment]
Hi David,

Sorry I will try to clarify. I was thinking if its possible to make a species tree for a single ortholog gene group that will only show the species included in the analysis and not each gene (similar to the species tree final output, SpeciesTree_rooted.txt), I dont know how its possible if there are more then one ortholog per species.
Anyway I was asking only to make sure I missed something in the output, if its not something that is there then nevermind.

Thanks,

**Comment by davidemms** [comment]
Hi Raz

There is a file in the output, "Orthogroups/Orthogroups_SingleCopyOrthologues.txt" that lists all the orthogroups that have exactly one gene per species, you could use the corresponding trees from these orthogroups.

All the best
David

**Comment by xbarvazx** [comment]
Awesome, thanks!
