### ISSUE TITLE
thanks David,

### ISSUE THREAD

**Issue by assafwww** [davidemms/OrthoFinder#428]
thanks David,

based on your recommendation, I just replaced the Tree_ids directory created previously (in "Results2" directory)
by the new one (the iqtree trees directory), without touching anything else, and then called `orthofinder -ft $blastDir/OrthoFinder/Results2 -a 20 -t 20 -s $specieTree`.
Orthofinder completed successfully and I think gave the expected data tables results in directories:

```
Comparative_Genomics_Statistics
Gene_Duplication_Events
Orthologues
Phylogenetically_Misplaced_Genes
Putative_Xenologs
Resolved_Gene_Trees
Species_Tree
WorkingDirectory
```

One directory seems missing, "Gene_Trees". I think it should be created in the new run since it includes rooted trees that could not be created by iqtree. 
Another thing is that based on the cpus usage, and the order of files created, the program did not work in parallel, but still the total runtime was ~2h, which is reasonable.

thanks a lot,
Assaf

_Originally posted by @assafwww in https://github.com/davidemms/OrthoFinder/issues/424#issuecomment-658718133_

**Comment by davidemms** [comment]
Hi Assaf

I've answered in the original post so I will delete this one if that's ok.

All the best
David

**Comment by assafwww** [comment]
Hi David, sure you can remove,
Assaf
