### ISSUE TITLE
OrthoFinder v2.4.0

### ISSUE THREAD

**Issue by Edison2021** [davidemms/OrthoFinder#430]
Hi David
Is N0.tsv in Phylogenetic_Hierarchical_Orthogroups equivalent to Orthogroups.tsv in older version?

Thanks
Edison

**Comment by davidemms** [comment]
Hi Edison

Yes, that's right. You can see in the species tree with node labels at what level each of those new files is defined. N0.tsv will always be at the root so is equivalent to the old Orthogroups.tsv.

All the best
David
