### ISSUE TITLE
One blast.txt file empty, impeding orthofinder progression

### ISSUE THREAD

**Issue by kmdowney12** [davidemms/OrthoFinder#437]
Hi, 

I'm running a very simple comparison of two species through OrthoFinder with Diamond. Not for a major part of a study, just a quick diagnostic test. Three of my comparisons are successful: Species 0-1, Species 1-1, and Species 1-0. But Species 0-0 comparison can't seem to finish. The fasta file should be fine, or it wouldn't have worked in the 0 vs 1 blast. 

It's two closely related diatom species from the same genus. 

Do you have any thoughts? 

Thank you for your time, 
Kala

**Comment by davidemms** [comment]
Hi Kala

The self-self alignment will take longer so it's likely that it's just a bigger proteome and is still running. How many sequences are there in each file?
```
# cd to the WorkingDirectory ..... then
grep -c ">" Species*fa
```

All the best
David

**Comment by kmdowney12** [comment]
Hi David, 

There are 31,409 sequences in the larger of the two (Species 0) and 11,390 in the smaller (Species 1). It's 0 vs 0 is what's causing the hold up. The other three comparisons (0_1, 1_0, and 1_1) took 5 minutes in total and I gave that last comparison another hour and a half. 

Thank you, 
Kala

**Comment by kmdowney12** [comment]
Hi David, 

It must have been a bug in our system. With an updated version of orthofinder, things went smoothly (though the 0_0 comparison did take longer than the others as you mentioned it would). 

Thank you again for your time, 
Kala
