### ISSUE TITLE
How to find the orthologous genes used to construct the 'SpeciesTree_rooted.txt' in each cluster in "Species_Tree/Orthogroups_for_concatenated_alignment.txt"?

### ISSUE THREAD

**Issue by fantasticair** [davidemms/OrthoFinder#439]
Hi David,
       The software you wrote is very good. I would like to know if it is possible to extract the genes for each cluster in the `Orthogroups_for_concatenated_alignment.txt` file that was used for getting `SpeciesTree_rooted.txt` because each cluster contains many paralogous genes, I would like to know which gene is used to build a phylogenetic tree that is ultimately determined to be the ancestral state?

Best wishes

**Comment by davidemms** [comment]
Hi

The genes used are the ones in the file `Orthogroups_for_concatenated_alignment.txt`that are single-copy in its species. 

All the best
David
