### ISSUE TITLE
add updated protein sequences of a species

### ISSUE THREAD

**Issue by krishnam** [davidemms/OrthoFinder#442]
Hi David,
I am adding an updated version of proteins file for a species which is already in the list of proteomes analysed by orthofinder.
placing it in "-f new_species" folder conflicts.
I wish to update the old proteome file with the new one (keeping species name the same) and rerun so as to generate blastp searches with new file and orthologs updated.
Please let me know.
Thanks.

**Comment by davidemms** [comment]
Hi

Place the new file in a separate directory (e.g. "new_files/") and in the original Results_???/WorkingDirectory/SpeciesIDs.txt comment out the old file using a '#' at the start of the line (if you are using an older version you have to be careful not to put any extra spaces, with the latest version you don't need to worry). Then use `-b original_dir -f new_files`.

All the best
David
