### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by Taojianchang** [davidemms/OrthoFinder#445]
Traceback (most recent call last):
  File "/home/jianchang/software/miniconda3/envs/orthofinder/bin/orthofinder", line 7, in <module>
    main(args)
  File "/home/jianchang/software/miniconda3/envs/orthofinder/bin/scripts_of/__main__.py", line 1687, in main
    GetOrthologues(speciesInfoObj, options, prog_caller)
  File "/home/jianchang/software/miniconda3/envs/orthofinder/bin/scripts_of/__main__.py", line 1513, in GetOrthologues
    options.name)
  File "/home/jianchang/software/miniconda3/envs/orthofinder/bin/scripts_of/orthologues.py", line 1012, in OrthologuesWorkflow
    ReconciliationAndOrthologues(recon_method, db.ogSet, nHighParallel, i if qMultiple else None, all_stride_dup_genes=all_stride_dup_genes) 
  File "/home/jianchang/software/miniconda3/envs/orthofinder/bin/scripts_of/orthologues.py", line 810, in ReconciliationAndOrthologues
    nOrthologues_SpPair = trees2ologs_of.DoOrthologuesForOrthoFinder(ogSet, speciesTree_ids_fn, trees2ologs_of.GeneToSpecies_dash, all_stride_dup_genes, qNoRecon)
  File "/home/jianchang/software/miniconda3/envs/orthofinder/bin/scripts_of/trees2ologs_of.py", line 648, in DoOrthologuesForOrthoFinder
    with open(files.FileHandler.GetDuplicationsFN(), csv_write_mode) as outfile, OrthologsFiles(dResultsOrthologues, speciesDict, ogSet.speciesToUse, nspecies, sp_to_index) as (ortholog_file_writers, suspect_genes_file_writers):
  File "/home/jianchang/software/miniconda3/envs/orthofinder/bin/scripts_of/trees2ologs_of.py", line 600, in __enter__
    self.ortholog_file_handles[j][i] = open(d1 + '%s__v__%s.tsv' % (self.speciesDict[sp1], self.speciesDict[sp0]), csv_write_mode)
OSError: [Errno 24] Too many open files: '/home/jianchang/WWX/Bathy/orthofinder_results/Results_Aug16_2020/Orthologues/Orthologues_GCA_005884635.1_ASM588463v1_genomic/GCA_005884635.1_ASM588463v1_genomic__v__2654588079.genes.tsv'

**Comment by Taojianchang** [comment]
Hi David,
I encountered the above problem when I use this command: orthofinder -f prodigal_results -t 32 -a 32 -M dendroblast -S blast -I 2.5 -n ${version} -o  ${Ortho_RESULTS}
but it won't happen when genome numbers were small.

**Comment by davidemms** [comment]
Hi

You need to increase the setting for the number of files your system can have open at the same time. Here is the help message printed by the latest version of OrthoFinder (the suggested limits given here are for 200 species, increase this is you want to analyse more species):

```
ERROR: The system limits on the number of files a process can open is too low. For 200 species OrthoFinder needs to be able to open at least r=40100 files. Please increase the limit and restart OrthoFinder
1. Check the hard and soft limits on the number of open files for your system:
    $ ulimit -Hn
    $ ulimit -Sn
2. If hard limit, h > r already, then you just need to increase the soft limit:
    $ ulimit -n 40100
3. Alternatively, if h < r then you need to edit the file '/etc/security/limits.conf', this requires root privileges. To increase the limit to 40100 for user  called 'emms' add the lines:
    emms hard nofile 40100
    emms soft nofile 40100
    (edit these lines to match your username)
4. Check the limit has now been updated (if you changed the hard limit you'll need to open a new session and confirm it's updated):
    $ ulimit -Sn
5. Once the limit is updated restart OrthoFinder with the original command

For full details see: https://github.com/davidemms/OrthoFinder/issues/384
```

All the best
David
