### ISSUE TITLE
Compiling from source under macOS?

### ISSUE THREAD

**Issue by janstrauss1** [davidemms/OrthoFinder#446]
Hi @davidemms ,

I know I can install `orthofinder` using `conda` on Mac. Yet, I would like to use the OrthoFinder source code version and install the dependencies myself.

Therefore, I have downloaded the source code using
`git clone https://github.com/davidemms/OrthoFinder.git`

Now, I'm not really sure if I still need to compile and install from source as it appears that calling `python OrthoFinder/orthofinder.py -h` from my home directory appears to work fine as mentioned in https://github.com/davidemms/OrthoFinder/issues/110#issuecomment-341389814?

What would then be the best practice to put the python script into my PATH to make it available from anywhere?

Many thanks in advance for your feedback!

**Comment by davidemms** [comment]
Hi

I think you can just add the directory containing "orthofinder.py" to your PATH variable (e.g. in .bashrc or the Mac equivalent) or, safer, copy orthofinder.py and the scripts_of directory to a location in your system path.

All the best
David
