### ISSUE TITLE
mafft and FastTree 

### ISSUE THREAD

**Issue by Edison2021** [davidemms/OrthoFinder#447]
Hi David
I am not sure how does OrthoFinder find mafft and FastTree.  I tried two different locations for these software: one in /usr/local/bin and the other one in OrthoFinder/bin. Both work well. Could you please explain a little to me how orthoFinder find them.

Thanks
Edison

**Comment by davidemms** [comment]
Hi Edison

It first looks in OrthoFinder/bin and if they are not found there then it looks in the system path (`echo $PATH`).

All the best
David
