### ISSUE TITLE
docker orthofinder 2.4 -  Specified directory doesn't exist:

### ISSUE THREAD

**Issue by eriklysoe** [davidemms/OrthoFinder#450]
Hi

I installed docker version
docker pull quay.io/biocontainers/orthofinder:2.4.0--0

And example data
eriklysoe@NIBIO:~/orthofinder/ExampleData$ pwd
/home/eriklysoe/orthofinder/ExampleData

And run
eriklysoe@NIBIO:~$ docker run quay.io/biocontainers/orthofinder:2.4.0--0 orthofinder -t 10 -f /home/eriklysoe/orthofinder/ExampleData                           
OrthoFinder version 2.4.0 Copyright (C) 2014 David Emms

Specified directory doesn't exist: /home/eriklysoe/orthofinder/ExampleData/
ERROR: An error occurred, ***please review the error messages*** they may contain useful information about the problem.

I don't understand, seems to be a problem with the path

Cheers
Erik

**Comment by davidemms** [comment]
Hi Erik

I'd advise against using Docker for this if you can as it's extremely slow. The best options for each platform are described here:
https://davidemms.github.io/orthofinder_tutorials/alternative-ways-of-getting-OrthoFinder.html

If you do want to proceed with docker, there are some instructions at the bottom of the page of the above link.

All the best
David

**Comment by eriklysoe** [comment]
Thank you, It worked with instructions found on you page :-)
