### ISSUE TITLE
Strange orthogroups. Almost 1000 genes in one species

### ISSUE THREAD

**Issue by ViriatoII** [davidemms/OrthoFinder#455]
I noticed I have some very strange orthogroups. The most extraordinary includes almost 1000 members from a proteome downloaded from uniprot. Isn't this strange?  Most my orthogroups have 0-5 members per species, some go up to 60 members in some species, but 973 is raising the alarm for me.

A quick uniprot consultation and most of these clustered genes are uncharacterized, but they seem indeed to be connected on 50% identity.
Examples: https://www.uniprot.org/uniprot/A0A0D3CTR8 and  https://www.uniprot.org/uniprot/A0A0D3DVJ6

Of the 973 genes, 120 are characterized, as any of the following:
```
14_3_3 domain-containing protein OS=Brassica oleracea var. oleracea OX=109376 PE=3 SV=1
Apple domain-containing protein OS=Brassica oleracea var. oleracea OX=109376 PE=4 SV=1
DDE Tnp4 domain-containing protein OS=Brassica oleracea var. oleracea OX=109376 PE=4 SV=1
DUF632 domain-containing protein OS=Brassica oleracea var. oleracea OX=109376 PE=4 SV=1
ELMO domain-containing protein OS=Brassica oleracea var. oleracea OX=109376 PE=4 SV=1
HTH myb-type domain-containing protein OS=Brassica oleracea var. oleracea OX=109376 PE=4 SV=1
KIX_2 domain-containing protein OS=Brassica oleracea var. oleracea OX=109376 PE=4 SV=1
Myb-like domain-containing protein OS=Brassica oleracea var. oleracea OX=109376 PE=4 SV=1
NAD(P)-bd_dom domain-containing protein OS=Brassica oleracea var. oleracea OX=109376 PE=4 SV=1
NAM-associated domain-containing protein OS=Brassica oleracea var. oleracea OX=109376 PE=4 SV=1
Peptidylprolyl isomerase OS=Brassica oleracea var. oleracea OX=109376 PE=4 SV=1
TF-B3 domain-containing protein OS=Brassica oleracea var. oleracea OX=109376 PE=4 SV=1
WRKY domain-containing protein OS=Brassica oleracea var. oleracea OX=109376 PE=4 SV=1
zf-CCHC_4 domain-containing protein OS=Brassica oleracea var. oleracea OX=109376 PE=4 SV=1
zf-GRF domain-containing protein OS=Brassica oleracea var. oleracea OX=109376 PE=4 SV=1
```

I initially though they could be plastideal genes but they are encoded in chromossomes. Any opinion on this? Do you reduce protein redundancy with cd-hit before Orthofinder (95% doesn't make so much difference for this species here). Or can these numbers just make sense?

Cheers,
Ricardo

**Comment by davidemms** [comment]
Hi Ricardo

There are two questions you need to ask yourself:
* Are they homologous? 
* And did they diverge before or after the most recent common ancestor of your input species? 

You'll need to make a tree with all relevant genes in to answer the second question (unless there aren't any homologs outside the species in which case you already have the answer).

All the best
David
