### ISSUE TITLE
Orthofinder pdf manual

### ISSUE THREAD

**Issue by vcastroagudin** [davidemms/OrthoFinder#458]
Hello,

Is there a manual available for Orthofinder2 ? is the one for version 1.6 good for the new software still?

Thanks,

Vanina

**Comment by davidemms** [comment]
Hi Vanina

I think some of the pdf could be out of date. The best reference is the README file, if there is anything that's missing or not up to date in there then please let me know and I'll fix it.

All the best
David

**Comment by vcastroagudin** [comment]
Thank you!!!
