### ISSUE TITLE
Is the Species Tree paper ready?

### ISSUE THREAD

**Issue by ViriatoII** [davidemms/OrthoFinder#459]
Hi again,

I have a conceptual question: I'm working with many Denovo assemblies. The species tree looks great. Does it stand on it's own for a paper result? Or is it more recommended to make a tree out of nuclear cds sequences with the standard programs? 

(I'm already using blast and RaxML within Orthofinder)

Cheers,
Ricardo

**Comment by davidemms** [comment]
Hi Ricardo

That's really a question for the reviewers, and it'll depend on what they think. An important consideration is the kind of paper you're writing and how central a 'result' the species tree is. 

My opinion would be that the OrthoFinder species tree from MSA matches quite closely the standard approach for species tree inference, so is not particularly controversial and is a pretty acceptable approach for most papers. You might find it useful to describe the approach:
* Single-copy genes were used from orthogroups that were present & single-copy in at least x% of the species (OrthoFinder prints this fraction to screen when it does the analysis)
* Columns that were more than 50% gaps in the single-copy species present in that orthogroup were trimmed
* Concatenated MSA
* Tree inferred with RAxML (also say what MSA program you used).

If you don't have bootstrap support values for your species tree you should run RAxML again on the species tree alignment with whatever the required options are to get support values.

All the best
David

**Comment by ViriatoII** [comment]
Thank you so much, have a great day!
