### ISSUE TITLE
ERROR: Cannot run diamond

### ISSUE THREAD

**Issue by emmannaemeka** [davidemms/OrthoFinder#462]
I am using Mac version Catalina. I obtained Orthofinder using
wget https://github.com/davidemms/OrthoFinder/releases/latest/download/OrthoFinder.tar.gz
and tar xzf OrthoFinder.tar.gz.

When I run python /Users/emmannadi/Desktop/Repeat_study/OrthoFinder/orthofinder.py -h 
it outputs  help

However when I run 
python  /Users/emmannadi/Desktop/Repeat_study/OrthoFinder/orthofinder.py  -M msa -T raxml-ng   -f /Users/emmannadi/Desktop/Repeat_study/CBS11016_Masked/Proteome/

It outputs

ERROR: Cannot run diamond
Format of make database command:
  diamond makedb --in INPUT -d OUTPUT
ERROR: Cannot run diamond
Format of search database command:
  diamond blastp -d DATABASE -q INPUT -o OUTPUT --more-sensitive -p 1 --quiet -e 0.001 --compress 1
Please check diamond is installed and that the executables are in the system path

ERROR: An error occurred, ***please review the error messages*** they may contain useful information about the problem.

I have diamond installed on my path, mere running diamond help outputs help.

What could be wrong?

**Comment by davidemms** [comment]
Hi

They'll be a copy of diamond in `scripts_of/bin` that it will try to use by preference. If this version won't run on your machine then this could cause the issue you report. If that's the case then delete that copy and OrthoFinder will instead pick yup the version installed on your machine.

All the best
David

**Comment by CaptainCold001** [comment]
Hi 
I still get the same error message even after deleting the copy of diamond from the bin folder
