### ISSUE TITLE
high one-to-many orthologs caused by fragments of same gene?

### ISSUE THREAD

**Issue by binlu1981** [davidemms/OrthoFinder#463]
Hi @davidemms , 

Can the higher number of one-to-many orthologs be due to fragments of the same gene counted twice?

Thanks

Bin

**Comment by davidemms** [comment]
Hi Bin

Yes, that could definitely be the case. If you're able to it is best if you provide just one representative sequence per locus.

All the best 
David

**Comment by binlu1981** [comment]
Thanks @davidemms . The BUSCO analysis reported ~5% fragmented genes in my assembly. Will this lead to a higher number of one-to-many orthologs

**Comment by davidemms** [comment]
Unfortunately I've not looked into that qualitatively before.
