### ISSUE TITLE
Running OrthoFinder using precomputed pairwise blast results of transcript sequences for the purpose of only getting orthogroups

### ISSUE THREAD

**Issue by ndrubins** [davidemms/OrthoFinder#466]
Hi,

This is a feature question rather than an issue.

I'm interested in running OrthoFinder on precomputed pairwise blast results of transcript sequences for the purpose of only getting orthogroups (i.e., orthofinder -b <blast_results_folder> -og). Assuming I haven't missed the option to do this in the manual, is it possible and if so how difficult will it be to add this option?

Thanks a lot

**Comment by davidemms** [comment]
Hi 

It's perfectly possible to do, you just need to have the files in the correct format. See here:
https://github.com/davidemms/OrthoFinder#using-pre-computed-blast-results

All the best
David

**Comment by ndrubins** [comment]
Thanks a lot for your help, and sorry for the late response.
