### ISSUE TITLE
Is orthofinder determinstic?

### ISSUE THREAD

**Issue by ChriKub** [davidemms/OrthoFinder#468]
@davidemms we are running orthofinder on annotations within the same species and are seeing genes which are not in the same OG, but we suspect they should be. We saw issue 277 and 374 on the same problem, but before we start looking into the problem and fine tune parameters to mitigate the problem we would like to know if the Orthofinder result is actually deterministic?

**Comment by davidemms** [comment]
Hi

Yes, multiple runs should produce the same results. For the orthogroups this should always be the case as far as I'm aware. The only times this might not be the case is for the later ortholog inference stage if you were to chose a MSA or tree inference method that is non-deterministic. But as far as I'm aware, all the common ones are as they typically use the same seed each time for the random number generator (with RAxML you can provide your own seed for the random but OrthoFinder always provides the same seed).

All the best
David
