### ISSUE TITLE
OrthoFinder and Reference species

### ISSUE THREAD

**Issue by npchar** [davidemms/OrthoFinder#47]
Hi every one,

I'm wondering how OrthoFinder is bulding orthogroups ? 
It looks like OrthoFinder is using a reference species (the last species in alphanumerical order ?) which is changing the number of orthogroups as well as the number of single copy orthologues predicted by orthofinder...

Looking for single copy orthologues in my set of sequences, I used the Orthogroups.csv file from Orthofinder, counted the number of genes found per orthogroups and per species. Then, I extracted the orthogoups for which no more than one gene were found per species. I printed a presence/absence (or gene occupancy) matrix per species and per orthogroups.
**Alph.SCO.pdf :**
![alpha sco](https://cloud.githubusercontent.com/assets/20398625/23069567/3e7aef9c-f528-11e6-83c8-aa60b347e61b.png)

As you can see on the SCO.png file, which represent the gene occupancy for every SCO identified by Orthofinder under my criteria, the first species (called "E") is showing 100% of presence for every SCO.
After I renamed the species (E corresponded to A specie in the first run), I found the same pattern for E, the last species in alphanumerical order.
**RevAlph.SCO.pdf**.
![revalpha sco](https://cloud.githubusercontent.com/assets/20398625/23069559/34ace20e-f528-11e6-8c91-6e17cd0195bb.png)

Am I doing something wrong ? Am'I pointing some limits of OrthoFinder ? Are my scripts unacurate ? Should I use some other tools already available ? 
Could you explain me what's going on ? 

Pierre

Some more precision about the exemple dataset I used : 

From the Uniprot, proteome ( http://www.uniprot.org/proteomes/), I downloaded the five first entry UP000000212, UP000000214, UP000000223, UP000000224 and UP000000229 (ftp link in the file: ExplProteome.txt)
[ExplProteome.txt](https://github.com/davidemms/OrthoFinder/files/783468/ExplProteome.txt)

```
mkdir TestOrthoFinder
cd TestOrthoFinder
for i in $(cat ExplProteome.txt) ; do wget $i  ; done
for i in $(ls *.gz); do gunzip $i ; done
```
I renamed the proteome ()
```
#Prepare Iteration
number=(0 1 2 3 4)
Alph=(A B C D E)
RevAlph=(E D C B A)
listFasta=($(ls *.fasta))

#Prepare Directory for both analysis :
mkdir TestAlph
mkdir TestRevAlph
for i in ${number[@]}
do
        ln ${listFasta[$i]} TestAlph/${Alph[$i]}.fa
        ln ${listFasta[$i]} TestRevAlph/${RevAlph[$i]}.fa
done
```
Then, running Orthofinder version 1.1.3 :
```
orthofinder.py -t 32 -f TestAlph/
orthofinder.py -t 32 -f RevTestAlph/
cp TestAlph/Result*/Orthogroups.csv AlphOrthogroups.csv
cp RevTest/Result*/Orthogroups.csv RevAlphOrthogroups.csv
```
I used two home-made script (available on github at : https://github.com/npchar/Phylogenomic )
The first is counting the number of genes/contigs/sequence per orthogroups and per species. The second is identifying SCO, and is creating a graphical representation of the gene occupancy matrix (need R::optparse, R::reshape2, R::ggplot2 ).
```
git clone https://github.com/npchar/Phylogenomic.git
./Phylogenomic/OrthoFinder-NumberOfGenesPerOrthogroupsPerSpecies.pl RevAlphOrthogroups.csv > RevAlphOrthogroups.ocurrence.csv
./Phylogenomic/OrthoFinder-NumberOfGenesPerOrthogroupsPerSpecies.pl AlphOrthogroups.csv > AlphOrthogroups.ocurrence.csv
./Phylogenomic/OrthoFinder-SCOmatrixBuilder.R -f AlphOrthogroups.ocurrence.csv -o Alpha
./Phylogenomic/OrthoFinder-SCOmatrixBuilder.R -f RevAlphOrthogroups.ocurrence.csv -o RevAlpha
```

It produced the SCO matrix representation for different % of gene occupancy : SCO.pdf

**Comment by davidemms** [comment]
Hi

OrthoFinder doesn't use any kind of reference sequence etc. The error is in your script perl script. It incorrectly counts the number of genes in the last species--if there are 0 genes in that species for that orthogroup it outputs 1 instead! 

The explanation of how OrthoFinder builds orthogroups is given in the OrthoFinder paper:
https://genomebiology.biomedcentral.com/articles/10.1186/s13059-015-0721-2

All the best
David
