### ISSUE TITLE
Newer versions of diamond

### ISSUE THREAD

**Issue by LifeMine-swyka** [davidemms/OrthoFinder#473]
Hello, 

I am installing orthofinder 2.4.0 via conda on a linux server and noticed that Orthofinder still only works with diamond versions <=0.9.24. Is this actually the case? Will Orthofinder be updated to work with diamond versions >=2.0.4?

**Comment by davidemms** [comment]
Hi

There was a problem with a version of diamond just after v0.9.24 but I hope it's been resolved now. I will check and then update the requirement. Thanks for raising this.

All the best
David

**Comment by LifeMine-swyka** [comment]
That's great! I look forward to it. I was always wondering if you thought about adding an argument to control the sensitivity setting of diamond? I assume the default is "fast", is that true?

**Comment by davidemms** [comment]
OrthoFinder sets it to "--more-sensitive" by default but you can adjust that or any of its other settings in the config.json file.

**Comment by Edison2021** [comment]
> r v0.9.24

Hi David
May I know what kind of problem cased by new version? Thanks!

**Comment by davidemms** [comment]
I've updated the conda recipe so that there is no longer an upper limit on the diamond version. Let me know if you have any issues.

All the best
David
