### ISSUE TITLE
paralogs and orthologs

### ISSUE THREAD

**Issue by krishnam** [davidemms/OrthoFinder#474]
Hi,
How do I extract the list of orthologs and paralogs from orthogroups ?
Are the multiple sequences of same species  in a given orthogroup called as paralogs ?

**Comment by davidemms** [comment]
Hi

The orthologues are all listed in "Orthologues/" directory and cross-referenced to the orthogroup they come from. Every pair of genes in an orthogroup that are not orthologues are therefore paralogues. In particular, all genes in an orthogroup from the same species are paralogues. 

An explanation is given here:
https://github.com/davidemms/OrthoFinder#orthogroups-orthologs--paralogs

All the best
David
