### ISSUE TITLE
ERROR: Species tree is not rooted

### ISSUE THREAD

**Issue by timregan** [davidemms/OrthoFinder#479]
[Mid.tree.txt](https://github.com/davidemms/OrthoFinder/files/5526953/Mid.tree.txt)
Hi there,

I would like to run Orthofinder to identify gene trees using a pre-computed species tree.
Any tree viewing software I have used assures me that my Newick tree is rooted, however, Orthofinder seems to think otherwise with the following error:
 ERROR: Species tree is not rooted

Any obvious reasons why this may be the case? 
Quite possible I'm missing something basic. Tree attached if it helps. 

Many thanks,
Tim

**Comment by davidemms** [comment]
Hi Tim

The tree currently has a tripartition at it's root, (N1,N2,N3). If you select one of these groups as the first group diverging from the remaining species and put the root on the branch leading to it then the tree will be correctly rooted. I.e. the root node will then be a bipartition.

All the best
David

**Comment by sknaack** [comment]
Hi David (Emms),

 I'm assessing the resolved gene trees from an analysis of >90 species presently. Two questions relating to the species tree/gene trees in this light. 

1. Is it a problem if a given input species tree (passed with the -s argument) isn't perfectly binary? Post analysis I found that the large species tree that I used as input (obtained from a collaborator) is actually not fully binary (although rooted). It was when I tried running dlcpar with it that this came to my attention and I got an error that it wasn't actually binary (one aberration for three extant species). With so many nodes I missed the aberrant branch when I checked. OrthoFinder 2 seemingly didn't fail, and I'm not seeing this requirement of a binary species tree emphasized as much as for other methods (like dlcpar), so I wondered if it was a definite problem or not. I can certainly readily re run the tree (-gt) analysis with this minor modification to the input species tree. 

2. How do you recommend confirming if further reconciliation analysis should be done on the resolved gene trees? such as with dlcpar? Figure 5 in the 2019 paper suggests the full dlcpar analysis is not likely tractable in my case, and the dlcpar search analysis would not likely be worthwhile. The resolved trees seem to be a reasonable working point in this light.

Thanks!

Sara (Knaack)

**Comment by davidemms** [comment]
Hi Sara

1. No it's not necessary, OrthoFinder can handle the species tree even if it's not binary. 

2. I think the reconciliation returned is the best that's currently achievable. If you wanted to test it then you could pick an individual tree and try a dlcpar analysis on it to see what orthologs it predicts and see if you think this is more or less accurate. But in general, although dlcpar could analyse it's own simulated dataset, the real world 4 species dataset was too large to be analysed, and the complexity increases *exponentially* with number of species. On the tests I did the accuracy also dropped off with larger trees. OrthoFinder's algorithm was more consistent in terms of accuracy as tree size increased. I didn't really focus on this much in the OrthoFinder paper but might publish a follow on paper that looks at this in more detail.

All the best
David
