### ISSUE TITLE
A insertion will resulting in a low bitscore?

### ISSUE THREAD

**Issue by 1398206876** [davidemms/OrthoFinder#483]
Hello David,

If gene A & gene B are orthologues，but in the evolution ,there is a large insertion in gene B, resulting in a low bitscore, will gene A & gene B be assigned to the same orthogroup？

If not ,How can I replace BLAST with some alignment programs that can support splice mapping ? Is it possible?

Thank you so much for your help!!!!!!

Best regards,

Haoyu

**Comment by davidemms** [comment]
Hi Haoyu

I think they should end up in the same orthogroup as long as there is enough homologous sequence to produce a hit either between the two sequences or between each of the sequences and other sequences also in the orthogroup. It will depend on the bit score compared to the bit scores for other sequences in the orthogroup. If you have an example where this isn't happening I'd be interested to see it. 

If you have a tool you want to replace BLAST with then there is a simple configuration file called "config.json" in the OrthoFinder directory where you just fill out the details for how to call the program. E.g. here's the entry for mmseqs, which allows you to select it on the OrthoFinder command line using the option "-S mmseqs":

```
    "mmseqs":{ 
    "program_type": "search",
    "db_cmd": "mmseqs createdb INPUT OUTPUT.fa ; mmseqs createindex OUTPUT.fa /tmp",
    "search_cmd": "mmseqs search PATH/mmseqsDBBASENAME DATABASE.fa OUTPUT.db /tmp/tmpBASEOUTNAME  --threads 1 ; mmseqs convertalis --threads 1 PATH/mmseqsDBBASENAME DATABASE.fa OUTPUT.db OUTPUT"
    },
```

Another way you could use this config functionality is that, for example, you could write a simple script that calls BLAST and then performs some post-processing on the results e.g. summing up all the BLAST hits between a pair of sequences. So you'd have a script e..g "my_blast" that looks like this:

```
script my_blast INFILE OUTFILE:
- Call BLAST on INFILE to produce results file OUTFILE
- Read OUTFILE, sum together hits and overwrite OUTFILE with new version of results file
```

and then you'd create an entry for "my_blast" in the config.json file telling OrthoFinder how to call it. This way when OrthoFinder calls "my_blast" it will get your modified BLAST results back.

All the best
David

**Comment by 1398206876** [comment]
Thank you!!!I'll be doing some of this work in the near future, and if I find an example I'll share it with you .Thanks again!

**Comment by davidemms** [comment]
No problem, I'll close the issue for now but reopen it if you have an example you want to share.

All the best
David
