### ISSUE TITLE
Conda version for Linux is 2.2.7

### ISSUE THREAD

**Issue by ryandward** [davidemms/OrthoFinder#486]
Would it be possible to update the version uploaded to Conda for Linux to a higher version? Many of parameters are unavailable in version 2.2.7.

**Comment by davidemms** [comment]
Hi Ryan

I think the noarch version should be suitable, isn't it? That's the latest version, 2.5.1. I may be wrong, but I thought the idea was that they were the correct solution since there is no need for separate packages for different platforms:
https://www.anaconda.com/blog/condas-new-noarch-packages

All the best
David

**Comment by davidemms** [comment]
Just to follow up on this: Is there something in your setup that it causing it to not pick up the latest version. Have you got any diagnostic output you can post? I didn't know this was something that could occur, if you can post the info I will see what there is I can do at my end to prevent it happening.

**Comment by ryandward** [comment]
Hi David,

Thank you for getting back to me so quickly. I am so sorry to drag you through this Conda stuff, I know it can be irritating. When I created this post, I was using my distro (Arch Linux) versions of all the flavors of Conda (Miniconda, Anaconda and Python-Conda) and could not access your noarch version with any of them

I just switched to the Miniconda distro-agnostic version from https://docs.conda.io/en/latest/miniconda.html which has fixed the issue.

I've spoken with a few colleagues today, and they have noted a similar issue accessing the noarch version with Conda maintained by distros.

Thanks again.

**Comment by davidemms** [comment]
Hi Ryan

Thanks for letting me know the details. In that case I think I'll look into creating an updated linux release in case others are also experiencing the same issue, it may be that a number of users are stuck on an older version without realising it!

All the best
David
