### ISSUE TITLE
Allow gzipped externally-computed blast results?

### ISSUE THREAD

**Issue by sujaikumar** [davidemms/OrthoFinder#49]
Hi David

Would it be easy to add support for gzipped Blast results? eg Blast0_1.txt.gz files in the case of externally computed Blasts?

Thanks!

**Comment by davidemms** [comment]
Hi Sujai

Yes, I think that would be relatively easy and sounds like a great idea! I'll see if I can add something over the next couple of weeks.

Thanks
David

**Comment by davidemms** [comment]
Hi

This is now available: 35bff26

OrthoFinder will now read gzipped blast results files (you can gzip old results files and still use them if you want). If you want to run a completely new OrthoFinder analysis you can use either "-S blast_gz" or "-S diamond" either of which will compress the sequence search results as they are calculated. In general I'd almost always recommend using diamond as it is far far faster (about 60x) and gives almost identical results, see 'Public Results' on the Quest for Orthologs website: http://orthology.benchmarkservice.org/cgi-bin/gateway.pl

All the best
David
