### ISSUE TITLE
[Errno 2] No such file or directory (alignment)

### ISSUE THREAD

**Issue by Fede-Rome** [davidemms/OrthoFinder#490]
Hallo David,

I got this warning (several actually, related to different OGs) at the gene tree inference step, when using -M msa -A muscle. Apparently some of the alignments files are not found.

WARNING: 
[Errno 2] No such file or directory: '/home/[...]/Results_Dec10_6/WorkingDirectory/Alignments_ids/OG0000030.fa'

Any clue? Many thanks for your help !

Federico

**Comment by Fede-Rome** [comment]
So I think it happened because some of the alignments were not produced (I think they were < 500 AAs after trimming). I will double check using the -z option (no trimming of the msa), should not get any warning

**Comment by davidemms** [comment]
Hi Federico

That's odd, and sounds like something might need fixing in the code. Would you be able to attach the file in 'WorkingDirectory/Sequences_ids/' for one of the alignments that wasn't found?

Many thanks
David

**Comment by Fede-Rome** [comment]
Hallo David,

here it is – for this OG no alignment file has been produced.

Many thanks again for your help, ciao for now,

Federico

**Comment by davidemms** [comment]
Hi Federico

I don't think the attachment worked, if you go to the github issue page you should be able to drag and drop the file there.

All the best
David

**Comment by Fede-Rome** [comment]
HI David,

here it is.

Many thanks ! 
Federico
[OG0000030.zip](https://github.com/davidemms/OrthoFinder/files/5702157/OG0000030.zip)

**Comment by davidemms** [comment]
I tried running muscle on this file and got a segmentation fault so it looks like that may be where the issue is.

**Comment by Fede-Rome** [comment]
OK great, I will !

**Comment by Fede-Rome** [comment]
So basically the developer of MUSCLE said the alignment was too large (>4000 sequences, avg length of 450 AAs) and could work only with the -maxiters 2 option. May I simply include this option in the command line when I start OrthoFinder ? Otherwise I will switch to mafft. 
Thanks again,
Federico

**Comment by davidemms** [comment]
Hi Federico

You can include that option in the "cmd_line" entry for "muscle" in the config.json file that's in the OrthoFinder directory.

All the best
David
