### ISSUE TITLE
No species tree made 

### ISSUE THREAD

**Issue by Jmaccaro** [davidemms/OrthoFinder#491]
Hi there, 
I ran orthofinder but it looks like it stopped right after generating Orthogroups. I did it with the -Mmsa and -S blast option originally. I need a species tree now but I didn't get anything after the orthogroups. How can I pick back up where I left off to finish and get a species tree?

**Comment by davidemms** [comment]
Hi

Have you got all the output that OrthoFinder printed to the terminal? It's hard to diagnose with so little information.

All the best
David
