### ISSUE TITLE
ERROR: Blast3_8.txt is corrupted

### ISSUE THREAD

**Issue by shiyi-pan** [davidemms/OrthoFinder#492]
Hi, I used orthofiner to do some research and met an error. here is my log file:

OrthoFinder version 2.4.1 Copyright (C) 2014 David Emms

2020-11-15 22:34:41 : Starting OrthoFinder 2.4.1
12 thread(s) for highly parallel tasks (BLAST searches etc.)
2 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "makeblastdb -help" - ok
Test can run "blastp -help" - ok
Test can run "mcl -h" - ok
Test can run "mafft /ds3512/home/panyp/NN1138-2/03.orthofinder_data/SoybeanData/OrthoFinder/Results_Nov15_1/WorkingDirectory//_dependencies_check/SimpleTest.
fa" - ok
Test can run "iqtree" - ok

WARNING: Files have been ignored as they don't appear to be FASTA files:
test.py
OrthoFinder expects FASTA files to have one of the following extensions: fasta, faa, fas, fa, pep

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2020-11-15 22:35:20 : Creating Blast database 1 of 36
2020-11-15 22:35:21 : Creating Blast database 2 of 36
2020-11-15 22:35:22 : Creating Blast database 3 of 36
2020-11-15 22:35:25 : Creating Blast database 4 of 36
2020-11-15 22:35:27 : Creating Blast database 5 of 36
2020-11-15 22:35:30 : Creating Blast database 6 of 36
2020-11-15 22:35:31 : Creating Blast database 7 of 36
2020-11-15 22:35:33 : Creating Blast database 8 of 36
2020-11-15 22:35:35 : Creating Blast database 9 of 36
2020-11-15 22:35:37 : Creating Blast database 10 of 36
2020-11-15 22:35:40 : Creating Blast database 11 of 36
2020-11-15 22:35:42 : Creating Blast database 12 of 36
2020-11-15 22:35:45 : Creating Blast database 13 of 36
2020-11-15 22:35:47 : Creating Blast database 14 of 36
2020-11-15 22:35:50 : Creating Blast database 15 of 36
2020-11-15 22:35:52 : Creating Blast database 16 of 36
2020-11-15 22:35:55 : Creating Blast database 17 of 36
2020-11-15 22:35:57 : Creating Blast database 18 of 36
2020-11-15 22:35:59 : Creating Blast database 19 of 36
2020-11-15 22:36:02 : Creating Blast database 20 of 36
2020-11-15 22:36:04 : Creating Blast database 21 of 36
2020-11-15 22:36:07 : Creating Blast database 22 of 36
2020-11-15 22:36:09 : Creating Blast database 23 of 36
2020-11-15 22:36:11 : Creating Blast database 24 of 36
2020-11-15 22:36:14 : Creating Blast database 25 of 36
2020-11-15 22:36:17 : Creating Blast database 26 of 36
2020-11-15 22:36:19 : Creating Blast database 27 of 36
2020-11-15 22:36:22 : Creating Blast database 28 of 36
2020-11-15 22:36:25 : Creating Blast database 29 of 36
2020-11-15 22:36:28 : Creating Blast database 30 of 36
2020-11-15 22:36:30 : Creating Blast database 31 of 36
2020-11-15 22:36:32 : Creating Blast database 32 of 36
2020-11-15 22:36:35 : Creating Blast database 33 of 36
2020-11-15 22:36:37 : Creating Blast database 34 of 36
2020-11-15 22:36:38 : Creating Blast database 35 of 36
2020-11-15 22:36:40 : Creating Blast database 36 of 36

Running BLAST all-versus-all
----------------------------
Using 12 thread(s)
2020-11-15 22:36:42 : This may take some time....

WARNING: program called by OrthoFinder produced output to stderr
Command: blastp -outfmt 6 -evalue 0.001 -query /ds3512/home/panyp/NN1138-2/03.orthofinder_data/SoybeanData/OrthoFinder/Results_Nov15_1/WorkingDirectory/Speci
es28.fa -db /ds3512/home/panyp/NN1138-2/03.orthofinder_data/SoybeanData/OrthoFinder/Results_Nov15_1/WorkingDirectory/BlastDBSpecies32 -out /ds3512/home/panyp
/NN1138-2/03.orthofinder_data/SoybeanData/OrthoFinder/Results_Nov15_1/WorkingDirectory/Blast28_32.txt

stdout
------
b''
stderr
------

b'Selenocysteine (U) at position 124 replaced by X\nSelenocysteine (U) at position 1225 replaced by X\nSelenocysteine (U) at position 1228 replaced by X\nSelenocysteine (U) at position 1225 replaced by X\nSelenocysteine (U) at position 124 replaced by X\nSelenocysteine (U) at position 1225 replaced by X\nSelenocysteine (U) at position 124 replaced by X\nSelenocysteine (U) at position 1228 replaced by X\nSelenocysteine (U) at position 298 replaced by X\nSelenocysteine (U) at position 301 replaced by X\nSelenocysteine (U) at position 43 replaced by X\nSelenocysteine (U) at position 1228 replaced by X\nSelenocysteine (U) at position 43 replaced by X\nSelenocysteine (U) at position 103 replaced by X\nSelenocysteine (U) at position 105 replaced by X\nSelenocysteine (U) at position 1228 replaced by X\nSelenocysteine (U) at position 440 replaced by X\nSelenocysteine (U) at position 473 replaced by X\nSelenocysteine (U) at position 475 replaced by X\nSelenocysteine (U) at position 243 replaced by X\nSelenocysteine (U) at position 138 replaced by X\nSelenocysteine (U) at position 141 replaced by X\nSelenocysteine (U) at position 138 replaced by X\nSelenocysteine (U) at position 141 replaced by X\nSelenocysteine (U) at position 82 replaced by X\nSelenocysteine (U) at position 103 replaced by X\nSelenocysteine (U) at position 105 replaced by X\nSelenocysteine (U) at position 1228 replaced by X\nSelenocysteine (U) at position 103 replaced by X\nSelenocysteine (U) at position 105 replaced by X\nSelenocysteine (U) at position 1228 replaced by X\nSelenocysteine (U) at position 103 replaced by X\nSelenocysteine (U) at position 105 replaced by X\nSelenocysteine (U) at position 1228 replaced by X\nSelenocysteine (U) at position 103 replaced by X\nSelenocysteine (U) at position 105 replaced by X\nSelenocysteine (U) at position 1228 replaced by X\nSelenocysteine (U) at position 103 replaced by X\nSelenocysteine (U) at position 105 replaced by X\nSelenocysteine (U) at position 1228 replaced by X\nSelenocysteine (U) at position 103 replaced by X\nSelenocysteine (U) at position 105 replaced by X\nSelenocysteine (U) at position 1228 replaced by X\nSelenocysteine (U) at position 1228 replaced by X\nSelenocysteine (U) at position 876 replaced by X\nSelenocysteine (U) at position 877 replaced by X\nSelenocysteine (U) at position 142 replaced by X\nSelenocysteine (U) at position 1185 replaced by X\nSelenocysteine (U) at position 1228 replaced by X\nSelenocysteine (U) at position 142 replaced by X\nSelenocysteine (U) at position 1185 replaced by X\nSelenocysteine (U) at position 876 replaced by X\nSelenocysteine (U) at position 877 replaced by X\nSelenocysteine (U) at position 1228 replaced by X\nSelenocysteine (U) at position 142 replaced by X\nSelenocysteine (U) at position 1185 replaced by X\nSelenocysteine (U) at position 1228 replaced by X\nSelenocysteine (U) at position 440 replaced by X\nSelenocysteine (U) at position 51 replaced by X\nSelenocysteine (U) at position 196 replaced by X\nSelenocysteine (U) at position 299 replaced by X\nSelenocysteine (U) at position 49 replaced by X\nSelenocysteine (U) at position 103 replaced by X\nSelenocysteine (U) at position 105 replaced by X\nSelenocysteine (U) at position 1228 replaced by X\nSelenocysteine (U) at position 103 replaced by X\nSelenocysteine (U) at position 105 replaced by X\nSelenocysteine (U) at position 1228 replaced by X\nSelenocysteine (U) at position 103 replaced by X\nSelenocysteine (U) at position 105 replaced by X\nSelenocysteine (U) at position 1228 replaced by X\nSelenocysteine (U) at position 103 replaced by X\nSelenocysteine (U) at position 105 replaced by X\nSelenocysteine (U) at position 1228 replaced by X\nSelenocysteine (U) at position 1228 replaced by X\nSelenocysteine (U) at position 142 replaced by X\nSelenocysteine (U) at position 1185 replaced by X\nSelenocysteine (U) at position 1228 replaced by X\nSelenocysteine (U) at position 876 replaced by X\nSelenocysteine (U) at position 877 replaced by X\nSelenocysteine (U) at position 97 replaced by X\nSelenocysteine (U) at position 170 replaced by X\nSelenocysteine (U) at position 440 replaced by X\nSelenocysteine (U) at position 51 replaced by X\nSelenocysteine (U) at position 196 replaced by X\nSelenocysteine (U) at position 299 replaced by X\nSelenocysteine (U) at position 49 replaced by X\nSelenocysteine (U) at position 473 replaced by X\nSelenocysteine (U) at position 475 replaced by X\nSelenocysteine (U) at position 243 replaced by X\nSelenocysteine (U) at position 1228 replaced by X\nSelenocysteine (U) at position 1228 replaced by X\nSelenocysteine (U) at position 876 replaced by X\nSelenocysteine (U) at position 877 replaced by X\nSelenocysteine (U) at position 142 replaced by X\n

2020-12-24 22:16:28 : Done all-versus-all sequence search

Running OrthoFinder algorithm
-----------------------------
2020-12-24 22:16:38 : Initial processing of each species
2020-12-24 22:39:13 : Initial processing of species 1 complete
ERROR: Blast3_8.txt is corrupted
ERROR: Error processing files Blast3_*

ERROR: 12th field in BLAST results file line should be the bit-score for the hit
Malformatted line in /ds3512/home/panyp/NN1138-2/03.orthofinder_data/SoybeanData/OrthoFinder/Results_Nov15_1/WorkingDirectory/Blast3_8.txt
Offending line was:
3_11741 8_4849  31.75   211     122     6       7       198
Process Process-15:
Traceback (most recent call last):
  File "/ds3512/home/panyp/ruanjian/python36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/ds3512/home/panyp/ruanjian/python36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/ds3512/home/panyp/ruanjian/OrthoFinder_source/scripts_of/__main__.py", line 520, in Worker_ProcessBlastHits
    WaterfallMethod.ProcessBlastHits(*args, d_pickle=d_pickle, qDoubleBlast=qDoubleBlast)
  File "/ds3512/home/panyp/ruanjian/OrthoFinder_source/scripts_of/__main__.py", line 507, in ProcessBlastHits
    Bij = blast_file_processor.GetBLAST6Scores(seqsInfo, blastDir_list, seqsInfo.speciesToUse[iSpecies], seqsInfo.speciesToUse[jSpecies], qDoubleBlast=qDoubleBlast)
  File "/ds3512/home/panyp/ruanjian/OrthoFinder_source/scripts_of/blast_file_processor.py", line 75, in GetBLAST6Scores
    score = float(row[11])
IndexError: list index out of range
2020-12-24 22:38:15 : Initial processing of species 0 complete
WARNING: Too few hits between species 2 and species 34 to normalise the scores, these hits will be ignored
2020-12-24 23:24:45 : Initial processing of species 2 complete
ERROR: An error occurred, ***please review the error messages*** they may contain useful information about the problem.

here is the  Blast3_8.txt file:

3_5     8_14896 64.94   425     145     2       1       421     1       425     0.0      565
3_5     8_23685 61.40   430     155     5       1       421     1       428     0.0      522
3_5     8_17750 61.40   430     155     5       1       421     1       428     0.0      522
3_5     8_18354 71.23   351     87      2       27      364     1       350     0.0      515
3_5     8_4021  60.32   431     160     5       1       421     1       430     0.0      517
3_5     8_29787 60.88   432     156     6       1       421     1       430     0.0      516
3_5     8_45781 68.03   319     102     0       1       319     1       319     3e-164   474
3_5     8_41014 68.03   319     102     0       1       319     1       319     4e-164   474
3_5     8_38599 66.16   328     110     1       1       327     1       328     2e-163   473

could you help me fix this problem ? thank you very much.

**Comment by davidemms** [comment]
Hi 

There appears to be a problem with the  Blast3_8.txt file produced by BLAST. The first few lines that you have pasted look like the correct format E.g.

3_5 8_14896 64.94 425 145 2 1 421 1 425 0.0 565

but OrthoFinder says it found the line:

3_11741 8_4849 31.75 211 122 6 7 198

which doesn't have the 12th entry in it, which is the BLAST bit score, which it needs. 

So something has gone wrong with BLAST. Do you have any ideas for what the problem could be? 

If there is a problem with just that file then you can just run that BLAST process again with:
```
blastp -outfmt 6 -evalue 0.001 -query WorkingDirectory/Species3.fa -db WorkingDirectory/BlastDBSpecies8 -out WorkingDirectory/Blast3_8.txt
```
And then start orthofinder again from the BLAST files:
```
orthofinder -b Results_Nov15_1/ -M msa -T iqtree
```

There was another warning in your output that you should also check:
> WARNING: Too few hits between species 2 and species 34 to normalise the scores, these hits will be ignored

Did you include all the protein sequences for these species? You can see the species IDs in "WorkingDirectory/SpeciesIDs.txt".

All the best
David

**Comment by shiyi-pan** [comment]
Ok, thank you for your reply, David. I will try as you suggest. Thank you .
