### ISSUE TITLE
Using RAxML for species tree and FastTree for gene trees?

### ISSUE THREAD

**Issue by pierrj** [davidemms/OrthoFinder#493]
Is it possible to use a different tree software for the species tree (slower, more accurate like RAxML) and the gene tree (but I don't want OrthoFinder to take forever to run)? Looks like there could be a solution using the -oa (stop after gene MSA calculation) but I was wondering if anyone had a solution for this. I'll post mine here if no one responds before I have time to work on it.

**Comment by davidemms** [comment]
Hi Pierre

The species tree is only used for the final stage of OrthoFinder, where it analyses the gene trees, so you can just do this:

0. Download the latest version of OrthoFinder, it's got some improvements relevant for this
1. Run orthofinder to completion using "-M msa" and the (faster) tree inference method you want to use for the gene trees.
2. Infer the species tree yourself using RAxML on the species tree MSA, which is here: "MultipleSequenceAlignments/SpeciesTreeAlignment.fa"
3. Run the final stage of OrthoFinder using `orthofinder -ft RESULTS_DIR -s YOUR_SPECIES_TREE`

Step 3 will analyse the gene trees using your new species tree. 

All the best
David

**Comment by pierrj** [comment]
Awesome thank you!
