### ISSUE TITLE
error running diamond but fine with blast

### ISSUE THREAD

**Issue by sethbarr** [davidemms/OrthoFinder#496]
Hi David, 

I've been attempting to get orthofinder running from the source installation. Running the example data is working with blast but diamond throws the following error

```
./orthofinder.py -f ExampleData/ 
OrthoFinder version 2.5.2 Copyright (C) 2014 David Emms

2021-01-18 03:45:08 : Starting OrthoFinder 2.5.2
24 thread(s) for highly parallel tasks (BLAST searches etc.)
3 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------

ERROR: Cannot run diamond
Format of make database command:
  diamond makedb --in INPUT -d OUTPUT
ERROR: Cannot run diamond
Format of search database command:
  diamond blastp -d DATABASE -q INPUT -o OUTPUT --more-sensitive -p 1 --quiet -e 0.001 --compress 1
Please check diamond is installed and that the executables are in the system path

ERROR: An error occurred, ***please review the error messages*** they may contain useful information about the problem.
```

Calling diamond directly seems to work fine: 

```
diamond help
diamond v2.0.6.144 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org

Syntax: diamond COMMAND [OPTIONS]

Commands:
makedb  Build DIAMOND database from a FASTA file
...
```

Running with the ```-S blast``` seems to run just fine.

**Comment by davidemms** [comment]
Can you try running diamond to create a database and to search some sequences against that database and see if that works. You can use one of the fasta files in the Example Data, the format of the commands you need is given in the error message you've pasted above.

If diamond works successfully for that, there one other rare issue that you can check: If you downloaded OrthoFinder from the github page then the version of diamond it will use is in the bin/ or scripts_of/bin directory in the orthofinder package. In a few cases users have a version of diamond that works on their machine but the one packaged with OrthoFinder doesn't. If that's the case you can delete the one packged with OrthoFinder and it will use the one installed on the system.

All the best
David

**Comment by sethbarr** [comment]
Thank you David. I appear to have run into that rare issue. Removing diamond from the scripts_of/bin fixed it. Thanks for the fast response!
