### ISSUE TITLE
Unable to Execute Orthofinder Command

### ISSUE THREAD

**Issue by mh425** [davidemms/OrthoFinder#497]
Hi, I am following the "[Downloading and running Orthofinder](https://davidemms.github.io/orthofinder_tutorials/downloading-and-running-orthofinder.html)" tutorial, and after completing all the prior steps I am unable to run request Orthofinder to print its help file or run Orthofinder on the example data. 

Instead I receive this message "./orthofinder: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/_MEIwYKN9o/libz.so.1)"

Any suggestions?

**Comment by davidemms** [comment]
Hi

It looks like you've got a very old C library on your computer (pre 2012?) so you won't be able to use the packaged version of orthofinder, but the python version should work fine ("OrthoFinder_source.tar.gz" from https://github.com/davidemms/OrthoFinder/releases). This requires python to be installed (it almost certainly will be already) plus the numpy and scipy libraries. There are two options for setting up these requirements:

1. Install the required numpy & scipy libraries yourself. This is the usually the easiest.
2. Install OrthoFinder using bioconda, this will install the libraries for you. This is easiest if you're already using conda.

For installing the libraries yourself, just google the commands for your linux distribution. E.g. for ubuntu it is `sudo apt-get install python-numpy python-scipy`. More details here: https://www.scipy.org/install.html

Alternatively, there are details on using bioconda here:
https://davidemms.github.io/orthofinder_tutorials/alternative-ways-of-getting-OrthoFinder.html

All the best
David

**Comment by mh425** [comment]
Hi David! Thank you so much for your help. I am new to this and thanks to you I was able to run Orthofinder successfully. :)

I was wondering how I could specify the species tree using the -s and -ft options. For example, if I want my species tree to follow this order 
"Aethionema(Heliophila(Arabidopsis, Caulanthus))", how exactly do I input this as a <file>?

**Comment by davidemms** [comment]
Hi

The species tree needs to be in Newick format in a text file. So "Aethionema(Heliophila(Arabidopsis, Caulanthus));", but with the species names exactly matching the filenames with the filename extensions removed. You don't need branch lengths. It will tell you if you have any error in your file. 

All the best
David
