### ISSUE TITLE
What evolutionary models are used to construct the species tree?

### ISSUE THREAD

**Issue by Neato-Nick** [davidemms/OrthoFinder#498]
Hi,

I'm looking for details to describe how the species tree was made when -m msa is enabled. So far in the OrthoFinder documentation I've just been able to find that FastTree is used, but [there are multiple models that can be selected.](http://www.microbesonline.org/fasttree/)

> FastTree uses the Jukes-Cantor or generalized time-reversible (GTR) models of nucleotide evolution and the JTT (Jones-Taylor-Thornton 1992), WAG (Whelan & Goldman 2001), or LG (Le and Gascuel 2008) models of amino acid evolution. To account for the varying rates of evolution across sites, FastTree uses a single rate for each site (the "CAT" approximation). To quickly estimate the reliability of each split in the tree, FastTree computes local support values with the Shimodaira-Hasegawa test (these are the same as PhyML 3's "SH-like local supports").

It looks like the default is JTT+CAT for amino acid evolution, is that just what orthofinder uses?

**Comment by davidemms** [comment]
Hi Nick

Yes, it uses the default model.

All the best
David
