### ISSUE TITLE
Get alignment without searching for trees

### ISSUE THREAD

**Issue by drelo** [davidemms/OrthoFinder#5]
I don't know how computationally demanding is the stage of using FastTree in the trees_for_orthogroups stage but is there a way to skip this step to obtain just the fasta alignments. Thanks for your help.

**Comment by davidemms** [comment]
Hi, there isn't an option for doing this but you could just replace line 198 in trees_for_orthogroups.py which reads "commandsSet = [(alignCmd, treeCms) for alignCmd, treeCms in zip(alignCommands, treeCommands)]" with "commandsSet = [(alignCmd, ) for alignCmd, treeCms in zip(alignCommands, treeCommands)]" and that will skip the inference of trees.

**Comment by drelo** [comment]
Thanks for your help.

El mar., 20 de oct. de 2015 a la(s) 10:19 a. m., davidemms <
notifications@github.com> escribió:

> Closed #5 <https://github.com/davidemms/OrthoFinder/issues/5>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidemms/OrthoFinder/issues/5#event-440318240>.
>
-- 

Postdoctoral Associate

Instituto de Cs Ambientales y Evolutivas
Universidad Austral de Chile
Campus Isla Teja s/n
Valdivia, Chile

**Comment by mdebiasse** [comment]
Good morning. Given this thread is about a year old, is this still the best way to get orthologue sequence alignments from OrthoFinder? Thank you!
