### ISSUE TITLE
Orthoxml Format

### ISSUE THREAD

**Issue by dandaman** [davidemms/OrthoFinder#50]
Hi David,

as I had trouble with this in the last two runs I want to make sure I've got the format right for the file provided by -x to obtain orthoxml format.

I'm am using the latest commit. 
The example from the manual:
HomSap.fa<tab>Homo sapiens<tab>36<tab>Ensembl<tab>Homo_sapiens.NCBI36.52.pep.all.fa

Does HomSap.fa need to be the file name as I initially gave it to orthofinder i.e. the same as value in the SpeciesID.txt column 2?

If I understand it correctly the only other field with restricted text is the NCBI taxonomy ID, the rest is not further checked and just used to fill xml content?

Best,
Daniel

**Comment by davidemms** [comment]
Yes, it should be the same as the filename (matching column 2 of SpeciesIDs.txt). 

However, I've just checked the code and if there is more than one dot in the original filename (eg. "Some_species.version3.fa") then it might have problems matching it. I will submit a fix for this.  There is no restriction on the NCBI taxonomy ID, the info is just used to fill the xml content.

All the best
David

**Comment by dandaman** [comment]
Hi David,

thanks for your response. I.e. for now I should either avoid >1dots in the fasta filenames or not use -x.

Best,
Daniel

**Comment by davidemms** [comment]
Hi Daniel

This has now been resolved, dots in the filename no longer cause a problem.

All the best
David
