### ISSUE TITLE
Species Tree seems not Right

### ISSUE THREAD

**Issue by biozhangzhou** [davidemms/OrthoFinder#501]
Hello SIr:

I'm using some gene clusters from genomes which have good quality of annotation and some other gene cluster which do not have a high quality annotation to do the gene famlily analysis by OrthoFinder;
But the result Species tree seems to cluster those high quality genome together, it there any reason for it ? And what i do to avoid it ?
Thanks

**Comment by biozhangzhou** [comment]
Hello SIr:

I'm using some gene clusters from genomes which have good quality of annotation and some other gene cluster which do not have a high quality annotation to do the gene famlily analysis by OrthoFinder;
But the result Species tree seems to cluster those high quality genome together, it there any reason for it ? And what i do to avoid it ?
Thanks

**Comment by davidemms** [comment]
Hi

How many sequences have you got in each species? Did OrthoFinder print any messages to screen about species tree inference? 

If the species tree is incorrect then you can correct the species tree yourself and provide the corrected tree to OrthoFinder using "-ft RESULTS_DIR -s SPECIES_TREE_FILE". This only needs to run the final step of OrthoFinder with the corrected tree and so it is comparatively quick.

All the best
David

**Comment by biozhangzhou** [comment]
I input  similar numbers of sequence for each specie. 
I think I figured why would wrong tree be produced. Due to the poor annotation quality of some species, their mRNA file may be problematic. Then I checked it and find some species have much more -(missing) in the .msa file than the other. I should try some other way to get the better gene sequence first.
