### ISSUE TITLE
Error code 127. Blast databases

### ISSUE THREAD

**Issue by Johno78** [davidemms/OrthoFinder#502]
Hi David,

I've been running OrthoFinder (2.5.2) successfully with protein sequences but I've run into a problem with trying to use nucleotides. It seems the makeblastdb command isn't being found. I changed to versions 2.5.1 and 2.5.2 (and ran on a different computer) without success.

I've attached a file showing the error. Perhaps I'm missing something extra I need to be doing?

Cheers,
John
[error.txt](https://github.com/davidemms/OrthoFinder/files/5928788/error.txt)

**Comment by davidemms** [comment]
Hi John

It will use BLAST for this so you will need to install that on your system. There are some instructions for getting hold of BLAST here: https://github.com/davidemms/OrthoFinder#optional-blast

All the best
David

**Comment by Johno78** [comment]
Hi David,

Thanks for your response. I'd missed the fact that running OrthoFinder on nucleotides required BLAST whereas protein sequences (by default) only needed Diamond.

Cheers,
John
