### ISSUE TITLE
SingleCopyOrthogroups.txt is empty

### ISSUE THREAD

**Issue by Liuzixuan2020** [davidemms/OrthoFinder#505]
Hi David,
These days,I run the OrthoFinder using the protein of 14 species and I run many times but all the results of SingleCopyOrthogroups.txt is empty.At first , I thought maybe it is because i didn't filter the isoform of each proteome,but after I filtered those sequences, the SingleCopyOrthogroups.txt is still empty.At the meantime,I also used Orthomcl do the same thing,but also had no singlecopy gene in those species.I think it is unnormal because one article says these species have about 6000 singlecpoy genes.I am quite confused now. Could you tell me how to find these Singlecopy genes?

Thank you！
liuzixuan

**Comment by davidemms** [comment]
Hi liuzixuan

I think it's unlikely that the species have 6000 single-copy genes. You could inspect the tree returned by OrthoFinder for any of the genes that the article claims are single-copy and I think that will probably confirm that they are not.

Best wishes
David

**Comment by Liuzixuan2020** [comment]
Hi David,

I wonder if the problem with the protein sequence of just one species will lead to the result of singlecopy genes being wrong,and I'll try to do what you suggested.

Thanks a lot!
liuzixuan

**Comment by davidemms** [comment]
Hi liuzixuan

The `Orthogroups/Orthogroups.GeneCount.tsv` will help you confirm this. You can analyse it to see which orthogroups are single-copy in all but one of your species.

Best wishes
