### ISSUE TITLE
Orthofinder results with CAFE

### ISSUE THREAD

**Issue by mictadlo** [davidemms/OrthoFinder#512]
Hi
I found [here](http://evomicsorg.wpengine.netdna-cdn.com/wp-content/uploads/2016/06/cafe_tutorial-1.pdf) a tutorial on how to run CAFE with MCL. However, I wonder whether it would be possible to use Orthofinder results instead of MCL?

Thank you in advance

Michal

**Comment by Liuzixuan2020** [comment]
Hi mictadlo,
I recommend a tutorial about using Orthofinder results to do CAFE. Here is the website (https://www.yuque.com/shawn-yepfo/oxua15/ftrlin) and It is written in Chinese.Wish I could help you
liuzixuan

**Comment by harish0201** [comment]
Hi,

I wrote a small tutorial a while back for running CAFE with Orthofinder, FWIW, let me link the same here:
https://github.com/harish0201/Analyses_Pipelines/blob/main/7.CAFE.sh

Let me know if you have any doubts.

**Comment by mictadlo** [comment]
Hi,
Thank you for sharing the links. How is it possible to determine the [age](https://github.com/harish0201/Analyses_Pipelines/blob/main/7.CAFE.sh#L43) parameter in `python2.7 OrthoFinder/tools/make_ultrametric.py -r age SpeciesTree_rooted.txt`?

Thank you in advance

Michal

**Comment by davidemms** [comment]
Hi Michal

That's the number of million years ago that your species began diverging. It's only an optional parameter, which will rescale the branch lengths for you. I think you would have to determine that from fossil evidence or with genes calibrate to fossil evidence. This is the first link I found on google:
https://doi.org/10.1016/j.crpv.2013.07.003

Best wishes
David
