### ISSUE TITLE
ExampleDataset > ExampleData

### ISSUE THREAD

**Issue by ghbhc** [davidemms/OrthoFinder#513]
Hello,

I was installing from the 2.5.2 source tarball, and ran into an error with the setup.py where it was looking for a dir called "ExampleDataset," but it appears that has been renamed to "ExampleData," so it failed.  Updating the occurrences of that string in the setup.py fixed the issue for me.  Just wanted to let you know.

**Comment by davidemms** [comment]
Thanks, I'll update!
