### ISSUE TITLE
ModelFinder error and missing SpeciesTree

### ISSUE THREAD

**Issue by KnudNorNielsen** [davidemms/OrthoFinder#516]
Hello David

Running OrthoFinder I ended up with an error in the SpeciesTree.log (below).
As a result, the run stopped with the Alignments and Gene_Trees folders empty.

It has been a large run with 17 genomes, and I would prefer not to rerun the alignments and trees, and will therefore like to hear if it is possible to restart from where it stopped.
It needs to have ModelFinder within IQtree run in -safe mode; how do you propose I could do that in the context of OrthoFinder (2.2.7)?

Cheers
Knud

SpeciesTree.log
> cat source/Results_Feb11/Orthologues_Feb15/WorkingDirectory/Alignments_ids/SpeciesTree.log

> IQ-TREE multicore version 1.6.12 for Linux 64-bit built Aug 15 2019
> Developed by Bui Quang Minh, Nguyen Lam Tung, Olga Chernomor,
> Heiko Schmidt, Dominik Schrempf, Michael Woodhams.
> 
> Host:    g-03-c0175 (AVX512, FMA3, 188 GB RAM)
> Command: iqtree -s /home/projects/cu_10081/generateddata/SCO/macARSEF324/orthoFinder/source/Results_Feb11/Orthologues_Feb15/WorkingDirectory/Alignments_ids/SpeciesTreeAlignment.fa -pre /home/projects/cu_10081/generateddata/SCO/macARSEF324/orthoFinder/source/Results_Feb11/Orthologues_Feb15/WorkingDirectory/Alignments_ids/SpeciesTree
> Seed:    468935 (Using SPRNG - Scalable Parallel Random Number Generator)
> Time:    Mon Feb 15 15:18:14 2021
> Kernel:  AVX+FMA - 1 threads (40 CPU cores detected)
> 
> HINT: Use -nt option to specify number of threads because your CPU has 40 cores!
> HINT: -nt AUTO will automatically determine the best number of threads to use.
> 
> Reading alignment file /home/projects/cu_10081/generateddata/SCO/macARSEF324/orthoFinder/source/Results_Feb11/Orthologues_Feb15/WorkingDirectory/Alignments_ids/SpeciesTreeAlignment.fa ... Fasta format detected
> Alignment most likely contains protein sequences
> Alignment has 17 sequences with 689770 columns, 146737 distinct patterns
> 149643 parsimony-informative, 130769 singleton sites, 409358 constant sites
>     Gap/Ambiguity  Composition  p-value
>    1  11    1.29%    failed      0.00%
>    2  10    0.77%    passed     73.50%
>    3  13    0.47%    passed     92.24%
>    4  12    0.52%    passed     87.97%
>    5  15    1.57%    failed      0.00%
>    6  14    2.65%    failed      0.00%
>    7  16    4.68%    failed      0.00%
>    8  1     2.30%    passed     51.74%
>    9  0     2.21%    failed      0.00%
>   10  3     9.06%    passed      9.83%
>   11  2     3.18%    passed     48.00%
>   12  5     2.50%    failed      0.00%
>   13  4     0.99%    passed     81.56%
>   14  7     3.52%    passed     63.97%
>   15  6     0.85%    passed     74.94%
>   16  9     0.55%    passed     95.73%
>   17  8     0.68%    passed     94.96%
> ****  TOTAL    2.22%  6 sequences failed composition chi2 test (p-value<5%; df=19)
> NOTE: minimal branch length is reduced to 0.000000144976 for long alignment
> 
> 
> Create initial parsimony tree by phylogenetic likelihood library (PLL)... 388.647 seconds
> NOTE: ModelFinder requires 3854 MB RAM!
> ModelFinder will test 546 protein models (sample size: 689770) ...
>  No. Model         -LnL         df  AIC          AICc         BIC
>   1  Dayhoff       5190868.533  31  10381799.066 10381799.069 10382153.833
>   2  Dayhoff+I     5077118.139  32  10154300.278 10154300.281 10154666.489
>   3  Dayhoff+G4    5058467.283  32  10116998.565 10116998.568 10117364.777
>   4  Dayhoff+I+G4  5057682.739  33  10115431.478 10115431.482 10115809.134
>   5  Dayhoff+R2    5060108.068  33  10120282.136 10120282.139 10120659.792
>   6  Dayhoff+R3    5055744.815  35  10111559.631 10111559.634 10111960.175
> **ERROR: Numerical underflow (lh-branch). Run again with the safe likelihood kernel via `-safe` option**

**Comment by davidemms** [comment]
Hi Knud

I'd recommend upgrading to the latest OrthoFinder version. If it failed on the species tree inference step then it is likely only a small proportion of the way into the tree inference stage. You can look in WorkingDirectory/Alignments_ids and WorkingDirectory/Trees_ids/ to see how many have been done. In this case, I would recommend starting the tree inference again from the completed orthogroups using the "-fg" option. You can edit the command line options for IQTREE in the config.json file in OrthoFinder.

A word of warning, I've not been able to make use of IQTREE myself for OrthoFinder as the scale of the task is far larger than the standard use case for IQTREE. For genome wide gene tree inference you need to infer perhaps 20,000 gene trees and with some gene families having thousands or tens of thousands of genes. IQTREE is a fantastic tool, but people just don't run it on this scale of task. It's better used on just those individual gene families you're particularly interested in. It's likely that IQTREE will require more RAM than you have available, even if you reduce the number of tasks running in parallel using the "-t" option.

Alternatively, if you wanted to not rerun any of the trees then you could:

1. Upgrade OrthoFinder to the latest version
2. Run this on your previous results directory using "-fg PREVIOUS_RESULTS_DIRECTORY/ -M msa". This will do a complete run but using FastTree.
3. Using as input the files in WorkingDirectory/Alignments_ids/ infer with IQTREE all (or some of!) the orthogroup trees. Put these new trees in WorkingDirectory/Trees_ids making sure the names match the original names. You can also do the same with the species tree.
4. Run OrthoFinder using "-ft PREVIOUS_RESULTS_DIRECTORY/" to analyse your new trees.

Best wishes 
David
