### ISSUE TITLE
ulimit error despite updating ulimit = r

### ISSUE THREAD

**Issue by garmonan** [davidemms/OrthoFinder#517]
Hi!

I'm trying to run Orthofinder with 213 species, and I encountered the error related to the number of files that a process can open. This already happened with a previous smaller dataset, and I fixed it updating the ulimit as it is suggested in the error message and it worked nicely. However, this time I'm at the step of "Reconciling gene and species trees" and the proposed solutions do not work.

I first tried with running the command  ulimit -n 45469 (which is the minimum r suggested by the error message), and confirmed that it had been updated after running ulimit -Hn and ulimit -Sn and seeing the same number on each. I restarted Orthofinder with the -ft command, and got the same error.

I also tried to change it manually in the /etc/security/limits.conf file, as it is alternatively suggested by the same error message. Restarted the program, and again the same error.

Am I doing something wrong? Thank you very much in advance for your help!

/Andrea

**Comment by garmonan** [comment]
PS. Some extra information, in case it can help:

When I open another terminal and run the ulimit -Hn and ulimit -Sn commands, they seem to be back to their default values. Then I update with ulimit -n 45469, verify that it has changed, restart orthofinder in that terminal window, and again the same error as explained in my main message.

**Comment by garmonan** [comment]
Hi again, 

I managed to fix the problem, I add here the post where I found the solution, in case someone else encounters the same problem as I did.

https://forums.linuxmint.com/viewtopic.php?t=300638

Cheers!

**Comment by davidemms** [comment]
Hi Andrea

Thanks for the update and for posting the link, I wasn't aware of that linux behaviour before. That's a big help for other uses who encounter the same issue!

Best wishes
David
