### ISSUE TITLE
conda installing older version of orthofinder 2.2.6

### ISSUE THREAD

**Issue by shzadiqbal** [davidemms/OrthoFinder#518]
hi all 
`conda install -c bioconda orthofinder`  
and 
`conda install -c bioconda/label/cf201901 orthofinder`

 orthofinder-2.2.6          |           py27_0          94 KB  bioconda/label/cf201901

this installs the older version of orthofinder and needs to be updated on conda repository. 

thank you

**Comment by davidemms** [comment]
Hi 

The latest version of conda is already version 2.5.2.

Someone reported a similar sounding problem with conda here, it may help: https://github.com/davidemms/OrthoFinder/issues/486

Best wishes
David
