### ISSUE TITLE
Option -os not working

### ISSUE THREAD

**Issue by SWittouck** [davidemms/OrthoFinder#52]
Hi David,

I am running OrthoFinder 1.1.4 and I noticed in the help info (-h) that it is possible to stop orthofinder after the orthogroup inference, while still outputting a fasta file per orthogroup (option -os). However, when I try this, OrthoFinder infers the orthogroups just fine, but then starts running Orthologue Prediction. This seems strange to me since it should stop before that step? In my case, this also produces the error "fastme: command not found" since I didn't install fastme (because I don't want OrthoFinder to infer trees). When I check the OrthoFinder output, I cannot find fasta files per orthogroup. 

Am I understanding the "-os" option incorrectly, or is it possible that this option does not show the desired behaviour? 

I enclosed my output in the file "OrthoFinder_error.txt" and the command I ran is the following:
orthofinder -f $pin_sequences -og -t 4

Kinds regards,
Stijn
[OrthoFinder_error.txt](https://github.com/davidemms/OrthoFinder/files/817089/OrthoFinder_error.txt)

**Comment by davidemms** [comment]
Hi Stijin

Sorry for the delay in replying. In order to use this option you also need to include the option "-M msa". I'll update the help output so it informs the user of this and I also have a figure explaining the options which I will include with future releases of OrthoFinder.
[OrthoFinder-options.pdf](https://github.com/davidemms/OrthoFinder/files/855587/OrthoFinder-options.pdf)

All the best 
David

**Comment by SWittouck** [comment]
Hi David,

Thanks for your reply. Adding the option -M msa worked perfectly!

Kind regards,
Stijn

**Comment by KUKUAFANGA** [comment]
Hi David, I have used OrthoFinder severally on my Mac OS and I am currently having issues when trying to replicate the analysis on a Linux OS.
I followed the instructions to install, after which i ran the example on the data set successfully. However I'm trying to run another analysis and upon extracting primary transcripts successfully, the command below fails to launch orthofinder: 

orthofinder -f primary_transcripts/

I'm getting 

(base) user:~/orthofinder_tutorial/OrthoFinder/PROTEOMES/primary_transcripts$ orthofinder -f primary_transcripts/
orthofinder: command not found

WHAT DO YOU SUGGEST I DO?

**Comment by davidemms** [comment]
Hi

There's a few different ways of installing orthofinder, did you download it from the OrthoFinder github page? If so, there's a packaged and a python source code version. If it's the source code version use
```python path_to_downloaded_orthofinder/orthofinder.py``` 
or with the packaged version use 
```path_to_downloaded_orthofinder/orthofinder``` 
plus whatever options you want to user. Replace "path_to_downloaded_orthofinder" with the correct path for where you downloaded and extracted OrthoFinder.

All the best 
David

**Comment by KUKUAFANGA** [comment]
user@IMGWKS1:~/orthofinder_tutorial/OrthoFinder$

i've been working in the right path since

**Comment by KUKUAFANGA** [comment]
Yes i downloaded it from the orthofinder github page

**Comment by KUKUAFANGA** [comment]
for f in *fa ; do python ~/orthofinder_tutorial/OrthoFinder/tools/primary_transcript.py $f ; done

The above works fine

Wrote 16570 genes
/home/user/orthofinder_tutorial/PROTEOMES/primary_transcripts/Teleopsis_dalmanni.Tel_dalmanni_2A_v1.0.pep.all.fa
(base) user@IMGWKS1:~/orthofinder_tutorial/PROTEOMES$ orthofinder -f primary_transcripts/
orthofinder: command not found
 
The command required to launch OrthoFinder still not found

**Comment by davidemms** [comment]
On Linux (and other systems) unless you've put an executable in the system path you will need to specify the full path to the executable file so that the computer knows where to find it. My answer above shows how to do this.

**Comment by KUKUAFANGA** [comment]
Thank you so much, I was working in the wrong path
