### ISSUE TITLE
Obtaining more trees

### ISSUE THREAD

**Issue by matthewturk5** [davidemms/OrthoFinder#522]
Hi David,

I have been using Orthofinder to try and generate trees for my orthogroups. I am using a large quantity of genomic information meaning that I have well over 2000 orthogroups for each of my categories. The trees that were generated when I ran the programme seem to always 'cap' at around OG0000900-OG0001000, meaning I am unable to view trees for later orthogroups. Is there a way to resolve this issue so that I am able to download and view trees for orthogroups that fall beyond this 'cap' e.g. OG0002680?

Apologies if this is unclear, I am an undergraduate student and this is my first time using your software!

Best wishes,

Matthew

**Comment by davidemms** [comment]
Hi Matthew

The smallest non-trivial unrooted tree has 4 genes, "(A,B),(CD);", which says that A & B are closer to one another than they are to C & D. For this reason OrthoFinder doesn't infer trees with fewer than 4 genes. My first guess is that this is what you're seeing. Let me know if this isn't where you are seeing the 'cap'.

Best wishes
David

**Comment by matthewturk5** [comment]
Hi David,

Thank you so much for your swift response and for taking the time to explain the 'cap' issues I was having. This does seem to line up with where I am seeing this issue.

Hope you are safe and well,

All the best,

Matthew
