### ISSUE TITLE
Gettings all orthologs to a sequence of interest

### ISSUE THREAD

**Issue by vragh** [davidemms/OrthoFinder#523]
Hi David (and fellow `OrthoFinder` users),

I've run the tool on a set of translated amino acid sequences (from _de novo_ transcriptomes; these are my "samples"). I included a set of "reference" proteomes in the analysis. These contain among themselves several sequences that I'm hoping to find orthologs to from my samples.

Now, it appears that there are two locations in the `OrthoFinder` results from where I can extract said orthologs.

1. One appears to be the `Phylogenetic_Hierarchical_Orthogroups/N0.tsv` file. I suppose I could simply pull out all rows corresponding to the orthogroup that the sequence of interest would belong to.
2. The other location seems to be the `Orthologues` directory. Here I believe I can find all pairwise matches to the sequence of interest by looking for them in the files under the appropriate `Orthologues_<sample_name>` directory.

Are these two approaches equivalent? Are the sequences that I'd get from method 2 outlined above a subset of the sequences I would get from method 1? If not, what is the relationship here? Most importantly, if both of these are incorrect, how do I get the set of orthologs (to my sequence of interest)?

Although `OrthoFinder` is excellently--and extensively--documented, I could not find an answer to my problem here. For instance, the [tutorial section on orthologs](https://davidemms.github.io/orthofinder_tutorials/exploring-orthofinders-results.html) explains how to find the ortholog(s) in a species/sample (to a sequence in one sample/species). But it does not say anything about how to go about finding the relevant orthologs in all samples?

Your help would be much appreciated.

**Comment by davidemms** [comment]
Orthologs & orthogroups are explained here: https://github.com/davidemms/OrthoFinder#orthogroups-orthologs--paralogs
