### ISSUE TITLE
Different structure of output directories and missing sequences

### ISSUE THREAD

**Issue by MartinTes** [davidemms/OrthoFinder#524]
Hello David,

I have recently installed the latest version of Orthofinder using bioconda:

conda create -n trenv -c conda-forge/label/cf202003 ruby
conda activate trenv
conda install  -c bioconda transrate

and when I run it on the example dataset (orthofinder -f ExampleData/) and with my own data, the structure of output folder was different from example one. Compare to the example output structure, in my case, excel files were placed in different places (please, see the attachment), and e.g. folder with sequences for each orthogroup sequence (including sequences) was missing at all. Otherwise, OrthoFinder seems running smoothly producing meaningful results (no error occurred in stout).

I am wondering if there is anything wrong with my installation or new release of Orthofinder or alternatively the manual is not up to date.

I would be very grateful for resolving this issue.

Kind Regards,
Martin Tesicky

![Folder_structure_1](https://user-images.githubusercontent.com/58419222/111664354-fd465a80-8811-11eb-827b-432a4cf01e12.png)
![Folder_structure_2](https://user-images.githubusercontent.com/58419222/111664361-fddef100-8811-11eb-9c44-fbc3a0a6d629.png)

**Comment by davidemms** [comment]
Hi Martin

The screenshots you show are what used to be produced by an old version of OrthoFinder (about 2 years old). If your current installation is producing a directory structure like this then conda is not installing the latest version for you. OrthoFinder will print what version it is when it starts. The current version is 2.5.2. You'll need to resolve the issue with conda. 

I remember someone else had an issue with conda versions, this may help you: https://github.com/davidemms/OrthoFinder/issues/486

Best wishes
David
