### ISSUE TITLE
Matching seq ID to orthogroup per species

### ISSUE THREAD

**Issue by danielleroodt** [davidemms/OrthoFinder#525]
Hi David,

Thank you for this software, I found it easy to use and very informative. I apologise if this is a simple issue or has been asked before, I searched but could not find an answer to my problem.

I used Orthofinder on 4 distantly related species. Separately I have an excel spreadsheet for each species with the species ID in the first column. I would like to annotate (or match) the orthogroup each seq ID was assigned to in Orthofinder. For example, if seq ID 1 was assigned to orthogroup OG0000000 I want to have that OG value added to the second column. To do that I need a file where each seq ID is a row (as opposed to the Orthogroups output where each orthogroup is a row, followed by columns of seq IDs).

Is there a way to extract each species' seq ID, followed by the orthogroup that ID was assigned to?

I hope this is clear enough. Thanks again!

**Comment by davidemms** [comment]
Hi

That sounds like a scripting task. I'd recommend reading the N0.tsv file (or the less accurate Orthogroups.tsv file if you're using an old version) and using the data to write out the file format you describe. Unfortunately 50% of bioinformatics turns out to be writing scripts to read files in one format and write them in another :s

All the best
David

**Comment by danielleroodt** [comment]
Hi David,

Indeed, I ended up writing something to achieve this. Just didn't want to reinvent the wheel if it wasn't necessary :)
I will also try the suggested approach using R (although I can't see that answer on this thread now).

Thanks for the response! And thanks again for Orthofinder.

Kind regards,
Danielle

**Comment by danielleroodt** [comment]
Thank you! This solution works well.
Appreciate it!

Kind regards,
Danielle
