### ISSUE TITLE
Which output file should be used for comparing orthologs of two species

### ISSUE THREAD

**Issue by dannyginzburg** [davidemms/OrthoFinder#528]
The species tree generated is correct, and the two species I'm interested in comparing are at a defined node of the tree (N2). For downstream analysis of orthologs between the two species, should I reference the HOGs in the N0.tsv file or those in N2.tsv?

Additionally, could you verify if the numbers in OrthologuesStats_Totals.tsv reflect the number of orthologs predicted via the deprecated method (i.e. corresponding to the data in the "speciesA_v_speciesB.tsv" in the "Orthologues" parent folder) or via the Phylogenetic Hierarchical Orthogroup prediction method? From my brief wrangling of the data, it looks like the numbers in OrthologuesStats_Totals.tsv correspond to the orthologues of the deprecated speciesA_v_speciesB.tsv folder; but I don't know this is this somehow coincidental given the emphasis on not using these data.

If the numbers in OrthologuesStats_Totals.tsv correspond to one of the HOG-based files, it's unclear to me how to recover the total set of genes corresponding to the numbers listed in the OrthologuesStats_Totals.tsv table. Specifically, I looked at the count of genes in species A from the set of HOGs which also have genes in species B (i.e. excluding all genes in species A assigned to an HOG which has no genes assigned to it in species B). This method yielded numbers different from those shown in OrthologuesStats_Totals.tsv from both the N0.tsv and N2.tsv files.

I'm happy to provide more details if needed.

Thanks very much.

**Comment by davidemms** [comment]
Hi

For comparisons between two species you should use orthologs. Orthogroups are useful for multi-species comparisons. So use the speciesA_v_speciesB.tsv folder.

It's not the orthologs that have been deprecated, they are derived using the same phylogenetic methods as the N0.tsv file etc. It was the orthogroup.tsv file that was generated using mcl clustering that has been deprecated. 

All the best
David

**Comment by dannyginzburg** [comment]
Hi David,

This is very helpful. Given that being the case, I have a follow up
question. In the speciesA_v_speciesB file of orthologs, what is the meaning
of there being potentially many rows of genes all annotated to the same
orthogroup? Are the species-specific genes in each row somehow more closely
related than to those on another row but which are also assigned to the
same orthogroup?

Thanks very much,
Danny

**Comment by davidemms** [comment]
Hi Danny

If different rows are from the same orthogroup then they are paralogs of each other i.e. they are related but they diverged (via a gene duplication event) further back in time than when the species diverged. The orthogroup ID is a cross-reference to the gene tree that the genes came from so you can look at the particular gene tree in a viewer such as dendroscope to see how exactly the genes are related.

All the best
David

**Comment by dannyginzburg** [comment]
Hi David,

Thanks very much for these explanations. Could you explain, please, what
the nature of the relationship is, then, from genes in speciesA to the
paralogs of orthologous genes in speciesB?

Below is a snippet of our results for context. My question is, what is the
relationship between the sorghum genes in cell B3 to the arabidopsis genes
in cell C4? Are these orthologs?

Thank you again for your time and help.

[image: image.png]


Danny Ginzburg
Research Assistant | Rhee Lab
Department of Plant Biology, Carnegie Institution for Science

**Comment by davidemms** [comment]
Hi Danny

The image isn't showing for me, it just says "[image: image.png]".

All the best
David

**Comment by dannyginzburg** [comment]
Sorry about that David. Not sure why that would be the case. Please let me
know if you're able to see the following attachment.

Best,
Danny

**Comment by davidemms** [comment]
Hi Danny

Those genes are paralogs, they diverged via a gene duplication event further back in time than when the species diverged and so they are less closely related than the orthologs on the same row. They're is an explanation of orthologs and paralogs on the front page: https://github.com/davidemms/OrthoFinder#orthogroups-orthologs--paralogs

Looking at a gene tree will help make this clear. The largest ones that come first can be a bit complicated so try finding an example from something like OG 1000 which has such a duplication. 

All the best
David

**Comment by dannyginzburg** [comment]
Thank you for this clarification, David. It wasn't clear to me, given the
explanation on the front page, that paralogs could reside in separate
genomes. Based on your description of how to interpret the results I have,
though, I now know that this is, indeed, possible.

Thanks again very much for the help.

Danny Ginzburg
Research Assistant | Rhee Lab
Department of Plant Biology, Carnegie Institution for Science
