### ISSUE TITLE
Help making a tree

### ISSUE THREAD

**Issue by dirostri** [davidemms/OrthoFinder#531]
Greetings, 

Is it possible to use OrthoFinder to calculate a new tree topology if given the (1) protein fasta of a **species of interest** , (2) a preconfigured tree in Newick and (3) the protein fastas used to make that tree? I have a species of interest and want to find out where in that tree it would be. 

I've been searching the manual and can't find any mention, and just want to make sure I'm not missing anything.

Best!

**Comment by davidemms** [comment]
Hi

The functionality of OrthoFinder is to take all the protein coding genes in your species of interest and infer all the gene trees and the species tree. If I understand your question then the answer is no, it has no functionality to alter a preconfigured tree.

Best wishes
David

**Comment by davidemms** [comment]
Just to follow up on this, OrthoFinder will infer a new species tree for you if you provide it with the complete proteomes of each of the species you are interested in. 

OrthoFinder will also provide all the data you need to carry out any further phylogenetic studies you want, e.g. for your particualr request you could run OrthoFinder with "-M msa" which will produce a file MultipleSequenceAlignments/SpeciesTreeAlignment.fa. You can then use this as input to iqtree together with your preconfigured tree in Newick to get it to just place your new species in the species tree without changing the topology of the existing species:

```
iqtree -m TEST -g ORIG_NEWICK_TREE.tre -s MultipleSequenceAlignments/SpeciesTreeAlignment.fa
```

Best wishes
David
