### ISSUE TITLE
Using DNA as input sequence, sequence search program

### ISSUE THREAD

**Issue by wyim-pgl** [davidemms/OrthoFinder#532]
Hi,
When we use -d option for nucleotide sequence, can we use mmseq2 or diamond blast?
I used -S option but they only use NCBI blast.
Thanks

**Comment by davidemms** [comment]
Hi

I don't think diamond supports nucleotide sequences. I'm not sure about mmseq2, if it does and you want to use it then you will need to add an entry to the config.json file to tell OrthoFinder how to call it for nucleotide sequences and then select this newly configured method on the command line using the -S option.

Best wishes
David

**Comment by Artifice120** [comment]
Diamond can take nucleotide input with diamond blastx
