### ISSUE TITLE
OrthoFinder works on ExampleData but when I give it my own data it returns error - 9 and host of other recurring error messages.

### ISSUE THREAD

**Issue by RijanDhakal2055** [davidemms/OrthoFinder#533]
Hi David,

I am running orthofinder (2.5.2) on a cluster that uses centOS. I got my sys-administrator to update everything to the current versions. I did a trial run on ExampleData as the manual suggested, it ran fine and created an output with around 3400 files and the proper citation and zero warnings. So, can I assume that the set-up was done properly?

I used the following script to call orthofinder on the cluster:-
#!/bin/bash
source /opt/asn/etc/asn-bash-profiles-special/modules.sh
module load orthofinder/2.5.2
orthofinder -S diamond -f protein_data 

Protein_data is the name of the folder with the fasta file for the species. I tried a trial run on exampledata in the same manner but had ExampleData in the place of protein_data and it worked fine.

(I googled around but could not find much on error -9)

But when I did give orthofinder my own "real" data I am getting the following errors:-

1. ERROR: external program called by OrthoFinder returned an error code: -9

Command: diamond blastp -d /scratch/Rijan_Orthofinder_directory/protein_data/OrthoFinder/Results_Apr09/WorkingDirectory/diamondDBSpecies4 -q /scratch/Rijan_Orthofinder_directory/protein_data/OrthoFinder/Results_Apr09/WorkingDirectory/Species19.fa -o /scratch/Rijan_Orthofinder_directory/protein_data/OrthoFinder/Results_Apr09/WorkingDirectory/Blast19_4.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b''

This error is repeated hundreds of times (with different species names but the same message)

I am also getting the following error towards the end:- 

2. WARNING: Too few hits between species 1 and species 0 to normalise the scores, these hits will be ignored

3. Detected 2227 oom-kill event(s) in StepId=580287.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler. (No idea what this is )

Also, finally the following error.

4. Process Process-39:
Traceback (most recent call last):
  File "/opt/asn/apps/orthofinder_2.5.2/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/asn/apps/orthofinder_2.5.2/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/beegfs/apps/dmc/apps/orthofinder_2.5.2/bin/scripts_of/__main__.py", line 524, in Worker_ProcessBlastHits
    WaterfallMethod.ProcessBlastHits(*args, d_pickle=d_pickle, qDoubleBlast=qDoubleBlast)
  File "/mnt/beegfs/apps/dmc/apps/orthofinder_2.5.2/bin/scripts_of/__main__.py", line 511, in ProcessBlastHits
    Bij = blast_file_processor.GetBLAST6Scores(seqsInfo, blastDir_list, seqsInfo.speciesToUse[iSpecies], seqsInfo.speciesToUse[jSpecies], qDoubleBlast=qDoubleBlast)
  File "/mnt/beegfs/apps/dmc/apps/orthofinder_2.5.2/bin/scripts_of/blast_file_processor.py", line 63, in GetBLAST6Scores    with (gzip.open(fn + ".gz", file_read_mode) if os.path.exists(fn + ".gz") else open(fn, file_read_mode)) as blastfile:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/Rijan_Orthofinder_directory/protein_data/OrthoFinder/Results_Apr09/WorkingDirectory/Blast1_5.txt'

Since it worked on Exampledata but it crashed on something else, I think I set the software properly but their is something wrong with my data and my fasta files?

**Comment by davidemms** [comment]
Hi

Yes, it sounds like the setup was fine and there is a problem with the data. It looks like there are a number of different errors here and it may be the analysis you're trying to do is too large for the server:

1. I don't know what error code -9 from diamond means but you may be able to find it the manual or from asking the developer. Another thing to try is to call the command that orthofinder says it called, "diamond blastp -d ..." etc. but without the '-quiet' flag and see what happens: Does the output say what went wrong? Does the result file "Blast19_4.txt" look right compared to the results files from running on the example data (e.g. "Blast0_1.txt").

2. This almost always occurs when not all of the genes in a species are provided as input to OrthoFinder. OrthoFinder requires all the genes each species as input.

3. The OMM killer is a program on the linux server that kills programs if the server runs out of memory. It sounds like there isn't enough RAM available on the machine. If the OMM killer kills any of orthofinder's tasks then the run will be unsuccessful.

4. I think this is a result of all the previous problems

Best wishes
David

**Comment by RijanDhakal2055** [comment]
Dear Sir,

You were right, RAM was the issue. I was able to conduct a successful run after making more RAM available to the job.

Thank you!
