### ISSUE TITLE
My Linux kernel version is too low. Can you tell me which version of the old software to use?

### ISSUE THREAD

**Issue by XK4959** [davidemms/OrthoFinder#534]
Report an error：
configure: error: GNU libc requires kernel header files from
Linux 3.2.0 or later to be installed before configuring.
The kernel header files are found usually in /usr/include/asm and
/usr/include/linux; make sure these directories use files from
Linux 3.2.0 or later.  This check uses <linux/version.h>, so
make sure that file was built correctly when installing the kernel header
files.  To use kernel headers not from /usr/include/linux, use the
configure option --with-headers.

My Linux kernel version:(base) [2018055070@node119 glibc-build]$ cat /proc/version
Linux version 2.6.32-431.el6.x86_64 (mockbuild@x86-023.build.eng.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) ) #1 SMP Sun Nov 10 22:19:54 EST 2013

Before, there was a problem with my glibc version. It has been resolved. For your reference, I also provide my glibc version.

My glibc version：(base) [2018055070@node119 glibc-build]$ rpm -qa | grep glibc
compat-glibc-headers-2.5-46.2.x86_64
glibc-devel-2.12-1.132.el6.x86_64
glibc-utils-2.12-1.132.el6.x86_64
glibc-2.12-1.132.el6.x86_64
glibc-common-2.12-1.132.el6.x86_64
glibc-2.12-1.132.el6.i686
compat-glibc-2.5-46.2.x86_64
glibc-headers-2.12-1.132.el6.x86_64

Looking forward to your reply, thank you very much！
xinlong

**Comment by XK4959** [comment]
Forgot to say, I followed the latest version, the cause is that the glibc version is too low, and 2.25 is required. During the installation, I was prompted that the Linux kernel version is too low, and I cannot change the kernel version, so I hope you can specify what version of orthofinder I can use for my existing glibc.

**Comment by davidemms** [comment]
Hi xinlong

Download the source code version, it will work with any kernel version. Instructions are here:
https://github.com/davidemms/OrthoFinder/#python-source-code-version

Best wishes
David

**Comment by XK4959** [comment]
Hi  David

Thank you very much!
Let me try it, and I will tell you the effect later.

Best wishes
Xinlong
