### ISSUE TITLE
Why the content of SingleCopyOrthogroups.txt is empty ??

### ISSUE THREAD

**Issue by mamtamasand** [davidemms/OrthoFinder#535]
Hello everyone 
I am using orthofinder with 22 species. In the results file, I got the Singlecopyorthologus.txt file is empty.
What was the reason for that.

**Comment by davidemms** [comment]
Hi

Single copy orthologs can be rare in some species sets, especially when co-orthologs are being correctly identified, the reason for it will be that there weren't any orthogroups identified that had one and only one copy in all 22 species.

Best wishes
David
