### ISSUE TITLE
Which gene to pick in orthogroup

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [davidemms/OrthoFinder#536]
Thanks for the great tool! 

I am doing a multiple species comparison between transcription factors, and I found that using orthologs works decently well to find orthologous TFs (and it's super easy because of orthofinder). :smile: 

I am working with obscure-ish fishes and most genes do not have a gene name. So I would like to convert them to zebrafish gene names, for interpretation. This works, unless in the case when multiple genes are part of a orthogroup. How would I choose the _most likely_ gene? Is this possible?

**Comment by Maarten-vd-Sande** [comment]
Thanks for the fast reply! Ugh.. Biology :wink: 

Okay, I will have to find a clever solution to this. Thanks again

**Comment by vragh** [comment]
@Maarten-vd-Sande what was the final solution you came up with if I may ask?

@davidemms  could you perhaps comment on the viability of calculating the pairwise sequence similarities between all orthologs in a pair of species as identified by `OrthoFinder` and assigning an "identity" based on that? So for example say we have sequences `A`, `B`, and `C` in `species 1` as the orthologs to sequences `D` and `E` in `species 2`. If `A` and `B` are most similar to `D` while `C` is most similar to `E`, then would it be acceptable to transfer the name/annotations from `D` to `A` and `B` (and from `E` to `C`) in the event that `A`, `B`, and `C` are unnamed?

**Comment by Maarten-vd-Sande** [comment]
@vragh I haven't found a solution yet. I just asked this question yesterday :smile:

**Comment by vragh** [comment]
> @vragh I haven't found a solution yet. I just asked this question yesterday smile

I had incorrectly assumed that you had, since you had closed the issue. Apologies!!

**Comment by davidemms** [comment]
Just to follow up on this, if there are multiple orthologs then I tend to inherit the annotation from all them. This gives the most accurate information as to the likely function of the gene.
