### ISSUE TITLE
Accessing Unassigned Genes

### ISSUE THREAD

**Issue by matthewturk5** [davidemms/OrthoFinder#537]
Hi,

I am keen to know the identities of genes that could not be assigned to an orthogroup. Is there a way to go around accessing this kind of data?

Best,

Matthew

**Comment by davidemms** [comment]
Hi Matthew

If the genes are unassigned it suggests OrthoFinder thought they probably didn't have orthologs, although it might only be right about 90% of the time. 

If you want to see if you can find out any more about the gene then you can see if it had **any** BLAST/DIAMOND hits. You can do this yourself by searching all the genes in one species against all the genes in the other species using DIAMOND. Alternatively, OrthoFinder has already done this but with genes assigned internal IDs, this can be a pain for reading yourself hence the suggestion of doing the search yourself. But if you want to use these files you can find what these IDs are by looking in the "SequenceIDs.txt" and "SpeciesIDs.txt" file and see the hits in the corresponding species-vs-species file e.g. "Blast0_1.txt.gz" for species 0 against species 1. These files are all in WorkingDirectory.

All the best
David
