### ISSUE TITLE
 Orthogroups file

### ISSUE THREAD

**Issue by assafwww** [davidemms/OrthoFinder#539]
Hi David,

After running orthofinder 2.5.2, I see that the directory "Phylogenetic_Hierarchical_Orthogroups" includes the file N0.tsv that should be equivalent to the previous Orthogroups.tsv file if I understand correctly. 
Is there any difference between version 2.5.2 and 2.4 in the way the first stage of orthogroup clustering is conducted, or only in later stages? It seems that in my data the newer version tends to create smaller orthogroups, and in specific cases tend to cut known gene families into smaller groups, which can be problematic biologically. I didn't see this problem while running version 2.4.  Any idea can help, currently I go back to 2.4 and check.

thanks a lot,
Assaf

**Comment by assafwww** [comment]
I see that the directory "Phylogenetic_Hierarchical_Orthogroups" includes orthogroups data for the different species tree nodes, where N0.tsv should represent the species tree root. So, should N0.tsv be the equivalent to the previous orthogroups.tsv file?
thanks again

**Comment by davidemms** [comment]
Hi Assaf

The initial clustering should be the same and so the Orthogroups.tsv should be the same. The only potential difference is that the diamond binary has been updated in the 2.5.2 release and so this may make some minor differences.

Just to clarify, the N0.tsv groups will be different from the Orthogroups.tsv groups. The N0.tsv file is from analysing the gene tree for each group in the Orthogroups.tsv file and splitting up any groups at gene duplication events which appear to occur before the last common ancestor. You can still refer to the Orthogroups.tsv file to see the larger groups that the phylogenetically inferred N0.tsv orthogroups came from.

Best wishes
David
