### ISSUE TITLE
No root authority, the maximum number of open files is not enough

### ISSUE THREAD

**Issue by XK4959** [davidemms/OrthoFinder#540]
Hi，David
I encountered the same error, but I don’t have administrator rights. Is there any way to run the software with the maximum number of open files of 1024?

ERROR: The system limits on the number of files a process can open is too low. For 176 species OrthoFinder needs to be able to open at least r=31076 files. Please increase the limit and restart OrthoFinder

Check the hard and soft limits on the number of open files for your system:
$ ulimit -Hn
$ ulimit -Sn
If hard limit, h > r already, then you just need to increase the soft limit:
$ ulimit -n 31076
Alternatively, if h < r then you need to edit the file '/etc/security/limits.conf', this requires root privileges. To increase the limit to 31076 for user called 'emms' add the lines:
emms hard nofile 31076
emms soft nofile 31076
(edit these lines to match your username)
Check the limit has now been updated (if you changed the hard limit you'll need to open a new session and confirm it's updated):
$ ulimit -Sn
Once the limit is updated restart OrthoFinder with the original command
Xinlong

**Comment by davidemms** [comment]
Hi Xinlong

Sorry, there's no way of doing this.

Best wishes
David
