### ISSUE TITLE
break in the middle but not stop

### ISSUE THREAD

**Issue by yingy-gao** [davidemms/OrthoFinder#543]
the task using othorfinder just break with no error, cannot move on to a result over a long time. can anyone help me with this?
the job always stop here in the last line and never make progress anymore, the job.error file has no error information
the result are as follow: 

...blast.txt.gz....
 9288822 Apr 17 16:00 Blast5_4.txt.gz
 9418091 Apr 17 16:20 Blast5_5.txt.gz
 25054516 Apr 17 15:46 diamondDBSpecies0.dmnd
 22087378 Apr 17 15:46 diamondDBSpecies1.dmnd
 18620512 Apr 17 15:46 diamondDBSpecies2.dmnd
 92921954 Apr 17 15:46 diamondDBSpecies3.dmnd
 27775437 Apr 17 15:46 diamondDBSpecies4.dmnd
 21232058 Apr 17 15:46 diamondDBSpecies5.dmnd
 35941561 Apr 17 15:46 SequenceIDs.txt
 24430037 Apr 17 15:46 Species0.fa
 21551193 Apr 17 15:46 Species1.fa
 18220281 Apr 17 15:46 Species2.fa
 90878889 Apr 17 15:46 Species3.fa
 27153730 Apr 17 15:46 Species4.fa
 20780924 Apr 17 15:46 Species5.fa
   136 Apr 17 15:46 SpeciesIDs.txt

**Comment by davidemms** [comment]
Hi

Could you post the output that OrthoFinder produced please and I will look to see what the problem might be.

Best wishes
David

**Comment by yingy-gao** [comment]
Dear David, 

Thank you and sorry for late response. I finished the task by using the lastest version orthofinder.

It would be my honor to learn the reason why the earlier version (installed with miniconda3 in a Virtual environment, python2.7 as interpreter)just stop(result file attached as a picture, I got no error report).


-----原始邮件-----
发件人:"David Emms" ***@***.***>
发送时间:2021-04-26 18:20:34 (星期一)
收件人: davidemms/OrthoFinder ***@***.***>
抄送: yingy-gao ***@***.***>, Author ***@***.***>
主题: Re: [davidemms/OrthoFinder] break in the middle but not stop (#543)






Hi

Could you post the output that OrthoFinder produced please and I will look to see what the problem might be.

Best wishes
David

**Comment by davidemms** [comment]
Hi

You're image hasn't been attached to the forum (which is here: https://github.com/davidemms/OrthoFinder/issues/543). Did you encounter the problem with the latest version of OrthoFinder, v. 2.5.2?

Best wishes
David

**Comment by yingy-gao** [comment]
the lastest version has no such problem

-----原始邮件-----
发件人:"David Emms" ***@***.***>
发送时间:2021-04-30 23:40:49 (星期五)
收件人: davidemms/OrthoFinder ***@***.***>
抄送: yingy-gao ***@***.***>, Author ***@***.***>
主题: Re: [davidemms/OrthoFinder] break in the middle but not stop (#543)






Hi

You're image hasn't been attached to the forum (which is here: #543). Did you encounter the problem with the latest version of OrthoFinder, v. 2.5.2?

Best wishes
David
