### ISSUE TITLE
Unassigned Genes = Overexpressed?

### ISSUE THREAD

**Issue by matthewturk5** [davidemms/OrthoFinder#544]
Hi,

I am working on a genome comparison between two plant species, currently focusing on a number of genes that have been unable to be assigned to an Orthogroup. I initially interpreted 'Unassigned' as suggestive that they were absent in the genome/proteome I am testing against, however, one of the genes that has appeared as 'Unassigned' is reported in the literature as being overexpressed in the genome.

I am curious as to why this may be the case - any help would be greatly appreciated! Thanks!

**Comment by davidemms** [comment]
Hi

Unassigned means that it wasn't assigned to an orthogroup. That would suggest that the gene didn't produce a good hit to the proteome you're testing against (e.g. there was another gene in your species which appeared to be the ortholog instead). Is the gene reported in the literature assigned to an orthogroup? Are there genes of both species in this orthogroup? If you also include you 'unassigned' gene and infer a tree for those sequences, what does it say about the relationships between the genes?

Best wishes
David

**Comment by wensulin93** [comment]
> Hi
> 
> Unassigned means that it wasn't assigned to an orthogroup. That would suggest that the gene didn't produce a good hit to the proteome you're testing against (e.g. there was another gene in your species which appeared to be the ortholog instead). Is the gene reported in the literature assigned to an orthogroup? Are there genes of both species in this orthogroup? If you also include you 'unassigned' gene and infer a tree for those sequences, what does it say about the relationships between the genes?
> 
> Best wishes David

Hi, I focus on LTR retrotransposons and orthofinder runs using only protein sequences of LTR retrotransposons from several species. The final results show that only about 67.7% of LTR retrotransposons are classified, and the rest are assigned to "Unassigned genes". Is this normal? Is there a solution? thank you
