### ISSUE TITLE
Why  the number of single-copy orthologs identified by orthofinder far less than BUSCO evaluation?

### ISSUE THREAD

**Issue by ypchan** [davidemms/OrthoFinder#546]
Dear author,

I using BUSCO to assess my annotation and get 1000+ single-copy orthologs, but orthofinder only give 387 sngle-copy protein? 

How to explain this difference？

Thanks
Yanpeng Chen

**Comment by davidemms** [comment]
Hi Yanpeng Chen

OrthoFinder will report how many orthogroups had one gene and only one gene from each of your input species. You'll have to check the BUSCO documentation, but I think it tells you how many of its "Benchmarking Universal Single-Copy Orthologs" were single copy in just the one species that you test it on.

Best wishes
David
