### ISSUE TITLE
Species and Gene trees with bootstrap support

### ISSUE THREAD

**Issue by aberaslop** [davidemms/OrthoFinder#549]
Hi,
First, thank you so much for such a nice program!
I am analyzing around 60 fungal genomes and I would like to, among other things, obtain a species tree as well as gene trees with bootstrap support. I have currently run OF with default parameters "./orthofinder -f species/". But somehow cannot find the support for the gene trees (I may be missing something here). 

What would be the best parameters to run OF with in order to obtain these trees (if computing time and memory were not a problem)? 
Thank you so much!

L.

**Comment by davidemms** [comment]
Hi

If you run OrthoFinder with the option "-M msa" it will use MSA to infer the gene trees. These will have Shimodaira-Hasegawa support values. You can run this analysis from you're previous results using
```-fg PREVIOUS_RESULTS_DIR -M msa```

If computing resources really were not a problem then you could go further and use iqtree with its bootstrap support option ..... but you would very soon find that however big your server is, computing resources are indeed a problem. Believe me, I've tried :)

All the best
David
