### ISSUE TITLE
Zero division when no Orthogroup found

### ISSUE THREAD

**Issue by TheGTeck** [davidemms/OrthoFinder#55]
Hi, i was trying to find orthogroups using a proteom file containing a lot of paralog (some selected A.thaliana protein), and an other file which contains totally different proteins. I expected orthofinder to not find any ortholog, but still group the first file proteins together.
This didn't worked (not really surprising since i'm not really giving relevant input files), but i found out the program raise an other kind of error.
Since there is no orthogroups, the Stats function halt on this line:

> writer_sp.writerow(["Percentage of orthogroups containing species"] + [percentFormat % (100.*sum([iSp in og_sp for og_sp in speciesPresence])/len(properOGs)) for iSp in iSpecies])

Line 662 of orthofinder.py

I saw most of the modulo and division were correctly formated (considering the case where denominator is equal to 0 ), but this line doesn't.
So if there is no orthogroup, the program crash.

**Comment by davidemms** [comment]
Hi

Yes, that's not really correct input but I'll look at making sure it doesn't get to this situation if such input is provided. 

All the best
David

**Comment by davidemms** [comment]
This has been resolved in https://github.com/davidemms/OrthoFinder/commit/55edb19a395f01183864242431b77dfd9d034e41

Thanks
David
