### ISSUE TITLE
Finding single copy orthogroups for some missing species ?

### ISSUE THREAD

**Issue by Abhishek7Nayak** [davidemms/OrthoFinder#550]
I  would like to find single copy orthologs. I got 140 single copy orthogroups with all the species present but i would like to find other single copy orthogroups where there are some missing species. How do I find those single copy orthogroups where some species are missing ?

**Comment by davidemms** [comment]
Hi

There's a file called "Orthogroups/Orthogroups.GeneCount.tsv" which can be easily analysed in Excel or some scripting language to identify the orthogroups that meet your criteria. 

All the best
David
