### ISSUE TITLE
Tree Visualization

### ISSUE THREAD

**Issue by JChristopherEllis** [davidemms/OrthoFinder#551]
What is the best software to use to visualize the SpeciesTree_rooted.txt file?

**Comment by davidemms** [comment]
I'd recommend Dendroscope. Alternatively there are some online gene tree viewers but I can't remember their names.

**Comment by JChristopherEllis** [comment]
Many thanks David, is the SpeciesTree_rooted.txt file in Newick format?

**Comment by davidemms** [comment]
Yes, newick.
