### ISSUE TITLE
"IOError: [Errno 121] Remote I/O error" when running OrthoFinder using BLAST results

### ISSUE THREAD

**Issue by gauravdiwan89** [davidemms/OrthoFinder#552]
Hello. I have been trying to run OrthoFinder starting from BLAST results that were previously generated using the "-fg" option.

The command I used was:

```
orthofinder -t 10 -a 10 -fg /path/to/my/directory/Results_Apr26
```

It starts off by creating a new Results folder and copies the species fasta files into the "WorkingDirectory". However I get an `IOError: [Errno 121] Remote I/O error` after that with the following Traceback:

```
Stacktrace:
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
  File "scripts_of/__main__.py", line 1786, in main
  File "scripts_of/__main__.py", line 1682, in CheckOptions
IOError: [Errno 121] Remote I/O error: '/path/to/my/directory/Results_Apr26/../Results_May04_1/WorkingDirectory/Files_test/Sp257/Sp202.txt'
[69211] Failed to execute script orthofinder
```

Weirdly, I cannot find the folder `Files_test` in either the BLAST files directory `Results_Apr26` or the new `Results_May04_1/WorkingDirectory` folder. Can you please help me with this error?

**Comment by davidemms** [comment]
Hi

It's a test run at the start to check that the operating system will allow OrthoFinder to open enough files for it to be able to carry out its analysis. It looks like the fact that the test failed but the failure wasn't correctly identified by OrthoFinder because "Remote I/O error" isn't the error message it was expecting. I'll update the error detection code so that it catches this possibility too.

The code should have posted a message to you like this: https://github.com/davidemms/OrthoFinder/issues/520 but with r=n_species * n_species + 100, for however many species there are in your analysis. It advises you that need to increase the limit on the number of open files.

Best wishes
David

**Comment by gauravdiwan89** [comment]
Actually I have already increased that number. The output of all three commands
```
ulimit -n
ulimit -Hn
unlimit -Sn
```
was 258614 (508*508 + 100), which itself was suggested by OrthoFinder.

**Comment by zxgsy520** [comment]
File "/export/personal/software/software/OrthoFinder/latest/bin/orthofinder", line 471, in ProcessBlastHits
    Bij = BlastFileProcessor.GetBLAST6Scores(seqsInfo, fileInfo, seqsInfo.speciesToUse[iSpecies], seqsInfo.speciesToUse[jSpecies], qDoubleBlast=qDoubleBlast)
  File "/export/personal/software/software/OrthoFinder/v2.5.2/bin/scripts/blast_file_processor.py", line 61, in GetBLAST6Scores
    with (gzip.open(fn + ".gz", 'rb') if os.path.exists(fn + ".gz") else open(fn, 'rb')) as blastfile:
IOError: [Errno 2] No such file or directory: '/export/personal1/txt/02_pep/Results_May05/WorkingDirectory/Blast0_0.txt'

**Comment by davidemms** [comment]
Hi Gaurav

It appears that the operating system is still throwing an error (Remote I/O error) when OrthoFinder tries to open that many files. It would be worth checking with your system admin if they know why that is. It is likely to be something system specific. The code referenced in the error is a simple function that just opens a number of files and then closes them again so it would show them quite straightforwardly how to reproduce the issue.

Best wishes 
David

**Comment by davidemms** [comment]
Hi @zxgsy520

This is unrelated to the discussion. I've opened an issue for you here: https://github.com/davidemms/OrthoFinder/issues/553

Best wishes
David

**Comment by gauravdiwan89** [comment]
Hi David,

Ok. Thanks a lot for your quick responses! I will check with my system admin.

Best regards
Gaurav
