### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/export/personal1/txt/02_pep/Results_May05/WorkingDirectory/Blast0_0.txt'

### ISSUE THREAD

**Issue by davidemms** [davidemms/OrthoFinder#553]
Submitted for @zxgsy520

File "/export/personal/software/software/OrthoFinder/latest/bin/orthofinder", line 471, in ProcessBlastHits
Bij = BlastFileProcessor.GetBLAST6Scores(seqsInfo, fileInfo, seqsInfo.speciesToUse[iSpecies], seqsInfo.speciesToUse[jSpecies], qDoubleBlast=qDoubleBlast)
File "/export/personal/software/software/OrthoFinder/v2.5.2/bin/scripts/blast_file_processor.py", line 61, in GetBLAST6Scores
with (gzip.open(fn + ".gz", 'rb') if os.path.exists(fn + ".gz") else open(fn, 'rb')) as blastfile:
IOError: [Errno 2] No such file or directory: '/export/personal1/txt/02_pep/Results_May05/WorkingDirectory/Blast0_0.txt'

**Comment by davidemms** [comment]
Hi 

The error reports that OrthoFinder is unable to access some files. Could you please give the command you used. Could you also check if the file '/export/personal1/txt/02_pep/Results_May05/WorkingDirectory/Blast0_0.txt' or '/export/personal1/txt/02_pep/Results_May05/WorkingDirectory/Blast0_0.txt.gz' is accessible.

Best wishes
David

**Comment by zxgsy520** [comment]
HI
I found the possible reason. It may be an abnormal coincidence in the protein sequence. E.g:
>model.evm.model.Contig217.1
KKNEKKKKKKKRLKKKEIVRRRRVHPAAPRRPASDHTTSATKTDARSLRGSPEESSRLR.RESLASREPP
CATSRSTGSRSCPDPWLKRRGHRTKS.RGQRESSSSSTKFGRRQFCCCSRRCVTADRTLPPSAVLPGEL.
.S.SKMCSDSSTPAQWKSPRRAGMSPPESSRDINSVGSSWATRDTPSPCSSTRSRSTLQKDTFMSTPLST
REAVVNGAWIEWIYRQASRRAKCCCSQPRAALEGASARPSRLSVV.EFSRKTSRSSRS.ARRTEL.QSAV
ASHKFALLRQQSTRRSTPAQKQSSRGSATL.LATTMKIQEHT
Thank you very much！
Xingguo
