### ISSUE TITLE
Best practices w.r.t. user-defined species trees?

### ISSUE THREAD

**Issue by vragh** [davidemms/OrthoFinder#554]
Hi @davidemms ,

What are some things one should keep in mind while preparing (and supplying to `OrthoFinder`) a user-defined species tree?

For instance, I am wondering if the branch lengths are important or whether they can be ignored.

**Comment by davidemms** [comment]
Hi

The branch lengths are not important. The topology of the tree is used for two things: 1. rooting the gene trees 2. Hierarchical orthogroups are inferred for each internal node in the species tree topology.

Best wishes 
David
