### ISSUE TITLE
When the protein file is too big

### ISSUE THREAD

**Issue by yifeng-evo** [davidemms/OrthoFinder#555]
Hello! I've used orthofinder initially to find orthologs of three genomes (let's say species A, B, and C). I got the ratio of genes in species A that have orthologs in B and C respectively. Now I want to know how many of the genes have orthologs in the Eukaryotes NR (ENR). So I actually added a protein file containing all eukaryotes NR proteins, which is probably too big for self-alignment using Diamond. Is there a way that I can get a list of genes in A, B and C that have orthologs in Eukaryote NR without going through the self-blast process in Orthofinder, which seems that it would take forever? All the other diamond jobs have been finished (A-ENR, B-ENR, C-ENR...) Thanks a lot for your response!

**Comment by davidemms** [comment]
Hi

Every single ortholog in every eukaryotic species in NR? OrthoFinder isn't really set up to do that unfortunately. OrthoFidner will take the proteomes of individual species (one species per file) and identify all the orthologs.

Best wishes
David
