### ISSUE TITLE
Does Orthofinder work with tblastx results ?

### ISSUE THREAD

**Issue by Mataivic** [davidemms/OrthoFinder#56]
Hello,

I want to do an orthologous gene search on a set of nucleic sequences. I have seen that OrthoFinder proceed to blastp, but since tblastx proceeds to compare translated nucleic sequences, could it works with tblastx results ?

Best regards,

Mataivic.

**Comment by davidemms** [comment]
Hi Mataivic

I think it may be possible to do this by making it to call tblastx instead but I haven't done it myself.

All the best
David

**Comment by Mataivic** [comment]
Hi,

I will tried to figure it out. i will let you know. 

Best regards,
Victor.
