### ISSUE TITLE
Is nucleotide option suitable to analyze ncRNAs?

### ISSUE THREAD

**Issue by riccardo-aiese** [davidemms/OrthoFinder#561]
Hello
first thank you very for this great algorithm and the continuos support! 

I recently noted the addition of the nucleotide option in OrthoFinder and I was wondering if it would be possible to analize non-coding sequences in order to identify orthogroups or even infer phylogeny. Is this possible or would it violate some assumptions of the methods/models used by OrthoFinder?

Thank you very much
Riccardo

**Comment by davidemms** [comment]
Hi Riccardo 

It wouldn't violate any assumptions, i think the only question would be how well would BLAST or whatever tool is used be able to detect homology.

Best wishes
David
