### ISSUE TITLE
Number of Gene Trees containing specific node/tip

### ISSUE THREAD

**Issue by xieyichun50** [davidemms/OrthoFinder#565]
Hi David,

I am exploring the gene duplication events using OrthoFinder v2.5.2.

I would like to do a duplicate ratio calculation by dividing the number of duplication events (should be the count here: Comparative_Genomics_Statistics/Duplications_per_Species_Tree_Node.tsv?) by the total number of gene trees containing that node.

Is there a way to extract the "number of gene trees containing specific tree node or tree tip" in the OrthoFinder results? (Currently I extract those gene trees by "grep" the gene trees with targeted species or a group of targeted species)

Thank you!
Yichun

**Comment by davidemms** [comment]
Hi Yichun

Sorry for the delay in responding to this issue. Currently the number of gene trees containing a given species tree node is not counted/analysed by OrthoFinder. The recommended way would be to traverse the trees using ete3 or some other tree library, finding the set of species below a node and then finding which species tree node this corresponds to by identifying the most recent common ancestor (MRCA) node on the species tree. There are still issues with this approach though with multiple counting of nodes if the gene tree topology does not match the species tree topology. Dealing with this would be complex and I don't have any specific suggestions for how this could be dealt with.

Best wishes
David
