### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [davidemms/OrthoFinder#567]
Putting this here for others in case they get this as well (since it took me stupidly long to figure this out).

I accidentally ran orthofinder with a negative number of threads, which makes orthofinder start a large amount of processes. This gave me a brokenpipeerror and kept hanging indefinitly. Changing the number to a positive number of threads solved the issue for me.

For the rest it works like a charm for me :muscle:

**Comment by davidemms** [comment]
Hi 

Thanks for reporting this, I'll reopen this issue as it sounds like it should be possible to put a check into orthofinder to prevent this.

Best wishes
David
