### ISSUE TITLE
The software has been inferring the gene tree for six days

### ISSUE THREAD

**Issue by lningyawen** [davidemms/OrthoFinder#568]
Hello davidemms:
         Thank you so much for building OrthoFinder. I chose thirty species to use this software to infer the species tree. But the software output shows that it is always in the state of inferring a gene tree.

**The following is the output of the software.**

OrthoFinder version 2.5.2 Copyright (C) 2014 David Emms

2021-04-29 09:16:11 : Starting OrthoFinder 2.5.2
50 thread(s) for highly parallel tasks (BLAST searches etc.)
50 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "mafft /gpfs/home/liunyw/dragon_cactus/orthofinder/OrthoFinder/Results_Apr29/WorkingDirectory//_dependencies_check/SimpleTest.fa" - ok
Test can run "iqtree" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2021-04-29 09:16:16 : Creating diamond database 1 of 28
.......................................................
2021-04-29 09:16:19 : Creating diamond database 28 of 28

Running diamond all-versus-all
------------------------------
Using 50 thread(s)
2021-04-29 09:16:19 : This may take some time....
2021-04-29 09:16:19 : Done 0 of 784
.......................................................
2021-04-29 10:11:24 : Done all-versus-all sequence search

Running OrthoFinder algorithm
-----------------------------
2021-04-29 10:11:25 : Initial processing of each species
2021-04-29 10:11:59 : Initial processing of species 14 complete
.......................................................
2021-04-29 10:13:49 : Written final scores for species 3 to graph file
2021-04-29 10:19:07 : Ran MCL

Writing orthogroups to file
---------------------------
OrthoFinder assigned 632704 genes (97.7% of total) to 32626 orthogroups. Fifty percent of all genes were in orthogroups with 40 or more genes (G50 was 40) and were contained in the largest 3820 orthogroups (O50 was 3820). There were 3084 orthogroups with all species present and 43 of these consisted entirely of single-copy genes.

2021-04-29 10:19:31 : Done orthogroups

Analysing Orthogroups
=====================
2021-04-29 10:19:33 : Starting MSA/Trees
Species tree: Using 752 orthogroups with minimum of 71.4% of species having single-copy genes in any orthogroup

Inferring multiple sequence alignments for species tree
-------------------------------------------------------
2021-04-29 10:19:48 : Done 0 of 752
.......................................................
2021-04-29 11:44:26 : Done 600 of 752

**Inferring remaining multiple sequence alignments and gene trees**
---------------------------------------------------------------

I have been running it for over six days now and I am not sure what is wrong.

And here's the command I used to generate the species tree.
`orthofinder -f ortho -S diamond -M msa -T iqtree -t 50 -a 50`

Thanks so much for all the help!

Yawen

**Comment by davidemms** [comment]
Hi Yawen

You can monitor what the computer is doing by using the 'top' command, almost certainly one or more of the trees are still running.

IQTREE is a great tool for inferring individual gene trees, but for inferring a large number of large orthogroup trees I think it is too computationally expensive. I've never had a server powerful enough to use it for this so would always advise against it.

Best wishes
David

**Comment by lningyawen** [comment]
Hi David

Thanks a lot for your responses. I have done it using the default tree building method, and it is very fast. I think this default tree building method is sufficient for my analysis.

Best regards
Yawen
