### ISSUE TITLE
Phyldog

### ISSUE THREAD

**Issue by evolgenomology** [davidemms/OrthoFinder#57]
Hi!

I saw a reference to creating phyldog input files in the latest OrthoFinder, however I couldn't identify the switch/flag to use to do this. Could you maybe add it to the README or manual if that is already functional?

Cheers

Philipp

**Comment by davidemms** [comment]
Hi Philipp

It's a work in progress at the moment and isn't functional yet. At the moment I'm just working on getting all the files ready for Phyldog, I haven't even looked at getting OrthoFinder to process the output from Phyldog yet! I can let you know if I make some more progress on this, Phyldog is a really great tool so I'd love to be able to use it with OrthoFinder. 

All the best
David
