### ISSUE TITLE
Failed to execute script orthofinder

### ISSUE THREAD

**Issue by C2051** [davidemms/OrthoFinder#572]
Hi, I came across an issue when I tried to run the orthofinder in the linux subsystem. And I installed the software with anaconda3.Here are the codes and error message.

(base) wangdan@DESKTOP-TM5M3VO:~/anaconda3/bin$ orthofinder -f orthotest/ -t 2

OrthoFinder version 2.5.2 Copyright (C) 2014 David Emms

2021-05-30 21:59:38 : Starting OrthoFinder 2.5.2
2 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /home/wangdan/anaconda3/bin/orthotest/OrthoFinder/Results_May30_2/WorkingDirectory/SimpleTest.phy -o /home/wangdan/anaconda3/bin/orthotest/OrthoFinder/Results_May30_2/WorkingDirectory/SimpleTest.tre" - ok
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
  File "scripts_of/__main__.py", line 1748, in main
    speciesInfoObj = ProcessesNewFasta(fastaDir, options.dna)
  File "scripts_of/__main__.py", line 1610, in ProcessesNewFasta
    with open(fastaDir + os.sep + fastaFilename, 'r') as fastaFile:
IOError: [Errno 13] Permission denied: '/home/wangdan/anaconda3/bin/orthotest//Maga.faa'
[52] Failed to execute script orthofinder
Any help will be much appreciated, thanks in advance.

**Comment by davidemms** [comment]
Hi

It looks like the filesystem permissions for /home/wangdan/anaconda3/bin/orthotest//Maga.faa don't allow orthofinder to read the file.

Best wishes 
David
