### ISSUE TITLE
Test can run "raxml" - failed

### ISSUE THREAD

**Issue by mictadlo** [davidemms/OrthoFinder#576]
Hi, I installed via bioconda OrthoFinder version 2.5.2. However, using `orthofinder -f short_fn -t 5 -a 5 -S diamond -M msa -T raxml -o orthofinder_ch`

```
Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "mafft orthofinder_ch/Results_Jun11/WorkingDirectory//_dependencies_check/SimpleTest.fa" - ok
Test can run "raxml" - failed

ERROR: Cannot run user-configured tree method 'raxml'
Please check program is installed and that it is correctly configured in the orthofinder/config.json file
```

What did I miss?

Thank you in advance,

Michal

**Comment by davidemms** [comment]
Hi Michal

Try to see if you can run raxml outside of
orthofinder, that's the most likely problem.

All the best
David
