### ISSUE TITLE
An extra species created while prepairing data for diamond

### ISSUE THREAD

**Issue by senramvx** [davidemms/OrthoFinder#577]
Hi, I'm running OrthoFinder in its default mode, and at a very initial stage, even before calling diamond, the code creates an additional species (with no name, just ".fa"), which is not in my dataset. Beside of this, any error is called and the code can complete all analyses. However, while analysing the generated species tree, I could notice a tip in blank (which should be related to this additional species).
It seems to me that OrthoFinder is having problems with my list of species while creating the working directory. However, all 147 species that I have are, in fact, successfully recognized and presented in the log file.

Any thoughts on what may be causing this error?

I'm running the analysis in a 64bit Ubuntu 20.04.

Thanks in advance for any support,

Marcus

2021-06-09 12:25:47 : Started OrthoFinder version 2.5.2
Command Line: /media/marcus-senra/LabWork/Bioinformatics/OrthoFinder/orthofinder -f Subjects/

WorkingDirectory_Base: /media/marcus-senra/LabWork/Running_Projects/Orthologs_Ciliates/OrthoFinder/Subjects/OrthoFinder/Results_Jun09/WorkingDirectory/

Species used: 
0: .fa
1: Anigsteinia_sp.fa
2: Anophryoides_haemophila.fa
3: Aristerostoma_sp.fa
4: Blepharisma_americanum.fa
5: Blepharisma_japonicum.fa
6: Brachonella_contorta.fa
7: Brachonella_sp.fa
8: Brachonella_spiralis.fa
9: Brassica_formis.fa
10: Bursaria_truncatella.fa
11: Campanella_umbellaria.fa
12: Carchesium_polypinum.fa
13: Chilodonella_uncinata.fa
14: Ciliophora_E5.fa
15: Ciliophora_F6.fa
16: Ciliophora_N9.fa
17: Ciliophora_R1.fa
18: Ciliophora_T1.fa
19: Ciliophora_Y5.fa
20: Ciliophora_Y7.fa
21: Ciliophora_Y9.fa
22: Climacostomum_virens.fa
23: Colpoda_aspera.fa
24: Condylostoma_magnum.fa
25: Cristigera_sp.fa
26: Cryptocaryon_irritans.fa
27: Cryptopharynx_sp.fa
28: Cyclidium_porcatum.fa
29: Cyclidium_sp.fa
30: Didinium_nasutum.fa
31: Diophrys_appendiculata.fa
32: Diplodinium_dentatum.fa
33: Dysteria_derouxi.fa
34: Entodinium_caudatum.fa
35: Entodinium_furca.fa
36: Epistylis_sp.fa
37: Euplotes_focardii.fa
38: Euplotes_harpa.fa
39: Euplotes_octocarinatus.fa
40: Euplotes_vannus.fa
41: Fabrea_salina.fa
42: Favella_ehrenbergii.fa
43: Frontonia_sp.fa
44: Furgasonia_blochmanni.fa
45: Geleia_acuta.fa
46: Geleia_sinica.fa
47: Geleia_sp.fa
48: Halteria_grandinella.fa
49: Ichthyophthirius_multifillis.fa
50: Kentrophoros_sp.fa
51: Laurentiella_sp.fa
52: Lembadion_sp.fa
53: Litonotus_pictus.fa
54: Litonotus_sp.fa
55: Loxodes_nr13.fa
56: Loxodes_nr15.fa
57: Loxodes_nr16.fa
58: Loxodes_rostrum.fa
59: Loxodes_sp.fa
60: Loxodes_striatus.fa
61: Mesodinium_pulex.fa
62: Mesodinium_rubrum.fa
63: Metopus_es.fa
64: Metopus_sp.fa
65: Microdiaphanosoma_sp.fa
66: Moneuplotes_crassus.fa
67: Muranothrix_gubernata.fa
68: Myoschiston_sp.fa
69: Nassula_variabilis.fa
70: Nolandia_orientalis.fa
71: Nyctotherus_ovalis.fa
72: Opercularia_sp.fa
73: Oxytricha_trifallax.fa
74: Paramecium_biaurelia.fa
75: Paramecium_bursaria.fa
76: Paramecium_caudatum.fa
77: Paramecium_decaurelia.fa
78: Paramecium_dodecaurelia.fa
79: Paramecium_jenningsi.fa
80: Paramecium_novaurelia.fa
81: Paramecium_octaurelia.fa
82: Paramecium_pentaurelia.fa
83: Paramecium_primaurelia.fa
84: Paramecium_quadecaurelia.fa
85: Paramecium_sexaurelia.fa
86: Paramecium_sonneborni.fa
87: Paramecium_sp1.fa
88: Paramecium_sp2.fa
89: Paramecium_sp3.fa
90: Paramecium_tetraurelia.fa
91: Paramecium_tredecaurelia.fa
92: Paramecium_undecaurelia.fa
93: Parasonderia_sp.fa
94: Paraurostyla_sp.fa
95: Plagiopyla_frontata.fa
96: Platyophrya_macrostoma.fa
97: Prorodon_ovum.fa
98: Protocruzia_adherens.fa
99: Protocruzia_tuzeti.fa
100: Pseudocohnilembus_persalinus.fa
101: Pseudokeronopsis_carnea.fa
102: Pseudokeronopsis_flava.fa
103: Pseudokeronopsis_sp1.fa
104: Pseudokeronopsis_sp2.fa
105: Pseudomicrothorax_dubius.fa
106: Pseudourostyla_cristata.fa
107: Pseudovorticella_sp.fa
108: Remanella_sp.fa
109: Rimaleptus_mucronatus.fa
110: Schmidingerella_taraikaensis.fa
111: Sonderia_sp.fa
112: Spathidium_sp.fa
113: Spirostomum_Valltjaern.fa
114: Spirostomum_minus.fa
115: Spirostomum_semivirescens.fa
116: Stentor_coeruleus.fa
117: Stentor_polymorphus.fa
118: Stentor_roeselii.fa
119: Sterkiella_histriomuscorum.fa
120: Strombidinopsis.fa
121: Strombidinopsis_acuminata.fa
122: Strombidium_inclinatum.fa
123: Strombidium_rassoulzadegani.fa
124: Strombidium_stylifer.fa
125: Strombidium_sulcatum.fa
126: Stylonychia_lamnae.fa
127: Stylonychia_mytilus.fa
128: Tetmemena_sp.fa
129: Tetrahymena_borealis.fa
130: Tetrahymena_ellioti.fa
131: Tetrahymena_malaccensis.fa
132: Tetrahymena_thermophila.fa
133: Thuricola_sp.fa
134: Tiarina_fusa.fa
135: Trachelocerca_sp.fa
136: Trichodina_sp.fa
137: Trichodinella_sp.fa
138: Trimyema_finlayi.fa
139: Uroleptopsis_citrina.fa
140: Urostomides_striatus.fa
141: Urostyla_sp.fa
142: Vorticella_campanula.fa
143: Vorticella_microstoma.fa
144: Vorticella_sp.fa
145: Zoothamnium_arbuscula.fa
146: Zoothamnium_sp.fa
147: Zosterodasys_sp.fa

**Comment by davidemms** [comment]
Hi Marcus

Can you try looking for hidden files in your directory, i.e. 'ls -a Subjects/".

All the best
David

**Comment by davidemms** [comment]
Hi Marcus

I'm assuming this resolved the issue, please reopen it if not and let me know the details.

Thanks
David
