### ISSUE TITLE
Does the "-p" option work?

### ISSUE THREAD

**Issue by shkao** [davidemms/OrthoFinder#58]
Hi,

I'm trying to prepare BLAST results separately which is described at the following section:
https://github.com/davidemms/OrthoFinder#running-blast-searches-separately--p-option

However, I got these after executing `orthofinder -f aa -p`:
```
OrthoFinder version 1.1.4 Copyright (C) 2014 David Emms

    This program comes with ABSOLUTELY NO WARRANTY.
    This is free software, and you are welcome to redistribute it under certain conditions.
    For details please see the License.md that came with this software.

Unrecognised argument: -p

ERROR: An error occurred, please review previous error messages for more information.
```

Any idea? Thanks in advance.

**Comment by davidemms** [comment]
Hi

The option is now '-op'. Apologies, I've been adding some extra options and to make everything consistent it was changed to -op (or --only-prepare). The current command line options can be seen by calling "orthofinder -h", I'll update the README file in the next few days.

All the best
David

**Comment by shkao** [comment]
I see, thank you David!

**Comment by MrTomRod** [comment]
Please update your readme and your pdf, I just wasted time because of this!

**Comment by davidemms** [comment]
Hi

I've updated the pdf. I haven't been able to find "-p" mentioned in the README.md file but if it's still there let me know where and I'll fix it.

All the best
David
