### ISSUE TITLE
FIX: primary_transcript_log.txt (doesn't account for all species)

### ISSUE THREAD

**Issue by janniksven** [davidemms/OrthoFinder#580]
So far, the script only accounts for isoforms labelled with integers, but in some species (e.g. Drosophila melanogaster), the isoforms are labelled with letters. Thus, to be able to use this script on species where the isoforms are labelled with letters, I would suggest changing lines 84 and 85 (function GetGeneName_NCBI) from:

    acc_line = re.sub("isoform [0-9]+ ", "", acc_line)
    acc_line = re.sub("isoform X[0-9]+ ", "", acc_line)

to:

    acc_line = re.sub("isoform [0-9, A-Z]+ ", "", acc_line)
    acc_line = re.sub("isoform X[0-9, A-Z]+ ", "", acc_line)

Cheers,
Jannik

**Comment by davidemms** [comment]
Hi Jannik

Thanks for that, I'll try it out and put it in the next release.

All the best
David
