### ISSUE TITLE
[12911] Failed to execute script orthofinder

### ISSUE THREAD

**Issue by anuneena** [davidemms/OrthoFinder#583]
Hi,
Can anyone say what am I lacking in this process.

I got output screen as follows:

Writing orthogroups to file
---------------------------
Traceback (most recent call last):
  File "orthofinder.py", line 7, in <module>
    main(args)
  File "scripts_of/__main__.py", line 1762, in main
    DoOrthogroups(options, speciesInfoObj, seqsInfo)    
  File "scripts_of/__main__.py", line 1389, in DoOrthogroups
    Stats(ogs, speciesNamesDict, speciesInfoObj.speciesToUse, files.FileHandler.iResultsVersion)
  File "scripts_of/__main__.py", line 751, in Stats
    j, _ = next((i, x) for i, x in enumerate(L) if x > nAssigned/2)
StopIteration
[12911] Failed to execute script orthofinder

I have attached whole output screen log file below for the reference.
[log.txt](https://github.com/davidemms/OrthoFinder/files/6731205/log.txt)

Note: worked with program directory only by replacing fasta files in /EXAMPLE DATA

Thank you..

**Comment by davidemms** [comment]
Hi

I think this is possibly because the full proteome wasn't supplied for one or more of the species which meant there wasn't enough data to support one or more of the calculations.

Best wishes
David
