### ISSUE TITLE
Commutativity of pairwise orthologs

### ISSUE THREAD

**Issue by vragh** [davidemms/OrthoFinder#584]
Hi @davidemms ,

If `OrthoFinder` reports `sequence_2` from `species_B` as a pairwise ortholog for `sequence_1` from `species_A` in `Orthologues/Species_A/Species_A__v__Species_B`, can I assume that `sequence 1` will definitely be listed as the pairwise ortholog to `sequence 2` in `Orthologues/Species_A/Species_B__v__Species_A`? 

I checked with a few example sequences, and this does seem to be the case, but I wanted to be certain all the same.

Apologies if this is a trivial question.

**Comment by davidemms** [comment]
Hi, no problem, that's a fair question. Yes, those two files are guaranteed to be mirror images of one another, what's in one will also be in the other.

**Comment by vragh** [comment]
That's great to know, thank you.
