### ISSUE TITLE
Tutorial: Unicode Decode Error

### ISSUE THREAD

**Issue by davidtleecal** [davidemms/OrthoFinder#588]
When attempting to run `for f in *fa ; do python ~/orthofinder_tutorial/OrthoFinder/tools/primary_transcript.py $f ; done` as referenced in the tutorial, I receive a decode error. This occurs even on a subset of the proteomes - in my case, I have tried with only `Mus_musculus.GRCm39.pep.all.fa` and `Homo_sapiens.GRCh38.pep.all.fa` and it returns the same error. I am supposing there may be either an unlikely issue with these files from Ensembl, or the unzip did not proceed correctly. Any insights would be much appreciated.

`Traceback (most recent call last):
  File "/Users/david/orthofinder_tutorial/OrthoFinder/tools/primary_transcript.py", line 147, in <module>
    main(args)
  File "/Users/david/orthofinder_tutorial/OrthoFinder/tools/primary_transcript.py", line 143, in main
    CreatePrimaryTranscriptsFile(fn, dout)
  File "/Users/david/orthofinder_tutorial/OrthoFinder/tools/primary_transcript.py", line 54, in CreatePrimaryTranscriptsFile
    lines = [l.rstrip() for l in infile]
  File "/Users/david/orthofinder_tutorial/OrthoFinder/tools/primary_transcript.py", line 54, in <listcomp>
    lines = [l.rstrip() for l in infile]
  File "/Users/david/opt/miniconda3/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/Users/david/orthofinder_tutorial/OrthoFinder/tools/primary_transcript.py", line 147, in <module>
    main(args)
  File "/Users/david/orthofinder_tutorial/OrthoFinder/tools/primary_transcript.py", line 143, in main
    CreatePrimaryTranscriptsFile(fn, dout)
  File "/Users/david/orthofinder_tutorial/OrthoFinder/tools/primary_transcript.py", line 54, in CreatePrimaryTranscriptsFile
    lines = [l.rstrip() for l in infile]
  File "/Users/david/orthofinder_tutorial/OrthoFinder/tools/primary_transcript.py", line 54, in <listcomp>
    lines = [l.rstrip() for l in infile]
  File "/Users/david/opt/miniconda3/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte`

**Comment by davidemms** [comment]
Hi

Can you read the input file in a text editor, does it look like a normal fasta file? 

Best wishes
David

**Comment by davidtleecal** [comment]
Thanks for suggesting that admittedly very obvious check I overlooked. Yes, it seems they aren't proper FASTA, and instead it's all gibberish, like so: (Homo sapiens start of file)

ãˇÏ˝kì‰∂ï6ä~ÁØËè≥+^yíwR'bG`Hƒ‰ê6r'ä∂‹∂uFoI~˜Ò˘ıÁYdfueôóÍ,Ÿí[WtU&âu{÷¬∫¸üº∑√é˛Jä"Jvøﬂ˝ı√_ﬂ}˝ó¯Óáü~¯Ó√ó¬Tâã/´÷|’Z¸7ˇ*˙™r"˚2L¢"…„›„*Ãøﬂ˝˘√˜æƒC≈¸–®à¢4∆C˛Ò˝˜?}˝„7˝ô~ÈÊ_fqòƒÈÔñ˜|ıáo~¯˘Ô˝•3_’_—OûºgÂóÛ{~˙˚w¯·[¸Ù?Í›?,/...

I obtained the aforementioned `*.all.fa.gz` from the following Ensembl addresses, then ran `gunzip *.gz`. This is admittedly now outside of the scope of Orthofinder, but if you could perhaps spare a few moments for ideas on what's going on? Something wrong with the decompression maybe?
http://ftp.ensembl.org/pub/release-104/fasta/mus_musculus/pep/
http://ftp.ensembl.org/pub/release-104/fasta/homo_sapiens/pep/

**Comment by davidemms** [comment]
No problem, I've just checked the links you've posted. The steps I take are:
```
wget http://ftp.ensembl.org/pub/release-104/fasta/mus_musculus/pep/Mus_musculus.GRCm39.pep.all.fa.gz
gunzip Mus_musculus.GRCm39.pep.all.fa.gz
less Mus_musculus.GRCm39.pep.all.fa
```
and then the file looks fine. Do you get the same thing when you run those steps, or is the file corrupted?

Hopefully that should work, if not then it does seem like it would have to be a problem with the decompression as the .gz files at that ftp link are decompressing as valid fasta files for me.

**Comment by davidtleecal** [comment]
It does work indeed. After some poking around, it appears that downloading via Safari, which I had done, yields a corrupted file of the exact same filesize. No issues via Chrome or via command line as you suggested. Thank you greatly for your time and help!
