### ISSUE TITLE
Error external program

### ISSUE THREAD

**Issue by JC-therea** [davidemms/OrthoFinder#592]
Dear David,

I am running OrthoFinder (v2.5.2) and I am having some problems with the blast part. I ran the following script:

```
module load Python/2.7.15-foss-2016b
module load MAFFT/7.453
module load iqtree/1.6.12

python2.7 $OrthoFinder_PATH -M msa -T iqtree -f $ORTHOFINDER_DIR -a 40 -t 40 -o /home/jmontanes/IQtree_OrthoFinder -n "MSA_IQtree_bigmem"
```

When I ran that script with a yeast subset that command produces the normal output and everything is fine. However, when I change the proteomes to a subset of insects I obtain some strange outputs:

```
Running diamond all-versus-all
------------------------------
Using 40 thread(s)
2021-07-19 15:51:41 : This may take some time....

ERROR: external program called by OrthoFinder returned an error code: -4

Command: diamond blastp -d /home/jmontanes/IQtree_OrthoFinder/Results_MSA_IQtree_bigmem/WorkingDirectory/diamondDBSpecies9 -q /home/jmontanes/IQtree_OrthoFinder/Results_MSA_IQtree_bigmem/WorkingDirectory/Species9.fa -o /home/jmontanes/IQtree_OrthoFinder/Results_MSA_IQtree_bigmem/WorkingDirectory/Blast9_9.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------

stderr
------

2021-07-19 15:51:42 : Done 0 of 256

ERROR: external program called by OrthoFinder returned an error code: -4

Command: diamond blastp -d /home/jmontanes/IQtree_OrthoFinder/Results_MSA_IQtree_bigmem/WorkingDirectory/diamondDBSpecies12 -q /home/jmontanes/IQtree_OrthoFinder/Results_MSA_IQtree_bigmem/WorkingDirectory/Species12.fa -o /home/jmontanes/IQtree_OrthoFinder/Results_MSA_IQtree_bigmem/WorkingDirectory/Blast12_12.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------

stderr
------
```
I checked the blast files and those files are empty. Do you know which could be the problem? I tried searching for that error code but I did not find any clue about it. 

Thank you very much in advance. 

Carlos

**Comment by davidemms** [comment]
Hi Carlos

Things to try:
1. Look at WorkingDirectory/Species9.fa and WorkingDirectory/Species12.fa files to see if there is any obvious problem with them.
2. Run the printed commands (but probably without the '--quiet' option) and see if diamond produces more information about what the problem is.

All the best
David

**Comment by JC-therea** [comment]
Hi David,

Thank you for your quick answer. I tried to run a previous version of diamond (I had it in another version of OrthoFinder) and worked. I tried to run the printed commands, but the output was  
`illegal instruction (core dumped)` 

so I will just run the previous version,

Thank you and best wishes

Carlos
