### ISSUE TITLE
blast results

### ISSUE THREAD

**Issue by asgiraldoc** [davidemms/OrthoFinder#593]
Hi David,

just a quick question, I'm interested to get the blast results (scores, evalue, etc)... How can I obtain them?

Thank you :)

**Comment by davidemms** [comment]
Hi 

They are in the WorkingDirectory. The translation from the internal orthofinder ids used in the results files to the original sequence/species names are given in the SequenceIDs.txt & SpeciesIDs.txt files, also in the WorkingDirectory.

All the best
David
