### ISSUE TITLE
[Question] Using  '-b dir -M msa -s treefile' doesn't create 'Orthogroups_for_concatenated_alignment.txt' file

### ISSUE THREAD

**Issue by matrs** [davidemms/OrthoFinder#597]
Hello,
thanks for this awesome software, it's been very useful.
I'm trying `orthofinder 2.5.4`  with the options `-b previous_results -M msa -s treefile`and checking the output files inside `Species_Tree`, there is no `Orthogroups_for_concatenated_alignment.txt` file created. When I run `-b previous_results -M msa`, without `-s` for specifying a tree, orthofinder does create  `Orthogroups_for_concatenated_alignment.txt`. Is this expected?

Regards,

Jose Luis

**Comment by davidemms** [comment]
Hi Jose Luis

Yes, this is expected. The Orthogroups_for_concatenated_alignment.txt is only needed for inferring the species tree when the user hasn't provided one. If a species tree is provided then this part of the analysis isn't required.

Best wishes
David

**Comment by matrs** [comment]
Thanks!
