### ISSUE TITLE
How to incrementally  add more genomes/spp. to a previous run?

### ISSUE THREAD

**Issue by drelo** [davidemms/OrthoFinder#6]
Let's say I did a test run with 4 species. Is it possible to add an additional fasta file (or specie) to the analysis, taking into account the result from a previous run or I just have to start from scratch for the whole batch of 5 species. I read the *Using pre-computed BLAST results* section and took a look at the files in the Results/Working directory but I am lost.

**Comment by davidemms** [comment]
Hi, this is a feature we intend to add in the next month or so. I can let you know when it's available. Thanks for your interest. David.

**Comment by davidemms** [comment]
Hi, this has now been implemented and is available in v0.4: https://github.com/davidemms/OrthoFinder/releases
