### ISSUE TITLE
empty/None/NA edge lengths in renamed Gene trees

### ISSUE THREAD

**Issue by dandaman** [davidemms/OrthoFinder#60]
Hi David,

running several analyses with a current version of OF (203a861ff24b0f63aebba6c513829dff3bb3f15e) I get renamed Gene trees were some edge/branch lengths are empty. Looking at the underlying Tree_id files these edges have negative branch lengths. I wonder how that affects species tree reconciliation. The generated files can be loaded with most phylogeny tools (python's ete or bio/phylo and dendropy) some tools will generate faulty tree objects e.g. with NA nodes like R/ape does. I think that it relates to the default value of edge lengths in the package you use for loading/writing trees to rename them. 

I think a proper value for these edges <0 would be1e-1000 (or 1/1000000 total tree length) before writing out trees.

Best,
Daniel

**Comment by davidemms** [comment]
Hi Daniel

Thanks for flagging that up. I'll implement your suggestion of 1/1000000 total tree length.

I think it probably won't change the tree reconciliation as that is only a topology-based process so hopefully it'll be unaffected.

All the best
David
