### ISSUE TITLE
Incorrect outgroup selected

### ISSUE THREAD

**Issue by A-Swafford** [davidemms/OrthoFinder#612]
I have a large set of fungal proteomes with Arabidopsis, Homo Sapiens, and Drosophila added as outgroups. Orthofinder continues to select a set of fungi as the outgroup, skewing results down the line.

Is there an option to define outgroups but still allow species tree estimation independent of the outgroup prediction?

**Comment by davidemms** [comment]
Yes, you can provide the correctly rooted species tree using "-s species_tree_file". To prepare this, you can use something like Dendroscope to change the outgroup of the species tree and export as newick format. Your change to the outgroup will only affect the final step of the OrthoFinder algorithm: analysis of the rooted gene trees for orthologs, orthogroups, paralogs etc. Hence the complete set of options would be:
```
-ft PREVIOUS_RESULTS_DIRECTORY -s ROOTED_SPECIES_TREE_FILENAME
```

Best wishes
David
