### ISSUE TITLE
error trying using a recent version mmseqs with OrthoFinder

### ISSUE THREAD

**Issue by drelo** [davidemms/OrthoFinder#615]
Dear all, 

I am trying to use OrthoFinder along with mmseqs. 

I created a conda environment, installed numpy and scipy and the downloaded the OrthoFinder_source.tar.gz file. 
I run the example  with 0 issues.  I installed mmseqs through conda `conda install -c conda-forge -c bioconda mmseqs2
`  and it is available when I do  ` which mmseqs`  and the program is working (I am using a similar version for other pipelines).  The most recent version installed 

But when I try

`/OrthoFinder/orthofinder.py  -f ./OrthoFinder/ExampleData -o XX  -t 2 -S mmseqs   ` 

> OrthoFinder version 2.5.4 Copyright (C) 2014 David Emms
> 
> 2021-09-08 11:03:25 : Starting OrthoFinder 2.5.4
> 2 thread(s) for highly parallel tasks (BLAST searches etc.)
> 1 thread(s) for OrthoFinder algorithm
> 
> Checking required programs are installed
> ----------------------------------------
> 
> ERROR: Cannot run mmseqs
> Format of make database command:
>   mmseqs createdb INPUT OUTPUT.fa ; mmseqs createindex OUTPUT.fa /tmp
> ERROR: Cannot run mmseqs
> Format of search database command:
>   mmseqs search /mmseqsDBINPUT DATABASE.fa OUTPUT.db /tmp/tmpOUTPUT  --threads 1 ; mmseqs convertalis --threads 1 /mmseqsDBINPUT DATABASE.fa OUTPUT.db OUTPUT
> Please check mmseqs is installed and that the executables are in the system path
> 
> ERROR: An error occurred, ***please review the error messages*** they may contain useful information about the problem.
> 

Just to try my approach I installed diamond through conda and it worked fine. Here is the _head_ of the output

> OrthoFinder version 2.5.4 Copyright (C) 2014 David Emms
> 
> 2021-09-08 11:21:12 : Starting OrthoFinder 2.5.4
> 2 thread(s) for highly parallel tasks (BLAST searches etc.)
> 1 thread(s) for OrthoFinder algorithm
> 
> Checking required programs are installed
> ----------------------------------------
> Test can run "mcl -h" - ok
> Test can run "fastme -i DIAMOND/Results_Sep08/WorkingDirectory/SimpleTest.phy -o DIAMOND/Results_Sep08/WorkingDirectory/SimpleTest.tre" - ok
> 
> Dividing up work for BLAST for parallel processing
> 

It seems an older version of mmseqs (2.2.7) [worked with OrthoFinder  2.3.1](https://github.com/davidemms/OrthoFinder/issues/228#issuecomment-453093522)  in 2019 but is an older one.

Is there any way to provide the path to mmseqs or fix this so we can take advantage of the more recent versions of mmseqs? Thank you very much for your help.

**Comment by davidemms** [comment]
Hi  Andres

Yes, you can specify the full path in the OrthoFinder "config.json" file.

Best wishes
David

**Comment by drelo** [comment]
Hi David,
Thanks for your quick response, sorry this must be super easy but I edited the lines like this 

```
  "mmseqs":{
    "program_type": "search",
    "db_cmd": "~/anaconda3/envs/ortho/bin/mmseqs createdb INPUT OUTPUT.fa ; ~/anaconda3/envs/ortho/bin/mmseqs createindex OUTPUT.fa /tmp",
    "search_cmd": "~/anaconda3/envs/ortho/bin/mmseqs search PATH/mmseqsDBBASENAME DATABASE.fa OUTPUT.db /tmp/tmpBASEOUTNAME  --threads 1 ; ~/anaconda3/envs/ortho/bin/mmseqs convertalis --threads 1 PATH/mmseqsDBBASENAME DATABASE.fa OUTPUT.db OUTPUT"
    },
```

and I got this error, 

> Checking required programs are installed
> ----------------------------------------
> 
> ERROR: Cannot run mmseqs
> Format of make database command:
>   ~/anaconda3/envs/ortho/bin/mmseqs createdb INPUT OUTPUT.fa ; ~/anaconda3/envs/ortho/bin/mmseqs createindex OUTPUT.fa /tmp
> ERROR: Cannot run mmseqs
> Format of search database command:
>   ~/anaconda3/envs/ortho/bin/mmseqs search /mmseqsDBINPUT DATABASE.fa OUTPUT.db /tmp/tmpOUTPUT  --threads 1 ; ~/anaconda3/envs/ortho/bin/mmseqs convertalis --threads 1 /mmseqsDBINPUT DATABASE.fa OUTPUT.db OUTPUT
> Please check mmseqs is installed and that the executables are in the system path
> 
> ERROR: An error occurred, ***please review the error messages*** they may contain useful information about the problem.
> 

Sorry I thought I edited this accordingly. I am attaching the full json file

[config_copy.txt](https://github.com/davidemms/OrthoFinder/files/7130805/config_copy.txt)

Best, 

Andres

**Comment by davidemms** [comment]
Hi Andres

I'm not certain here, but it could be because the '~' is a bash expansion/macro. See what happens if you replace it with the path written out explicitly.

All the best
David

**Comment by drelo** [comment]
Hi David, 

Oh I forgot that detail, now I put the full path

> ERROR: Cannot run mmseqs
> Format of make database command:
>   /home/andrespara/anaconda3/envs/ortho/bin/mmseqs createdb INPUT OUTPUT.fa ; /home/andrespara/anaconda3/envs/ortho/bin/mmseqs createindex OUTPUT.fa /tmp
> ERROR: Cannot run mmseqs
> Format of search database command:
>   /home/andrespara/envs/ortho/bin/mmseqs search /mmseqsDBINPUT DATABASE.fa OUTPUT.db /tmp/tmpOUTPUT  --threads 1 ; /home/andrespara/anaconda3/envs/ortho/bin/mmseqs convertalis --threads 1 /mmseqsDBINPUT DATABASE.fa OUTPUT.db OUTPUT
> Please check mmseqs is installed and that the executables are in the system path

I suspect I had to only edit it in four places now it doesn't work after those 4 edits, with the full path. 

[config_full.txt](https://github.com/davidemms/OrthoFinder/files/7131173/config_full.txt)


Best

Andrés

**Comment by ohdongha** [comment]
Hi, 
I am getting exactly the same error message when trying "-S mmseqs" on the newest version 2.5.4 (installed from "OrthoFinder_source.tar.gz").
When I reinstalled a slightly older version 2.5.2 (also from "OrthoFinder_source.tar.gz"), it worked without an issue.  
Cheers,
Dong-Ha

**Comment by drelo** [comment]
Hi Dong-Ha, changing to version 2.5.2 worked fine, and there was no need to
edit the config file, it just used the mmseqs installed with conda. Thanks
for the tip.

Cheers

Andres

**Comment by davidemms** [comment]
I located the error here, the path for the temporary directory for testing the mmseqs dependency was being handled incorrectly. I'll be generating a new orthofinder release in the coming days with this fix included. Thanks for reporting!

**Comment by pvandam-gt** [comment]
Hi David,
I ran into the same problem today. Could you let me know when the bug fix is due for release in a new version please?
Cheers!
Peter
