### ISSUE TITLE
BLAST statistics missing for inferred orthologs

### ISSUE THREAD

**Issue by gauravdiwan89** [davidemms/OrthoFinder#621]
Hello,

I have used OrthoFinder to find orthologs between several species. In the final set of `.tsv` files containing pairwise Orthologs between species, I saw several many-to-one and one-to-many relationships. I wanted to further analyse these proteins by looking at their Diamond BLAST results from Orthofinder. For this, I retrieved the relevant BLAST results from the `WorkingDirectory` (using the indices for the species found in the `Log.txt` file). However, I found that for many of the pairs of sequences there are no BLAST statistics in these files. Can you please clarify why this must be happening?

I can send some example files for diagnosis if necessary. Please let me know!

Thanks.

**Comment by davidemms** [comment]
Hi

The orthologs are inferred by analysing the gene trees, not the BLAST scores. The 2019 paper details the methods used. The sequences included in each tree are determined by the clustering process. This uses a graph and so doesn't necessarily require a hit between two sequences for them to be in the tree. Note, one case where this might occur is for large gene families, since by default diamond will return at most 25 hits for a sequence, even if potentially many more exist. 

Best wishes
David

**Comment by gauravdiwan89** [comment]
Hi David,

Thanks a lot for the clarification. Yes, I do understand the the orthologs are inferred from the gene trees, though I missed the details about the clustering process. All is clear now.

I had another question regarding the inferred orthologs:

In some pairwise orthologs between species, a certain protein may have a one-to-one ortholog. However the same protein may be a part of a many-to-one relationship in another pairwise species comparison.

If I would like to combine the orthologs for this protein from all species, how should I treat the many-to-one relationships? Should I include the other proteins which are in the "many" as part of the orthologs from all the species?

Please let me know.

Best regards,
Gaurav

**Comment by davidemms** [comment]
Hi Gaurav

To combine the orthologs from multiple species you'll need to use orthogroups, they are the mathematically consistent extension of orthology to more then two species: https://github.com/davidemms/OrthoFinder#orthogroups-orthologs--paralogs

Best wishes
David

**Comment by gauravdiwan89** [comment]
Thank you very much, David. I'm really sorry, I read the linked information but things are not quite clear to me. If the Orthogroup is the collection of the orthologs from all the species, then how does one benefit from the next steps of the program involving gene tree - species tree reconciliation to delineate orthologs? 

In my mind, all the proteins that I see in the subdirectories of the `Orthologues` folder are the orthologs from all species and any remaining proteins in the Orthogroup will be the paralogs in the respective species. I am also basing this a bit on the information in #474 and #596

Can you please help me with my understanding?

Best regards,
Gaurav

**Comment by gauravdiwan89** [comment]
Thanks David, after some more thought and analysis, I have understood the use of the Orthogroups vs the pairwise species files.
