### ISSUE TITLE
Want to build phylogetic tree using single copy othologues

### ISSUE THREAD

**Issue by sowptika** [davidemms/OrthoFinder#628]
Dear David,
I have executed Orthofinder using 93 strains of a bacteria species (used the simple command "orthofinder -f <path of the folder with .faa files>). Now the output folder of "Single_Copy_Orthologue_Sequences" has files of each orthogroup with 93 protein sequences in it. I want to know how can I construct an msa and build a phylogenetic tree with the nucleotide sequences of these single copy orthologue sequences? Also what is more logical to build: a phylo tree with the protein sequences or the corresponding nucleotide sequences? 

Looking for kind advice. Thank you in advance.

**Comment by davidemms** [comment]
Hi

I think you should be able to find tools online that will create a concatenated MSA for you from individual fasta files. If you want to use nucleotide sequences then you will need to be able to identify the coding DNA sequence for each protein sequence. Often it is best to use the amino acid alignment to creaate the nucleotide alignment. Again, there should be tools online that can do this. I will usually use protein sequences for tree inference, but it can be good practice to also try using nucleotide sequences too.

Best wishes
David

**Comment by davidemms** [comment]
Hi Sowptika Pal

Yes you can use the .ffn files with the '-d' option, but usually you get better results using protein sequences. 

OrthoFinder uses the best species tree inference methods that I could design to work automatically for any input dataset. The data selection method it uses for "-M msa" will probably give a higher quality selection using the 'single copy orthologue sequences' method than most alternative variations that are published. Details are here: https://github.com/davidemms/OrthoFinder#species-tree-inference. 

You can also analyse the Orthogroups/Orthogroups.GeneCount.tsv file yourself if you want to consider alternative selection methods.

Best wishes
David

**Comment by davidemms** [comment]
... Another worthwhile thing to do is to run OrthoFinder with the "-M msa" option but then when it finishes redo the tree using "MultipleSequenceAlignments/SpeciesTreeAlignment.fa" but with IQTREE.
