### ISSUE TITLE
blastp uses 16 parallel search threads regardless of -t option

### ISSUE THREAD

**Issue by ehrenbentz** [davidemms/OrthoFinder#629]
Hi David,
I am using Orthofinder.py with blastp to produce a msa and a tree using raxml-ng. I am working on a linux machine with 32 cores (64 threads) and 256Gb of memory. The command below appears to be running blastp, but it only runs with 16 parallel threads regardless of what I specify with the -t option. The command used and the initial stdout are below.  
Is there a reason for this that I am missing? I'm not sure if this is normal behavior (4 all-vs-all comparisons = 16 threads?) or if it is not passing the -t option?

If this is not normal, Is there a way to hard-code the number of threads? 
I dug through the scripts to try and force it to use 64 threads, but I'm only so-so with python, so I was unable to find the correct code to modify. Any thoughts?

-E

command:
orthofinder.py -f Data -t 64 -a 16 -M msa -S blast -A mafft -T raxml-ng -X
also tried:
orthofinder.py -f Data --threads 64 -a 16 -M msa -S blast -A mafft -T raxml-ng -X
orthofinder.py -f Data -t 32 -a 8 -M msa -S blast -A mafft -T raxml-ng -X
orthofinder.py -f Data --threads 32 -a 4 -M msa -S blast -A mafft -T raxml-ng -X

Running on 4 protein.fasta files in Data/
All give the same stout, but only 16 threads are started.

2021-10-05 08:22:05 : Starting OrthoFinder 2.5.4
64 thread(s) for highly parallel tasks (BLAST searches etc.)
16 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "makeblastdb -help" - ok
Test can run "blastp -help" - ok
Test can run "mcl -h" - ok
Test can run "mafft /mnt/raid0/Bio/Orthofinder/Data/OrthoFinder/Results_Oct05/WorkingDirectory//_dependencies_check/SimpleTest.fa" - ok
Test can run "raxml-ng" - ok

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2021-10-05 08:22:06 : Creating Blast database 1 of 4
2021-10-05 08:22:06 : Creating Blast database 2 of 4
2021-10-05 08:22:06 : Creating Blast database 3 of 4
2021-10-05 08:22:07 : Creating Blast database 4 of 4

Running BLAST all-versus-all
----------------------------
Using 64 thread(s)
2021-10-05 08:22:07 : This may take some time....

**Comment by davidemms** [comment]
Hi

For the first stage, BLAST all-v-all, it paralellises over the searches of species X against species Y. As you've only got 4 species there are only 16 of these searches in total so there is nothing more for the remaining threads to do. Once it moves onto the tree inference it will parallelise over all the trees (of which there will be thousands for a normal dataset) so you will see all the cores being used then.

All the best 
David

**Comment by ehrenbentz** [comment]
Ah, I thought that might be the case. That makes sense.
Thanks for the quick response!
-E
