### ISSUE TITLE
Inparalogs and outparalogs

### ISSUE THREAD

**Issue by Mataivic** [davidemms/OrthoFinder#63]
Hello,

I may have missed it in the readme and the paper, but does Orthofinder do a distinction between inparalogs and outparalogs when building orthogroups ?

Thank you.

**Comment by davidemms** [comment]
Hi

The definition OrthoFinder uses for constructing orthogroups is given in the section "Orthogroups, Orthologues & Paralogues". 

So, how does that relate to inparalogs and outparalogs? Well, what people usually mean by inparalogs are paralogs which duplicated in a species after that species diverged from the most closely related other species in the analysis. Outparalogs diverged before this event. So an orthogroup will contain all inparalogs **and** it will also include outparalogs that diverged after **the first speciation** event for the species in the OrthoFinder analysis (that's just the definition of an orthogroup). 

But you can, if you want, define in/out paralogy with respect to any point in time you want, not just the most recent speciation event. So if you define your reference point to be the first speciation event for your set of species (and you are clear that this is what you're doing) then an orthogroup will contain all orthologs and inparalogs but no outparalogs.

Hope this helps
David
