### ISSUE TITLE
Shared orthogroups are missing in the species vs species file

### ISSUE THREAD

**Issue by dominikmerges** [davidemms/OrthoFinder#630]
Dear David,

I am looking into shared homologues between to individuals of the same species. I let orthofinder run on a bigger dataset with 18 species (mostly closely related and 3 more distantly related). 
To identify the core genome of the two individuals of interest, I checked this file:
Results_Sep29_2/Orthologues/Orthologues_U_ph_1.proteins/U_pha_1.proteins__v__U_ph_2.proteins.tsv
To get an idea which genes are not shared between the 2, I checked this file:
Results_Sep29_2/Orthogroups/Orthogroups.tsv
To my surprise, In this file are orthogroups present, which have homologues for both species, but are not listed in the U_pha_1.proteins__v__U_ph_2.proteins.tsv file. 
I am wondering how that can be? I am happy to send you the files in case you would like a look.

Many thanks and all the best,
Dominik

**Comment by davidemms** [comment]
Hi Dominik

You're missing the distinction between orthogroups and orthologs, there's an explanation here: https://github.com/davidemms/OrthoFinder#orthogroups-orthologs--paralogs

Best wishes 
David
