### ISSUE TITLE
[HOW TO UPDATE] How to remove some sequences from analysis

### ISSUE THREAD

**Issue by acpguedes** [davidemms/OrthoFinder#641]
Hi,

I'm wondering if there is any option to update the analysis by removing or add some sequences without re-run the entire analysis again.

Thanks in advance

**Comment by davidemms** [comment]
Hi

You can add or remove a whole species (and it's strongly recommended that you include all protein sequences from any species you do include):
https://github.com/davidemms/OrthoFinder#adding-extra-species

All the best
David
