### ISSUE TITLE
Any way around "The system limits on the number of files a process can open is too low" error without increasing limits?

### ISSUE THREAD

**Issue by ParthKRaval** [davidemms/OrthoFinder#646]
ERROR: The system limits on the number of files a process can open is too low. Please increase the limit and restart OrthoFinder.

Admin of our HPC says this can not be done due to some security issues.

Any way around this? 

Thanks in advance,
Parth KR

**Comment by davidemms** [comment]
Hi Parth KR

Sorry, but there's no way around this currently.

Best wishes
David
