### ISSUE TITLE
Small bug in create_files_for_hogs.py [Fix]

### ISSUE THREAD

**Issue by matrs** [davidemms/OrthoFinder#647]
The script has a small bug in the line 234, which defines `orthofinder_results` instead of  `orthofinder_results_dir`, which produces:

```
AttributeError: 'Namespace' object has no attribute 'orthofinder_results_dir'
```

So the fix is to  change 234:
parser.add_argument("orthofinder_results_dir", help="Input directory containing OrthoFinder results")

Saludos

**Comment by davidemms** [comment]
Hi

Thanks for reporting this! I've submitted your suggested fix.

Best wishes
David
