### ISSUE TITLE
How to get species-specific genes from OrthoFinder results..?

### ISSUE THREAD

**Issue by pjyoti29** [davidemms/OrthoFinder#656]
Orthogroups_UnassignedGenes.tsv file  contains all of the genes that were not assigned to any orthogroup. But then why they are given an orthogroup ID. Can we say these gene list specific to that particular species and can be used as species-specific genes.

thanks..!!

**Comment by davidemms** [comment]
Hi

These are genes that were not even clustered with any genes. As such, they are a subset of the species-specific genes. There are also species-specific genes which have multiple paralogs in that species, you can find them by looking in the file "Orthogroups/Orthogroups.GeneCount.tsv". If you create a 'Total' column (the sum for that row) then you can search for orthogroups where the number of genes in species X is equal to the Total.

Best wishes
David
