### ISSUE TITLE
Using blastn 

### ISSUE THREAD

**Issue by HendAbuElmakarem** [davidemms/OrthoFinder#667]
Hi, 

I would like to know if there's a way to do a blastn search using orthofinder. I can see that using ` -S blast_nucl` still produces the results of megablast search.

Thanks

Hend

**Comment by davidemms** [comment]
Hi Hend

You need to supply the '-d' option to tell it the input is DNA sequences. 

Best wishes
David

**Comment by HendAbuElmakarem** [comment]
Hi David,

I do that already, but I've noticed that Orthofinder probably uses
megablast as its default blast program (based on the output I get) and I
was wondering if I can use blastn instead (to get somewhat similar
sequences).

Thanks,
Hend

**Comment by davidemms** [comment]
Hi Hend

It should use whatever `blastn` is found first in your system path. You can see what this is by running `which blastn` and can adjust your path if you need to.

Best wishes
David
