### ISSUE TITLE
Inferring gene and species tree run time

### ISSUE THREAD

**Issue by benyoung93** [davidemms/OrthoFinder#675]
Good morning. 
Firstly thanks for the amazing package, it has been providing some really great results !!!

This is not really an issue, more of a learning/understanding of the time needed for the tree steps. I have been doing some googling and reading of other "issues" on run time but have not found any really inforamtive answers. I apologize if they are out there please feel free to link them if they answer my query :). 

I have a query, so I am running Orthofinder on 3 transcriptomes.  
- Sponge A (de-novo assembled) = ~200k transcripts 
- Sponge B (de-novo assembled) = ~150k transcripts
- Coral (protein fasta from genome) = ~30k transcripts (the "out" group)

So far this is my orthofinder ouput 

```
OrthoFinder version 2.5.4 Copyright (C) 2014 David Emms

2022-03-01 13:50:35 : Starting OrthoFinder 2.5.4
4 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /Users/benyoung/Desktop/both_spp_orthofinder/results_2/Results_Mar01/WorkingDirectory/SimpleTest.phy -o /Users/benyoung/Desktop/both_spp_orthofinder/results_2/Results_Mar01/WorkingDirectory/SimpleTest.tre" - ok

WARNING: Files have been ignored as they don't appear to be FASTA files:
.DS_Store
OrthoFinder expects FASTA files to have one of the following extensions: fas, faa, pep, fasta, fa

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2022-03-01 13:50:42 : Creating diamond database 1 of 3
2022-03-01 13:50:42 : Creating diamond database 2 of 3
2022-03-01 13:50:45 : Creating diamond database 3 of 3

Running diamond all-versus-all
------------------------------
Using 4 thread(s)
2022-03-01 13:50:48 : This may take some time....
2022-03-01 13:50:48 : Done 0 of 9
2022-03-01 14:53:40 : Done all-versus-all sequence search

Running OrthoFinder algorithm
-----------------------------
2022-03-01 14:53:42 : Initial processing of each species
2022-03-01 14:54:04 : Initial processing of species 0 complete
2022-03-01 14:56:18 : Initial processing of species 1 complete
2022-03-01 14:58:59 : Initial processing of species 2 complete
2022-03-01 14:59:21 : Connected putative homologues
2022-03-01 14:59:25 : Written final scores for species 0 to graph file
2022-03-01 14:59:52 : Written final scores for species 1 to graph file
2022-03-01 15:00:30 : Written final scores for species 2 to graph file

WARNING: program called by OrthoFinder produced output to stderr

Command: mcl /Users/benyoung/Desktop/both_spp_orthofinder/results_2/Results_Mar01/WorkingDirectory/OrthoFinder_graph.txt -I 1.5 -o /Users/benyoung/Desktop/both_spp_orthofinder/results_2/Results_Mar01/WorkingDirectory/clusters_OrthoFinder_I1.5.txt -te 1 -V all

stdout
------
b''
stderr
------
b'[mcl] cut <62> instances of overlap\n'
2022-03-01 15:07:46 : Ran MCL

Writing orthogroups to file
---------------------------
OrthoFinder assigned 465839 genes (81.5% of total) to 91382 orthogroups. Fifty percent of all genes were in orthogroups with 5 or more genes (G50 was 5) and were contained in the largest 29522 orthogroups (O50 was 29522). There were 5983 orthogroups with all species present and 229 of these consisted entirely of single-copy genes.

2022-03-01 15:13:00 : Done orthogroups

Analysing Orthogroups
=====================

Calculating gene distances
--------------------------
2022-03-01 15:19:28 : Done

Inferring gene and species trees
--------------------------------
```

As you can see all the initial steps ran in ~3hours and 30 minutes on the 1st March 2022
  
It is now the 4th of March 2022 and Orthofinder is still "inferring gene and species trees"

I have looked at other posts and if you are using a large number of genomes it says run time could be a few days, but for three transcriptomes this seems like a longgggggg time. 

At present there is no information in the results "Gene_trees directory. I do have all the results in the "Orthogroups" and "Orthologues" directories however. 

Some useful information that may help this query 

Orthofinder command 
```
orthofinder -f ~/Desktop/both_spp_orthofinder/data -o ~/Desktop/both_spp_orthofinder/results_2
```

Computer Specifications 
Processor - 3.2 GHz Quad-Core Intel Core i5
Memory - 16 GB 1600 MHz DDR3

Please let me know if you need anymore information, I will happily provide it :). Till then Im just gunna let it keep running and hope it finishes :). 

Benjamin

**Comment by davidemms** [comment]
Hi Benjamin

You can look in the `WorkingDirectory/Tree_ids` and `WorkingDirectory/Alignment_ids` directories (they are the approximate names) to see what trees & MSA have been completed. 

I think it should turn out fine. What counts is the number of sequences, runtime will be approximately quadratic in this number! If you look in the `Orthogroups.GeneCount.tsv` file you can see the size distribution. Your largest few orthogroups will take a disproportionately large amount of time. Additionally, you won't get any update on stdout until the first 1000 are done. After this, the remainder will be far quicker.

In terms of input, if you use something like Trinity for your assembly then you can use its transcriptome to identify just the longest protein sequence per gene. If you are able to do this for your transcriptomes this will improve things considerably--this is the input that OrthoFinder would expect and you'll get more accurate results and it will be a lot faster.

Best wishes
David
