### ISSUE TITLE
WARNING: program called by OrthoFinder produced output to stderr

### ISSUE THREAD

**Issue by Mirror1211** [davidemms/OrthoFinder#676]
Hi everyone

I conducted an analysis using Orthofinder in these days. And I found some information in slurm files as follows:

"WARNING: program called by OrthoFinder produced output to stderr

Command: mcl /public/home/chenqing/ZhangJ_wangxiaorong/whole-genome_sequencing/genome_evolution_and_phylogenomics/sequence/00_ortholog_detection/05_orthofinder/Or
thoFinder/Results_Mar05/WorkingDirectory/OrthoFinder_graph.txt -I 1.5 -o /public/home/chenqing/ZhangJ_wangxiaorong/whole-genome_sequencing/genome_evolution_and_ph
ylogenomics/sequence/00_ortholog_detection/05_orthofinder/OrthoFinder/Results_Mar05/WorkingDirectory/clusters_OrthoFinder_I1.5.txt -te 1 -V all

stdout
------

stderr
------
[mcl] cut <3> instances of overlap

2022-03-05 21:01:34 : Ran MCL

Writing orthogroups to file
---------------------------
OrthoFinder assigned 551005 genes (95.8% of total) to 37281 orthogroups. Fifty percent of all genes were in orthogroups with 19 or more genes (G50 was 19) and were contained in the largest 7381 orthogroups (O50 was 7381). There were 5373 orthogroups with all species present and 186 of these consisted entirely of single-copy genes.

2022-03-05 21:03:24 : Done orthogroups"

I don’t know whether there’s a problem with the analysis.
If so, how am I supposed to handle this problem.

Thanks a lot

Jing Zhang

**Comment by davidemms** [comment]
Hi Jing Zhang

That warning is not a problem at all, you can safely ignore it. It is MCL saying that in the clustering stage it had to break 3 'overlaps' to resolve the clustering. This occurs on some inputs but isn't a problem.

Best wishes
David

**Comment by Mirror1211** [comment]
Thanks a lot

Best wishes
