### ISSUE TITLE
orthologues directory

### ISSUE THREAD

**Issue by r0620660** [davidemms/OrthoFinder#677]
Hi,

I have a question about the orthologues directory in the output files. Are these files based on the results in the orthogroups directory (so based on the old orthofinder method), or is it based on info from the phylogenetic_heirarchical_orthogroups directory (newer method)? If the latter is true, can I get all the orthologs between two species by filtering the N0.tsv file? 

Kind regards,
Nand

**Comment by davidemms** [comment]
They're based on the phylogenetic methods also used for the newer phylogenetic HOGs.

Best wishes
David
