### ISSUE TITLE
Orthofinder dies at Writing orthogroups to file step

### ISSUE THREAD

**Issue by emmannaemeka** [davidemms/OrthoFinder#679]
Dear all,
Please I am having this issue running orthofinder. Please how can I proceed?

2022-03-25 16:02:30 : Starting OrthoFinder 2.5.4
8 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "mcl -h" - ok
Test can run "fastme -i /Users/pamluka/Desktop/asf_yinka_analysis/asf_resuls/orthofinder/OrthoFinder/Results_Mar25/WorkingDirectory/SimpleTest.phy -o /Users/pamluka/Desktop/asf_yinka_analysis/asf_resuls/orthofinder/OrthoFinder/Results_Mar25/WorkingDirectory/SimpleTest.tre" - ok

WARNING: Files have been ignored as they don't appear to be FASTA files:
.DS_Store
OrthoFinder expects FASTA files to have one of the following extensions: faa, pep, fa, fas, fasta

Dividing up work for BLAST for parallel processing
--------------------------------------------------
2022-03-25 16:02:46 : Creating blast_nucl database 1 of 6
2022-03-25 16:02:52 : Creating blast_nucl database 2 of 6
2022-03-25 16:02:57 : Creating blast_nucl database 3 of 6
2022-03-25 16:02:59 : Creating blast_nucl database 4 of 6
2022-03-25 16:03:01 : Creating blast_nucl database 5 of 6
2022-03-25 16:03:03 : Creating blast_nucl database 6 of 6

Running blast_nucl all-versus-all
---------------------------------
Using 8 thread(s)
2022-03-25 16:03:04 : This may take some time....
2022-03-25 16:03:06 : Done 0 of 36
2022-03-25 16:03:11 : Done 10 of 36
2022-03-25 16:03:13 : Done 20 of 36
2022-03-25 16:03:19 : Done all-versus-all sequence search

Running OrthoFinder algorithm
-----------------------------
2022-03-25 16:03:19 : Initial processing of each species
WARNING: Too few hits between species 0 and species 0 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 0 and species 1 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 0 and species 2 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 0 and species 3 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 0 and species 4 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 0 and species 5 to normalise the scores, these hits will be ignored
2022-03-25 16:03:20 : Initial processing of species 0 complete
WARNING: Too few hits between species 1 and species 0 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 1 and species 1 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 1 and species 2 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 1 and species 3 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 1 and species 4 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 1 and species 5 to normalise the scores, these hits will be ignored
2022-03-25 16:03:20 : Initial processing of species 1 complete
WARNING: Too few hits between species 2 and species 0 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 2 and species 1 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 2 and species 2 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 2 and species 3 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 2 and species 4 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 2 and species 5 to normalise the scores, these hits will be ignored
2022-03-25 16:03:20 : Initial processing of species 2 complete
WARNING: Too few hits between species 3 and species 0 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 3 and species 1 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 3 and species 2 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 3 and species 3 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 3 and species 4 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 3 and species 5 to normalise the scores, these hits will be ignored
2022-03-25 16:03:20 : Initial processing of species 3 complete
WARNING: Too few hits between species 4 and species 0 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 4 and species 1 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 4 and species 2 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 4 and species 3 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 4 and species 4 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 4 and species 5 to normalise the scores, these hits will be ignored
2022-03-25 16:03:20 : Initial processing of species 4 complete
WARNING: Too few hits between species 5 and species 0 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 5 and species 1 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 5 and species 2 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 5 and species 3 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 5 and species 4 to normalise the scores, these hits will be ignored
WARNING: Too few hits between species 5 and species 5 to normalise the scores, these hits will be ignored
2022-03-25 16:03:20 : Initial processing of species 5 complete
2022-03-25 16:03:23 : Connected putative homologues
2022-03-25 16:03:24 : Written final scores for species 0 to graph file
2022-03-25 16:03:24 : Written final scores for species 1 to graph file
2022-03-25 16:03:24 : Written final scores for species 2 to graph file
2022-03-25 16:03:24 : Written final scores for species 3 to graph file
2022-03-25 16:03:24 : Written final scores for species 4 to graph file
2022-03-25 16:03:24 : Written final scores for species 5 to graph file
2022-03-25 16:03:24 : Ran MCL

Writing orthogroups to file
---------------------------
/opt/miniconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3440: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/opt/miniconda3/lib/python3.9/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/opt/miniconda3/bin/orthofinder", line 7, in <module>
    main(args)
  File "/opt/miniconda3/bin/scripts_of/__main__.py", line 1775, in main
    DoOrthogroups(options, speciesInfoObj, seqsInfo)    
  File "/opt/miniconda3/bin/scripts_of/__main__.py", line 1402, in DoOrthogroups
    Stats(ogs, speciesNamesDict, speciesInfoObj.speciesToUse, files.FileHandler.iResultsVersion)
  File "/opt/miniconda3/bin/scripts_of/__main__.py", line 756, in Stats
    j, _ = next((i, x) for i, x in enumerate(L) if x > nAssigned/2)
StopIteration

**Comment by davidemms** [comment]
Hi

It looks like you haven't provided all genes from each of your input species and so there is not enough information for OrthoFinder to run properly.

Best wishes
David

**Comment by Liuhanlin22** [comment]
Hi

I have also encountered problems with this one. How should we provide all the genes for each input species.

Best wishes
