### ISSUE TITLE
Running OrthoFinder using not entire proteomes but a certain large gene family

### ISSUE THREAD

**Issue by yushengak47** [davidemms/OrthoFinder#680]
Dear all,

I'm interested in the evolution of a certain gene family among ~20 species, each species may have several hundreds of family members. I wonder is it rational to run OrthoFinder using only proteins of this family (not the entire proteome)  for defining ortho-groups? I don't need other results like trees, duplication events. Any idea?

Thanks.

**Comment by davidemms** [comment]
Hi

What information do you want, orthogroups? orthologs? OrthoFinder needs the gene trees to infer orthologs, if you only need orthogroups though you won't need the gene trees. 

I'd recommend either:

- do the analysis directly yourself using BLAST to work out members of the family and then infer the tree and analyse it manually to determine the information you require. This is probably the quickest way if you only want to know about one gene family & have limited computational resources.
- Run OrthoFinder on the full proteomes of all 20 species. If you only require orthogroups you can use the option '-og' to only run the analysis to the end of the orthogroup stage. If you want orthologs then don't use the '-og' option.

Best wishes
David
