### ISSUE TITLE
Differences in Orthofinder orthogroups based on species distance 

### ISSUE THREAD

**Issue by LeoVincenzi** [davidemms/OrthoFinder#683]
Dear developers,
I'm facing some dubts analysing gene families extracted from Orthofinder results. 
I was wondering if the distance between species could affect the results of Orthofinder. 

My question comes from some analysis I'm performing to study paralogous species between species. When I consider genes classified togheter in the same family after an orthofinder clustering between distant species, I find a sequence identity around 50-60%. On the other hand, if the clustering was performed between close species or either varieties of the same species, the identity reach the 96-97%. 
This make me think that there is a sort of affection of species'distance on the clustering phase. I don't know if there's a rule for which I should consider only distant species or only close species.

**Comment by davidemms** [comment]
Hi

You're describing exactly what you would expect from gene families: genes within the family from more distant species  will be more diverged. The purpose of OrthoFinder is to account for this when identifying the gene families.

Best wishes
David
