### ISSUE TITLE
Restart after disk quota exceeded

### ISSUE THREAD

**Issue by swuyts** [davidemms/OrthoFinder#69]
Hi David,

Thanks for this awesome tool! I've been running a quite heavy job with orthofinder and just woke up to this error:

Process Process-21:  
Traceback (most recent call last):  
  File "multiprocessing/process.py", line 258, in _bootstrap  
  File "multiprocessing/process.py", line 114, in run  
  File "orthofinder/orthofinder.py", line 473, in Worker_ProcessBlastHits  
  File "orthofinder/orthofinder.py", line 463, in ProcessBlastHits  
  File "orthofinder/scripts/matrices.py", line 37, in DumpMatrixArray  
  File "orthofinder/scripts/matrices.py", line 32, in DumpMatrix  
IOError: [Errno 122] Disk quota exceeded: 

Obviously I need to remove/compress some other files to allow Orthofinder some more temporary disk space. But after that, can I just resume the run using the -b option?

And if so, can I also compress some files in the WorkingDirectory of Orthofinder to reduce disc space usage?

Thank you,
Sander

**Comment by davidemms** [comment]
Yes, use the -b option. 

I don't think you can compress any of the files currently as practically all the space will be taken up by the BLAST results files and these need to be uncompressed for OrthoFinder to read them. That said, it doesn't sound like a bad idea to update OrthoFinder to compress these files and work with these compressed versions. I can take a look at implementing this but it'd be over the next week or two.

All the best
David

**Comment by swuyts** [comment]
Hi David,

That sounds like a great enhancement, since disc space on the scratch disc of our shared cluster is limited and I would run into problems as soon as I keep on adding more genomes.

Looking forward to the implementation.

Regards,
Sander

**Comment by davidemms** [comment]
Hi Sander

That's slightly trickier but I'll have a look and see what can be done.

All the best
David

**Comment by davidemms** [comment]
Would you be able to run the following on the directory structure created by OrthoFinder and let me know the results:
 
```
find . -type d -print0 | while read -d '' -r dir; do
    files=("$dir"/*)
    printf "%5d files in directory %s\n" "${#files[@]}" "$dir"
done 
```

It will print out the number of files in each subdirectory, using the method given here: 
http://stackoverflow.com/questions/15216370/how-to-count-number-of-files-in-each-directory

Thanks
David

**Comment by swuyts** [comment]
Of course,

Unfortunately this did not result in any new insights as it returned the following:

` 1 files in directory .
128224 files in directory ./WorkingDirectory
`

**Comment by swuyts** [comment]
Maybe this can give you more insights?

I've printed the amount of files in WorkingDirectory per filetype:

```
$ find WorkingDirectory/ -type f | sed 's/.*\.//' | sort | uniq -c
    223 fa
  78270 pic
  49731 txt
```

**Comment by davidemms** [comment]
There is no way currently to reduce the number of files, that number if necessary to allow quick access to all the pairwise comparisons without requiring everything to be held in RAM. Can you run it on something other than the scratch disc which will allow more files?

**Comment by swuyts** [comment]
Thanks David! I'll be looking into alternatives then :)
