### ISSUE TITLE
error code: 1

### ISSUE THREAD

**Issue by paul-bio** [davidemms/OrthoFinder#713]
Hi, it worked well previously, but I got an error....
Maybe there is problem making blastdb with **species17.**
Do you have any suggestions?
Thank you.

ERROR: external program called by OrthoFinder returned an **error code: 1**

Command: diamond makedb --in /path_to_orthofinder_dir/Results_Jun14_1/WorkingDirectory/**Species17.fa** -d /path_to_orthofinder_dir/Results_Jun14_1/WorkingDirectory/**diamondDBSpecies17**

stdout
------
b''
stderr
------
b'diamond v2.0.15.153 (C) Max Planck Society for the Advancement of Science\nDocumentation, support and updates available at http://www.diamondsearch.org\nPlease cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)\n\n#CPU threads: 32\nScoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)\nDatabase input file: /path_to_orthofinder_dir/Results_Jun14_1/WorkingDirectory/**Species17.fa**\nOpening the database file...  [0s]\nLoading sequences...  [0.01s]\nError: Error reading input stream at line 9516: Invalid character (.) in sequence\n'
ERROR: diamond makedb failed
ERROR: An error occurred, ***please review the error messages*** they may contain useful information about the problem.

**Comment by paul-bio** [comment]
I found there are (.) mark in the middle of sequence.
![image](https://user-images.githubusercontent.com/73869977/173491680-246d0eb4-b9a2-412c-9064-5495d4a854a2.png)

When I erased it, it worked.

So I will close this issue.

**Comment by lukaskon** [comment]
I read somewhere that "." is an internal stop codon, so I would check that before removing them.
