### ISSUE TITLE
extract subsets of orthogroups

### ISSUE THREAD

**Issue by dcopetti** [davidemms/OrthoFinder#72]
Hello,
I would like to extract from the Orthogroups.csv file the orthogroups that contain single-copy genes and are present in all species. Is there some simple command line (awk? grep?) way to do it?

More in general, are there tools to parse and visualize the output of OrthoFinder? Like producing Venn diagrams, creating subsets of the csv file for some species, and such.
Thanks

**Comment by DRL** [comment]
Hi dcopetti,
 
i wrote a tool for doing these kind of things. 

You can check it out at https://github.com/DRL/kinfin.

Official documentation is not there yet, but one should be able to figure things out based on the files in the example/ folder and the help.

Let me know if you have questions.

cheers, 

dom

**Comment by davidemms** [comment]
Hi 

Other people may have written tools for visualisation and parsing of the results files (thanks dom!). I might see if I can put together and make available some scripts over the coming months. 

It'd also be great to hear from users if they have any scripts that they can make available!

All the best
David

**Comment by yuzhenpeng** [comment]
[WARN] - PFAM-ID file 'data/Pfam-A.clans.tsv.gz' not found.

[STATUS] - Downloading 'ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.clans.tsv.gz' to '/Bio/home/yanglab/opt/biosoft/kinfin-master/build/lib/kinfin/../data/Pfam-A.clans.tsv.gz'.
