### ISSUE TITLE
entry order in Orthogroups.txt

### ISSUE THREAD

**Issue by macmanes** [davidemms/OrthoFinder#76]
David, 

In Orthogroups.txt, when there is more than 1 member of a group, how is the order of the members determined?

```
OG0000382: contig1 contig2 contig3 contig4
```

Is contig1 the 'most representative', or is the order simply based on the order they were found in the blast results or fasta files?

**Comment by davidemms** [comment]
Hi

There is no significance to the ordering of the sequences within an orthogroup. I think it might come down to the ordering in the input fasta files but if so that isn't intentional.

All the best
David
