### ISSUE TITLE
How to install FastTree for OF and all users on Mac

### ISSUE THREAD

**Issue by jdarias93** [davidemms/OrthoFinder#77]
Hello,

I'm running OSX 10.12.4, and I'm currently trying to install FastTree to use the tree estimation feature of OrthoFinder, however, I'm not sure what to do. After I download the C file from the website and try to follow the directions by putting: `gcc -O3 -finline-functions -funroll-loops -Wall -o FastTree FastTree.c -lm` into terminal, it results in a Unix executable file that runs and then immediately exits the terminal.

I'm not sure what to do next. What I think I have to do is somehow get the executable file to the system path, but I don't want to accidentally do something wrong. Any help is appreciated! Thanks in advance.

**Comment by davidemms** [comment]
Hi

This is really a fasttree issue so I suggest you contact the fasttree developers. They have a section on there website on installation:
http://www.microbesonline.org/fasttree/#Install

It does say:
```
If FastTree will not run, then try compiling it with this command instead:

gcc -DNO_SSE -O3 -finline-functions -funroll-loops -Wall -o FastTree FastTree.c -lm
```
Have you tried that?

All the best
David
