### ISSUE TITLE
Python 3.11 depreciation

### ISSUE THREAD

**Issue by SwiftSeal** [davidemms/OrthoFinder#775]
Python 3.11 has depreciated "U" open mode. Not sure if this has been flagged yet (only released yesterday!), and bioconda recipe specifies any python version >=2.7.

https://github.com/davidemms/OrthoFinder/blob/ca89e03afcc10ab87a2641c1e5949f499582cc1e/scripts_of/newick.py#L208

**Comment by davidemms** [comment]
Thanks @SwiftSeal, I was a bit slow on the ball with this one but it's now resolved: https://github.com/davidemms/OrthoFinder/issues/782

Best wishes
David
