### ISSUE TITLE
OGs badly aligned

### ISSUE THREAD

**Issue by arete1** [davidemms/OrthoFinder#78]
Hi!
I really enjoy using orthofinder, but I think I need some help. I analyzed 10 species from the same genus and with genes from the same domain. I am interested in orthogroups where all species are present (25). I retrieved some of the 25 OGs and aligned them with MUSCLE and got 20 % -30 % pairwise alignment. The minimum I need is 50 %. I think I would have to change the BLAST e valuebto e-10 or adjust MCL somehow. Do you have an idea how this can be done?

Thank you

**Comment by davidemms** [comment]
Hi

Can I check what you mean by 20-30% pairwise alignment? I'm guessing that if you take any two sequences in the alignment then 20-30% of the alignment doesn't have a gap in either of the two sequences? This doesn't sound that uncommon to me for a multiple sequence alignment (although I guess it is low if all your species are from the same genus). In general I would expect to see the domains well aligned but with a higher proportion of gaps outside of the conserved domains. Do you have a strong reason to expect this not to be the case? 

My guess is that this is what the orthogroups actually look like and that changing BLAST or MCL parameters wouldn't help. You could test this by doing a BLAST search with one of the sequences from one of the orthogroups and attempting to manually construct that orthogroup and seeing what the alignment looks like for this manual orthogroup.

Also, would trimming your alignments be suitable if you need a minimum of 50% alignment?

Let me know if this produces an interesting result or if you have any other questions

All the best
David
