### ISSUE TITLE
OrthologousGroups.txt does not exist

### ISSUE THREAD

**Issue by mictadlo** [davidemms/OrthoFinder#781]
Hi,
Is there a replacement for `OrthologousGroups.txt` I ran and found `Orthogroups/Orthogroups.txt`.

If yes, where could I find `Orthogroups/Orthogroups.txt` so I can fix a script?

I really appreciate any help you can provide.

Michal

**Comment by davidemms** [comment]
Hi Michal

`Orthogroups/Orthogroups.txt` is the replacement file. Full details of all the results files are here: https://github.com/davidemms/OrthoFinder#orthofinder-results-files

Best wishes
David
