### ISSUE TITLE
Error running Orthofinder prior to generating trees

### ISSUE THREAD

**Issue by ChuChuChaddy** [davidemms/OrthoFinder#806]
I am using Orthofinder to help annotate and get a phylogenetic tree in order to improve our genome scaffolding (there are 200k contings) with Cactus. My input data was our supernova assembly, an older assembly for the same species with better scaffolding, and a closely related species with  a chromosome level genome. After wrapping up blast and identifying orthologous genes, orthofinder moves onto the next step. Below is the end of the output, followed by the error message. What is "rU"? I can't find it in a helpfile.

Thanks for your time and help!

Inferring gene and species trees
--------------------------------

Best outgroup(s) for species tree
---------------------------------
2023-03-03 19:55:34 : Starting STRIDE

**but I have received the error:**

Traceback (most recent call last):
  File "/workingdir/scripts_of/stride.py", line 506, in GetRoot
    speciesTree = tree.Tree(speciesTreeFN, format=2)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workingdir/scripts_of/tree.py", line 221, in __init__
    read_newick(newick, root_node = self, format=format)
  File "/workingdir/scripts_of/newick.py", line 208, in read_newick
    nw = open(newick, 'rU').read()
         ^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workingdir/orthofinder", line 7, in <module>
    main(args)
  File "/workingdir/scripts_of/__main__.py", line 1801, in main
    GetOrthologues(speciesInfoObj, options, prog_caller)
  File "/workingdir/scripts_of/__main__.py", line 1540, in GetOrthologues
    orthologues.OrthologuesWorkflow(speciesInfoObj.speciesToUse,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workingdir/scripts_of/orthologues.py", line 1039, in OrthologuesWorkflow
    roots, clusters_counter, rootedSpeciesTreeFN, nSupport, _, _, stride_dups = stride.GetRoot(spTreeFN_ids, files.FileHandler.GetOGsTreeDir(), stride.GeneToSpecies_dash, nHighParallel, qWriteRootedTree=True)
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workingdir/scripts_of/stride.py", line 509, in GetRoot
    speciesTree = tree.Tree(speciesTreeFN, format=1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workingdir/scripts_of/tree.py", line 221, in __init__
    read_newick(newick, root_node = self, format=format)
  File "/workingdir/scripts_of/newick.py", line 208, in read_newick
    nw = open(newick, 'rU').read()
         ^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'

**Comment by nhartwic** [comment]
"rU" is a deprecated method of opening files in python. I'm pretty sure it was removed entirely (and made into the error you are seeing) with python 3.11.

If you just want to get running, downgrade your python version to 3.9 or 3.10

**Comment by davidemms** [comment]
Thanks for reporting this, it has been resolved in the new version, 2.5.5: https://github.com/davidemms/OrthoFinder/releases/tag/v2.5.5
