### ISSUE TITLE
OSError: [Errno 23] Too many open files in system

### ISSUE THREAD

**Issue by TANGLi83-star** [davidemms/OrthoFinder#809]
hi David, i'm running orthofinder on mac m1, when i use the command "orthofinder -f /data", it first said 

ERROR: The system limits on the number of files a process can open is too low. For 140 species OrthoFinder needs to be able to open at least r=19700 files. Please increase the limit and restart OrthoFinder
1. Check the hard and soft limits on the number of open files for your system:
    $ ulimit -Hn
    $ ulimit -Sn
2. If hard limit, h > r already, then you just need to increase the soft limit:
    $ ulimit -n 19700
3. Alternatively, if h < r then you need to edit the file '/etc/security/limits.conf', this requires root privileges. To increase the limit to 19700 for user  called 'emms' add the lines:
    emms hard nofile 19700
    emms soft nofile 19700
    (edit these lines to match your username)
4. Check the limit has now been updated (if you changed the hard limit you'll need to open a new session and confirm it's updated):
    $ ulimit -Sn
5. Once the limit is updated restart OrthoFinder with the original command

For full details see: https://github.com/davidemms/OrthoFinder/issues/384

and then I run the command "ulimit -n 19700" and rerun the "orthofinder -f /data", this time it still have error as follow:

OSError: [Errno 23] Too many open files in system: '/Users/tangli83/biosoft/orthofinder/k10240/OrthoFinder/Results_Mar14_1/WorkingDirectory/Files_test/Sp40/Sp58.txt'

please help me, thanks!

**Comment by davidemms** [comment]
Hi

The new release, version 2.5.5, includes an enhancement so that far fewer files need to be opened at once (less than 2 times the number of species), so that should resolve this issue.

Best wishes 
David
