### ISSUE TITLE
Node Support for Species Tree With Paralogous Orthogroups

### ISSUE THREAD

**Issue by saoirseguita** [davidemms/OrthoFinder#811]
Hi, 

When OrthoFinder generates the species tree, how does it calculate node support? I understand that it follows the STAG method, and it appears that a consensus of gene trees are used in a coalescent way to provide node support for a species, but how does the presence of genes with multiple copies (e.g. paralogs in a single orthogroup) affect this? 

For example, imagine a tree where species A has two copies of the gene, and species B has one. Gene 1 from species A branches with the gene from species B, but gene 2 from species A may be found elsewhere on the tree across a great phylogenetic distance, e.g. branching with species Z. How is this reconciled when considering node support? Would this gene tree support A+B, A+Z, both, or neither in the final species tree? 

Insights appreciated; thank you so much! 

Saoirse.

**Comment by davidemms** [comment]
Hi Saoirse

In the STAG method, a species tree is inferred from each orthogroup (that has all species present). Each of thes has a single node for each species. The consensus is then taken of these 'single-copy' trees. That initial species tree inference step from the orthogroup works by constructing a distance matrix based on the closest genes between each species pair. These genes are almost certainly orthologs, thus providing a good estimate of the species tree from each orthogroup. A less concise version is given in the paper.

Best wishes
David
