### ISSUE TITLE
Species Tree seems incorrect

### ISSUE THREAD

**Issue by shiyi-pan** [davidemms/OrthoFinder#814]
Hi, i have been running Orthofinder on some soybean genomes and is related species, with Arabidopsis and Lotus as outgroups. 
Before running Orthofinder, I filtered the proteins shorter than 50 aa.
The Species Tree seems incorrect, the wild soybean is divergent later than cultivated soybeans.
Here is my script:
python orthofinder.py  -t 8 -a 8 -S diamond -M msa -A mafft -I 1.5 -T fasttree -f inputdata -o output
Here is my Species Tree file:
(Nelnuc:0.135815,(Aratha:0.34715,(Aradur:0.15454,((Medtru:0.08532,Cicari:0.07058)1:0.0766,((SoyW01:0.00243,SoyL01:0.01224)1:0.00099,(GmWm82:0.0013,GmZH13:0.00359)1:0.00055)1:0.11444)1:0.03568)1:0.16018)1:0.135815);
SoyW01 is wild soybean, SoyL01,GmWm82,GmZH13 are cultivated soybeans.
Could give me some advise, Thank you very much.

**Comment by davidemms** [comment]
Hi

Looking at the tree, the soybean genomes are separated by exceptionally short branches, so it looks like it's very difficult to phylogenetically resolve. It could also be that a tree doesn't well explain the relationships between these four genomes, and the true relationships may be significantly more ocmplex if there has been introgression. 

The data from OrthoFinder is provides what you'd need if you wanted to investigate this further. E.g. you could use something like IQTREE to analyse the MSA used for the species tree: `MultipleSequenceAlignments/SpeciesTreeAlignment.fa`. This could also include trying more sophisticated models on sequence evolution e.g. CAT30. You could also do your own analysis by analysing `Orthogroups/Orthogroups.GeneCount.tsv` to decide which orthogroup sequences to use for species tree inference, or try using the ASTRAL tree inference method. You could also use tree/network inference methods, although I can't remember the name of any currently.

Best wishes
David
