### ISSUE TITLE
Primary transcripts

### ISSUE THREAD

**Issue by maggs-x** [davidemms/OrthoFinder#817]
Hi David,

I'm using OrthoFinder to identify orthogroups across several vertebrates. I used the primary_transcripts.py function to pull the primary transcripts from several taxa including mouse, humans, and zebrafish. I'm concerned because the number of primary transcripts far exceeds the number of protein-coding genes I expect from these taxa. The OrthoFinder results reflect this by showing a massive number of duplication events for humans, mice and zebrafish. I'm wondering if you could shed any light on this. In humans, for example, I'm getting over 42,000 primary transcripts. I'm hesitant to trust the duplication stats in the OrthoFinder results for example because of this. Please let me know your thoughts and if there is something I'm missing. Thank you!

Best,

Maggs

**Comment by davidemms** [comment]
Hi Maggs

You're right to check the input files and this does sound higher than I'd expect. I wonder if the files aren't annotated in a way that the primary transcripts script is able to process. Can you send me a link to where you're downloading the files from and I'll take a look.

All the best
David

**Comment by maggs-x** [comment]
Thanks for responding so quickly David. Here are the links I used to download protein datasets for human, mouse and zebrafish. The human proteome had >100,000 sequences originally, prior to running primary_transcripts.py

human: https://www.ncbi.nlm.nih.gov/data-hub/genome/GCF_000001405.40/
mouse: https://www.ncbi.nlm.nih.gov/data-hub/genome/GCF_000001635.27/
zebrafish: https://www.ncbi.nlm.nih.gov/data-hub/genome/GCF_000002035.6/

I also downloaded protein datasets from NCBI for platyfish, crotalus tigris, and sceloporus undulatus. The number of primary transcripts for these taxa seemed reasonable. Let me know if you'd like links for their proteomes as well.

Thanks so much for your help!

Maggs
________________________________

**Comment by maggs-x** [comment]
Hi David,

Any chance you found any errors in these files? On my end they look okay.

I’m also wondering how many starting points otherfinder uses when it searches through tree space with the maximum likelihood methods?

Hope you’re having a good week!

Best,

Maggs

Maggs X
they/them
________________________________

**Comment by davidemms** [comment]
Hi Maggs

Unfortunately the NCBI files are not well annotated in a way that makes it easy to distinguish between different transcripts of the same gene. I have had some contact with them about this and it was a problem they were already aware of and would be keen to get a solution for, but I think it's probably difficult for them to make changes to their formatting given its ubiquity.

My top recommendation would be to use proteomes from UniProt, they are of a very high quality and well annotated. Ensembl is also a very good resource, as are the various resources for specific groups of species (provided they provide a 'primary protein sequence' file).

For tree inference, it uses FastTree with default options by default, but you can choose to use any method you like with whatever arguments using the "-T" and specifiying the exact command line arguments you'd like it to use in the "config.json" file: https://github.com/davidemms/OrthoFinder#configjson--adding-addtional-programs-for-tree-inference-local-alignment-or-msa . When choosing a method, bear in mind that you are inferring gene trees for every gene family across your species, this is a large scale analysis and so expensive methods will require a lot of compute resources.

Best wishes
David

**Comment by maggs-x** [comment]
Thanks David!
________________________________

**Comment by SalvadorGJ** [comment]
Hi, 

This hint could be useful for someone dealing with the same issue. If I want to use the NCBI protein.faa.gz from a genome assembly, I also download the associated genomic.gff.gz and protein.gpff.gz stored in the same FTP path. With these both files I'm able to parse each of the protein FASTA sequence header and build an ENSEMBL-like header, which properly tag the transcript ID and the gene ID (GeneID Accession). By doing that before using primary_transcripts.py I get the appropriate amount of primary genes in well annotated proteomes. I will suggest using this only with reference-status assemblies.

**Comment by maggs-x** [comment]
Hey thank you so much! That’s really helpful!

Best,

Maggs

Maggs X
they/them
________________________________
