### ISSUE TITLE
ERROR: The system limits on the number of files a process can open is too low. For 454 species OrthoFinder needs to be able to open at least r=206216 files.

### ISSUE THREAD

**Issue by Ahmer1122** [davidemms/OrthoFinder#818]
ERROR: The system limits on the number of files a process can open is too low. For 454 species OrthoFinder needs to be able to open at least r=206216 files. Please increase the limit and restart OrthoFinder
1. Check the hard and soft limits on the number of open files for your system:
    $ ulimit -Hn
    $ ulimit -Sn
2. If hard limit, h > r already, then you just need to increase the soft limit:
    $ ulimit -n 206216
3. Alternatively, if h < r then you need to edit the file '/etc/security/limits.conf', this requires root privileges. To increase the limit to 206216 for user  called 'emms' add the lines:
    emms hard nofile 206216
    emms soft nofile 206216
    (edit these lines to match your username)
4. Check the limit has now been updated (if you changed the hard limit you'll need to open a new session and confirm it's updated):
    $ ulimit -Sn
5. Once the limit is updated restart OrthoFinder with the original command

For full details see: https://github.com/davidemms/OrthoFinder/issues/384

ERROR: An error occurred, ***please review the error messages*** they may contain useful information about the problem.

After changing the limit to 1000000 both H and S orthofinder is still giving this error?

**Comment by davidemms** [comment]
Hi

The new release, version 2.5.5, includes an enhancement so that far fewer files need to be opened at once (less than 2 times the number of species), so that should resolve this issue.

Best wishes 
David
