### ISSUE TITLE
OrthoFinder needs too much memory for orthologue inference

### ISSUE THREAD

**Issue by YannDussert** [davidemms/OrthoFinder#82]
Hi,
I am using OrthoFinder v1.1.2 with a dataset of 13 species (total number of proteins: 213364) on a cluster.
I run into a memory issue at the step 5 (Reconciling gene and species trees), when the program asks for a very large quantity of memory (more than 160 Gb). Is this normal, or is there be a problem with my dataset or the program?

Thank you in advance for your answer!
Yann

**Comment by davidemms** [comment]
Hi Yann

That seems like far more than I would expect. At that stage it is calling DLCpar to carry out the gene tree/species tree reconciliation and it shouldn't normally use that much memory. Could you post the output from the run and I'll take a look.

Thanks
David

**Comment by YannDussert** [comment]
Hello David,

I am attaching the files with the stderr and stdout. For information, OrthoFinder was used with the -b option (pre-computed blast results) and only one thread (-a 1).

Thanks!
Yann
[orthoFinder.stdout.txt](https://github.com/davidemms/OrthoFinder/files/1087565/orthoFinder.stdout.txt)
[orthoFinder.stderr.txt](https://github.com/davidemms/OrthoFinder/files/1087566/orthoFinder.stderr.txt)

**Comment by davidemms** [comment]
Hi Yann

OrthoFinder now implements its own method for the reconciliation which is more accurate and many times faster and doesn't have these memory issues. You can try it in the latest version.

All the best
David
