### ISSUE TITLE
N0.tsv's version to Orthogroups.GeneCount.tsv 

### ISSUE THREAD

**Issue by goshng** [davidemms/OrthoFinder#822]
Hi,

For OG, I find Orthogroups/Orthogroups.GeneCount.tsv for the number of genes in orthogroups. But, is there a gene count TSV-format file for Phylogenetic_Hierarchical_Orthogroups/N0.tsv. 

Thanks for the great work.

SangChul

**Comment by davidemms** [comment]
Hi SangChul

You can use the `tools/orthogroup_gene_count.py` script to generate it.

Best wishes
David
