### ISSUE TITLE
Meaning of branch lengths in resolved gene trees

### ISSUE THREAD

**Issue by JasonAnthonyHill** [davidemms/OrthoFinder#824]
I was wondering how the branch lengths of the resolved gene trees are derived under default parameters in the latest version of OrthoFinder. I read through the manual a couple of times and could not find that information. I may have missed it, but could you shed any light on where the branch lengths in the orthogroups come from?

**Comment by xbx-xbx-1208** [comment]
Do you have some thinking about this? I met the same issue as yours.

**Comment by davidemms** [comment]
The original gene tree distances are the DendroBLAST branch lengths. Those in the resolved trees inherit these distances but with minimal changes to accommodate the topology changes carried out in the tree resolution step.

**Comment by JasonAnthonyHill** [comment]
Ok! That makes sense, I can see it now that I look at it that way. Thanks.
