### ISSUE TITLE
"Command line argument error: Argument "out". File is not accessible: ..."

### ISSUE THREAD

**Issue by jdarias93** [davidemms/OrthoFinder#85]
Hello, so OrthoFinder v.1.1.8 encountered these errors during the BLAST all-v-all stage. I had simply wanted to add a new species to the WorkingDirectory, but then it resulted in these errors:

> Running BLAST all-versus-all
> ----------------------------
> Using 16 thread(s)
> 2017-06-19 10:11:09 : This may take some time....
> 2017-06-19 10:11:09 : Done 0 of 21
> libc++abi.dylib: terminating with uncaught exception of type std::__1::ios_base::failure: ios_base::clear: unspecified iostream_category error
> Command line argument error: Argument "out". File is not accessible:  `/Users/josharias/Downloads/OrthoFinder-1.1.8_source/orthofinder/AcanthPEP/Results_Jun07/WorkingDirectory/Blast3_10.txt'
> Command line argument error: Argument "out". File is not accessible:  `/Users/josharias/Downloads/OrthoFinder-1.1.8_source/orthofinder/AcanthPEP/Results_Jun07/WorkingDirectory/Blast10_8.txt'
> Command line argument error: Argument "out". File is not accessible:  `/Users/josharias/Downloads/OrthoFinder-1.1.8_source/orthofinder/AcanthPEP/Results_Jun07/WorkingDirectory/Blast8_10.txt'
> Command line argument error: Argument "out". File is not accessible:  `/Users/josharias/Downloads/OrthoFinder-1.1.8_source/orthofinder/AcanthPEP/Results_Jun07/WorkingDirectory/Blast10_1.txt'
> Command line argument error: Argument "out". File is not accessible:  `/Users/josharias/Downloads/OrthoFinder-1.1.8_source/orthofinder/AcanthPEP/Results_Jun07/WorkingDirectory/Blast1_10.txt'
> libc++abi.dylib: terminating with uncaught exception of type std::__1::ios_base::failure: ios_base::clear: unspecified iostream_category error
> libc++abi.dylib: terminating with uncaught exception of type std::__1::ios_base::failure: ios_base::clear: unspecified iostream_category error
> libc++abi.dylib: terminating with uncaught exception of type std::__1::ios_base::failure: ios_base::clear: unspecified iostream_category error
> libc++abi.dylib: terminating with uncaught exception of type std::__1::ios_base::failure: ios_base::clear: unspecified iostream_category error
> libc++abi.dylib: terminating with uncaught exception of type std::__1::ios_base::failure: ios_base::clear: unspecified iostream_category error
> BLAST failed to write output
> libc++abi.dylib: terminating with uncaught exception of type std::__1::ios_base::failure: ios_base::clear: unspecified iostream_category error
> libc++abi.dylib: terminating with uncaught exception of type std::__1::ios_base::failure: ios_base::clear: unspecified iostream_category error
> BLAST failed to write output
> libc++abi.dylib: terminating with uncaught exception of type std::__1::ios_base::failure: ios_base::clear: unspecified iostream_category error
> libc++abi.dylib: terminating with uncaught exception of type std::__1::ios_base::failure: ios_base::clear: unspecified iostream_category error
> BLAST failed to write output
> libc++abi.dylib: terminating with uncaught exception of type std::__1::ios_base::failure: ios_base::clear: unspecified iostream_category error
> libc++abi.dylib: terminating with uncaught exception of type std::__1::ios_base::failure: ios_base::clear: unspecified iostream_category error
> libc++abi.dylib: terminating with uncaught exception of type std::__1::ios_base::failure: ios_base::clear: unspecified iostream_category error
> 
> Running OrthoFinder algorithm
> -----------------------------
> 2017-06-19 13:47:20 : Initial processing of each species
> 
> ERROR: 12th field in BLAST results file line should be the bit-score for the hit
> Malformatted line in /Users/josharias/Downloads/OrthoFinder-1.1.8_source/orthofinder/AcanthPEP/Results_Jun07/WorkingDirectory/Blast0_10.txt
> Offending line was:
> 0_17660	10_72
> ERROR: An error occurred, please review previous error messages for more information.

Any help is appreciated. Thank you!

**Comment by davidemms** [comment]
Hi 

The problem comes on the 4th line of the output. It looks like BLAST is unable to write to files in the directory "/Users/josharias/Downloads/OrthoFinder-1.1.8_source/orthofinder/AcanthPEP/Results_Jun07/WorkingDirectory/". My guess is that there is some read/write issue for that directory on your machine. Are the permissions correct? 

Thanks
David
