### ISSUE TITLE
diamond dropped --ignore-warnings flag, leads to error

### ISSUE THREAD

**Issue by ryan-preble** [davidemms/OrthoFinder#873]
It appears as though the t version of diamond distributed with anaconda (0.9.19) does not use the --ignore-warnings flag, causing the program to die when called by OrthoFinder. Here was my stderr:

```
OrthoFinder version 2.5.5 Copyright (C) 2014 David Emms

2024-01-13 17:33:26 : Starting OrthoFinder 2.5.5
20 thread(s) for highly parallel tasks (BLAST searches etc.)
2 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
diamond produced the following output:

Error: Invalid option: ignore-warnings


Error: Invalid option: ignore-warnings


ERROR: Cannot run diamond
...
```

...Which was followed with a description of the environment and the commands called. A quick look at the diamond help page shows that --ignore-warnings is not a valid flag. I will edit config.json to remove the flag from the diamond commands, and I will check back in if this does not resolve the issue.  Note that I am not building more recent versions of diamond myself because I am working on a shared system and I don't always have the necessary permissions. I will also check to see if it is possible to force an installation of more recent versions of diamond on my system.

**Comment by ryan-preble** [comment]
Best solution is to just mask the version of diamond distributed with anaconda and supply your own. I don't know who is updating the anaconda distribution, but I might recommend updating the version of diamond supplied with it.

**Comment by hyr13579** [comment]
Hello? Can you tell me in detail how to solve the problem when Diamand cannot be used? Thank you vary much!

**Comment by ryan-preble** [comment]
> Hello? Can you tell me in detail how to solve the problem when Diamand cannot be used? Thank you vary much!

I downloaded OrthoFinder over anaconda, so it was located in a folder with a name like `~/envs/orthofinder/bin`. There should also be a program in that folder named `diamond`. Rename this file to something like `diamond_DEPRECATED` or delete it altogether. Then go to the diamond github page (https://github.com/bbuchfink/diamond) and download the file for your system. Then unpack the file and retrieve the diamond executable. Either put it in `~/envs/orthofinder/bin` or some other place where it will be found in your `PATH` variable.

**Comment by hyr13579** [comment]
I did this and succeeded, but there was a warning, as follows, have you ever encountered it? Thank you!

WARNING: program called by OrthoFinder produced output to stderr

Command: diamond blastp --ignore-warnings -d /mnt/share/2024.1.22/11/tri40/OrthoFinder/Results_Jan22_1/WorkingDirectory/diamondDBSpecies27 -q /mnt/share/2024.1.22/11/tri40/OrthoFinder/Results_Jan22_1/WorkingDirectory/Species36.fa -o /mnt/share/2024.1.22/11/tri40/OrthoFinder/Results_Jan22_1/WorkingDirectory/Blast36_27.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1

stdout
------
b''
stderr
------
b'Warning: Failed to delete temporary file /mnt/share/2024.1.22/11/tri40/OrthoFinder/Results_Jan22_1/WorkingDirectory/diamond-tmp-DioQLv\n'

**Comment by ryan-preble** [comment]
> I did this and succeeded, but there was a warning, as follows, have you ever encountered it? Thank you!
> 
> WARNING: program called by OrthoFinder produced output to stderr
> 
> Command: diamond blastp --ignore-warnings -d /mnt/share/2024.1.22/11/tri40/OrthoFinder/Results_Jan22_1/WorkingDirectory/diamondDBSpecies27 -q /mnt/share/2024.1.22/11/tri40/OrthoFinder/Results_Jan22_1/WorkingDirectory/Species36.fa -o /mnt/share/2024.1.22/11/tri40/OrthoFinder/Results_Jan22_1/WorkingDirectory/Blast36_27.txt --more-sensitive -p 1 --quiet -e 0.001 --compress 1
> 
> ## stdout
> ## b''
> stderr
> b'Warning: Failed to delete temporary file /mnt/share/2024.1.22/11/tri40/OrthoFinder/Results_Jan22_1/WorkingDirectory/diamond-tmp-DioQLv\n'

I have not ever had that error but I don't think it's a problem. You can always delete temporary files manually if you need to.
