### ISSUE TITLE
diamond hanging/failing to allocate memory while processing Test.fa

### ISSUE THREAD

**Issue by thackl** [davidemms/OrthoFinder#88]
I'm running different data sets with diamond, and there is that initial step involving aligning Test.fa were something seems to be off. The one below is running since yesterday afternoon 

```
diamond v0.8.24.86 | by Benjamin Buchfink <buchfink@gmail.com>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 20
Database file: /nobackup1b/users/chisholmlab/simons_metagenomes/mg-quantification/orthofinder/sar11/temp_83583209132/Test.fa
Opening the database file...  [0.00742s]
Loading sequence data (0 sequences processed)... 
```
Two other processes took quite long, and than ran into `Failed to allocate sufficient memory`, but than continued with aligning the SpeciesXX.fa files.
```
diamond v0.8.24.86 | by Benjamin Buchfink <buchfink@gmail.com>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 20
Database file: /nobackup1b/users/chisholmlab/simons_metagenomes/mg-quantification/orthofinder/pro/temp_83583209132/Test.fa
Opening the database file...  [0.002023s]
Loading sequence data (0 sequences processed)...  [3910.18s]
Failed to allocate sufficient memory. Please refer to the readme for instructions on memory usage.
Failed to allocate sufficient memory. Please refer to the readme for instructions on memory usage.
```
Not sure if that is somewhat expected behaviour, or what to make of it...

**Comment by davidemms** [comment]
Hi Thomas

No, this isn't expected behaviour. I would recommend reporting it to the developers of Diamond: https://github.com/bbuchfink/diamond.

The contents of the test.fa file that is used are:
 

> >0_0
> MNINSPNDKEIALKSYTETFLDILRQELGDQMLYKNFFANFEIKDVSKIGHITIGTTNVTPNSQYVIRAY
> ESSIQKSLDETFERKCTFSFVLLDSAVKKKVKRERKEAAIENIELSNREVDKTKTFENYVEGNFNKEAIR
> IAKLIVEGEEDYNPIFIYGKSGIGKTHLLNAICNELLKKEVSVKYINANSFTRDISYFLQENDQRKLKQI
> RNHFDNADIVMFDDFQSYGIGNKKATIELIFNILDSRINQKRTTIICSDRPIYSLQNSFDARLISRLSMG
> LQLSIDEPQKADLLKILDYMIDINKMTPELWEDDAKNFIVKNYANSIRSLIGAVNRLRFYNSEIVKTNSR
> YTLAIVNSILKDIQQVKEKVTPDVIIEYVAKYYKLSRSEILGKSRRKDVVLARHIAIWIVKKQLDLSLEQ
> IGRFFGNRDHSTIINAVRKIEKETEQSDITFKRTISEISNEIFKKN
> >1_2
> MKTKLKRFLEEISVHFNEANSELLDAFVHSIDFVFEENDNIYIYFESPYFFNEFKNKLNHLINVENAVVF
> NDYLSLEWKKIIKENKRVNLLNKKEADTLKEKLATLKKQEKYKINPLSKGIKEKYNFGNYLVFEFNKEAV
> YLAKQIANKTTHSNWNPIIIEGKPGYGKSHLLQAIANERQKLFPEEKICVLSSDDFGSEFLKSVIAPDPT
> HIESFKSKYKDYDLLMIDDVQIISNRPKTNETFFTIFNSLVDQKKTIVITLDCKIEEIQDKLTARMISRF
> QKGINVRINQPNKNEIIQIFKQKFKENNLEKYMDDHVIEEISDFDEGDIRKIEGSVSTLVFMNQMYGSTK
> TKDQILKSFIEKVTNRKNLILSKDPKYVFDKIKYHFNVSEDVLKSSKRKKEIVQARHICMYVLKNVYNKN
> LSQIGKLLRKDHTTVRHGIDKVEEELENDPNLKSFLDLFKN

(github won't let me attach a .fa file)

And the test commands are:
```
diamond-sse2 makedb --in test.fa -d test_database
diamond-sse2 blastp -d test_database -q test.fa -o test_search_results.txt --sensitive -p 1 --quiet -e 0.001
```

All the best
David

**Comment by thackl** [comment]
OK, thanks. I will investigate further and let you know about my findings.

**Comment by thackl** [comment]
OK, seems to be an issue with my particular diamond version, with which I can reproduce the problem on the test data. After update to the latest version, things run smoothly. Sorry to have bothered you with this. Thanks for the help.
Cheers
Thomas

**Comment by davidemms** [comment]
That's great you got it fixed, thanks for letting me know.

Cheers
David
