### ISSUE TITLE
[Feature Request] Allow for passing options to Diamond and other dependencies

### ISSUE THREAD

**Issue by StefanFlaumberg** [davidemms/OrthoFinder#907]
Dear OrthoFinder team,

It would be great to have a way to pass free arguments to the sequence search, msa and gene tree building programs. Their default behavior might sometimes be far from optimal. For example, passing a more strict E-value cutoff or coverage cutoffs may decrease the number of false positive findings during blastp search.

This can be realized by introducing something like `-So`, `-Ao` and `-To` options, after which one would write arguments to be passed respectively to the search, alignment or tree program being used. Like writing `-S diamond -So '--evalue 1E-5 --matrix BLOSUM45'` to use diamond blastp for search and to pass the evalue and matrix arguments to it.

Personally, I'm mostly interested in passing options to the searching program.

I think such an improvement would make OrthoFinder much more flexible)

Best regards,
Stefan

**Comment by davidemms** [comment]
Hi Stefan

You can edit the arguments using the config.json file.

All the best
David
