### ISSUE TITLE
not an issue, clarification wanted for which sequences are represented in orthogroups

### ISSUE THREAD

**Issue by vmkhot** [davidemms/OrthoFinder#909]
I ran orthofinder on 253 genomes - the run was successful - producing the orthogroup sequences, a species tree etc. 

When I checked the rooted species tree, I found that it was rooted at the wrong position so I manually rerooted the species tree at the outgroup and reran Orthofinder with the -ft -s options. This produced new results for the Phylogenetic_Hierarchical_Orthogroups dir but did not create new Orthogroup_Sequences or MultipleSequenceAlignments directories. 

I am planning to use the orthogroup sequences or orthogroup MSAs from Orthofinder to generate bootstrap trees for gene-tree-species-tree-reconciliation later and am wondering if I need to recreate the orthogroup sequences per orthogroup manually from the `Phylogenetic_Hierarchical_Orthogroups/N0.tsv` files for a more accurate set of orthogroups to use downstream? OR are the groups in the Orthogroup_Sequences dir in fact already taken from these resolved gene trees?

I suspect I have some confusion about what these files actually are and would love some clarity on it! 

Thanks in advance for your help and the very useful program :) 

Varada

**Comment by lauriebelch** [comment]
Hi Varada,

Try using the -b flag instead of -ft

-ft uses pre-computed orthogroups, so won't create new orthogroup sequences
-b uses pre-computed BLAST results, so will re-do the orthogroups

Hope this works!

Thanks,

Laurie

**Comment by vmkhot** [comment]
Hi Laurie,

Thanks for your response! In my analysis, for example, I have a large orthogroup being split into 20 HOGs.  I think from reading #910 and #367, I've come to the conclusion that I should indeed be using HOGs from N0.tsv file rather than the regenerated orthogroup sequences for downstream comparative genomics right? 

For the downstream comparative genomics, gene duplications at all nodes after the root matter for me. 

Thanks,

Varada

**Comment by lauriebelch** [comment]
Hi Varada,

Yes I agree that you should use the HOGs from N0 for downstream analysis

Most of the output files still use the old orthogroups (including Duplications.tsv), but we are changing that for orthofinder3 later this year, and you can use the orthogroup and gene IDs to match everything up to the hierarchical orthogroups (e.g N0)

Thanks,

Laurie
