### ISSUE TITLE
Question_process_Orthofinder

### ISSUE THREAD

**Issue by cristoyerenahs** [davidemms/OrthoFinder#911]
Good Afternoon.
Orthofinder team.

I have run the Orthofinder (./orthofinder -f mydata) process with 1000 proteomes of different bacteria species, After some days, I had some erros in order to generate the outputs files.

I want to attach the errors. 

Could you help about the erros?

Thanks
![erros](https://github.com/davidemms/OrthoFinder/assets/60819833/c5bfb38b-520c-427f-becd-b5246cfe9ce0)

**Comment by davidemms** [comment]
Hi

You can also try the code in the branch 'linear_species_addition', which will be merged into the main branch soon. It has a solution to the problem of too many open files. You will need to install some extras python dependencies: biopython six scikit-learn.

All the best
David
