### ISSUE TITLE
issue with running Orthofinder

### ISSUE THREAD

**Issue by SrichandanPadhi** [davidemms/OrthoFinder#912]
I am getting the following error while running orthofinder. The program runs upto some extent and then displayed error, the error is from speciesTree. Kindly check the below enclosed snapshot.

The command is 
/home/srichandanp/miniconda3/envs/orthofinder/bin/orthofinder -f /scratch/srichandanp/Genome_Analysis/OrthoFinder_Sequences/

![image](https://github.com/davidemms/OrthoFinder/assets/128894160/de1226b7-94f1-40ae-a4b3-fb8fd7bcb906)

**Comment by lauriebelch** [comment]
Hi SrichandanPadhi,

It seems to have failed to generate a species tree. Can I ask how many species you are analysing, and what kind of species (e.g. plants, bacteria, fungi, a mix)

If possible, it might we worth running orthofinder with your own species tree (using the `-s` option)

Thanks,
Laurie

**Comment by SrichandanPadhi** [comment]
Hi..
Thank you for your prompt response.

I actually was running on nucleotide sequences with -d as an option. Later
I did with the translated sequences, it worked fine and perfectly.
