### ISSUE TITLE
HIV teste 1

### ISSUE THREAD

**Issue by Dribio1** [davidemms/OrthoFinder#913]
Vacina multiepitopo

**Comment by lauriebelch** [comment]
Olá Dribio1,

Was there an issue that I might be able to help with?

Thanks,

Laurie

**Comment by Dribio1** [comment]
Hi Laurie
I need to fine the HIV core genoma using the orthofinder programa. But I
can’t to use comand line. Can I do these using another and friendly
program? Please
Thanks a lot to answer me
Best regards

Adriana Alves Oliveira Paim

M.Sc. Ph.D. in Microbiology/Virology

Post-doctoral Researcher UFMG

Cel (+55) 31 998147229


Em sex., 12 de jul. de 2024 às 09:28, lauriebelch ***@***.***>
escreveu:

**Comment by lauriebelch** [comment]
Olá Adriana,

You could try something like CoreGenes5.0 https://coregenes.ngrok.io/ (which is explained in this paper https://pubmed.ncbi.nlm.nih.gov/36423143/).

Espero que isso seja util para você

Melhores cumprimentos,

Laurie

**Comment by Dribio1** [comment]
Thank you so much, Laurie!
Best

Adriana Alves Oliveira Paim

M.Sc. Ph.D. in Microbiology/Virology

Post-doctoral Researcher UFMG

Cel (+55) 31 998147229


Em sex., 12 de jul. de 2024 às 10:36, lauriebelch ***@***.***>
escreveu:
