### ISSUE TITLE
header changed in MSA

### ISSUE THREAD

**Issue by jpinus** [davidemms/OrthoFinder#916]
Hello, 

i'm using orthofinder on BUSCO genes from over 500 metagenomes.
The header of all single BUSCO genes from one library is the same pattern, for example:
`>3565_AO_639252at33208`

However, after running OrthoFinder on my directory containing all the *.faa files and examining the generated Multiple Sequence Alignment (MSA) files, I noticed the headers now appear as follows:
```
>3565_A_3565_AO@639252at33208
>3565_AO_3565_AO@639252at33208
```
This change is causing issues in my subsequent workflow.

Therefore, my question is: why does OrthoFinder modify the headers in this manner, and how can I prevent this from happening?

I am using OrthoFinder version 2.5.5, and here is the command I executed:

```
orthofinder.py -f .\
 -M msa\
 -S diamond_ultra_sens\
 -t $NSLOTS
```

Thank you for your assistance.

**Comment by davidemms** [comment]
Hi

This is to help identify which species each gene came from and also to avoid issues where sequence IDs are not unique across species. You can use '-X' to turn it off, or could use a tool such as sed to globally remove these species identifiers if you have a consistent naming pattern for your input fasta files.

All the best
David
