### ISSUE TITLE
Option to stop Orthofinder after building the species tree?

### ISSUE THREAD

**Issue by Laura-Alex** [davidemms/OrthoFinder#918]
Thank you for the very helpful program!

I don't know if I I'm alone in this, but I mostly use Orthofinder for building species trees from proteomes. Would it be possible to have a stopping point after the species tree, before all the other computationally-intensive steps are run?

Thank you for your time!

**Comment by Jonathan-Holmes-Bioinformatics** [comment]
Hi Laura-Alex,

Currently there is no way to stop OrthoFinder following the species tree building. many of the computationally expensive steps generating the Orthogroups and Trees are required in the building of the species tree. 

You may be able to stop the run after building the Orthogroup gene trees using the `-ot` flag before running [STAG](https://github.com/davidemms/STAG) to generate an unrooted species tree.

**Comment by davidemms** [comment]
Hi

Thanks for your comment, just to confirm we don't have an option for that although I can see it's an interesting suggestion. We'll take a note in case it is something we can implement in the future. 

Best wishes
David
