### ISSUE TITLE
Running OrthoFinder with Large Species Set (>2k)

### ISSUE THREAD

**Issue by BioOmics** [davidemms/OrthoFinder#919]
Hello,

I'm currently running `OrthoFinder` on a cluster with `2000` species. Besides using the `-op` option for `BLAST`, are there any other commands or methods for distributing the tasks?

Additionally, while executing `fastme` on `OG000000N`, the process is **very slow** due to the large amount of protein data (>100k) in these OGs. I would like to skip the GeneTree construction because **we only need the SpeciesTree** and the OG categories at the end. How can I do this?

Furthermore, I understand that `ulimit` should be set to the square of the number of species plus 100, which would require opening 4 million files simultaneously for 2000 species. Is there a way to handle file opening incrementally or otherwise manage this constraint?

Are there any other optimization strategies or suggestions you could provide?

Thank you!

**Comment by Jonathan-Holmes-Bioinformatics** [comment]
Hi BioOmics,

Unfortunately the workflow for OrthoFinder first requires the gene tree inference from the Orthogroups in order to construct the species tree using the [STAG](https://github.com/davidemms/STAG) algorithm. So currently using OrthoFinder you cannot generate a species tree without the gene trees. 

There are several other stop points that may be useful if you want to infer your own species tree from the blast or Orthogroup data:

`-op`: Stop after preparing input files for all-vs-all sequence search (e.g. BLAST/DIAMOND)
`-og`: Stop after inferring orthogroups
`-os`: Stop after writing sequence files for orthogroups (requires '-M msa')
`-oa`: Stop after inferring mulitple sequence alignments for orthogroups (requires '-M msa')
`-ot`: Stop after inferring gene trees for orthogroups

 As far as I'm aware there is no current way to reduce the number of simultaneous open files.

**Comment by BioOmics** [comment]
Thanks!

Here, after done `orthofinder -b WorkingDirectory/ -S diamond -t 50 -a 50 -M msa`, can i run `orthofinder -fg ./Results_Jul27_1 -t 50` to change using the [STAG](https://github.com/davidemms/STAG) algorithm?  (Because using ` -M msa`  to generate a species tree is not good)

best

**Comment by davidemms** [comment]
Hi

There are updates in the version 3 beta just released which may help with this. See the release notes for details.

One approach you could alao use with either version is to infer only the orthogroups and use this analysis to select orthogroups to use for a manual species tree inference. E.g. in the STAG paper it describes how this is done using a concentrated MSA using a small number of orthogroups, rather than inferring alignments for all of them. Likewise, you could consider using trees for a subset of the orthogroups and running the STAG algorithm directly on them. 

Best wishes
David

**Comment by BioOmics** [comment]
Thank you for your update.

I am using [OrthoFinder v3.0.1b1](https://github.com/davidemms/OrthoFinder/releases/tag/3.0.1b1) and encountering some issues:

### Installation

I failed to install it using the following command:
```bash
conda create -n orthofinderv3 -c defaults -c bioconda -c conda-forge orthofinder=3.0.1b1
```

So I first installed version 2:
```bash
conda create -n orthofinderv2 orthofinder
```

### Installing ASTRAL
Since `OrthoFinder_source/scripts_of/bin/astral-pro` required `GLIBC_2.29` when executing, it threw the following error:
```bash
./orthofinder.py --core ExampleData/OrthoFinder/Results_Core/ --assign ExampleData/AdditionalSpecies

....

Test can run "mafft_memsave" - ok
Test can run "fasttree_fastest" - ok
Test can run "astral-pro -i /mnt/public3/chaohy/software/OrthoFinder_source/ExampleData/OrthoFinder/Results_Core/../Results_Oct17/WorkingDirectory/dependencies/astral.input.nwk -o /mnt/public3/chaohy/software/OrthoFinder_source/ExampleData/OrthoFinder/Results_Core/../Results_Oct17/WorkingDirectory/dependencies/astral.output.nwk -t 2" - failed
Returned a non-zero code: 1

stderr:
b"astral-pro: /.bio-apps/ext-libs/lib64/libm.so.6: version `GLIBC_2.29' not found (required by astral-pro)\n"
b"astral-pro: /.bio-apps/ext-libs/lib64/libm.so.6: version `GLIBC_2.23' not found (required by astral-pro)\n"
b"astral-pro: /.bio-apps/ext-libs/lib64/libc.so.6: version `GLIBC_2.32' not found (required by astral-pro)\n"
b"astral-pro: /.bio-apps/ext-libs/lib64/libc.so.6: version `GLIBC_2.34' not found (required by astral-pro)\n"
ERROR: Cannot run astral-pro
```
So I downloaded [ASTRAL-Pro](https://github.com/chaoszhang/A-pro) and compiled it successfully. Then, I modified the code in OrthoFinder v3 to execute ASTRAL-Pro.

I changed [astral.py#L21](https://github.com/davidemms/OrthoFinder/blob/92d520dfa65ab128db20702b8fcd01cbbffac4cd/scripts_of/astral.py#L21) to:
```bash
def get_astral_command(astral_input, species_tree, threads):
    return " ".join(["java -D\"java.library.path=/mypath/Astral/lib\" -jar /mypath/Astral/astral.1.1.6.jar", "-i", astral_input, "-o", species_tree, "-t", str(threads)])
```
I also changed [__main__.py#L251](https://github.com/davidemms/OrthoFinder/blob/92d520dfa65ab128db20702b8fcd01cbbffac4cd/scripts_of/__main__.py#L251) to:
```bash
cmd = " ".join(["java -D\"java.library.path=/mnt/public3/chaohy/software/A-pro-master/Astral/lib\" -jar /mnt/public3/chaohy/software/A-pro-master/Astral/astral.1.1.6.jar", "-i", fn_test, "-o", fn_output, "-t", "2"])
```

### Running OrthoFinder v3.0.1b1

```bash
./orthofinder.py -f ExampleData/ -n Core
# Executed successfully
```
But the following command encountered an error:
```bash
./orthofinder.py --core TestData/OrthoFinder/Results_Core/ --assign TestData/AdditionalSpecies

OrthoFinder version 3.0.1b1 Copyright (C) 2014 David Emms

2024-10-17 16:57:30 : Starting OrthoFinder 3.0.1b1
48 thread(s) for highly parallel tasks (BLAST searches etc.)
6 thread(s) for OrthoFinder algorithm

INFO: For --assign defaulting to 'mafft --memsave' to reduce RAM usage

INFO: For --assign defaulting to 'FastTree -fastest' to reduce RAM usage

Results directory: /mnt/public3/chaohy/software/OrthoFinder_source/TestData/OrthoFinder/Results_Core/../Results_Oct17/

Checking required programs are installed
----------------------------------------
Running with the recommended MSA tree inference by default. To revert to legacy method use '-M dendroblast'.

Test can run "mafft_memsave" - ok
Test can run "fasttree_fastest" - ok
Test can run "java -D"java.library.path=/mnt/public3/chaohy/software/A-pro-master/Astral/lib" -jar /mnt/public3/chaohy/software/A-pro-master/Astral/astral.1.1.6.jar -i /mnt/public3/chaohy/software/OrthoFinder_source/TestData/OrthoFinder/Results_Core/../Results_Oct17/WorkingDirectory/dependencies/astral.input.nwk -o /mnt/public3/chaohy/software/OrthoFinder_source/TestData/OrthoFinder/Results_Core/../Results_Oct17/WorkingDirectory/dependencies/astral.output.nwk -t 2" - ok

Creating orthogroup profiles
----------------------------
2024-10-17 16:57:33 : Done 0 of 24281
2024-10-17 16:58:08 : Done 1000 of 24281
...
2024-10-17 16:58:15 : Done 24000 of 24281

Adding new species in /mnt/public3/chaohy/software/OrthoFinder_source/TestData/AdditionalSpecies/ to existing analysis in /mnt/public3/chaohy/software/OrthoFinder_source/TestData/OrthoFinder/Results_Core/

Running diamond profiles search
-------------------------------
2024-10-17 17:05:05 : Done profiles search

Writing orthogroups to file
---------------------------
2024-10-17 17:05:21 : Starting MSA/Trees

Inferring multiple sequence alignments and gene trees
-----------------------------------------------------
2024-10-17 17:05:47 : Done 0 of 20389
2024-10-17 17:07:41 : Done 1000 of 20389
...
2024-10-17 17:13:23 : Done 20000 of 20389
2024-10-17 17:13:39 : Done MSA/Trees
'NoneType' object has no attribute 'write'
  File "/mnt/public3/chaohy/software/OrthoFinder_source/scripts_of/__main__.py", line 1399, in main
    clustersFilename_pairs, i_og_restart = BetweenCoreOrthogroupsWorkflow(continuationDir, speciesInfoObj, seqsInfo, options, prog_caller, speciesNamesDict, results_files, q_hogs)
  File "/mnt/public3/chaohy/software/OrthoFinder_source/scripts_of/__main__.py", line 1052, in BetweenCoreOrthogroupsWorkflow
    rooted_species_tree_ids.write(outfile=rooted_species_tree_fn)
Traceback (most recent call last):
  File "/mnt/public3/chaohy/software/OrthoFinder_source/./orthofinder.py", line 7, in <module>
    main(args)
  File "/mnt/public3/chaohy/software/OrthoFinder_source/scripts_of/__main__.py", line 1399, in main
    clustersFilename_pairs, i_og_restart = BetweenCoreOrthogroupsWorkflow(continuationDir, speciesInfoObj, seqsInfo, options, prog_caller, speciesNamesDict, results_files, q_hogs)
  File "/mnt/public3/chaohy/software/OrthoFinder_source/scripts_of/__main__.py", line 1052, in BetweenCoreOrthogroupsWorkflow
    rooted_species_tree_ids.write(outfile=rooted_species_tree_fn)
AttributeError: 'NoneType' object has no attribute 'write'
```

At this point, I am unable to resolve the above error. Do you have any suggestions?

**Comment by davidemms** [comment]
Hi 

It looks like you've installed an old version of ASTRAL-Pro that isn't supported - there's a banner on the ASTRAL page you linked to with instructions on how to install the supported version. As a result the species tree inference has failed, I've tracked the error in the stack trace you posted and will push a commit to produce a clearer error message. 

It's interesting that the conda install of the OrthoFinder v3 beta failed, could you post the output you get from that and I can see what the issue is there.

All the best
David

**Comment by BioOmics** [comment]
Thanks!!!!

I downloaded the latest version of ASTRAL-Pro (to be precise, ASTRAL-Pro3), and everything is now working perfectly.

A small suggestion: on your [release](https://github.com/davidemms/OrthoFinder/releases) page, the link points to an old version of ASTRAL, and the version linked in the [README.md](https://github.com/davidemms/OrthoFinder/blob/master/README.md) is still: https://github.com/smirarab/ASTRAL, but that version still contains errors (Or i made a mistake). I eventually found the correct version here: https://github.com/chaoszhang/ASTER.

Here is my experience, which may help others:

```bash
wget https://github.com/chaoszhang/ASTER/archive/refs/heads/Linux.zip
unzip Linux.zip
cd ASTER-Linux
make
```

Then, replace OrthoFinderv3’s astral-pro with `astral-pro3`:

```bash
cp /myPath/ASTER-Linux/bin/astral-pro3 /myPath/OrthoFinder_source/scripts_of/bin/astral-pro
```
This way, i can run it smoothly without modifying any of the source code in OrthoFinderv3


---
Next, I'll select the appropriate core and run tests on 1k species.

Thank you again for your response!

**Comment by davidemms** [comment]
Thanks for pointing that out, I've updated the link in both locations.

**Comment by BioOmics** [comment]
Hi,

Sorry to bother you again. I found that after replacing astral-pro3 with OrthoFinderv3, the program runs smoothly to completion, but the resulting species tree lacks genetic distances, and I’m unsure where the issue might be.

Here's an example of the resulting tree output:
```bash
((Mycoplasma_gallisepticum:0,Mycoplasma_genitalium:0)1:0,(M_haemocanis:0,((Mycoplasma_agalactiae:0,M_arthritidis:0)1:0,Mycoplasma_hyopneumoniae:0)1:0)1:0);
```

Below are the differences between the two versions:

- astral-pro in OrthoFinderv3:
![image](https://github.com/user-attachments/assets/ae1d8021-f9a7-431f-b9eb-7b0ba3f15bc2)

- astral-pro3 in ASTER-Linux:
![image](https://github.com/user-attachments/assets/7fae410e-053d-4693-987f-db275f8b8e5b)

Currently, I’m unable to download the ASTRAL Version v1.15.1.3 source code, which leaves me stuck on a machine lacking GLIBC_2.* dependencies without root privileges. This makes it impossible for me to compile the code myself or use OrthoFinderv3 effectively. I hope this feedback can help improve OrthoFinder.

Thank you!

**Comment by chaoszhang** [comment]
Sorry for breaking the current pipeline. Currently ASTRAL and ASTRAL-Pro have intergreted CASTLES, which can compute branch lengths in substitution units (including terminal branch lengths). This require input gene trees to be annotated with branch lengths.
