### ISSUE TITLE
dlcpar is installed and in the path but orthofinder can't find it

### ISSUE THREAD

**Issue by zillurbmb51** [davidemms/OrthoFinder#94]
Hi there,
I was trying to run for 44 apicomplexan organisms with the latest version (1.1.8). I am having the following problem. `[zillur@genomics OrthoFinder-1.1.8]$ ./orthofinder -M msa -A muscle -T raxml -f /gondor/zillur/orthology_new/july_5/
OrthoFinder version 1.1.8 Copyright (C) 2014 David Emms

    This program comes with ABSOLUTELY NO WARRANTY.
    This is free software, and you are welcome to redistribute it under certain conditions.
    For details please see the License.md that came with this software.

16 thread(s) for highly parallel tasks (BLAST searches etc.)
1 thread(s) for OrthoFinder algorithm

Checking required programs are installed
----------------------------------------
Test can run "makeblastdb -help" - ok
Test can run "blastp -help" - ok
Test can run "mcl -h" - ok
Test can run "fastme -i /gondor/zillur/orthology_new/july_5/SimpleTest.phy -o /gondor/zillur/orthology_new/july_5/SimpleTest.tre" - ok
Test can run "dlcpar_search --version" - failed
ERROR: Cannot run dlcpar_search
Please check DLCpar is installed and that the executables are in the system path.

Dependencies have been met for inference of orthogroups but not for the subsequent orthologue inference.
Either install the required dependencies or use the option '-og' to stop the analysis after the inference of orthogroups.

ERROR: An error occurred, please review previous error messages for more information.
[zillur@genomics OrthoFinder-1.1.8]$ dlcpar_search --version
/usr/lib64/python2.7/site-packages/scipy/__init__.py:110: UserWarning: Numpy 1.8.2 or above is recommended for this version of scipy (detected version 1.8.0)
  UserWarning)
dlcpar_search 1.0
[zillur@genomics OrthoFinder-1.1.8]$ conda update numpy scipy
Fetching package metadata ...............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /usr/local/anaconda2:
#
numpy                     1.12.1                   py27_0  
scipy                     0.19.1              np112py27_0`  

What should I do now? Thanks in advance.

Best regards
Zillur

**Comment by davidemms** [comment]
This was a problem with the installation of scipy on the user's machine producing a warning when dlcpar was run: "/usr/lib64/python2.7/site-packages/scipy/init.py:110: UserWarning: Numpy 1.8.2 or above is recommended for this version of scipy (detected version 1.8.0)".

As per the results of attempting to update scipy using "conda update numpy scipy" (see above), there was already a correctly configured version of scipy available on the user's machine. To ensure this version of scipy was used and to therefore resolve the issue it was just necessary to run

export PYTHONPATH=/usr/local/anaconda2:$PYTHONPATH

before running OrthoFinder to ensure that the scipy and numpy libraries installed in the /usr/local/anaconda2 directory were used.

**Comment by zillurbmb51** [comment]
Thank you very much for your kind reply. Well, after "export
PYTHONPATH=/usr/local/anaconda2:$PYTHONPATH", I had to update scipy and
numpy.

Best Regards
Zillur Rahman
Phd Student at Bioinformatics Lab
University of Puerto Rico, Rio-Piedras

**Comment by davidemms** [comment]
Thanks for the info, it helps anyone else who has a similar issue.

All the best
David
