### ISSUE TITLE
evalue and similarity/identity % for blast

### ISSUE THREAD

**Issue by Mataivic** [davidemms/OrthoFinder#96]
Hello,

I have not seen any parameters for using various e-values or similarity/identity percent for the blastp runs. Have you planned to do it ?

Thanks.

**Comment by davidemms** [comment]
Hi

I'd not particularly thought of using the similarity/identity percent as I don't see how parameters could be chosen that: 1. would be correctly set so as to be relevant to the amount of similarity expected to be seen for all the different orthogroups across a set of species (I'd expect it to vary on an orthogroup by orthogroup and species by species basis) 2. and would provide more information than the length normalised bit score cut-off that is used by OrthoFinder as a criterion, taking into account both the sequence divergence within the putative orthogroup and for the divergence between the species pair. 

As for the evalue, the answer is a qualified yes, I have considered exposing it to the user but it's worth checking what effect you'd be hoping for by varying it. Is your intention to try and change the orthogroups that are returned by OrthoFinder? If so, then changing the evalue is unlikely to do what you might expect. Orthogroups have a clear definition unrelated to e-values (https://github.com/davidemms/OrthoFinder#orthogroups-orthologues--paralogues) and OrthoFinder does not use the e-value score to construct orthogroups. 

The only reasons I would consider changing the BLAST e-value would be:
- I would use a larger (less stringent) e-value if my species are diverged to such an extent that I'm not getting BLAST hits between some orthologues. Without getting these hits from BLAST, OrthoFinder would find it hard to put the genes into their correct orthogroups (although if the genes hit orthologues in other species then it might not be a problem). Is this occurring for you with the default e-value of 1e-3? If so then it could be good to change it.
- I would use a smaller (more stringent) e-value if all the hits between all orthologues (including the most distantly related ones) scored e-values far smaller than the cut-off used. If you know in advance that this is going to be the case before doing the BLAST searches then using a smaller e-value may reduce the time taken for the BLAST searches although I don't know if this would be a significant change in time or not.

So just to be clear, the e-value parameter passed to BLAST (the only place that it is used) shouldn't affect the orthogroups identified. The only effect you could have is that you could get poor recall if you set too stringent an evalue resulting in not getting significant hits between orthologues in the first place!

I hope this helps, let me know if you are finding yourself in either of the two situations above in which case there may be some use in varying the evalue.

All the best
David

**Comment by Mataivic** [comment]
All clear !

I work with people studying several which are closely related, so I would use a more stringent e-value (that's what they usually do). I think I'll plan some tests to see what happen if the e-value changes.

**Comment by davidemms** [comment]
Hi

It's only just occurred to me, you can already adjust the e-value etc. as you wish by using the OrthoFinder configuration file as described in the pdf manual section, "5.7 User-specified MSA, Tree Inference or Sequence Seach Program"!

All you would need to do would be to add an entry for your personalised version of BLAST to the orthofinder/config.json file saying how you would like to invoke BLAST, setting any command line options you would like e.g.

```
    "my_blast":{ 
    "program_type": "search",
    "db_cmd": "makeblastdb -dbtype prot -in INPUT -out OUTPUT",
    "search_cmd": "blastp -outfmt 6 -evalue 1e-3 -query INPUT -db DATABASE -out OUTPUT"
    }
```
(note, as per the .json format if this is the last entry in config.json then there should be no comma after it but there should be after each of the previous entries. This should be clear when you look at the file.)

And then if you call "orthofinder -h" you'll see the option "my_blast" for the "-S" flag and you can use it by adding "-S my_blast" to your normal command line. 

Let me know if you have any issues with this.

All the best
David

**Comment by Mataivic** [comment]
Hi, all right, I'll give a try when I'll have some time (but first, holidays ;) )

Regards,

Victor.

**Comment by Tiramisu023** [comment]
> I would use a smaller (more stringent) e-value if all the hits between all orthologues (including the most distantly related ones) scored e-values far smaller than the cut-off used. If you know in advance that this is going to be the case before doing the BLAST searches then using a smaller e-value **may reduce the time taken for the BLAST searches although I don't know if this would be a significant change in time or not.**

hello Davidemms, actually Blast doesn't save time when using a more stringent e-value. 
If we use the **blastp** without **-max_target_seqs** (default = 500), it's almost a global blast search, because the copy number of genes (or qualified records) struggle to reach 500.
