### ISSUE TITLE
Problem with user provided species tree

### ISSUE THREAD

**Issue by ShaulPollak** [davidemms/OrthoFinder#97]
Hey, when using the attached input_tree as an input for the -s flag, i get errors with dlc:
File "/Library/Python/2.7/site-packages/dlcpar/common.py", line 45, in check_tree
    raise Exception("tree must be rooted and binary: %s" % name)
Exception: tree must be rooted and binary: /Results_Jul17/Orthologues_Jul17/WorkingDirectory/Trees_ids/SpeciesTree_user_ids_rooted.txt

When looking at the tree using FigTree, it looks rooted and binary
[SpeciesTree_user_ids_rooted.txt](https://github.com/davidemms/OrthoFinder/files/1152320/SpeciesTree_user_ids_rooted.txt)
[input_tree.txt](https://github.com/davidemms/OrthoFinder/files/1152327/input_tree.txt)

**Comment by davidemms** [comment]
Hi 

You have polytomies for (3,81,84), (14,38,65,89) and (2,62,63). If you resolve these and check you don't have any others then it should work fine. Feel free to reopen this issue if you still have problems with this.

All the best
David
