### ISSUE TITLE
bring back orthologs fasta files from previous release

### ISSUE THREAD

**Issue by ekayal** [davidemms/OrthoFinder#98]
Hello,
I was wondering how to get the fasta files for the orthogroups that OrthoFinder finds. In the Statistics_Overall.csv, it reports the number of orthogroups and classify them per number of species present in each, among other things. But I could not locate a folder that would have the fasta files of the orthogroups and/or their alignments that were used for building gene trees. For instance, I want all the orthogroups with all species present.
Interestingly, the older version of the program was doing exactly that. Is it possible to have that feature added to the new version?
Thank you very much in advance.
E

**Comment by davidemms** [comment]
Hi

You can still get fasta files for the orthogroups with the latest version of OrthoFinder. To do this, you just need to specify the option "-M msa", see Figure 2 in the pdf manual that describes the options for controlling the workflow. As you will see in the figure, you have a number of options. By default it will carry out the following steps:

> orthogroups -> fasta files of sequences -> multiple sequence alignments -> gene trees -> orthologues

but there are options to start/stop the analysis at various points along this workflow to make things more convenient for the user, e.g. if you've already got orthogroups you can use the "-fg orthogroups_dir" option to start from this point.

All the best
David

**Comment by Mataivic** [comment]
Hello,

Is this feature available in version 1.1.2 or only in the newest versions ?

Thanks.

**Comment by davidemms** [comment]
It's available from version 1.1.4. 

All the best
David
