### ISSUE TITLE
How to resume Interrupted orthfinder run

### ISSUE THREAD

**Issue by zillurbmb51** [davidemms/OrthoFinder#99]
Hi there,
I was running orthofinder for 44 species. After 4 days of run, it was interrupted for power supply problem. Now everything is fine. I got some output in ../Result_Jul_13_3/WorkingDirectory. Attached file contains all the file names in the working directory. Is there any way to resume my previous analysis or I have to start from beginning? Can I add different options now; like " -T raxml" with updated config.json file? Thanks in advance.
Best Regards
Zillur
[all_out_in_working_dir.txt](https://github.com/davidemms/OrthoFinder/files/1159987/all_out_in_working_dir.txt)

**Comment by davidemms** [comment]
Hi

It depends on whether all the BLAST searches finished correctly. 

- **If** they did then you can restart the analysis using the "-b" option but I would be very careful to make sure that they really did finish. You could use "ls -l" to check when the Blast*.*.txt files were last written to. If the timestamp on some of them is close to the time of the power supply problem then that is a strong indication that the didn't finish. You could also check the end of the blast results files to check that the query sequences for the last hits in each file are the last sequences in the corresponding species (refer to the SequenceIDs.txt file to see what the last sequence in each species is).

- If not all of the BLAST searches finished then you could manually run just those ones and then use the "-b" option once these are complete. It may not be worth your time to do this though, it might just be better to start from the beginning and let the computer spend the time doing it instead. Unless you can efficiently work out what blast commands you need to run etc. according to what has/hasn't finished then this might be a poor use of your time. 

If you do restart it with the "-b" option then yes, you can use different options like "-T raxml".

All the best
David
